// Generated by Lucent from clock.lucent.ts. Do not edit.
#include "m_clock.h"

#pragma push_macro("before")
#undef before
#pragma push_macro("later")
#undef later
#pragma push_macro("tick")
#undef tick
#pragma push_macro("ticks")
#undef ticks

namespace lucent_app {

double m_clock::tick(lucent::Fn<double()> p0_) {
  double v1_ = lucent_app::m_clock::ticks;
  lucent_app::m_clock::ticks = v1_ + 1.0;
  double v4_ = p0_();
  return v4_ + 100.0;
}

lucent::Promise<double> m_clock::later(double p0_) {
  double v1_ = lucent_app::m_clock::ticks;
  double before = v1_;
  lucent::Promise<void> v3_ = lucent::delay(2.0);
  co_await v3_;
  double v5_ = lucent_app::m_clock::ticks;
  lucent_app::m_clock::ticks = v5_ + 1.0;
  double v8_ = lucent_app::m_clock::ticks;
  co_return p0_ + (v8_ - before);
}

void m_clock::init() {
  lucent_app::m_clock::ticks = 0.0;
}

}  // namespace lucent_app

#pragma pop_macro("ticks")
#pragma pop_macro("tick")
#pragma pop_macro("later")
#pragma pop_macro("before")
