// Generated by Lucent from counter.lucent.ts. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("around")
#undef around
#pragma push_macro("bump")
#undef bump
#pragma push_macro("count")
#undef count
#pragma push_macro("steps")
#undef steps

namespace lucent_app {

namespace m_counter {

inline double count{};

double bump();
double around(lucent::Fn<double()> p0_);
lucent::Promise<double> steps(double p0_);
void init();

}  // namespace m_counter

}  // namespace lucent_app

#pragma pop_macro("steps")
#pragma pop_macro("count")
#pragma pop_macro("bump")
#pragma pop_macro("around")
