// Generated by scripts/embed-native.ts from packages/host-expo/native. Do not edit.

/** Hand-written native source, embedded so it survives bundling. */
export const NATIVE_SOURCES: Readonly<Record<string, string>> = {
  "Lucent.podspec": "Pod::Spec.new do |s|\n  s.name           = '{{ident}}'\n  s.version        = '0.0.0'\n  s.summary        = 'Native code generated by Lucent'\n  s.description    = 'Swift generated ahead of time from *.lucent.ts files.'\n  s.author         = ''\n  s.homepage       = 'https://github.com/Fausto95/lucent'\n  s.platforms      = { :ios => '16.4', :tvos => '16.4' }\n  s.source         = { git: '' }\n  s.static_framework = true\n\n  s.dependency 'ExpoModulesCore'\n\n  s.pod_target_xcconfig = {\n    'DEFINES_MODULE' => 'YES',\n  }\n\n  s.source_files = \"**/*.{h,m,mm,swift,hpp,cpp}\"\nend\n",
  "build.gradle": "plugins {\n  id 'com.android.library'\n  id 'expo-module-gradle-plugin'\n}\n\ngroup = '{{androidPackage}}'\nversion = '0.0.0'\n\nandroid {\n  namespace \"{{androidPackage}}\"\n  defaultConfig {\n    versionCode 1\n    versionName \"0.0.0\"\n  }\n  lintOptions {\n    abortOnError false\n  }\n}\n",
  "compose-buildscript.gradle": "buildscript {\n  repositories { google(); mavenCentral() }\n  dependencies { classpath(\"org.jetbrains.kotlin:compose-compiler-gradle-plugin:${rootProject.ext.kotlinVersion}\") }\n}\n",
  "compose.gradle": "\napply plugin: 'org.jetbrains.kotlin.plugin.compose'\nandroid { buildFeatures { compose true } }\ndependencies {\n  implementation 'androidx.compose.ui:ui:1.7.6'\n  implementation 'androidx.compose.foundation:foundation:1.7.6'\n  implementation 'androidx.compose.material3:material3:1.3.1'\n}\n",
};

export function nativeSource(file: string): string {
  const source = NATIVE_SOURCES[file];
  if (source === undefined) throw new Error(`Unknown native source ${file} in host-expo`);
  return source;
}
