// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("kind")
#undef kind
#pragma push_macro("side")
#undef side
#pragma push_macro("v")
#undef v

namespace lucent_app {

struct S_Object_4b1186b8;

struct S_Object_4b1186b8 : lucent::Object {
  lucent::String kind{};
  double side{};
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object_4b1186b8>& v);

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object_4b1186b8>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "kind", v->kind);
  lucent::jsonField(w, first, "side", v->side);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("v")
#pragma pop_macro("side")
#pragma pop_macro("kind")
