// Generated by Lucent. Do not edit.
#pragma once
#include <lucent/lucent.h>

#pragma push_macro("a")
#undef a
#pragma push_macro("discount")
#undef discount
#pragma push_macro("items")
#undef items
#pragma push_macro("kind")
#undef kind
#pragma push_macro("meta")
#undef meta
#pragma push_macro("name")
#undef name
#pragma push_macro("note")
#undef note
#pragma push_macro("paid")
#undef paid
#pragma push_macro("point")
#undef point
#pragma push_macro("price")
#undef price
#pragma push_macro("r")
#undef r
#pragma push_macro("r_id_")
#undef r_id_
#pragma push_macro("side")
#undef side
#pragma push_macro("tags")
#undef tags
#pragma push_macro("v")
#undef v

namespace lucent_app {

inline lucent::Actor& actor_0() {
  static lucent::Actor& a = lucent::Actor::create("json");
  return a;
}

struct S_Item;
struct S_Order;
struct S_Object3;
struct S_Object4;
struct S_Object5;

struct S_Item : lucent::Object {
  lucent::String name{};
  double price{};
  lucent::Array<lucent::String> tags{};
  lucent::Opt<lucent::String> note{};
  lucent::Opt<double> discount{};
};

struct S_Order : lucent::Object {
  double r_id_{};
  lucent::Array<lucent::Ref<lucent_app::S_Item>> items{};
  bool paid{};
  lucent::Dict<double> meta{};
  std::tuple<double, double> point{};
};

struct S_Object3 : lucent::Object {
  lucent::String kind{};
  double r{};
};

struct S_Object4 : lucent::Object {
  lucent::String kind{};
  double side{};
};

struct S_Object5 : lucent::Object {
  double a{};
};

}  // namespace lucent_app

namespace lucent {

template <>
struct JsonRead<lucent::Ref<lucent_app::S_Order>> {
  static lucent::Ref<lucent_app::S_Order> read(const JsonValue& v, const std::string& p);
};

template <>
struct JsonRead<lucent::Ref<lucent_app::S_Item>> {
  static lucent::Ref<lucent_app::S_Item> read(const JsonValue& v, const std::string& p);
};

template <>
struct JsonRead<lucent::Ref<lucent_app::S_Object3>> {
  static lucent::Ref<lucent_app::S_Object3> read(const JsonValue& v, const std::string& p);
};

template <>
struct JsonRead<lucent::Ref<lucent_app::S_Object4>> {
  static lucent::Ref<lucent_app::S_Object4> read(const JsonValue& v, const std::string& p);
};

template <>
struct JsonRead<lucent::Ref<lucent_app::S_Object5>> {
  static lucent::Ref<lucent_app::S_Object5> read(const JsonValue& v, const std::string& p);
};

template <>
struct JsonRead<std::variant<lucent::Ref<lucent_app::S_Object3>, lucent::Ref<lucent_app::S_Object4>>> {
  static std::variant<lucent::Ref<lucent_app::S_Object3>, lucent::Ref<lucent_app::S_Object4>> read(const JsonValue& v, const std::string& p);
};

template <>
struct JsonRead<std::variant<bool, double, lucent::String>> {
  static std::variant<bool, double, lucent::String> read(const JsonValue& v, const std::string& p);
};

}  // namespace lucent

namespace lucent_app {

void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Item>& v);
void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Order>& v);
void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object3>& v);
void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object4>& v);
void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object5>& v);

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Item>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "name", v->name);
  lucent::jsonField(w, first, "price", v->price);
  lucent::jsonField(w, first, "tags", v->tags);
  lucent::jsonField(w, first, "note", v->note);
  lucent::jsonField(w, first, "discount", v->discount);
  (void)first;
  w.raw("}");
}

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Order>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "id", v->r_id_);
  lucent::jsonField(w, first, "items", v->items);
  lucent::jsonField(w, first, "paid", v->paid);
  lucent::jsonField(w, first, "meta", v->meta);
  lucent::jsonField(w, first, "point", v->point);
  (void)first;
  w.raw("}");
}

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object3>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "kind", v->kind);
  lucent::jsonField(w, first, "r", v->r);
  (void)first;
  w.raw("}");
}

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object4>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "kind", v->kind);
  lucent::jsonField(w, first, "side", v->side);
  (void)first;
  w.raw("}");
}

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object5>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "a", v->a);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

namespace lucent {

inline lucent::Ref<lucent_app::S_Order> JsonRead<lucent::Ref<lucent_app::S_Order>>::read(const JsonValue& v, const std::string& p) {
  if (v.kind != JsonValue::Kind::Object) {
    jsonShapeError(p, "an object", v.describe());
  }
  auto out = std::make_shared<lucent_app::S_Order>();
  out->r_id_ = jsonMember<double>(v, "id", p);
  out->items = jsonMember<lucent::Array<lucent::Ref<lucent_app::S_Item>>>(v, "items", p);
  out->paid = jsonMember<bool>(v, "paid", p);
  out->meta = jsonMember<lucent::Dict<double>>(v, "meta", p);
  out->point = jsonMember<std::tuple<double, double>>(v, "point", p);
  return out;
}

inline lucent::Ref<lucent_app::S_Item> JsonRead<lucent::Ref<lucent_app::S_Item>>::read(const JsonValue& v, const std::string& p) {
  if (v.kind != JsonValue::Kind::Object) {
    jsonShapeError(p, "an object", v.describe());
  }
  auto out = std::make_shared<lucent_app::S_Item>();
  out->name = jsonMember<lucent::String>(v, "name", p);
  out->price = jsonMember<double>(v, "price", p);
  out->tags = jsonMember<lucent::Array<lucent::String>>(v, "tags", p);
  out->note = jsonMember<lucent::Opt<lucent::String>>(v, "note", p);
  out->discount = jsonMember<lucent::Opt<double>>(v, "discount", p);
  return out;
}

inline lucent::Ref<lucent_app::S_Object3> JsonRead<lucent::Ref<lucent_app::S_Object3>>::read(const JsonValue& v, const std::string& p) {
  if (v.kind != JsonValue::Kind::Object) {
    jsonShapeError(p, "an object", v.describe());
  }
  auto out = std::make_shared<lucent_app::S_Object3>();
  out->kind = jsonMember<lucent::String>(v, "kind", p);
  out->r = jsonMember<double>(v, "r", p);
  return out;
}

inline lucent::Ref<lucent_app::S_Object4> JsonRead<lucent::Ref<lucent_app::S_Object4>>::read(const JsonValue& v, const std::string& p) {
  if (v.kind != JsonValue::Kind::Object) {
    jsonShapeError(p, "an object", v.describe());
  }
  auto out = std::make_shared<lucent_app::S_Object4>();
  out->kind = jsonMember<lucent::String>(v, "kind", p);
  out->side = jsonMember<double>(v, "side", p);
  return out;
}

inline lucent::Ref<lucent_app::S_Object5> JsonRead<lucent::Ref<lucent_app::S_Object5>>::read(const JsonValue& v, const std::string& p) {
  if (v.kind != JsonValue::Kind::Object) {
    jsonShapeError(p, "an object", v.describe());
  }
  auto out = std::make_shared<lucent_app::S_Object5>();
  out->a = jsonMember<double>(v, "a", p);
  return out;
}

inline std::variant<lucent::Ref<lucent_app::S_Object3>, lucent::Ref<lucent_app::S_Object4>> JsonRead<std::variant<lucent::Ref<lucent_app::S_Object3>, lucent::Ref<lucent_app::S_Object4>>>::read(const JsonValue& v, const std::string& p) {
  switch (v.kind) {
    case JsonValue::Kind::Object:
      {
        const JsonValue* d = v.find(LUCENT_STR("kind"));
        if (!d || (d->kind != JsonValue::Kind::String)) {
          jsonShapeError(p + ".kind", "one of the kind values", d ? d->describe() : "undefined");
        }
        if (d->string == LUCENT_STR("circle")) {
          return std::variant<lucent::Ref<lucent_app::S_Object3>, lucent::Ref<lucent_app::S_Object4>>(std::in_place_type<lucent::Ref<lucent_app::S_Object3>>, JsonRead<lucent::Ref<lucent_app::S_Object3>>::read(v, p));
        }
        if (d->string == LUCENT_STR("square")) {
          return std::variant<lucent::Ref<lucent_app::S_Object3>, lucent::Ref<lucent_app::S_Object4>>(std::in_place_type<lucent::Ref<lucent_app::S_Object4>>, JsonRead<lucent::Ref<lucent_app::S_Object4>>::read(v, p));
        }
        jsonShapeError(p + ".kind", "one of the kind values", "another string");
      }
    default:
      jsonShapeError(p, "one of S:kind:string;r:number | S:kind:string;side:number", v.describe());
  }
}

inline std::variant<bool, double, lucent::String> JsonRead<std::variant<bool, double, lucent::String>>::read(const JsonValue& v, const std::string& p) {
  switch (v.kind) {
    case JsonValue::Kind::Number:
      return std::variant<bool, double, lucent::String>(std::in_place_type<double>, JsonRead<double>::read(v, p));
    case JsonValue::Kind::String:
      return std::variant<bool, double, lucent::String>(std::in_place_type<lucent::String>, JsonRead<lucent::String>::read(v, p));
    case JsonValue::Kind::Bool:
      return std::variant<bool, double, lucent::String>(std::in_place_type<bool>, JsonRead<bool>::read(v, p));
    default:
      jsonShapeError(p, "one of boolean | number | string", v.describe());
  }
}

}  // namespace lucent

#pragma pop_macro("v")
#pragma pop_macro("tags")
#pragma pop_macro("side")
#pragma pop_macro("r_id_")
#pragma pop_macro("r")
#pragma pop_macro("price")
#pragma pop_macro("point")
#pragma pop_macro("paid")
#pragma pop_macro("note")
#pragma pop_macro("name")
#pragma pop_macro("meta")
#pragma pop_macro("kind")
#pragma pop_macro("items")
#pragma pop_macro("discount")
#pragma pop_macro("a")
