// Generated by Lucent from never-values.lucent.ts. Do not edit.
#include "m_never_u2d_values.h"

#pragma push_macro("attempt")
#undef attempt
#pragma push_macro("calls")
#undef calls
#pragma push_macro("count")
#undef count
#pragma push_macro("declared")
#undef declared
#pragma push_macro("declaredLet")
#undef declaredLet
#pragma push_macro("e")
#undef e
#pragma push_macro("fail")
#undef fail
#pragma push_macro("fromArrow")
#undef fromArrow
#pragma push_macro("fromMethod")
#undef fromMethod
#pragma push_macro("key")
#undef key
#pragma push_macro("lookup")
#undef lookup
#pragma push_macro("n")
#undef n
#pragma push_macro("name")
#undef name
#pragma push_macro("names")
#undef names
#pragma push_macro("ok")
#undef ok
#pragma push_macro("parse")
#undef parse
#pragma push_macro("pick")
#undef pick
#pragma push_macro("registry")
#undef registry
#pragma push_macro("reject")
#undef reject
#pragma push_macro("returned")
#undef returned
#pragma push_macro("text")
#undef text

namespace lucent_app {

void C_Registry::construct() {
  lucent::Map<lucent::String, lucent::String> v0_ = lucent::Map<lucent::String, lucent::String>();
  this->names = v0_;
}

lucent::Ref<C_Registry> C_Registry::create() {
  auto self = std::make_shared<C_Registry>();
  self->construct();
  return self;
}

lucent::String C_Registry::lookup(lucent::String p0_) {
  lucent::Map<lucent::String, lucent::String> v1_ = this->names;
  lucent::Opt<lucent::String> name = v1_.get(p0_);
  bool v5_ = !lucent::strictEquals(name, lucent::undefined);
  if (v5_) {
    return name.value();
  }
  lucent_app::m_never_u2d_values::fail(lucent::String(LUCENT_STR("name for ")) + p0_);
  return []() -> lucent::String {
    lucent::unreachable();
  }();
}

void m_never_u2d_values::fail(lucent::String p0_) {
  lucent::Array<lucent::String> v1_ = lucent_app::m_never_u2d_values::calls;
  (void)v1_.push(p0_);
  lucent::Error v5_ = lucent::withSite(lucent::makeError(LUCENT_STR("Error"), lucent::String(LUCENT_STR("no ")) + p0_), __FILE__, __LINE__, "fail");
  lucent::throwError(v5_);
}

lucent::String m_never_u2d_values::attempt(lucent::Fn<lucent::String()> p0_) {
  lucent_app::m_never_u2d_values::calls = lucent::Array<lucent::String>{};
  {
    std::exception_ptr ex11_;
    try {
      lucent::String v2_ = p0_();
      lucent::Array<lucent::String> v4_ = lucent_app::m_never_u2d_values::calls;
      lucent::String v6_ = v4_.join(LUCENT_STR(","));
      return lucent::concat(v2_, LUCENT_STR(" ["), v6_, LUCENT_STR("]"));
    } catch (const lucent::GeneratorReturn&) {
      throw;
    } catch (...) {
      ex11_ = std::current_exception();
    }
    if (ex11_) {
      lucent::Error v11_ = lucent::currentError(ex11_);
      lucent::Error e = std::move(v11_);
      lucent::String v14_ = e->message;
      lucent::Array<lucent::String> v16_ = lucent_app::m_never_u2d_values::calls;
      lucent::String v18_ = v16_.join(LUCENT_STR(","));
      return lucent::concat(LUCENT_STR("threw "), v14_, LUCENT_STR(" ["), v18_, LUCENT_STR("]"));
    }
  }
  lucent::unreachable();
}

double m_never_u2d_values::parse(lucent::String p0_) {
  double n = lucent::stringToNumber(p0_);
  bool v3_ = lucent::isNaN(n);
  if (v3_) {
    lucent_app::m_never_u2d_values::fail(lucent::String(LUCENT_STR("number in ")) + p0_);
    return []() -> double {
      lucent::unreachable();
    }();
  }
  return n;
}

lucent::String m_never_u2d_values::returned(lucent::String p0_) {
  lucent::Fn<lucent::String()> v1_ = lucent::Fn<lucent::String()>([text = p0_]() mutable -> lucent::String {
    double v1_ = lucent_app::m_never_u2d_values::parse(text);
    return lucent::toJsString(v1_);
  });
  return lucent_app::m_never_u2d_values::attempt(v1_);
}

lucent::String m_never_u2d_values::fromMethod(lucent::String p0_) {
  lucent::Ref<lucent_app::C_Registry> registry = lucent_app::C_Registry::create();
  lucent::Map<lucent::String, lucent::String> v3_ = registry->names;
  (void)v3_.set(LUCENT_STR("a"), LUCENT_STR("ada"));
  lucent::Fn<lucent::String()> v8_ = lucent::Fn<lucent::String()>([registry = registry, key = p0_]() mutable -> lucent::String {
    return registry->lookup(key);
  });
  return lucent_app::m_never_u2d_values::attempt(v8_);
}

lucent::String m_never_u2d_values::fromArrow(bool p0_) {
  lucent::Fn<lucent::String()> v1_ = lucent::Fn<lucent::String()>([ok = p0_]() mutable -> lucent::String {
    lucent::String v5_{};
    if (ok) {
      v5_ = LUCENT_STR("picked");
    } else {
      lucent_app::m_never_u2d_values::fail(LUCENT_STR("pick"));
      v5_ = []() -> lucent::String {
        lucent::unreachable();
      }();
    }
    return v5_;
  });
  lucent::Fn<lucent::String()> pick = std::move(v1_);
  lucent::Fn<lucent::String()> v2_ = lucent::Fn<lucent::String()>([]() mutable -> lucent::String {
    lucent_app::m_never_u2d_values::fail(LUCENT_STR("reject"));
    return []() -> lucent::String {
      lucent::unreachable();
    }();
  });
  lucent::Fn<lucent::String()> reject = std::move(v2_);
  lucent::Fn<lucent::String()> v5_ = lucent::Fn<lucent::String()>([ok = p0_, pick = pick, reject = reject]() mutable -> lucent::String {
    lucent::String v5_{};
    if (ok) {
      v5_ = pick();
    } else {
      v5_ = reject();
    }
    return v5_;
  });
  return lucent_app::m_never_u2d_values::attempt(v5_);
}

lucent::String m_never_u2d_values::declared(bool p0_) {
  lucent::Fn<lucent::String()> v1_ = lucent::Fn<lucent::String()>([ok = p0_]() mutable -> lucent::String {
    if (ok) {
      return LUCENT_STR("skipped");
    }
    lucent_app::m_never_u2d_values::fail(LUCENT_STR("const"));
    lucent::String name = []() -> lucent::String {
      lucent::unreachable();
    }();
    return name;
  });
  return lucent_app::m_never_u2d_values::attempt(v1_);
}

lucent::String m_never_u2d_values::declaredLet(bool p0_) {
  lucent::Fn<lucent::String()> v1_ = lucent::Fn<lucent::String()>([ok = p0_]() mutable -> lucent::String {
    if (ok) {
      return LUCENT_STR("skipped");
    }
    lucent_app::m_never_u2d_values::fail(LUCENT_STR("let"));
    double count = []() -> double {
      lucent::unreachable();
    }();
    count = count + 1.0;
    return lucent::toJsString(count);
  });
  return lucent_app::m_never_u2d_values::attempt(v1_);
}

void m_never_u2d_values::init() {
  lucent_app::m_never_u2d_values::calls = lucent::Array<lucent::String>{};
}

}  // namespace lucent_app

#pragma pop_macro("text")
#pragma pop_macro("returned")
#pragma pop_macro("reject")
#pragma pop_macro("registry")
#pragma pop_macro("pick")
#pragma pop_macro("parse")
#pragma pop_macro("ok")
#pragma pop_macro("names")
#pragma pop_macro("name")
#pragma pop_macro("n")
#pragma pop_macro("lookup")
#pragma pop_macro("key")
#pragma pop_macro("fromMethod")
#pragma pop_macro("fromArrow")
#pragma pop_macro("fail")
#pragma pop_macro("e")
#pragma pop_macro("declaredLet")
#pragma pop_macro("declared")
#pragma pop_macro("count")
#pragma pop_macro("calls")
#pragma pop_macro("attempt")
