import path from "node:path";
import ts from "typescript";
import { Codes, fail } from "../diagnostics.ts";
import { coreTypesPath, type LucentModule, type LucentProgram } from "../program.ts";
import { type ClassInfo, cppIdent, type LType, T, unionOf } from "../types.ts";
import { BindingsEmitter, type ModuleExports, publicMembers } from "./bindings.ts";
import { emitClass } from "./classes.ts";
import { Ctx, type Global } from "./context.ts";
import { FnEmitter } from "./function.ts";
import { cppQuoted } from "./literals.ts";

export interface EmitResult {
  /** Generated C++ sources, keyed by file name. */
  files: Map<string, string>;
  /** JavaScript proxy for each module, keyed by module name. */
  proxies: Map<string, string>;
  diagnostics: import("../diagnostics.ts").Diagnostic[];
}

export function emitProgram(lp: LucentProgram): EmitResult {
  const ctx = new Ctx(lp.checker, lp.modules);
  const byFile = new Map(lp.modules.map((m) => [path.resolve(m.sourceFile.fileName), m]));
  const exportsOf = new Map<LucentModule, ModuleExports>();
  const imports = new Map<LucentModule, LucentModule[]>();

  // Pass 1: classes, then functions and variables, so every body can refer to
  // any top-level declaration.
  for (const m of lp.modules) {
    exportsOf.set(m, { module: m, functions: [], classes: [], consts: [], enums: [] });
    imports.set(m, []);
    for (const s of m.sourceFile.statements) {
      if (ts.isClassDeclaration(s)) {
        if (!s.name) {
          ctx.diagnostics.push({ code: Codes.UnsupportedTopLevel, message: "classes need a name", file: m.file });
          continue;
        }
        const info = ctx.reg.registerClass(s, m.name, isExported(s));
        const sym = lp.checker.getSymbolAtLocation(s.name)!;
        ctx.globals.set(sym, { kind: "class", cpp: `lucent_app::${info.cppName}`, module: m, info });
        if (info.exported) exportsOf.get(m)!.classes.push(info);
      }
    }
  }
  for (const m of lp.modules) {
    for (const s of m.sourceFile.statements) {
      ctx.guard(() => collect(ctx, m, s, exportsOf.get(m)!, imports.get(m)!, byFile));
    }
  }

  // Pass 2: code.
  const header: string[] = [];
  const structDecls: string[] = [];
  const classDefs: string[] = [];
  const genericClassDefs: string[] = [];
  const moduleDecls = new Map<LucentModule, string[]>();
  const moduleDefs = new Map<LucentModule, string[]>();
  const genericFns: string[] = [];
  const staticInits = new Map<LucentModule, string[]>();
  for (const m of lp.modules) {
    moduleDecls.set(m, []);
    moduleDefs.set(m, []);
    staticInits.set(m, []);
  }

  for (const info of ctx.reg.classes.values()) {
    const m = lp.modules.find((x) => x.name === info.module)!;
    const out = ctx.guard(() => emitClass(ctx, m, info));
    if (!out) continue;
    (info.typeParams.length ? genericClassDefs : classDefs).push(out.definition);
    if (out.members) moduleDefs.get(m)!.push(out.members);
    staticInits.get(m)!.push(...out.staticInits);
  }

  for (const [sym, g] of ctx.globals) {
    void sym;
    if (g.kind === "function") ctx.guard(() => emitFunction(ctx, g, moduleDecls.get(g.module)!, moduleDefs.get(g.module)!, genericFns));
  }

  // Module state and init().
  for (const m of lp.modules) {
    const decls = moduleDecls.get(m)!;
    const em = new FnEmitter(ctx, { module: m, async: false, returnType: T.void });
    for (const [, g] of ctx.globals) {
      if (g.kind !== "var" || g.module !== m) continue;
      decls.unshift(`inline ${ctx.reg.cpp(g.type)} ${g.cpp.split("::").pop()}{};`);
      if (g.decl.initializer) {
        const v = ctx.guard(() => em.exprAs(g.decl.initializer!, g.type));
        if (v !== undefined) em.line(`${g.cpp} = ${v};`);
      } else {
        em.line(`${g.cpp} = ${ctx.reg.cpp(g.type)}{};`);
      }
    }
    decls.push("void init();");
    moduleDefs.get(m)!.push(`void ${m.ns}::init() {\n${[...staticInits.get(m)!, ...em.body()].join("\n")}\n}`);
  }

  // Structs (after everything has been lowered, so the registry is complete).
  const bindings = new BindingsEmitter(ctx);
  const mods = lp.modules.map((m) => exportsOf.get(m)!);
  const initOrder = topoSort(lp.modules, imports);
  const bindingsCpp = bindings.generate(mods, initOrder);

  for (const s of ctx.reg.structs.values()) structDecls.push(`struct ${s.cppName};`);
  const structDefs = [...ctx.reg.structs.values()].map((s) => {
    const fields = s.fields.map((f) => `  ${ctx.reg.cpp(f.type)} ${cppIdent(f.name)}{};`);
    return `struct ${s.cppName} : lucent::Object {\n${fields.join("\n")}\n};`;
  });
  const classFwd = [...ctx.reg.classes.values()].map((c) =>
    c.typeParams.length ? `template <${c.typeParams.map((p) => `class ${cppIdent(p)}`).join(", ")}>\nstruct ${c.cppName};` : `struct ${c.cppName};`,
  );
  const json = jsonWriters(ctx);

  header.push("// Generated by Lucent. Do not edit.");
  header.push("#pragma once");
  header.push("#include <lucent/lucent.h>");
  header.push("");
  header.push("namespace lucent_app {");
  header.push(...structDecls, ...classFwd, "");
  header.push(...structDefs, "");
  header.push(...classDefs, "");
  header.push(...genericClassDefs, "");
  for (const m of lp.modules) {
    header.push(`namespace ${m.ns} {`);
    header.push(...moduleDecls.get(m)!.map((l) => `${l}`));
    header.push(`}  // namespace ${m.ns}`, "");
  }
  header.push(...json.decls, "");
  header.push(...genericFns, "");
  header.push(...json.defs);
  header.push("}  // namespace lucent_app", "");

  const files = new Map<string, string>();
  files.set("lucent_app.h", header.join("\n"));
  for (const m of lp.modules) {
    files.set(`${m.ns}.cpp`, `// Generated by Lucent from ${path.basename(m.file)}. Do not edit.\n#include "lucent_app.h"\n\nnamespace lucent_app {\n\n${moduleDefs.get(m)!.join("\n\n")}\n\n}  // namespace lucent_app\n`);
  }
  files.set("lucent_bindings.cpp", bindingsCpp);

  const proxies = new Map<string, string>();
  for (const m of mods) proxies.set(m.module.name, jsProxy(m));
  return { files, proxies, diagnostics: [...lp.diagnostics, ...ctx.diagnostics] };
}

function isExported(n: ts.Node): boolean {
  return ts.canHaveModifiers(n) && !!ts.getModifiers(n)?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
}

function collect(ctx: Ctx, m: LucentModule, s: ts.Statement, exp: ModuleExports, deps: LucentModule[], byFile: Map<string, LucentModule>): void {
  const checker = ctx.checker;
  if (ts.isImportDeclaration(s)) {
    const spec = (s.moduleSpecifier as ts.StringLiteral).text;
    if (s.importClause?.isTypeOnly) return;
    const resolved = ts.resolveModuleName(spec, m.sourceFile.fileName, ctx.checker ? {} : {}, ts.sys);
    void resolved;
    const sym = checker.getSymbolAtLocation(s.moduleSpecifier);
    const target = sym?.valueDeclaration ?? sym?.declarations?.[0];
    const file = target && ts.isSourceFile(target) ? path.resolve(target.fileName) : undefined;
    if (file && path.resolve(coreTypesPath()) === file) return;
    const dep = file ? byFile.get(file) : undefined;
    if (!dep) fail(s.moduleSpecifier, Codes.UnsupportedImport, `Lucent modules can only import other *.lucent.ts files and @lucent-lang/core (got "${spec}")`);
    deps.push(dep);
    return;
  }
  if (ts.isTypeAliasDeclaration(s) || ts.isInterfaceDeclaration(s) || ts.isClassDeclaration(s)) return;
  if (ts.isEnumDeclaration(s)) {
    const members = s.members.map((mem) => {
      const v = checker.getConstantValue(mem);
      if (v === undefined) fail(mem, Codes.UnsupportedTopLevel, "enum members must be constants");
      return { name: mem.name.getText(), value: v };
    });
    if (isExported(s)) exp.enums.push({ name: s.name.text, members });
    return;
  }
  if (ts.isFunctionDeclaration(s)) {
    if (!s.name) fail(s, Codes.UnsupportedTopLevel, "functions need a name");
    if (!s.body) {
      // Overload signature or declaration.
      fail(s, Codes.UnsupportedTopLevel, "function overloads and declarations without a body are not supported");
    }
    const sym = checker.getSymbolAtLocation(s.name)!;
    const sig = checker.getSignatureFromDeclaration(s)!;
    const type = ctx.reg.lowerSignature(sig, s) as LType & { k: "fn" };
    const isAsync = !!ts.getModifiers(s)?.some((x) => x.kind === ts.SyntaxKind.AsyncKeyword);
    const em = new FnEmitter(ctx, { module: m, async: isAsync, returnType: T.void });
    const params = em.paramInfos(s, type);
    const g: Global = { kind: "function", cpp: `lucent_app::${m.ns}::${cppIdent(s.name.text)}`, module: m, decl: s, type, async: isAsync, params, generic: !!s.typeParameters?.length };
    ctx.globals.set(sym, g);
    if (isExported(s)) exp.functions.push(g as Extract<Global, { kind: "function" }>);
    return;
  }
  if (ts.isVariableStatement(s)) {
    const list = s.declarationList;
    if (!(list.flags & (ts.NodeFlags.Let | ts.NodeFlags.Const))) fail(s, Codes.UnsupportedTopLevel, "use `let` or `const` instead of `var`");
    for (const d of list.declarations) {
      if (!ts.isIdentifier(d.name)) fail(d, Codes.UnsupportedTopLevel, "destructuring at the top level is not supported");
      const sym = checker.getSymbolAtLocation(d.name)!;
      const type = ctx.reg.lower(checker.getTypeOfSymbolAtLocation(sym, d.name), d.name);
      const g: Global = { kind: "var", cpp: `lucent_app::${m.ns}::${cppIdent(d.name.text)}`, module: m, decl: d, type, isConst: !!(list.flags & ts.NodeFlags.Const) };
      ctx.globals.set(sym, g);
      if (isExported(s)) exp.consts.push(g as Extract<Global, { kind: "var" }>);
    }
    return;
  }
  if (ts.isExportDeclaration(s)) fail(s, Codes.UnsupportedExport, "export lists and re-exports are not supported; export declarations directly");
  if (ts.isExportAssignment(s)) fail(s, Codes.UnsupportedExport, "default exports are not supported");
  if (ts.isEmptyStatement(s)) return;
  fail(s, Codes.UnsupportedTopLevel, "only declarations are allowed at the top level of a Lucent module");
}

function emitFunction(ctx: Ctx, g: Extract<Global, { kind: "function" }>, decls: string[], defs: string[], genericFns: string[]): void {
  const s = g.decl;
  const ret = g.async ? (g.type.ret.k === "promise" ? g.type.ret.inner : g.type.ret) : g.type.ret;
  const em = new FnEmitter(ctx, { module: g.module, async: g.async, returnType: ret });
  let params: string[] = [];
  ctx.guard(() => {
    params = em.emitParams(s, g.params);
    em.emitFunctionBody(s);
  });
  const retCpp = g.async ? `lucent::Promise<${ctx.reg.cppRet(ret)}>` : ctx.reg.cppRet(ret);
  const name = cppIdent(s.name!.text);
  if (g.generic) {
    const tmpl = `template <${s.typeParameters!.map((p) => `class ${cppIdent(p.name.text)}`).join(", ")}>`;
    genericFns.push(`namespace ${g.module.ns} {\n${tmpl}\n${retCpp} ${name}(${params.join(", ")}) {\n${em.body().join("\n")}\n}\n}  // namespace ${g.module.ns}`);
    decls.push(`${tmpl}\n${retCpp} ${name}(${params.join(", ")});`);
    return;
  }
  decls.push(`${retCpp} ${name}(${params.join(", ")});`);
  defs.push(`${retCpp} ${g.module.ns}::${name}(${params.join(", ")}) {\n${em.body().join("\n")}\n}`);
}

function topoSort(modules: LucentModule[], deps: Map<LucentModule, LucentModule[]>): LucentModule[] {
  const out: LucentModule[] = [];
  const state = new Map<LucentModule, number>();
  const visit = (m: LucentModule) => {
    if (state.get(m) === 2) return;
    if (state.get(m) === 1) return; // cycle: keep file order
    state.set(m, 1);
    for (const d of deps.get(m) ?? []) visit(d);
    state.set(m, 2);
    out.push(m);
  };
  modules.forEach(visit);
  return out;
}

function jsonWriters(ctx: Ctx): { decls: string[]; defs: string[] } {
  const decls: string[] = [];
  const defs: string[] = [];
  for (const s of ctx.reg.structs.values()) {
    const t = `lucent::Ref<${s.cppName}>`;
    decls.push(`void jsonWrite(lucent::JsonWriter& w, const ${t}& v);`);
    const fields = s.fields.map((f) => `  lucent::jsonField(w, first, ${cppQuoted(f.name)}, v->${cppIdent(f.name)});`);
    defs.push(`inline void jsonWrite(lucent::JsonWriter& w, const ${t}& v) {\n  if (!v) { w.raw("null"); return; }\n  w.raw("{");\n  bool first = true;\n${fields.join("\n")}\n  (void)first;\n  w.raw("}");\n}`);
  }
  for (const c of ctx.reg.classes.values()) {
    if (c.typeParams.length) continue;
    const t = `lucent::Ref<${c.cppName}>`;
    decls.push(`void jsonWrite(lucent::JsonWriter& w, const ${t}& v);`);
    const fields: string[] = [];
    ctx.guard(() => {
      for (const m of publicMembers(ctx, c)) if (m.kind === "field") fields.push(`  lucent::jsonField(w, first, ${cppQuoted(m.name)}, v->${cppIdent(m.name)});`);
    });
    defs.push(`inline void jsonWrite(lucent::JsonWriter& w, const ${t}& v) {\n  if (!v) { w.raw("null"); return; }\n  w.raw("{");\n  bool first = true;\n${fields.join("\n")}\n  (void)first;\n  w.raw("}");\n}`);
  }
  return { decls, defs };
}

/** The JavaScript that replaces a `*.lucent.ts` module in the app bundle. */
function jsProxy(m: ModuleExports): string {
  const lines = [
    "// Generated by Lucent. Do not edit.",
    '"use strict";',
    'Object.defineProperty(exports, "__esModule", { value: true });',
    'const { loadModule, lucentClass } = require("@lucent-lang/runtime");',
    // `react-native` is required from the app's own location, so the app's
    // copy is used even in monorepos with several versions installed.
    `const m = loadModule(${JSON.stringify(m.module.name)}, () => require("react-native").TurboModuleRegistry);`,
  ];
  for (const f of m.functions) lines.push(`exports.${f.decl.name!.text} = m.${f.decl.name!.text};`);
  for (const c of m.classes) lines.push(`exports.${c.decl.name!.text} = lucentClass(m.${c.decl.name!.text});`);
  for (const c of m.consts) lines.push(`exports.${c.decl.name.getText()} = m.${c.decl.name.getText()};`);
  for (const e of m.enums) {
    const entries: string[] = [];
    for (const mem of e.members) {
      entries.push(`${JSON.stringify(mem.name)}: ${JSON.stringify(mem.value)}`);
      if (typeof mem.value === "number") entries.push(`${JSON.stringify(String(mem.value))}: ${JSON.stringify(mem.name)}`);
    }
    lines.push(`exports.${e.name} = Object.freeze({ ${entries.join(", ")} });`);
  }
  return lines.join("\n") + "\n";
}

export type { ClassInfo };
export { unionOf };
