import ts from "typescript";
import { Codes, fail } from "../diagnostics.ts";
import {
  findSdkType,
  jniDescriptor,
  parseSdkType,
  type SdkClassSchema,
  type SdkMethodSchema,
} from "../sdk/schema.ts";
import type { ClassInfo, LType } from "../types.ts";

/** An SDK class's instance methods, its SDK superclasses' included, with the module each is typed in. */
export function sdkInstanceMethods(
  base: LType & { k: "native" },
): { module: string; cls: SdkClassSchema; method: SdkMethodSchema }[] {
  const out: { module: string; cls: SdkClassSchema; method: SdkMethodSchema }[] = [];
  const seen = new Set<string>();
  for (let t: { module: string; name: string } | undefined = base; t;) {
    const cls = findSdkType("android", t.module, t.name);
    if (cls?.kind !== "class") break;
    for (const m of cls.methods ?? []) {
      if (m.static) continue;
      const key = javaKey(m);
      if (seen.has(key)) continue;
      seen.add(key);
      out.push({ module: t.module, cls, method: m });
    }
    const up = cls.extends ? parseSdkType(cls.extends, t.module) : undefined;
    t = up?.k === "ref" ? up : undefined;
  }
  return out;
}

/** A Java method's dispatch key: name and parameter descriptor, as NativeProxy computes it. */
export function javaKey(m: SdkMethodSchema): string {
  const d =
    m.descriptor ??
    jniDescriptor(
      m.params.map((p) => p.type),
      m.returns,
      m.typeParams,
    );
  return `${m.java ?? m.name}${d.slice(0, d.indexOf(")") + 1)}`;
}

/** The generated Java subclass that stands for instances of `info` (JNI name). */
export function javaSubclassName(info: ClassInfo): string {
  return `dev/lucent/generated/${info.cppName.replace(/^C_/, "")}`;
}

/**
 * The Java subclass of a Lucent class's SDK base: it overrides the methods
 * the Lucent class defines (and any abstract ones, which then throw
 * AbstractMethodError), each forwarding to C++ with NativeProxy's keys; the
 * others keep the SDK's body. Made with the handle of the C++ side, released
 * when Java collects the object.
 */
export function javaSubclass(info: ClassInfo): { path: string; source: string } {
  const base = info.sdkBase!;
  const baseCls = findSdkType("android", base.module, base.name);
  if (baseCls?.kind !== "class")
    fail(info.decl, Codes.UnsupportedClassFeature, `${base.name} has no binding`);
  if (baseCls.interface)
    fail(info.decl, Codes.UnsupportedClassFeature, `${base.name} is an interface: implement it`);
  if (!(baseCls.constructors ?? []).some((c) => !c.params.length))
    fail(
      info.decl,
      Codes.UnsupportedClassFeature,
      `${base.name} has no public constructor without arguments to extend`,
    );
  const defined = new Set(
    info.decl.members
      .filter(
        (m): m is ts.MethodDeclaration =>
          ts.isMethodDeclaration(m) && !!m.body && ts.isIdentifier(m.name),
      )
      .map((m) => (m.name as ts.Identifier).text),
  );
  const name = javaSubclassName(info).split("/").pop()!;
  const methods: string[] = [];
  for (const { method } of sdkInstanceMethods(base)) {
    if (!method.abstract && !defined.has(method.name)) continue;
    const d =
      method.descriptor ??
      jniDescriptor(
        method.params.map((p) => p.type),
        method.returns,
        method.typeParams,
      );
    const { params, ret } = javaTypes(d);
    const args = params.map((_, i) => `a${i}`);
    const dispatch = `NativeProxy.dispatch(handle, ${JSON.stringify(javaKey(method))}, new Object[] {${args.join(", ")}})`;
    const body = ret === "void" ? `    ${dispatch};` : `    return ${unboxed(ret, dispatch)};`;
    methods.push(
      `  @Override\n  public ${ret} ${method.java ?? method.name}(${params.map((p, i) => `${p} ${args[i]}`).join(", ")}) {\n${body}\n  }`,
    );
  }
  const source = [
    "// Generated by Lucent. Do not edit.",
    "package dev.lucent.generated;",
    "",
    "import dev.lucent.NativeProxy;",
    "",
    `/** Lucent's ${info.decl.name?.text ?? name}: forwards to its C++ side. */`,
    `public final class ${name} extends ${javaName(baseCls.native)} {`,
    "  private final long handle;",
    "",
    `  public ${name}(long handle) {`,
    "    super();",
    "    this.handle = handle;",
    "  }",
    "",
    ...methods.flatMap((m) => [m, ""]),
    "  @Override",
    '  @SuppressWarnings({"deprecation", "removal"})',
    "  protected void finalize() throws Throwable {",
    "    try {",
    "      NativeProxy.releaseHandle(handle);",
    "    } finally {",
    "      super.finalize();",
    "    }",
    "  }",
    "}",
    "",
  ].join("\n");
  return { path: `${javaSubclassName(info)}.java`, source };
}

/** `android/net/ConnectivityManager$NetworkCallback` → `android.net.ConnectivityManager.NetworkCallback`. */
function javaName(internal: string): string {
  return internal.replace(/[/$]/g, ".");
}

/** Java source types of a JNI method descriptor. */
function javaTypes(descriptor: string): { params: string[]; ret: string } {
  let p = 1;
  const one = (): string => {
    const c = descriptor[p++]!;
    switch (c) {
      case "Z":
        return "boolean";
      case "B":
        return "byte";
      case "C":
        return "char";
      case "S":
        return "short";
      case "I":
        return "int";
      case "J":
        return "long";
      case "F":
        return "float";
      case "D":
        return "double";
      case "V":
        return "void";
      case "[":
        return `${one()}[]`;
      case "L": {
        const end = descriptor.indexOf(";", p);
        const name = descriptor.slice(p, end);
        p = end + 1;
        return javaName(name);
      }
      default:
        throw new Error(`bad descriptor ${descriptor}`);
    }
  };
  const params: string[] = [];
  while (descriptor[p] !== ")") params.push(one());
  p++;
  return { params, ret: one() };
}

/** What a forwarded method returns: boxed results unboxed, others cast. */
function unboxed(type: string, call: string): string {
  const boxes: Record<string, string> = {
    boolean: "Boolean",
    byte: "Byte",
    char: "Character",
    short: "Short",
    int: "Integer",
    long: "Long",
    float: "Float",
    double: "Double",
  };
  const box = boxes[type];
  if (box) return `((${box}) ${call}).${type}Value()`;
  return `(${type}) ${call}`;
}
