import { defineConfig } from "vite-plus";
import TimedSequencer from "./config/vitest.sequencer.ts";

// Left alone by vp fmt and vp lint: what scripts generate (formatting it would
// only make the next run's output differ), vendored code, and native projects.
const generated = [
  // Built and copied by the package build.
  "packages/*/dist/**",
  "packages/lucent/lib/**",
  "packages/lucent/runtime/**",
  "**/.lucent/**",
  // Vendored, and generated by scripts/gen-unicode.ts.
  "packages/runtime/cpp/third_party/**",
  "packages/runtime/cpp/lucent/unicode_data.inc",
  // Written by scripts/website.ts, which checks them byte for byte.
  "apps/website/src/generated/**",
  "apps/website/static/schemas/**",
  // Docs pages and posts: formatting would move JSX inside a list item (a <Steps> step)
  // out of the item, and scripts/website.ts writes the reference pages byte for byte.
  "apps/website/src/content/**",
  // Docusaurus's generated files and its build.
  "apps/website/.docusaurus/**",
  "apps/website/build/**",
  // Written by lucent sdk coverage --json.
  "config/sdk-coverage.json",
  // Written by scripts/sync-examples.ts from the e2e cases and scripts/example-app.
  "apps/bare-example/src/**",
  "apps/expo-example/src/**",
  // Xcode and Gradle projects.
  "apps/*/ios/**",
  "apps/*/android/**",
  // The documentation's one-file component, kept byte for byte as it is published.
  "apps/bare-example/.views-spike/like.lucent.tsx",
];

/**
 * The slow tests: they build and run whole programs with the platforms'
 * toolchains (Swift, the JVM, Mac Catalyst, Gradle), or extract an SDK into
 * an empty cache, minutes where the others take seconds. CI runs them, and
 * so does `pnpm test:all`; a plain `pnpm test` here leaves them out.
 */
const slow = [
  "packages/compiler/test/platforms-cold-sdk.test.ts",
  "packages/compiler/test/swift-shims.test.ts",
  "packages/compiler/test/swift-overloads.test.ts",
  "packages/compiler/test/swift-shapes.test.ts",
  "packages/compiler/test/swift-requirements.test.ts",
  "packages/compiler/test/ios-subclass.test.ts",
  "packages/compiler/test/kotlin-shims.test.ts",
  "packages/compiler/test/unknown-library.test.ts",
  "packages/compiler/test/ui/*-run.test.ts",
  "packages/lucent/test/android-project.test.ts",
  "packages/lucent/test/bare-example-bundle.test.ts",
  "packages/lucent/test/component-types.test.ts",
  "packages/lucent/test/swift-packages.test.ts",
];
const all = !!process.env.CI || !!process.env.LUCENT_ALL_TESTS;

// Only when vitest loads the config: lint and format load it too.
if (!all && process.env.VITEST)
  console.log(
    `Leaving out the ${slow.length} slow test groups (vite.config.ts); pnpm test:all runs them.`,
  );

export default defineConfig({
  test: {
    include: [
      "packages/*/test/**/*.test.ts",
      "apps/website/test/**/*.test.ts",
      // The example app's plain logic (routes, summaries), without React Native.
      "scripts/example-app/**/*.test.ts",
      // The repository's own scripts (the CI change classifier).
      "scripts/*.test.ts",
    ],
    exclude: ["**/node_modules/**", "**/.git/**", ...(all ? [] : slow)],
    testTimeout: 60000,
    // Shards balanced by each file's time (config/test-timings.json), not by its path.
    sequence: { sequencer: TimedSequencer },
    globalSetup: [
      "./config/vitest.setup-tmp.ts",
      "./config/vitest.setup-sdk.ts",
      "./config/vitest.setup-build.ts",
    ],
    setupFiles: ["./config/vitest.setup-yield.ts"],
    // As on CI, wherever the tests run: libraries that change behaviour under CI
    // (Ink renders only the last frame) do so locally too.
    env: { CI: "true" },
  },
  // Oxfmt's defaults.
  fmt: { ignorePatterns: generated },
  lint: {
    ignorePatterns: generated,
    plugins: ["eslint", "typescript", "unicorn", "oxc", "import", "promise", "react", "vitest"],
    categories: { correctness: "error", suspicious: "error" },
    // No type-aware rules or type check (tsgolint): it checks the Lucent
    // modules tsconfig.json leaves out, whose lucent: imports only resolve
    // through Lucent's editor plugin, with TypeScript's Go port rather than
    // the repository's TypeScript. pnpm typecheck runs tsc on the project.
    rules: {
      // Every package compiles JSX with the automatic runtime (react/jsx-runtime).
      "react/react-in-jsx-scope": "off",
      // Every sort() here sorts an array the code just built (a spread, keys,
      // readdirSync, a map), where sorting in place is the point; none sorts a
      // caller's array.
      "unicorn/no-array-sort": "off",
      // Helpers stay beside their only caller; hoisting them to module scope
      // spreads one function's logic across the file.
      "unicorn/consistent-function-scoping": "off",
      // The dangling names are someone else's: React Native and JSI globals
      // (__turboModuleProxy, __lucentModules), build-time defines
      // (__LUCENT_EXTRACTOR__), and the ES5 scripts the JSI harness runs.
      "eslint/no-underscore-dangle": "off",
      // Inner scopes reuse a name for the same concept (args, c, f, name); none
      // of the findings was a bug.
      "eslint/no-shadow": "off",
      // new Array(n) only makes sized arrays (a class file's constant pool, a
      // diff table); TypeScript types n as a number, which is the ambiguity the
      // rule guards against.
      "unicorn/no-new-array": "off",
      // then() callbacks here run side effects (assertions, logging); a return
      // value would mean nothing to the chain.
      "promise/always-return": "off",
      // NetInfo.fetch and stylex.vite are how those packages document their
      // default exports.
      "import/no-named-as-default-member": "off",
      // Vitest takes a failure message as expect's second argument.
      "vitest/valid-expect": ["error", { maxArgs: 2 }],
      // Tests that compile for every target assert through this helper.
      "vitest/expect-expect": ["error", { assertFunctionNames: ["expect", "compilesEverywhere"] }],
      // Stylesheets are imported for their side effect.
      "import/no-unassigned-import": ["error", { allow: ["**/*.css"] }],
    },
    overrides: [
      {
        // A Lucent file's JSX is its platforms' toolkits' (SwiftUI's, Compose's),
        // not React's: its component's setup runs once, and its body's calls
        // are the toolkit's (`Environment(…)`, `LaunchedEffect(…)`).
        files: ["**/*.lucent.tsx"],
        rules: {
          "react/purity": "off",
          "react/capitalized-calls": "off",
        },
      },
      {
        // Each e2e case exercises JavaScript semantics, including the ones
        // these rules warn about (lost precision, errors without a cause,
        // settling a promise twice); the code is the test's data, run on Node
        // and compiled to C++, and the outputs compared.
        files: ["packages/compiler/test/e2e/cases/**"],
        rules: {
          "eslint/no-loss-of-precision": "off",
          "eslint/preserve-caught-error": "off",
          "unicorn/prefer-string-starts-ends-with": "off",
          "unicorn/no-array-reverse": "off",
          "promise/no-multiple-resolved": "off",
          "oxc/approx-constant": "off",
        },
      },
      {
        // The example app's screens start their work once, on mount (tests,
        // benchmarks, SDK calls), and App reads the status bar height again once
        // mounted, as Android only knows it then.
        files: ["scripts/example-app/**", "apps/bare-example/App.tsx", "apps/expo-example/App.tsx"],
        rules: {
          "react/set-state-in-effect": "off",
          "react/exhaustive-effect-dependencies": "off",
        },
      },
    ],
  },
});
