// Generated by Lucent. Do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const { loadModule, lucentClass } = require("./_lucent/runtime.js");
const m = loadModule("counter", () => require("react-native").TurboModuleRegistry, require("./_lucent/identity.js"));
exports.bump = m.bump;
exports.around = m.around;
exports.steps = m.steps;
