// Generated by Lucent. Do not edit.
#include "m_generic_u2d_instantiations.h"
#include "lucent_app_C_Shown.h"
#include "lucent_app_S_Object_ca633bfa.h"
#include "lucent_app_C_Sub.h"
#include <lucent/jsi/convert.h>
#include <lucent/jsi/host.h>

#pragma push_macro("arrays")
#undef arrays
#pragma push_macro("identity")
#undef identity
#pragma push_macro("positions")
#undef positions
#pragma push_macro("v")
#undef v

namespace lucent::js {

jsi::Value errorInstanceToJs(jsi::Runtime& rt, Host& h, const Error& v) {
  return jsi::Value::undefined();
}

}  // namespace lucent::js

namespace {

using namespace lucent::js;

void install_m_generic_u2d_instantiations(jsi::Runtime& rt, Host& host, jsi::Object& exports) {
  defineFunction(rt, exports, "arrays", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("arrays", "packages/compiler/test/e2e/cases/generic-instantiations.lucent.ts", 29), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_generic_u2d_instantiations::arrays());
    });
  });
  defineFunction(rt, exports, "positions", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("positions", "packages/compiler/test/e2e/cases/generic-instantiations.lucent.ts", 48), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_generic_u2d_instantiations::positions());
    });
  });
  defineFunction(rt, exports, "identity", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("identity", "packages/compiler/test/e2e/cases/generic-instantiations.lucent.ts", 76), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_generic_u2d_instantiations::identity());
    });
  });
}

const ModuleDef kModules[] = {{"generic-instantiations", install_m_generic_u2d_instantiations}};

}  // namespace

namespace lucent::js {

const ModuleDef* registeredModules(size_t& count) {
  count = 1;
  return kModules;
}

void resetModuleState() {
  lucent_app::m_generic_u2d_instantiations::init();
}

}  // namespace lucent::js

#pragma pop_macro("v")
#pragma pop_macro("positions")
#pragma pop_macro("identity")
#pragma pop_macro("arrays")
