// Generated by Lucent from generic-instantiations.lucent.ts. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_C_Shown.h"

#pragma push_macro("arrays")
#undef arrays
#pragma push_macro("give")
#undef give
#pragma push_macro("identity")
#undef identity
#pragma push_macro("positions")
#undef positions
#pragma push_macro("shows")
#undef shows
#pragma push_macro("take")
#undef take

namespace lucent_app {

namespace m_generic_u2d_instantiations {

lucent::String shows(lucent::Array<lucent::Ref<lucent_app::C_Shown<lucent::Opt<double>>>> p0_);
lucent::String take(lucent::Ref<lucent_app::C_Shown<lucent::Opt<double>>> p0_);
lucent::Ref<lucent_app::C_Shown<lucent::Opt<double>>> give();
lucent::String arrays();
lucent::String positions();
lucent::String identity();
void init();

}  // namespace m_generic_u2d_instantiations

}  // namespace lucent_app

#pragma pop_macro("take")
#pragma pop_macro("shows")
#pragma pop_macro("positions")
#pragma pop_macro("identity")
#pragma pop_macro("give")
#pragma pop_macro("arrays")
