// Generated by scripts/sync-examples.ts from scripts/example-app. Do not edit.
// NitroBenchmarks (github.com/mrousavy/NitroBenchmarks) with Lucent next to
// the native module kinds it compares: 100,000 calls of addNumbers and of
// addStrings through each.
import { useEffect, useState } from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import { modules } from "../compare/modules";
import { RUNS, timeNumbers, timeStrings, warmup } from "../compare/timeCalls";
import type { CompareModule } from "../compare/types";
import { styles } from "./styles";

/** Each loop runs this many times, interleaved across modules; the best counts. */
const ROUNDS = 3;

type Row = { name: string; numbers: number; strings: number; error?: string };

const tick = () => new Promise<void>((r) => setTimeout(() => r(), 30));
const ms = (v: number) => (Number.isFinite(v) ? v.toFixed(2) : "–");

function best(rows: Row[], key: "numbers" | "strings", lucent: boolean): number {
  return Math.min(...rows.filter((r) => (r.name === "Lucent") === lucent && !r.error).map((r) => r[key]));
}

export function CompareScreen() {
  const [rows, setRows] = useState<Row[]>([]);
  const [running, setRunning] = useState(false);

  async function run() {
    setRunning(true);
    const out: Row[] = modules.map((m) => ({ name: m.name, numbers: Infinity, strings: Infinity }));
    setRows(out.map((r) => ({ ...r })));
    const attempt = (i: number, f: (m: CompareModule) => void) => {
      if (out[i]!.error) return;
      try {
        f(modules[i]!);
      } catch (e) {
        out[i]!.error = e instanceof Error ? e.message : String(e);
      }
    };
    modules.forEach((_, i) => attempt(i, (m) => warmup(m.module)));
    for (const key of ["numbers", "strings"] as const) {
      const time = key === "numbers" ? timeNumbers : timeStrings;
      for (let round = 0; round < ROUNDS; round++) {
        for (let i = 0; i < modules.length; i++) {
          await tick();
          attempt(i, (m) => (out[i]![key] = Math.min(out[i]![key], time(m.module))));
          setRows(out.map((r) => ({ ...r })));
        }
      }
    }
    setRunning(false);
  }

  useEffect(() => {
    void run();
  }, []);

  const done = !running && rows.length > 0;
  const ratio = (key: "numbers" | "strings") => (best(rows, key, false) / best(rows, key, true)).toFixed(2);

  return (
    <>
      <View style={styles.header}>
        <Text style={styles.title}>Lucent vs native modules</Text>
        <Text style={styles.subtitle}>
          NitroBenchmarks: {RUNS.toLocaleString("en-US")} calls of addNumbers(num, 5) and addStrings("hello ", "world"). Best of {ROUNDS}, in ms.
        </Text>
        {__DEV__ ? <Text style={styles.warn}>Debug build: use a Release build for representative numbers.</Text> : null}
        <Text testID="compare-summary" style={[styles.summary, done && styles.ok]}>
          {running ? "Running…" : done ? `fastest other ÷ Lucent: numbers ${ratio("numbers")}x, strings ${ratio("strings")}x` : ""}
        </Text>
        <Pressable testID="compare-run" disabled={running} onPress={run} style={({ pressed }) => [styles.button, (pressed || running) && styles.pressed]}>
          <Text style={styles.buttonText}>Run again</Text>
        </Pressable>
      </View>
      <ScrollView contentContainerStyle={styles.list}>
        <View style={styles.benchHead}>
          <Text style={styles.benchHeadName}>module</Text>
          <Text style={styles.benchHeadCell}>addNumbers</Text>
          <Text style={styles.benchHeadCell}>addStrings</Text>
        </View>
        {rows.map((r) => (
          <View key={r.name} testID={`compare-${r.name}`} style={styles.benchRow}>
            <Text style={[styles.benchName, r.name === "Lucent" && styles.ok]}>{r.error ? `❌ ${r.name}` : r.name}</Text>
            <Text style={styles.benchCell}>{r.error ?? ms(r.numbers)}</Text>
            <Text style={styles.benchCell}>{r.error ? "" : ms(r.strings)}</Text>
          </View>
        ))}
      </ScrollView>
    </>
  );
}
