// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("kids")
#undef kids
#pragma push_macro("name")
#undef name
#pragma push_macro("v")
#undef v

namespace lucent_app {

struct S_Doc;

struct S_Doc : lucent::Object {
  lucent::String name{};
  lucent::Opt<lucent::Map<lucent::String, lucent::Ref<lucent_app::S_Doc>>> kids{};
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Doc>& v);

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Doc>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "name", v->name);
  lucent::jsonField(w, first, "kids", v->kids);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("v")
#pragma pop_macro("name")
#pragma pop_macro("kids")
