// Generated by Lucent from recursive-shapes.lucent.ts. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("evens")
#undef evens
#pragma push_macro("grow")
#undef grow
#pragma push_macro("lenA")
#undef lenA
#pragma push_macro("lenB")
#undef lenB
#pragma push_macro("names")
#undef names
#pragma push_macro("selfs")
#undef selfs
#pragma push_macro("size")
#undef size
#pragma push_macro("sum")
#undef sum
#pragma push_macro("treeSize")
#undef treeSize

namespace lucent_app {

namespace m_recursive_u2d_shapes {

double size(lucent::Ref<lucent_app::S_TreeNode> p0_);
double treeSize(lucent::Ref<lucent_app::S_TreeNode> p0_);
lucent::Ref<lucent_app::S_TreeNode> grow(lucent::Ref<lucent_app::S_TreeNode> p0_);
double lenA(lucent::Ref<lucent_app::S_ListA> p0_);
double lenB(lucent::Ref<lucent_app::S_ListA> p0_);
lucent::String evens(lucent::Ref<lucent_app::S_Even> p0_);
lucent::String selfs(lucent::Ref<lucent_app::S_Self> p0_);
double sum(std::variant<lucent::Ref<lucent_app::S_Object7>, lucent::Ref<lucent_app::S_Object6>> p0_);
lucent::String names(lucent::Ref<lucent_app::S_Doc> p0_);
void init();

}  // namespace m_recursive_u2d_shapes

}  // namespace lucent_app

#pragma pop_macro("treeSize")
#pragma pop_macro("sum")
#pragma pop_macro("size")
#pragma pop_macro("selfs")
#pragma pop_macro("names")
#pragma pop_macro("lenB")
#pragma pop_macro("lenA")
#pragma pop_macro("grow")
#pragma pop_macro("evens")
