// Generated by scripts/sync-examples.ts from the app's benchmarks/* dependencies. Do not edit.
import * as Lucent from "./compare.lucent";
import type { CompareModule } from "./types";

export const modules: CompareModule[] = [
  { name: "TurboModule", load: () => require("bench-turbo").BenchTurbo },
  { name: "NitroModule", load: () => require("bench-nitro").BenchNitro },
  { name: "CxxNitroModule", load: () => require("bench-nitro").BenchNitroCxx },
  { name: "CxxTurboModule", load: () => require("bench-turbo-cxx").BenchTurboCxx },
  { name: "Lucent", load: () => Lucent },
];
