// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("line")
#undef line

namespace lucent_app {

struct C_ParseError;

struct C_ParseError : lucent::ErrorObject {
  double line{};
  void construct(lucent::String p0_, double p1_);
  static lucent::Ref<C_ParseError> create(lucent::String p0_, double p1_);
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_ParseError::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "line", this->line);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("line")
