// Generated by Lucent from exported-errors.lucent.ts. Do not edit.
#include "m_exported_u2d_errors.h"
#include "lucent_app_C_TokenError.h"

#pragma push_macro("asError")
#undef asError
#pragma push_macro("describe")
#undef describe
#pragma push_macro("fail")
#undef fail
#pragma push_macro("failToken")
#undef failToken
#pragma push_macro("kind")
#undef kind
#pragma push_macro("later")
#undef later
#pragma push_macro("line")
#undef line
#pragma push_macro("message")
#undef message
#pragma push_macro("parse")
#undef parse
#pragma push_macro("raise")
#undef raise
#pragma push_macro("token")
#undef token

namespace lucent_app {

void C_ParseError::construct(lucent::String p0_, double p1_) {
  this->name = LUCENT_STR("Error");
  this->line = p1_;
  (void)(this->message = p0_, lucent::undefined);
  this->name = LUCENT_STR("ParseError");
}

lucent::Ref<C_ParseError> C_ParseError::create(lucent::String p0_, double p1_) {
  auto self = std::make_shared<C_ParseError>();
  self->construct(p0_, p1_);
  return self;
}

void C_TokenError::construct(lucent::String p0_) {
  lucent::String v2_ = lucent::String(LUCENT_STR("unexpected ")) + p0_;
  this->lucent_app::C_ParseError::construct(v2_, 1.0);
  this->token = p0_;
  this->name = LUCENT_STR("TokenError");
}

lucent::Ref<C_TokenError> C_TokenError::create(lucent::String p0_) {
  auto self = std::make_shared<C_TokenError>();
  self->construct(p0_);
  return self;
}

lucent::Ref<lucent_app::C_ParseError> m_exported_u2d_errors::parse(double p0_) {
  lucent::String v3_ = lucent::String(LUCENT_STR("bad line ")) + lucent::toJsString(p0_);
  return lucent_app::C_ParseError::create(v3_, p0_);
}

lucent::Error m_exported_u2d_errors::asError(double p0_) {
  lucent::String v3_ = lucent::String(LUCENT_STR("as error ")) + lucent::toJsString(p0_);
  lucent::Ref<lucent_app::C_ParseError> v4_ = lucent_app::C_ParseError::create(v3_, p0_);
  return lucent::Error(v4_);
}

double m_exported_u2d_errors::fail(double p0_) {
  lucent::String v3_ = lucent::String(LUCENT_STR("failed at ")) + lucent::toJsString(p0_);
  lucent::Ref<lucent_app::C_ParseError> v4_ = lucent_app::C_ParseError::create(v3_, p0_);
  lucent::throwError(v4_);
}

double m_exported_u2d_errors::failToken(lucent::String p0_) {
  lucent::Ref<lucent_app::C_TokenError> v1_ = lucent_app::C_TokenError::create(p0_);
  lucent::throwError(v1_);
}

lucent::Promise<double> m_exported_u2d_errors::later(double p0_) {
  try {
    lucent::String v3_ = lucent::String(LUCENT_STR("later ")) + lucent::toJsString(p0_);
    lucent::Ref<lucent_app::C_ParseError> v4_ = lucent_app::C_ParseError::create(v3_, p0_);
    lucent::throwError(v4_);
  } catch (...) {
    return lucent::Promise<double>::rejected(lucent::currentError(std::current_exception()));
  }
}

void m_exported_u2d_errors::raise(lucent::Ref<lucent_app::C_ParseError> p0_) {
  lucent::throwError(p0_);
}

lucent::String m_exported_u2d_errors::describe(lucent::Ref<lucent_app::C_ParseError> p0_) {
  lucent::String v1_ = p0_->name;
  lucent::String v3_ = p0_->message;
  double v5_ = p0_->line;
  lucent::String v6_ = lucent::toJsString(v5_);
  return lucent::concat(v1_, LUCENT_STR(": "), v3_, LUCENT_STR(" @"), v6_);
}

lucent::String m_exported_u2d_errors::kind(lucent::Error p0_) {
  bool v1_ = lucent::isInstance<lucent_app::C_TokenError>(p0_);
  if (v1_) {
    lucent::Ref<lucent_app::C_TokenError> v3_ = lucent::downcast<lucent_app::C_TokenError>(p0_);
    lucent::String v4_ = v3_->token;
    return lucent::String(LUCENT_STR("token ")) + v4_;
  }
  bool v6_ = lucent::isInstance<lucent_app::C_ParseError>(p0_);
  if (v6_) {
    lucent::Ref<lucent_app::C_ParseError> v8_ = lucent::downcast<lucent_app::C_ParseError>(p0_);
    double v9_ = v8_->line;
    return lucent::String(LUCENT_STR("parse ")) + lucent::toJsString(v9_);
  }
  lucent::String v13_ = p0_->message;
  return lucent::String(LUCENT_STR("error ")) + v13_;
}

void m_exported_u2d_errors::init() {
}

}  // namespace lucent_app

#pragma pop_macro("token")
#pragma pop_macro("raise")
#pragma pop_macro("parse")
#pragma pop_macro("message")
#pragma pop_macro("line")
#pragma pop_macro("later")
#pragma pop_macro("kind")
#pragma pop_macro("failToken")
#pragma pop_macro("fail")
#pragma pop_macro("describe")
#pragma pop_macro("asError")
