// Generated by Lucent from boundary-paths.lucent.ts. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("asked")
#undef asked
#pragma push_macro("awaited")
#undef awaited
#pragma push_macro("mapped")
#undef mapped
#pragma push_macro("nested")
#undef nested
#pragma push_macro("sizes")
#undef sizes
#pragma push_macro("total")
#undef total

namespace lucent_app {

namespace m_boundary_u2d_paths {

double total(lucent::Array<double> p0_);
double sizes(lucent::Dict<lucent::Array<double>> p0_);
double mapped(lucent::Array<double> p0_, lucent::Fn<double(double)> p1_);
double nested(lucent::Dict<lucent::Fn<double(double)>> p0_);
lucent::Promise<double> awaited(lucent::Promise<double> p0_);
lucent::Promise<lucent::String> asked(lucent::Fn<lucent::Promise<lucent::String>(lucent::String)> p0_);
void init();

}  // namespace m_boundary_u2d_paths

}  // namespace lucent_app

#pragma pop_macro("total")
#pragma pop_macro("sizes")
#pragma pop_macro("nested")
#pragma pop_macro("mapped")
#pragma pop_macro("awaited")
#pragma pop_macro("asked")
