// Generated by scripts/sync-examples.ts from scripts/example-app. Do not edit.
// expo-clipboard's ClipboardModule.kt (plain text).
import { ClipboardManager, ClipData, ClipDescription } from "lucent:android/android.content";
import { appContext } from "lucent:android";
import { main } from "lucent:thread";
import { error } from "@lucent-lang/core";

function clipboard(): ClipboardManager {
  const manager = appContext().getSystemService(ClipboardManager);
  if (!manager) throw error("ERR_CLIPBOARD_UNAVAILABLE", "The clipboard is not available");
  return manager;
}

export function getStringAsync(): Promise<string> {
  // Android only lets the focused app read the clipboard; its callbacks run on the main thread.
  return main(() => {
    const clip = clipboard().getPrimaryClip();
    if (!clip || clip.getItemCount() === 0) return "";
    return clip.getItemAt(0)?.coerceToText(appContext()) ?? "";
  });
}

export function setStringAsync(text: string): Promise<boolean> {
  return main(() => {
    const clip = ClipData.newPlainText(null, text);
    if (!clip) return false;
    clipboard().setPrimaryClip(clip);
    return true;
  });
}

export function hasStringAsync(): Promise<boolean> {
  return main(() => clipboard().getPrimaryClipDescription()?.hasMimeType(ClipDescription.MIMETYPE_TEXT_PLAIN) ?? false);
}
