// Generated by scripts/sync-examples.ts from scripts/example-app. Do not edit.
// What the platform bindings do beyond haptics, as observable values.

/** The OS name from the SDK (UIDevice.systemName; "Android" + Build.VERSION.RELEASE). */
export declare function systemName(): Promise<string>;
/** Identity of platform objects, off and on the main thread. */
export declare function identity(): Promise<string>;
/** A platform error, as the Lucent error code it becomes. */
export declare function errorCode(): Promise<string>;
