// Generated by scripts/sync-examples.ts from scripts/example-app. Do not edit.
// expo-secure-store's SecureStoreModule.kt: values encrypted with an AES/GCM
// key from the Android Keystore, stored in SharedPreferences.
import { SharedPreferences } from "lucent:android/android.content";
import { KeyGenParameterSpec_Builder, KeyProperties } from "lucent:android/android.security.keystore";
import { Base64 } from "lucent:android/android.util";
import { KeyStore, KeyStore_SecretKeyEntry, type Key } from "lucent:android/java.security";
import { Cipher, KeyGenerator } from "lucent:android/javax.crypto";
import { GCMParameterSpec } from "lucent:android/javax.crypto.spec";
import { appContext } from "lucent:android";
import { error, utf8Decode, utf8Encode } from "@lucent-lang/core";

const ALIAS = "lucent-secure-store";

function prefs(): SharedPreferences {
  const p = appContext().getSharedPreferences("SecureStore", 0);
  if (!p) throw error("ERR_SECURESTORE", "No SharedPreferences");
  return p;
}

function key(): Key {
  const store = KeyStore.getInstance("AndroidKeyStore");
  store?.load(null);
  const entry = store?.getEntry(ALIAS, null);
  if (entry) return (entry as KeyStore_SecretKeyEntry).getSecretKey()!;
  const generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore");
  const spec = new KeyGenParameterSpec_Builder(ALIAS, KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT)
    .setBlockModes([KeyProperties.BLOCK_MODE_GCM])
    ?.setEncryptionPaddings([KeyProperties.ENCRYPTION_PADDING_NONE])
    ?.build();
  if (!generator || !spec) throw error("ERR_SECURESTORE", "Could not create the encryption key");
  generator.init(spec);
  return generator.generateKey()!;
}

export async function setItemAsync(name: string, value: string): Promise<void> {
  const cipher = Cipher.getInstance("AES/GCM/NoPadding");
  if (!cipher) throw error("ERR_SECURESTORE", "No AES/GCM cipher");
  cipher.init(Cipher.ENCRYPT_MODE, key());
  const encrypted = cipher.doFinal(utf8Encode(value)) ?? new Uint8Array(0);
  const iv = cipher.getIV() ?? new Uint8Array(0);
  const stored = `${Base64.encodeToString(iv, Base64.NO_WRAP)}:${Base64.encodeToString(encrypted, Base64.NO_WRAP)}`;
  if (!prefs().edit()?.putString(name, stored)?.commit()) throw error("ERR_SECURESTORE", "Could not save the value");
}

export async function getItemAsync(name: string): Promise<string | null> {
  const stored = prefs().getString(name, null);
  if (!stored) return null;
  const [iv, encrypted] = stored.split(":");
  const cipher = Cipher.getInstance("AES/GCM/NoPadding");
  if (!cipher || iv === undefined || encrypted === undefined) throw error("ERR_SECURESTORE", "Unreadable stored value");
  cipher.init(Cipher.DECRYPT_MODE, key(), new GCMParameterSpec(128, Base64.decode(iv, Base64.NO_WRAP)));
  const plain = cipher.doFinal(Base64.decode(encrypted, Base64.NO_WRAP));
  return plain ? utf8Decode(plain) : null;
}

export async function deleteItemAsync(name: string): Promise<void> {
  prefs().edit()?.remove(name)?.commit();
}
