/**
 * How an Android app hosts its Lucent components. In the native package: a
 * manager per component (the Java side of its views), the list
 * LucentPackage gives React Native, and the component's descriptor, which
 * React Native's autolinking adds to the renderer's registry from the
 * package's react-native.config.js (componentDescriptors) and the header
 * it includes for them. The C++ host glue is emit/views.ts's.
 */
import { cpp, java } from "@lucent-lang/codegen";
import type { ComponentDescription } from "./contract.ts";
import { VIEWS_DIR } from "./fabric.ts";

const JAVA = "android/src/main/java/dev/lucent";

/** Where autolinking includes the descriptors from: react/renderer/components/<libraryName>/. */
const DESCRIPTORS_HEADER =
  "android/include/react/renderer/components/lucentnative/ComponentDescriptors.h";

/**
 * The components Android implements, in registration order. While
 * Android's build is `deferred` (after expo prebuild, which compiles the
 * other platforms), every described component: a component on one
 * platform is one on every platform (ui/merge.ts), so Android's build
 * implements each of them, or fails.
 */
function androidComponents(
  components: readonly ComponentDescription[],
  deferred: boolean,
): ComponentDescription[] {
  return components
    .filter((c) => deferred || c.platforms.android)
    .toSorted((a, b) =>
      a.registration < b.registration ? -1 : a.registration > b.registration ? 1 : 0,
    );
}

/** The descriptor type autolinking registers for a component (runtime/cpp/rn/LucentViewsAndroid.h). */
export const hostDescriptor = (registration: string) =>
  `lucent::views::HostDescriptor<lucent::views::${registration}::ComponentDescriptor>`;

/**
 * The native package's files registering `components` on Android, by
 * path; none without any. `deferred`: Android's build comes later.
 */
export function androidViewFiles(
  components: readonly ComponentDescription[],
  deferred = false,
): Map<string, string> {
  const android = androidComponents(components, deferred);
  const files = new Map<string, string>();

  if (!android.length) return files;

  for (const c of android)
    files.set(`${JAVA}/generated/${c.registration}Manager.java`, managerSource(c));

  files.set(`${JAVA}/LucentViewManagers.java`, managersSource(android));
  files.set(DESCRIPTORS_HEADER, descriptorsHeader(android));

  return files;
}

/** react-native.config.js (the template's) listing the Android components' descriptors, if any. */
export function autolinkingConfig(
  template: string,
  components: readonly ComponentDescription[],
  deferred = false,
): string {
  const android = androidComponents(components, deferred);

  if (!android.length) return template;

  const list = android.map((c) => `          ${JSON.stringify(hostDescriptor(c.registration))},`);

  return template.replace(
    /^(\s*)(cxxModuleHeaderName: "LucentModule",)$/m,
    (_, indent: string, line: string) =>
      `${indent}${line}\n${indent}componentDescriptors: [\n${list.join("\n")}\n${indent}],`,
  );
}

function managerSource(c: ComponentDescription): string {
  const name = `${c.registration}Manager`;

  return java.printUnit({
    banner: `Generated by Lucent from ${c.id}. Do not edit.`,
    package: "dev.lucent.generated",
    imports: ["dev.lucent.LucentViewManager"],
    types: [
      java.cls(
        name,
        [
          java.constructor(
            ["public"],
            name,
            [],
            [
              java.exprStmt(
                java.call(undefined, "super", [
                  java.str(c.registration),
                  // Whether its views keep a slot for the React children it takes.
                  ...(c.children ? [java.bool(true)] : []),
                ]),
              ),
            ],
          ),
        ],
        {
          modifiers: ["public", "final"],
          extends: java.type("LucentViewManager"),
          doc: `The views of ${c.id}.`,
        },
      ),
    ],
  });
}

function managersSource(components: readonly ComponentDescription[]): string {
  const managers = components.map((c) =>
    java.newObject(java.type(`dev.lucent.generated.${c.registration}Manager`)),
  );

  return java.printUnit({
    banner: "Generated by Lucent. Do not edit.",
    package: "dev.lucent",
    imports: ["com.facebook.react.uimanager.ViewManager", "java.util.Arrays", "java.util.List"],
    types: [
      java.cls(
        "LucentViewManagers",
        [
          java.constructor(["private"], "LucentViewManagers", [], []),
          java.method(
            ["static"],
            java.type("List", java.type("ViewManager")),
            "create",
            [],
            [java.ret(java.call(java.name("Arrays"), "asList", managers))],
            { annotations: [java.annotation("SuppressWarnings", java.str("rawtypes"))] },
          ),
        ],
        { modifiers: ["final"], doc: "The managers of the app's Lucent components." },
      ),
    ],
  });
}

function descriptorsHeader(components: readonly ComponentDescription[]): string {
  return cpp.printUnit({
    banner: "Generated by Lucent. Do not edit.",
    decls: [
      {
        k: "comment",
        text: "React Native's autolinking includes it for the descriptors react-native.config.js lists.",
      },
      { k: "pragmaOnce" },
      cpp.include("LucentViewsAndroid.h"),
      ...components.map((c) => cpp.include(`${VIEWS_DIR}/${c.registration}.h`)),
    ],
  });
}
