/**
 * A component's Compose content (Android): the JSX the component returns
 * and its composition statements (ui/composition.ts), compiled to Kotlin,
 * next to the slots through which the setup's C++ reaches it.
 *
 * The body is Compose written in TypeScript: a composable showing UI is a
 * JSX element, whose props are Kotlin's named arguments and whose
 * children are its trailing @Composable content lambda
 * (`<Box modifier={…}><BasicText text={…} /></Box>`), or a function of
 * the lambda's scope (`{(row) => …}`). Calls, modifier chains,
 * `remember`, effects and animations are Compose's own:
 * each declaration's binding (compose-api.ts) says what it is in Kotlin,
 * its parameters' names, kinds and number types. What the
 * body takes from its setup crosses through a generated state holder, one
 * slot each:
 *
 * - a prop (`props.on`), a signal (`taps.get()`) or a value a setup
 *   function computes, called where the body composes (`caption()`), is a
 *   value slot: Compose state, which an effect of the setup sets whenever
 *   what it reads changes, so the body recomposes;
 * - a setup function the body calls from a callback, or passes as one
 *   (`clickable(tap)`), is an action slot: a Kotlin function whose calls
 *   run the Lucent function in the main context.
 *
 * toolkit-body.ts finds the slots, as SwiftUI bodies' are found.
 *
 * The generated file (`dev/lucent/compose/<registration>.kt`) holds the
 * state class (`<registration>State`), the composable
 * (`<registration>Content`) and the host object (`<registration>Host`),
 * which gives the content to the runtime's host (LucentComposition, in
 * the same package). Anything the body does that has no Kotlin form here
 * fails with a diagnostic.
 */
import { kotlin as kt } from "@lucent-lang/codegen";
import ts from "typescript";
import { Codes, fail } from "../diagnostics.ts";
import type { SdkParam } from "../sdk/schema.ts";
import {
  bindingOf,
  givesElements,
  isComposeDeclaration,
  type NumberKind,
  numberKindOf,
  receivesScope,
  schemaNumberKind,
} from "./compose-api.ts";
import { type ComposeBinding, type ComposeWrite, isElement } from "./compose-dts.ts";
import type { ViewField, ViewType } from "./contract.ts";
import {
  type ActionSlot,
  crossingOf,
  isBind,
  type ListSlot,
  type BodySetup,
  type Crossings,
  isAsync,
  keyOfUse,
  type ScalarType,
  skipParentheses,
  valueName,
} from "./toolkit-body.ts";
import type { FunctionLike } from "./roots.ts";
import {
  chainUse,
  type HelperCallback,
  helperArgs,
  helperAt,
  type HelperUse,
  type ViewHelper,
} from "./view-helpers.ts";

export interface ComposeContent {
  /** JNI names of the state holder and the host object. */
  readonly stateClass: string;
  readonly hostClass: string;
  /** The Kotlin file, relative to the Android library's Java sources. */
  readonly file: string;
  readonly kotlin: string;
}

const PACKAGE = "dev.lucent.compose";

/** The composable's parameter: the state holder. */
const STATE = "lucent";

/** The runtime's host of Compose content (runtime/native/android/src/compose). */
const RUNTIME_HOST = "LucentComposition";

/** A list's item holder, in what the item shows. */
const ITEM = "lucent_item";

const BASE_IMPORTS = [
  "android.content.Context",
  "androidx.compose.runtime.Composable",
  "androidx.compose.runtime.mutableStateOf",
];

/**
 * The Kotlin of `setup`'s body: its composition statements, then the JSX
 * it returns, its slots found into `crossings`.
 */
export function composeContent(
  checker: ts.TypeChecker,
  setup: BodySetup,
  jsx: ts.Expression,
  lifted: readonly ts.Statement[],
  crossings: Crossings,
): ComposeContent {
  const r = setup.registration;
  const values = new KotlinValues(r);
  const helpers = new Map<FunctionLike, HelperFunction>();
  const writer = new BodyWriter(checker, jsx, lifted, crossings, { registration: r, helpers });
  const statements = writer.body();
  const names = { state: `${r}State`, content: `${r}Content`, host: `${r}Host` };
  // Made first: it meets every value type, whose data classes go before it.
  const state = stateClass(names.state, r, crossings, values);
  const items = crossings.lists.map((l) => itemClass(values, l, `${r}Item${l.index}`));

  const text = kt.printUnit({
    banner: `Generated by Lucent from ${setup.export}'s content. Do not edit.`,
    fileAnnotations: ['Suppress("UNCHECKED_CAST")'],
    packageName: PACKAGE,
    imports: [...new Set([...BASE_IMPORTS, ...writer.imports])].sort(),
    decls: [
      ...values.decls,
      ...items,
      state,
      {
        k: "fun",
        annotations: ["Composable"],
        modifiers: [],
        name: names.content,
        params: [kt.param(STATE, kt.type(names.state))],
        body: statements,
      },
      hostObject(names),
      ...[...helpers.values()].map((h) => helperFun(values, h)),
      ...(writer.usesText ? [TEXT_FUN] : []),
    ],
  });

  const jni = (name: string) => `${PACKAGE.replaceAll(".", "/")}/${name}`;

  return {
    stateClass: jni(names.state),
    hostClass: jni(names.host),
    file: `${PACKAGE.replaceAll(".", "/")}/${r}.kt`,
    kotlin: text,
  };
}

// --- the generated declarations --------------------------------------------------------------

/**
 * A helper view as a Kotlin composable (ui/view-helpers.ts): its values,
 * which the setup computes where it is used, its callbacks, what its user
 * gives it, and its code: its composition statements, then its content.
 */
interface HelperFunction {
  readonly helper: ViewHelper;
  readonly name: string;
  readonly values: readonly HelperValue[];
  readonly body: kt.Stmt[];
}

/**
 * A value of a helper view: `source`, in its code or in a helper it uses
 * (`via`: those uses, innermost first, the last in this helper's code).
 */
interface HelperValue {
  readonly name: string;
  readonly source: ts.Expression;
  readonly type: ViewType;
  readonly via?: HelperUse;
}

/** The helper view a writer writes, and the values it has met so far. */
interface Frame {
  readonly helper: ViewHelper;
  readonly values: HelperValue[];
}

/** What the writers of one body share: the component's name, and its helper views. */
interface Shared {
  readonly registration: string;
  readonly helpers: Map<FunctionLike, HelperFunction>;
}

/** A helper view's composable: a parameter per value and per callback. */
function helperFun(values: KotlinValues, h: HelperFunction): kt.Decl {
  return {
    k: "fun",
    annotations: ["Composable"],
    modifiers: [],
    name: h.name,
    params: [
      ...h.values.map((v) => kt.param(v.name, values.type(v.type))),
      ...h.helper.callbacks.map((c) =>
        kt.param(
          c.name,
          kt.fn(
            c.params.map((k) => kt.type(KOTLIN_TYPES[k])),
            kt.type("Unit"),
          ),
        ),
      ),
    ],
    body: h.body,
  };
}

const KOTLIN_TYPES: Record<ScalarType["k"], string> = {
  number: "Double",
  boolean: "Boolean",
  string: "String",
};

function kotlinType(t: ScalarType): kt.Type {
  const named = kt.type(KOTLIN_TYPES[t.k]);

  return t.nullable ? kt.nullable(named) : named;
}

function actionType(a: ActionSlot): kt.Type {
  return kt.fn(
    a.params.map((p) => kotlinType(crossingOf(p))),
    kt.type("Unit"),
  );
}

/** A field's type: an optional one may be missing, which Kotlin holds as null. */
function fieldType(f: ViewField): ViewType {
  return f.optional && f.type.k !== "nullable" ? { k: "nullable", inner: f.type } : f.type;
}

/**
 * The Kotlin side of plain data (emit/toolkit-values.ts): each value's
 * Kotlin type, its first value, and how it is read from the boxed Java
 * objects that encode it. An object is a data class of its own (equal
 * values keep Compose state unchanged), read from a record by a function
 * of the file.
 */
class KotlinValues {
  /** The data classes of the objects met, and their readers. */
  readonly decls: kt.Decl[] = [];

  private readonly names = new Map<string, string>();
  private readonly prefix: string;

  constructor(prefix: string) {
    this.prefix = prefix;
  }

  type(t: ViewType): kt.Type {
    switch (t.k) {
      case "number":
        return kt.type("Double");
      case "boolean":
        return kt.type("Boolean");
      case "string":
      case "enum":
        return kt.type("String");
      case "nullable":
        return kt.nullable(this.type(t.inner));
      case "array":
        return kt.type("List", this.type(t.element));
      case "object":
        return kt.type(this.dataClass(t));
    }
  }

  /** The value Compose state holds before the setup's effect sets it. */
  zero(t: ViewType): kt.Expr {
    switch (t.k) {
      case "number":
        return kt.num("0.0");
      case "boolean":
        return kt.bool(false);
      case "string":
      case "enum":
        return kt.str("");
      case "nullable":
        return kt.nullLit;
      case "array":
        return kt.call(kt.name("emptyList"), []);
      case "object":
        return kt.call(kt.name(this.dataClass(t)), []);
    }
  }

  /** The value of type `t` the boxed object `x` encodes. */
  decode(t: ViewType, x: kt.Expr): kt.Expr {
    switch (t.k) {
      case "number":
      case "boolean":
      case "string":
      case "enum":
        return kt.cast(x, this.type(t));
      case "nullable":
        return t.inner.k === "array" || t.inner.k === "object"
          ? kt.ifExpr(kt.binary(x, "==", kt.nullLit), kt.nullLit, this.decode(t.inner, x))
          : kt.cast(x, this.type(t));
      case "array":
        return kt.call(
          kt.member(kt.cast(x, kt.type("Array", kt.nullable(kt.type("Any")))), "map"),
          [],
          kt.lambda([], [kt.exprStmt(this.decode(t.element, kt.name("it")))]),
        );
      case "object":
        return kt.call(kt.name(`read${this.dataClass(t)}`), [{ value: x }]);
    }
  }

  /** The data class of an object type, named by its fields, and the function reading it. */
  private dataClass(t: ViewType & { k: "object" }): string {
    const key = JSON.stringify(t);
    const found = this.names.get(key);

    if (found) return found;

    const name = `${this.prefix}Value${this.names.size}`;
    const fields = kt.name("fields");

    this.names.set(key, name);
    this.decls.push(
      {
        k: "class",
        modifiers: ["data"],
        name,
        params: t.fields.map((f) => ({
          property: "val" as const,
          ...kt.param(f.name, this.type(fieldType(f)), this.zero(fieldType(f))),
        })),
        members: [],
      },
      {
        k: "fun",
        modifiers: ["private"],
        name: `read${name}`,
        params: [kt.param("x", kt.nullable(kt.type("Any")))],
        ret: kt.type(name),
        body: [
          kt.val("fields", kt.cast(kt.name("x"), kt.type("Array", kt.nullable(kt.type("Any"))))),
          kt.ret(
            kt.call(
              kt.name(name),
              t.fields.map((f, i) => ({
                value: this.decode(fieldType(f), kt.index(fields, kt.num(i))),
              })),
            ),
          ),
        ],
      },
    );

    return name;
  }
}

/** `fun <name>(slot: Int, value: Any?)`: assigns `slot`'s target, which the setup's C++ calls. */
function setter<S extends { readonly index: number }>(
  name: string,
  slots: readonly S[],
  assign: (slot: S, value: kt.Expr) => kt.Stmt,
): kt.Fun {
  return {
    k: "fun",
    modifiers: [],
    name,
    params: [kt.param("slot", kt.type("Int")), kt.param("value", kt.nullable(kt.type("Any")))],
    body: [
      {
        k: "when",
        subject: kt.name("slot"),
        branches: [
          ...slots.map((s) => ({
            conditions: [kt.num(s.index)],
            body: [assign(s, kt.name("value"))],
          })),
          {
            conditions: [],
            body: [
              kt.throwStmt(
                kt.call(kt.name("IllegalArgumentException"), [{ value: kt.str("no such slot") }]),
              ),
            ],
          },
        ],
      },
    ],
  };
}

/**
 * The state holder: Compose state per value slot and a function per
 * action slot, which the setup's C++ assigns (`set`, `setAction`).
 */
function stateClass(
  name: string,
  prefix: string,
  crossings: Crossings,
  values: KotlinValues,
): kt.Decl {
  const state = crossings.values.map((s): kt.Member => ({
    k: "val",
    modifiers: [],
    name: s.name,
    init: kt.call(kt.name("mutableStateOf"), [{ value: values.zero(s.type) }], undefined, [
      values.type(s.type),
    ]),
  }));
  const actions = crossings.actions.map((a): kt.Member => ({
    k: "var",
    modifiers: ["lateinit"],
    name: a.name,
    type: actionType(a),
  }));

  return {
    k: "class",
    name,
    members: [
      ...state,
      ...actions,
      ...crossings.lists.flatMap((l) => listMembers(values, l, `${prefix}Item${l.index}`)),
      setter("set", crossings.values, (s, value) =>
        kt.assign(kt.member(kt.name(s.name), "value"), values.decode(s.type, value)),
      ),
      setter("setAction", crossings.actions, (s, value) =>
        kt.assign(kt.name(s.name), kt.cast(value, actionType(s))),
      ),
      setter("setList", crossings.lists, (l, value) =>
        kt.assign(
          kt.member(kt.name(l.name), "value"),
          kt.call(kt.name(`merge${capital(l.name)}`), [{ value }]),
        ),
      ),
    ],
  };
}

const capital = (name: string) => `${name[0]!.toUpperCase()}${name.slice(1)}`;

/** A list's key in Kotlin: a String, or a Double. */
function keyType(list: ListSlot): ViewType {
  return { k: list.keyType.k };
}

/**
 * A list's item holder: its key, and Compose state per value the setup
 * computes for it, which a record sets in place (an equal value changes
 * nothing).
 */
function itemClass(values: KotlinValues, list: ListSlot, name: string): kt.Decl {
  const record = kt.name("record");

  return {
    k: "class",
    name,
    params: [{ property: "val", ...kt.param("key", values.type(keyType(list))) }],
    members: [
      ...list.values.map((v): kt.Member => ({
        k: "val",
        modifiers: [],
        name: v.name,
        init: kt.call(kt.name("mutableStateOf"), [{ value: values.zero(v.type) }], undefined, [
          values.type(v.type),
        ]),
      })),
      {
        k: "fun",
        modifiers: [],
        name: "update",
        params: [kt.param("record", kt.type("Array", kt.nullable(kt.type("Any"))))],
        body: list.values.map((v, i) =>
          kt.assign(
            kt.member(kt.name(v.name), "value"),
            values.decode(v.type, kt.index(record, kt.num(i + 1))),
          ),
        ),
      },
    ],
  };
}

/**
 * The holder's members for a list: its items (Compose state: the content
 * shows them), the items by key, and the merge of new records into them.
 * An item whose key stays keeps its holder; the list's state changes only
 * when the keys or their order do (lists of the same holders are equal).
 */
function listMembers(values: KotlinValues, list: ListSlot, item: string): kt.Member[] {
  const key = values.type(keyType(list));
  const byKey = `${list.name}Items`;
  const one = `${list.name}Item`;
  const records = kt.type("Array", kt.nullable(kt.type("Any")));

  return [
    {
      k: "val",
      modifiers: [],
      name: list.name,
      init: kt.call(
        kt.name("mutableStateOf"),
        [{ value: kt.call(kt.name("emptyList"), []) }],
        undefined,
        [kt.type("List", kt.type(item))],
      ),
    },
    {
      k: "val",
      modifiers: ["private"],
      name: byKey,
      init: kt.call(kt.name("HashMap"), [], undefined, [key, kt.type(item)]),
    },
    {
      k: "fun",
      modifiers: ["private"],
      name: `merge${capital(list.name)}`,
      params: [kt.param("records", kt.nullable(kt.type("Any")))],
      ret: kt.type("List", kt.type(item)),
      body: [
        kt.val(
          "next",
          kt.call(
            kt.member(kt.cast(kt.name("records"), records), "map"),
            [],
            kt.lambda(
              [],
              [kt.exprStmt(kt.call(kt.name(one), [{ value: kt.cast(kt.name("it"), records) }]))],
            ),
          ),
        ),
        kt.exprStmt(
          kt.call(kt.member(kt.member(kt.name(byKey), "keys"), "retainAll"), [
            {
              value: kt.call(
                kt.member(
                  kt.call(
                    kt.member(kt.name("next"), "map"),
                    [],
                    kt.lambda([], [kt.exprStmt(kt.member(kt.name("it"), "key"))]),
                  ),
                  "toSet",
                ),
                [],
              ),
            },
          ]),
        ),
        kt.ret(kt.name("next")),
      ],
    },
    {
      k: "fun",
      modifiers: ["private"],
      name: one,
      params: [kt.param("record", records)],
      ret: kt.type(item),
      body: [
        kt.val("key", values.decode(keyType(list), kt.index(kt.name("record"), kt.num(0)))),
        kt.val(
          "item",
          kt.call(
            kt.member(kt.name(byKey), "getOrPut"),
            [{ value: kt.name("key") }],
            kt.lambda([], [kt.exprStmt(kt.call(kt.name(item), [{ value: kt.name("key") }]))]),
          ),
        ),
        kt.exprStmt(kt.call(kt.member(kt.name("item"), "update"), [{ value: kt.name("record") }])),
        kt.ret(kt.name("item")),
      ],
    },
  ];
}

/**
 * The host object: gives the runtime's host of Compose content
 * (dev.lucent.compose.LucentComposition, which owns the ComposeView, its
 * composition and its disposal) the content, reading the state holder the
 * setup's C++ made. The composition reads each value where it uses it,
 * from the holder's state: nothing of the first commit is captured.
 */
function hostObject(names: { state: string; content: string; host: string }): kt.Decl {
  const content = kt.call(kt.name(names.content), [
    { value: kt.cast(kt.name("state"), kt.type(names.state)) },
  ]);

  const create: kt.Fun = {
    k: "fun",
    annotations: ["JvmStatic"],
    modifiers: [],
    name: "create",
    params: [kt.param("context", kt.type("Context")), kt.param("state", kt.type("Any"))],
    ret: kt.type(RUNTIME_HOST),
    body: [
      kt.ret(
        kt.call(
          kt.name(RUNTIME_HOST),
          [{ value: kt.name("context") }],
          kt.lambda([], [kt.exprStmt(content)]) as kt.Expr & { k: "lambda" },
        ),
      ),
    ],
  };

  return { k: "object", name: names.host, members: [create] };
}

/** A number as JavaScript writes it in text, for the integers and plain decimals content shows. */
const TEXT_FUN: kt.Decl = {
  k: "fun",
  modifiers: ["private"],
  name: "lucentText",
  params: [kt.param("value", kt.type("Double"))],
  ret: kt.type("String"),
  body: [
    kt.ret(
      kt.ifExpr(
        kt.binary(
          kt.binary(
            kt.name("value"),
            "==",
            kt.call(kt.member(kt.name("Math"), "rint"), [{ value: kt.name("value") }]),
          ),
          "&&",
          kt.binary(
            kt.call(kt.member(kt.name("Math"), "abs"), [{ value: kt.name("value") }]),
            "<",
            kt.num("1e15"),
          ),
        ),
        kt.call(kt.member(kt.call(kt.member(kt.name("value"), "toLong"), []), "toString"), []),
        kt.call(kt.member(kt.name("value"), "toString"), []),
      ),
    ),
  ],
};

// --- the body ----------------------------------------------------------------------------------

/** Where code of the body runs: in the composition, in a coroutine, or in a callback. */
interface Where {
  readonly composable: boolean;
  readonly suspending: boolean;
  /** The lambda's label (its call's name), for `return`; none in the body itself. */
  readonly label?: string;
}

/**
 * An expression in Kotlin: a number's Kotlin type (and its value, for a
 * literal), or a string; plain data the setup computed has its view type.
 */
interface Val {
  readonly e: kt.Expr;
  readonly num?: NumberKind;
  readonly literal?: number;
  readonly text?: boolean;
  readonly vt?: ViewType;
  /** A lambda's receiver scope: Kotlin's implicit receiver, what its members are called on unqualified. */
  readonly scope?: true;
}

/** Plain data in Kotlin: a number is a Double, and a string is text. */
function plainVal(e: kt.Expr, vt: ViewType): Val {
  return {
    e,
    vt,
    ...(vt.k === "number" ? { num: "Double" as const } : {}),
    ...(vt.k === "string" || vt.k === "enum" ? { text: true } : {}),
  };
}

const COMPOSITION: Where = { composable: true, suspending: false };

/** In a lambda of a list's scope: it adds elements, and composes nothing itself. */
const ADDING: Where = { composable: false, suspending: false };

/**
 * What a call or an element gives one of Kotlin's parameters (an index of
 * the member's): an expression, an element's children, or a prop written
 * alone (`singleLine`), which is true.
 */
type Given = { readonly index: number; readonly at: ts.Node } & (
  | { readonly arg: ts.Expression }
  | { readonly children: readonly ts.JsxChild[] }
  | { readonly flag: true }
);

class BodyWriter {
  readonly imports = new Set<string>();
  usesText = false;

  /** The body's own names: Kotlin's name, and a number's Kotlin type. */
  private readonly locals = new Map<
    ts.Symbol,
    { name: string; num?: NumberKind; text?: boolean; vt?: ViewType; scope?: true }
  >();

  private readonly checker: ts.TypeChecker;
  private readonly jsx: ts.Expression;
  private readonly statements: readonly ts.Statement[];
  private readonly crossings: Crossings;
  private readonly shared: Shared;
  /** The helper view written, when the writer writes one; the helpers it is in, outermost first. */
  private readonly frame?: Frame;
  private readonly stack: readonly FunctionLike[];

  constructor(
    checker: ts.TypeChecker,
    jsx: ts.Expression,
    statements: readonly ts.Statement[],
    crossings: Crossings,
    shared: Shared,
    frame?: Frame,
    stack: readonly FunctionLike[] = [],
  ) {
    this.checker = checker;
    this.jsx = jsx;
    this.statements = statements;
    this.crossings = crossings;
    this.shared = shared;
    this.stack = stack;
    if (frame) this.frame = frame;
  }

  /** The content: its composition statements, in order, then what its JSX shows. */
  body(): kt.Stmt[] {
    return [
      ...this.statements.flatMap((s) => this.statement(s, COMPOSITION)),
      ...this.content(this.jsx),
    ];
  }

  /**
   * A composable function's code: the body, or a content lambda. Its
   * statements run where it composes, and what it returns is its content
   * (`show` writes it).
   */
  private composition(
    fn: ts.ArrowFunction | ts.FunctionExpression,
    show: (e: ts.Expression) => kt.Stmt[],
    where: Where = COMPOSITION,
  ): kt.Stmt[] {
    const b = fn.body;

    if (!ts.isBlock(b)) return show(b);

    return b.statements.flatMap((s) =>
      ts.isReturnStatement(s)
        ? s.expression
          ? show(s.expression)
          : fail(s, Codes.ToolkitBody, "a content lambda ends by returning what it shows")
        : this.statement(s, where),
    );
  }

  // --- statements ---

  private statement(s: ts.Statement, where: Where): kt.Stmt[] {
    if (ts.isVariableStatement(s)) {
      if (!(s.declarationList.flags & ts.NodeFlags.Const))
        fail(
          s,
          Codes.ToolkitBody,
          "the content declares values with const: state it changes is Compose state (remember) or the setup's",
        );

      return s.declarationList.declarations.map((d) => {
        if (!ts.isIdentifier(d.name) || !d.initializer)
          fail(d, Codes.ToolkitBody, "declare one name with its value: const x = …");

        const v = this.expr(d.initializer, where);
        const symbol = this.checker.getSymbolAtLocation(d.name);

        if (symbol)
          this.locals.set(symbol, {
            name: d.name.text,
            ...(v.num ? { num: v.num } : {}),
            ...(v.text ? { text: true } : {}),
            ...(v.vt ? { vt: v.vt } : {}),
          });

        return kt.val(d.name.text, v.e);
      });
    }

    if (ts.isExpressionStatement(s)) return [kt.exprStmt(this.expr(s.expression, where).e)];

    if (ts.isIfStatement(s)) {
      const branch = (b: ts.Statement) =>
        ts.isBlock(b)
          ? b.statements.flatMap((x) => this.statement(x, where))
          : this.statement(b, where);

      return [
        {
          k: "if",
          test: this.condition(s.expression, where),
          body: branch(s.thenStatement),
          ...(s.elseStatement ? { orElse: branch(s.elseStatement) } : {}),
        },
      ];
    }

    if (ts.isReturnStatement(s) && where.label)
      return [
        {
          k: "return",
          label: where.label,
          ...(s.expression ? { value: this.expr(s.expression, where).e } : {}),
        },
      ];

    fail(s, Codes.ToolkitBody, `the content cannot compile ${describe(s)} to Compose yet`);
  }

  // --- content ---

  /**
   * Content: an element (`<Box …/>`), a fragment or an array of content,
   * `cond && …`, `cond ? … : …`, or nothing.
   */
  private content(e: ts.Expression, where: Where = COMPOSITION): kt.Stmt[] {
    const x = skipParentheses(e);

    if (ts.isJsxElement(x) || ts.isJsxSelfClosingElement(x))
      return [kt.exprStmt(this.element(x, where))];

    if (ts.isJsxFragment(x)) return this.children(x.children, where);

    if (ts.isArrayLiteralExpression(x))
      return x.elements.flatMap((item) =>
        ts.isSpreadElement(item)
          ? fail(item, Codes.ToolkitBody, "content is an array literal of elements: no `...`")
          : this.content(item, where),
      );

    if (ts.isConditionalExpression(x))
      return [
        {
          k: "if",
          test: this.condition(x.condition, where),
          body: this.content(x.whenTrue, where),
          orElse: this.content(x.whenFalse, where),
        },
      ];

    if (ts.isBinaryExpression(x) && x.operatorToken.kind === ts.SyntaxKind.AmpersandAmpersandToken)
      return [{ k: "if", test: this.condition(x.left, where), body: this.content(x.right, where) }];

    if (x.kind === ts.SyntaxKind.NullKeyword || x.kind === ts.SyntaxKind.FalseKeyword) return [];

    if (ts.isCallExpression(x) && this.elementBinding(x)) this.refuseCalled(x);

    const helper = ts.isCallExpression(x) ? helperAt(this.checker, x.expression) : undefined;

    if (helper && ts.isCallExpression(x)) return [kt.exprStmt(this.used(x, helper))];

    fail(
      x,
      Codes.ToolkitBody,
      "content is elements: `<Box …/>`, a fragment of them, `cond && <Box …/>` or `cond ? <A …/> : <B …/>`",
    );
  }

  /** An element's children, or a fragment's: its elements in order (text is refused). */
  private children(children: readonly ts.JsxChild[], where: Where): kt.Stmt[] {
    return children.flatMap((child) => {
      if (ts.isJsxText(child)) {
        if (child.containsOnlyTriviaWhiteSpaces) return [];

        fail(child, Codes.ToolkitBody, 'content is elements: write text with `<Text text="…" />`');
      }

      if (ts.isJsxExpression(child)) {
        // `{/* … */}`: nothing.
        if (!child.expression) return [];

        if (child.dotDotDotToken)
          fail(child, Codes.ToolkitBody, "content is elements: no `{...}` among children");

        return this.content(child.expression, where);
      }

      return this.content(child, where);
    });
  }

  /** The children given as one function (`{(row) => …}`), if they are. */
  private childFunction(
    children: readonly ts.JsxChild[],
  ): ts.ArrowFunction | ts.FunctionExpression | undefined {
    const given = children.filter((c) => !(ts.isJsxText(c) && c.containsOnlyTriviaWhiteSpaces));
    const only = given.length === 1 ? given[0] : undefined;
    const e =
      only && ts.isJsxExpression(only) && only.expression && skipParentheses(only.expression);

    return e && (ts.isArrowFunction(e) || ts.isFunctionExpression(e)) ? e : undefined;
  }

  private refuseContent(node: ts.Node, label: string): never {
    fail(
      node,
      Codes.ToolkitBody,
      `${label}'s content is a function returning what it shows: \`() => <…/>\``,
    );
  }

  /** Refused: a composable showing content called as a function, where JSX writes it. */
  private refuseCalled(c: ts.CallExpression): never {
    const name = skipParentheses(c.expression).getText();

    fail(
      c,
      Codes.ToolkitBody,
      `\`${name}\` shows content: write it as an element, \`<${name} …/>\`, in what the body or an element's children show`,
    );
  }

  /** The binding of an element's composable, when a call or a tag names one. */
  private elementBinding(
    node: ts.CallExpression | ts.JsxOpeningLikeElement,
  ): ComposeBinding | undefined {
    const binding = bindingOf(this.checker.getResolvedSignature(node)?.declaration);

    return binding && isElement(binding.member, binding.owner) ? binding : undefined;
  }

  /**
   * An element: its composable called with its props as Kotlin's named
   * arguments, and its children as the content lambda.
   */
  private element(x: ts.JsxElement | ts.JsxSelfClosingElement, where: Where): kt.Expr {
    const opening = ts.isJsxElement(x) ? x.openingElement : x;
    const tag = opening.tagName;
    const label = tag.getText();
    const helper = helperAt(this.checker, tag);

    if (helper) return this.used(x, helper);

    const binding = this.elementBinding(opening);

    if (!binding?.args)
      fail(
        tag,
        Codes.ToolkitBody,
        `\`${label}\` is not Compose's: content shows lucent:compose's elements`,
      );

    this.checkWhere(opening, label, binding, where);

    const params = "params" in binding.member ? binding.member.params : [];
    const [props] = binding.args;
    const given: Given[] = [];

    for (const a of opening.attributes.properties) {
      if (ts.isJsxSpreadAttribute(a))
        fail(a, Codes.ToolkitBody, `${label}'s props are written one by one: \`name={value}\``);

      const name = a.name.getText();
      const index =
        props?.k !== "named"
          ? undefined
          : name === "children"
            ? props.children
            : props.indices.find((k) => params[k]!.name === name);

      if (index === undefined)
        fail(a, Codes.ToolkitBody, `the content cannot give ${label} \`${name}\``);

      given.push({ index, at: a, ...this.attribute(a) });
    }

    const children = ts.isJsxElement(x) ? x.children : undefined;
    const fnChild = children && this.childFunction(children);

    if (children && props?.k === "named" && props.children !== undefined) {
      if (fnChild) given.push({ index: props.children, at: fnChild, arg: fnChild });
      else if (children.some((c) => !(ts.isJsxText(c) && c.containsOnlyTriviaWhiteSpaces)))
        given.push({ index: props.children, at: x, children });
    }

    const list = listForm(binding);

    if (list && this.frame)
      fail(
        x,
        Codes.ToolkitBody,
        "a helper view shows no list of its own: its user's list may show helpers",
      );

    if (list) return this.keyedList(x, binding, list, given);

    const object = ts.isPropertyAccessExpression(tag) ? tag.expression : undefined;

    return this.write(x, binding, given, where, label, object).e;
  }

  /** An attribute's value: `name="text"`, `name={value}`, or `name` alone (true). */
  private attribute(a: ts.JsxAttribute): { arg: ts.Expression } | { flag: true } {
    const init = a.initializer;

    if (!init) return { flag: true };

    if (ts.isStringLiteral(init)) return { arg: init };

    if (ts.isJsxExpression(init) && init.expression)
      return { arg: skipParentheses(init.expression) };

    fail(a, Codes.ToolkitBody, `write ${a.name.getText()}'s value as \`name={value}\``);
  }

  // --- expressions ---

  private condition(e: ts.Expression, where: Where): kt.Expr {
    if (!(this.checker.getTypeAtLocation(e).flags & ts.TypeFlags.BooleanLike))
      fail(
        e,
        Codes.ToolkitBody,
        'a condition in content is a boolean: compare the value (`n > 0`, `s !== ""`)',
      );

    return this.expr(e, where).e;
  }

  private expr(node: ts.Expression, where: Where): Val {
    const e = skipParentheses(node);

    // What the setup computes (a prop, a signal, what its functions give): Compose state it keeps set.
    // In a helper view, what it computes from its props: a parameter of its own.
    if (
      this.frame
        ? this.crossings.computedIn(e, this.frame.helper)
        : this.crossings.computedBySetup(e)
    )
      return this.valueSlot(e);

    const prop = this.callbackProp(e);

    if (prop) return { e: kt.name(prop.name) };

    if (ts.isNumericLiteral(e)) return numberLiteral(e, Number(e.text));

    if (
      ts.isPrefixUnaryExpression(e) &&
      e.operator === ts.SyntaxKind.MinusToken &&
      ts.isNumericLiteral(e.operand)
    )
      return numberLiteral(e, -Number(e.operand.text));

    if (ts.isPrefixUnaryExpression(e) && e.operator === ts.SyntaxKind.ExclamationToken)
      return { e: kt.not(this.condition(e.operand, where)) };

    if (ts.isStringLiteral(e) || ts.isNoSubstitutionTemplateLiteral(e))
      return { e: kt.str(e.text), text: true };

    if (ts.isTemplateExpression(e)) return this.template(e, where);

    if (e.kind === ts.SyntaxKind.TrueKeyword) return { e: kt.bool(true) };

    if (e.kind === ts.SyntaxKind.FalseKeyword) return { e: kt.bool(false) };

    if (e.kind === ts.SyntaxKind.NullKeyword) return { e: kt.nullLit };

    if (ts.isAwaitExpression(e)) {
      if (!where.suspending)
        fail(
          e,
          Codes.ToolkitBody,
          "await in content runs in a coroutine: in an async block of LaunchedEffect",
        );

      return this.expr(e.expression, where);
    }

    if (ts.isConditionalExpression(e)) {
      const a = this.expr(e.whenTrue, where);
      const b = this.expr(e.whenFalse, where);
      const num = a.num && b.num ? (a.num === b.num ? a.num : "Double") : undefined;

      return {
        e: kt.ifExpr(this.condition(e.condition, where), convert(a, num), convert(b, num)),
        ...(num ? { num } : {}),
        ...(a.text && b.text ? { text: true } : {}),
      };
    }

    if (ts.isBinaryExpression(e)) return this.binary(e, where);

    if (ts.isIdentifier(e)) return this.identifier(e);

    if (ts.isPropertyAccessExpression(e)) return this.property(e, where);

    if (ts.isCallExpression(e)) return this.call(e, where);

    if (ts.isArrowFunction(e) || ts.isFunctionExpression(e)) return { e: this.lambda(e, "") };

    if (ts.isJsxElement(e) || ts.isJsxSelfClosingElement(e) || ts.isJsxFragment(e))
      fail(
        e,
        Codes.ToolkitBody,
        "an element is content: return it, or give it as an element's children",
      );

    fail(e, Codes.ToolkitBody, `the content cannot compile ${describe(e)} to Compose yet`);
  }

  private template(e: ts.TemplateExpression, where: Where): Val {
    let out: kt.Expr = kt.str(e.head.text);

    for (const span of e.templateSpans) {
      out = kt.binary(out, "+", this.text(span.expression, where));

      if (span.literal.text) out = kt.binary(out, "+", kt.str(span.literal.text));
    }

    return { e: out, text: true };
  }

  /** A value as text, as JavaScript writes it. */
  private text(node: ts.Expression, where: Where): kt.Expr {
    const v = this.expr(node, where);
    const t = this.checker.getTypeAtLocation(node);

    if (v.text || t.flags & ts.TypeFlags.StringLike) return v.e;

    if (v.num) {
      this.usesText = true;

      return kt.call(kt.name("lucentText"), [{ value: convert(v, "Double") }]);
    }

    if (t.flags & ts.TypeFlags.BooleanLike) return kt.call(kt.member(v.e, "toString"), []);

    fail(
      node,
      Codes.ToolkitBody,
      "content writes numbers, booleans and strings as text: compute other text in setup",
    );
  }

  private binary(e: ts.BinaryExpression, where: Where): Val {
    const op = e.operatorToken.kind;
    const K = ts.SyntaxKind;

    if (op === K.AmpersandAmpersandToken || op === K.BarBarToken)
      return {
        e: kt.binary(
          this.condition(e.left, where),
          op === K.AmpersandAmpersandToken ? "&&" : "||",
          this.condition(e.right, where),
        ),
      };

    if (op === K.EqualsEqualsToken || op === K.ExclamationEqualsToken)
      fail(e.operatorToken, Codes.ToolkitBody, "content compares with === and !==");

    const a = this.expr(e.left, where);
    const b = this.expr(e.right, where);

    if (op === K.PlusToken && (a.text || b.text))
      return { e: kt.binary(this.textOf(a, e.left), "+", this.textOf(b, e.right)), text: true };

    const ARITHMETIC: Partial<Record<ts.SyntaxKind, kt.BinaryOp>> = {
      [K.PlusToken]: "+",
      [K.MinusToken]: "-",
      [K.AsteriskToken]: "*",
      [K.SlashToken]: "/",
      [K.PercentToken]: "%",
    };
    const COMPARISON: Partial<Record<ts.SyntaxKind, kt.BinaryOp>> = {
      [K.LessThanToken]: "<",
      [K.GreaterThanToken]: ">",
      [K.LessThanEqualsToken]: "<=",
      [K.GreaterThanEqualsToken]: ">=",
      [K.EqualsEqualsEqualsToken]: "==",
      [K.ExclamationEqualsEqualsToken]: "!=",
    };

    // Numbers meet as Doubles, as JavaScript's do.
    const both = a.num && b.num ? "Double" : undefined;
    const arithmetic = ARITHMETIC[op];

    if (arithmetic) {
      if (!both) fail(e, Codes.ToolkitBody, "arithmetic in content is on numbers");

      return { e: kt.binary(convert(a, both), arithmetic, convert(b, both)), num: "Double" };
    }

    const comparison = COMPARISON[op];

    if (comparison) return { e: kt.binary(convert(a, both), comparison, convert(b, both)) };

    fail(
      e.operatorToken,
      Codes.ToolkitBody,
      `the content cannot compile ${e.operatorToken.getText()} to Compose yet`,
    );
  }

  private textOf(v: Val, node: ts.Expression): kt.Expr {
    if (v.text) return v.e;

    if (v.num) {
      this.usesText = true;

      return kt.call(kt.name("lucentText"), [{ value: convert(v, "Double") }]);
    }

    fail(node, Codes.ToolkitBody, "content adds text to text or numbers");
  }

  private identifier(id: ts.Identifier): Val {
    if (id.text === "undefined") return { e: kt.nullLit };

    const symbol = this.symbol(id);

    if (!symbol) fail(id, Codes.ToolkitBody, `\`${id.text}\` is not known here`);

    const local = this.locals.get(symbol);

    if (local?.scope) return { e: kt.thisExpr, scope: true };

    if (local)
      return {
        e: kt.name(local.name),
        ...(local.num ? { num: local.num } : {}),
        ...(local.text ? { text: true } : {}),
        ...(local.vt ? { vt: local.vt } : {}),
      };

    const decl = symbol.declarations?.[0];

    if (isComposeDeclaration(decl)) {
      // A value (a constant, a companion that is its class's value): not a function or a type.
      const binding = bindingOf(symbol.declarations?.find(ts.isVariableDeclaration));
      if (!binding?.write.property)
        fail(id, Codes.ToolkitBody, `the content cannot read \`${id.text}\` as a value`);

      return this.number(id, this.path(binding.write));
    }

    if (this.crossings.inSetup(decl))
      return { e: kt.member(kt.name(STATE), this.crossings.setupName(id).name) };

    fail(
      id,
      Codes.ToolkitBody,
      `the content cannot read \`${id.text}\`: it reads its setup's props, signals and functions, and lucent:compose`,
    );
  }

  private property(e: ts.PropertyAccessExpression, where: Where): Val {
    const receiver = skipParentheses(e.expression);

    // A value of the setup's the body reads is one it computes (a slot): anything else is refused.
    this.crossings.setupMember(e);

    const object = this.plainObject(receiver, where);

    if (object) return this.field(e, object);

    const binding = bindingOf(this.symbol(e.name)?.declarations?.[0]);

    if (!binding?.write.property)
      fail(
        e,
        Codes.ToolkitBody,
        `the content cannot read \`${e.getText()}\`: it reads lucent:compose's values`,
      );

    if (binding.member.kotlin?.composable && !where.composable)
      fail(
        e,
        Codes.ToolkitBody,
        `${e.getText()} is composable: read it where the body composes, not in a callback`,
      );

    // A static (`Color.White`, `Spring.StiffnessLow`): its class's; else the receiver's, a scope's unqualified.
    const of = binding.write.k === "static" ? undefined : this.expr(receiver, where);
    const value = !of
      ? this.path(binding.write)
      : of.scope
        ? binding.write.k === "top"
          ? this.path(binding.write)
          : kt.name(this.written(binding.write))
        : kt.member(of.e, this.written(binding.write));

    return this.number(e, value);
  }

  /** `e` with the Kotlin number type of `node`'s TypeScript type (a Double, or a branded Kotlin number). */
  private number(node: ts.Node, e: kt.Expr): Val {
    const num = numberKindOf(this.checker, this.checker.getTypeAtLocation(node));

    return { e, ...(num ? { num } : {}) };
  }

  /** The name a binding writes, its imports noted: `Box`, `padding`, `White` (of `Color`). */
  private written(w: ComposeWrite): string {
    for (const i of w.imports) this.imports.add(i);

    return w.name;
  }

  /** What a binding written on its own is: `Box`, `Alignment.Center`, `PaddingValues.Absolute`. */
  private path(w: ComposeWrite): kt.Expr {
    const names = [...(w.k === "static" ? w.owner!.split(".") : []), ...this.written(w).split(".")];

    return names.slice(1).reduce<kt.Expr>((e, n) => kt.member(e, n), kt.name(names[0]!));
  }

  /** A call: of a setup function, or of lucent:compose's. */
  private call(c: ts.CallExpression, where: Where): Val {
    const callee = skipParentheses(c.expression);

    if (this.elementBinding(c)) this.refuseCalled(c);

    // A helper view's callback prop, called (in a callback): its user's lambda.
    const prop = this.callbackProp(callee);

    if (prop) {
      if (where.composable)
        fail(
          c,
          Codes.ToolkitBody,
          `\`${callee.getText()}\` is a callback: call it from a callback, \`() => ${c.getText()}\``,
        );

      return {
        e: kt.call(
          kt.name(prop.name),
          c.arguments.map((a, i) => ({
            value: convert(this.expr(a, where), prop.params[i] === "number" ? "Double" : undefined),
          })),
        ),
      };
    }

    if (ts.isIdentifier(callee)) {
      const symbol = this.symbol(callee);
      const decl = symbol?.declarations?.[0];

      if (symbol && this.crossings.inSetup(decl)) return this.setupCall(c, callee, symbol, where);
    } else if (ts.isPropertyAccessExpression(callee)) this.crossings.setupMember(c);
    else fail(c, Codes.ToolkitBody, `the content cannot call ${describe(callee)}`);

    const binding = bindingOf(this.checker.getResolvedSignature(c)?.declaration);

    if (!binding?.args)
      fail(
        callee,
        Codes.ToolkitBody,
        `the content cannot call \`${callee.getText()}\`: it calls lucent:compose and its setup's functions`,
      );

    this.checkWhere(c, callee.getText(), binding, where);

    const label = binding.write.name;
    const object = ts.isPropertyAccessExpression(callee) ? callee.expression : undefined;

    return this.write(c, binding, this.callGiven(c, binding, label), where, label, object);
  }

  /** What a call's arguments give Kotlin's parameters, by the binding's map of them. */
  private callGiven(c: ts.CallExpression, binding: ComposeBinding, label: string): Given[] {
    const params = "params" in binding.member ? binding.member.params : [];
    const given: Given[] = [];

    c.arguments.forEach((a, i) => {
      const slot = binding.args![i];
      const arg = skipParentheses(a);

      if (!slot || ts.isSpreadElement(a))
        fail(a, Codes.ToolkitBody, `the content cannot pass this argument of ${label}`);

      if (slot.k === "param") {
        given.push({ index: slot.index, at: a, arg });
        return;
      }

      // An object of Kotlin's named parameters.
      if (!ts.isObjectLiteralExpression(arg))
        fail(
          a,
          Codes.ToolkitBody,
          `write ${label}'s ${params[slot.indices[0]!]?.name ?? "arguments"} as an object literal: its fields are Kotlin's named arguments`,
        );

      for (const p of arg.properties) {
        const index =
          ts.isPropertyAssignment(p) && ts.isIdentifier(p.name)
            ? slot.indices.find((k) => params[k]!.name === (p.name as ts.Identifier).text)
            : undefined;

        if (index === undefined || !ts.isPropertyAssignment(p))
          fail(p, Codes.ToolkitBody, `write each of ${label}'s named arguments as \`name: value\``);

        given.push({ index, at: p, arg: skipParentheses(p.initializer) });
      }
    });

    return given;
  }

  /**
   * A binding's use, a call or an element, given its Kotlin parameters:
   * an extension of its first argument, a method of `object` (a scope's,
   * unqualified), or a function.
   */
  private write(
    site: ts.Node,
    binding: ComposeBinding,
    given: readonly Given[],
    where: Where,
    label: string,
    object: ts.Expression | undefined,
  ): Val {
    const w = binding.write;
    const args = this.args(site, binding, given, where, label);

    // `20.dp`, `text.fn(…)`: an extension of the first argument.
    if (w.receiverArg) {
      const [receiver, ...rest] = args.args;

      if (!receiver) fail(site, Codes.ToolkitBody, `${w.name} takes its value`);

      const target = kt.member(receiver.value, this.written(w));
      const e = w.property ? target : kt.call(target, rest, args.trailing);

      return this.number(site, e);
    }

    // A method: of the object it is called on (a member, an extension; a scope's unqualified); else a function.
    const of =
      (w.k === "member" || w.k === "extension") && object
        ? this.expr(skipParentheses(object), where)
        : undefined;
    const target = !of
      ? this.path(w)
      : of.scope
        ? kt.name(this.written(w))
        : kt.member(of.e, this.written(w));

    return this.number(site, kt.call(target, args.args, args.trailing));
  }

  /** A call of a setup function: its value (a slot) where the body composes, the Lucent function in a callback. */
  private setupCall(
    c: ts.CallExpression,
    callee: ts.Identifier,
    symbol: ts.Symbol,
    where: Where,
  ): Val {
    if (!this.crossings.setupFunction(symbol))
      fail(callee, Codes.ToolkitBody, `\`${callee.text}\` is not a function of the setup`);

    // A value it computes is Compose state (computedBySetup); a handler runs on events only.
    if (where.composable) this.crossings.refuseDrawingCall(c, callee, "compose");

    // Called by a callback: the Lucent function runs. A list's item crosses as its key.
    const slot = this.crossings.action(callee, c.arguments);
    const args = c.arguments.map((a, i) =>
      this.crossings.itemOf(a)
        ? kt.member(kt.name(ITEM), "key")
        : convert(this.expr(a, where), slot.params[i]?.k === "number" ? "Double" : undefined),
    );

    return {
      e: kt.call(
        kt.member(kt.name(STATE), slot.name),
        args.map((value) => ({ value })),
      ),
    };
  }

  /** A composable runs where the body composes; a suspend function (a promise) in a coroutine. */
  private checkWhere(c: ts.Node, name: string, binding: ComposeBinding, where: Where): void {
    if (binding.member.kotlin?.composable && !where.composable)
      fail(
        c,
        Codes.ToolkitBody,
        `${name} is composable: call it where the body composes, not in a callback`,
      );

    if (binding.member.kotlin?.suspend && !where.suspending)
      fail(c, Codes.ToolkitBody, `${name} suspends: await it in an async block (LaunchedEffect's)`);
  }

  /**
   * A call's or an element's arguments as Kotlin's, by name; a function
   * literal (or an element's children) given for the Kotlin declaration's
   * last parameter is its trailing lambda.
   */
  private args(
    site: ts.Node,
    binding: ComposeBinding,
    given: readonly Given[],
    where: Where,
    label: string,
  ): { args: kt.Arg[]; trailing?: kt.Expr & { k: "lambda" } } {
    const params = "params" in binding.member ? binding.member.params : [];
    const last = params.length - 1;
    const args: kt.Arg[] = [];
    let trailing: (kt.Expr & { k: "lambda" }) | undefined;

    const bound = new Set<string>();
    const put = (index: number, value: kt.Expr, lambda: boolean) => {
      const param = params[index]!;

      // A trailing lambda is Kotlin's last parameter's: none when a default after it is left out.
      if (
        index === last &&
        lambda &&
        value.k === "lambda" &&
        !binding.write.receiverArg &&
        !binding.member.kotlin?.omits
      )
        trailing = value as kt.Expr & { k: "lambda" };
      else
        args.push(
          binding.write.receiverArg && index === 0 ? { value } : { name: param.name, value },
        );
    };

    for (const g of given) {
      const param = params[g.index]!;

      if ("flag" in g) {
        put(g.index, kt.bool(true), false);
        continue;
      }

      // Children: the content lambda showing them.
      if ("children" in g) {
        if (param.kotlin?.role !== "content") this.refuseContent(g.at, label);

        put(g.index, kt.lambda([], this.children(g.children, COMPOSITION)), true);
        continue;
      }

      const arg = g.arg;

      // A bound signal: the value, and the callback of its changes setting the signal.
      if (ts.isCallExpression(arg) && isBind(this.checker, arg)) {
        const change = param.kotlin?.changedBy;

        if (!change) fail(arg, Codes.ToolkitBody, `${label}'s ${param.name} takes no bound signal`);

        bound.add(change);
        args.push(...this.bound(arg, param.name, change));
        continue;
      }

      const literal = ts.isArrowFunction(arg) || ts.isFunctionExpression(arg);

      put(g.index, this.argument(arg, param, where, label), literal);
    }

    // A value given as it is needs its change callback too, which Kotlin requires.
    for (const p of params) {
      const change = p.kotlin?.changedBy;
      const given = (name: string) =>
        bound.has(change!) || args.some((a) => a.name === name) || (trailing && name === change);

      if (change && given(p.name) && !given(change))
        fail(
          site,
          Codes.ToolkitBody,
          `${label} takes ${change} with ${p.name}, or a bound signal: \`${p.name}={bind(signal)}\``,
        );
    }

    return { args, ...(trailing ? { trailing } : {}) };
  }

  /** `bind(signal)`: the value Compose state holds, and a change setting the signal. */
  private bound(call: ts.CallExpression, value: string, change: string): kt.Arg[] {
    if (this.frame)
      fail(
        call,
        Codes.ToolkitBody,
        "a helper view binds no signal: its user binds the view that changes one",
      );

    const slots = this.crossings.bind(call);

    return [
      { name: value, value: kt.member(kt.member(kt.name(STATE), slots.value.name), "value") },
      {
        name: change,
        value: kt.lambda(
          ["value"],
          [
            kt.exprStmt(
              kt.call(kt.member(kt.name(STATE), slots.change.name), [{ value: kt.name("value") }]),
            ),
          ],
        ),
      },
    ];
  }

  /** An argument for a Kotlin parameter: content, a callback, or a value of the parameter's number type. */
  private argument(arg: ts.Expression, param: SdkParam, where: Where, label: string): kt.Expr {
    const fn = ts.isArrowFunction(arg) || ts.isFunctionExpression(arg) ? arg : undefined;

    // A @Composable content lambda: it returns what it shows.
    if (param.kotlin?.role === "content") {
      if (!fn) this.refuseContent(arg, label);

      const params = this.parameters(fn, param);

      return kt.lambda(
        params,
        this.composition(fn, (e) => this.content(e)),
      );
    }

    // A lambda of a list's scope: it adds the elements it returns (LazyColumn's items).
    if (fn && givesElements(param)) {
      const params = this.parameters(fn, param);

      return kt.lambda(
        params,
        this.composition(fn, (e) => this.content(e, ADDING), ADDING),
      );
    }

    if (fn) return this.lambda(fn, label, param.kotlin?.returnsThrough, param);

    // A number of the parameter's Kotlin type: its schema's, or (generic) what the call instantiates it with.
    const num =
      schemaNumberKind(param.type) ??
      (param.type.k === "tparam"
        ? numberKindOf(this.checker, this.checker.getContextualType(arg))
        : undefined);

    return convert(this.expr(arg, where), num);
  }

  /**
   * A callback or a coroutine's block: code that runs later, outside the
   * composition. A lambda whose result only its receiver makes (`through`,
   * DisposableEffect's `onDispose`) returns the function it gives that
   * member: it ends with `onDispose { cleanup }`.
   */
  private lambda(
    fn: ts.ArrowFunction | ts.FunctionExpression,
    label: string,
    through?: string,
    param?: SdkParam,
  ): kt.Expr & { k: "lambda" } {
    const params = this.parameters(fn, param);
    const where: Where = {
      composable: false,
      suspending: isAsync(fn),
      ...(label ? { label } : {}),
    };

    if (through) {
      const statements = ts.isBlock(fn.body) ? [...fn.body.statements] : [];
      const last = statements.pop();
      const given =
        last && ts.isReturnStatement(last) && last.expression && skipParentheses(last.expression);

      if (!given || !(ts.isArrowFunction(given) || ts.isFunctionExpression(given)))
        fail(
          fn,
          Codes.ToolkitBody,
          `${label}'s lambda ends by returning the function it gives ${through}: \`return () => …\``,
        );

      return kt.lambda(params, [
        ...statements.flatMap((s) => this.statement(s, where)),
        kt.exprStmt(kt.call(kt.name(through), [], this.lambda(given, through))),
      ]) as kt.Expr & { k: "lambda" };
    }

    const body = ts.isBlock(fn.body)
      ? fn.body.statements.flatMap((s) => this.statement(s, where))
      : [kt.exprStmt(this.expr(fn.body, where).e)];

    return kt.lambda(params, body) as kt.Expr & { k: "lambda" };
  }

  /**
   * A lambda's parameters as Kotlin's: its scope (the first, where the
   * Kotlin lambda has a scope receiver) is Kotlin's implicit receiver,
   * the others its parameters.
   */
  private parameters(fn: ts.ArrowFunction | ts.FunctionExpression, param?: SdkParam): string[] {
    const scoped = !!param && receivesScope(param);

    return fn.parameters.flatMap((p, i) => {
      if (!scoped || i > 0) return [this.parameter(p)];

      const symbol = ts.isIdentifier(p.name) ? this.checker.getSymbolAtLocation(p.name) : undefined;

      if (symbol) this.locals.set(symbol, { name: "this", scope: true });

      return [];
    });
  }

  /**
   * A keyed list (Lucent's, over a Compose list form: LazyListScope's
   * items): the list's holders, keyed by what its key prop computes, each
   * shown by the item content its children give, whose item is its holder.
   */
  private keyedList(
    site: ts.JsxElement | ts.JsxSelfClosingElement,
    binding: ComposeBinding,
    form: ListForm,
    given: readonly Given[],
  ): kt.Expr {
    const byIndex = new Map(given.flatMap((g) => ("arg" in g ? [[g.index, g.arg] as const] : [])));
    const source = byIndex.get(form.source);
    const content = byIndex.get(form.content);
    const key = byIndex.get(form.key);
    const tag = (ts.isJsxElement(site) ? site.openingElement : site).tagName.getText();

    if (!key || !(ts.isArrowFunction(key) || ts.isFunctionExpression(key)) || ts.isBlock(key.body))
      fail(
        site,
        Codes.ToolkitBody,
        `a Compose list keys its items: <${tag} key={(item) => item.id} …>`,
      );

    if (!source || !content || !(ts.isArrowFunction(content) || ts.isFunctionExpression(content)))
      fail(
        site,
        Codes.ToolkitBody,
        `a Compose list shows its items with a function of the item's scope and the item: <${tag} …>{(_, item) => …}</${tag}>`,
      );

    if (
      given.some((g) => g.index !== form.source && g.index !== form.content && g.index !== form.key)
    )
      fail(site, Codes.ToolkitBody, "a Compose list takes its items, its key and its item content");

    const scoped = receivesScope(form.params[form.content]!);
    const list = this.crossings.list(
      site,
      source,
      content,
      { ...(key.parameters[0] ? { param: key.parameters[0] } : {}), expression: key.body },
      scoped ? 1 : 0,
    );

    if (scoped) this.parameters(content, form.params[form.content]);

    const body = this.composition(content, (e) => this.content(e));
    const items = kt.lambda([ITEM], body) as kt.Expr & { k: "lambda" };
    const last = form.content === form.params.length - 1 && !binding.member.kotlin?.omits;

    return kt.call(
      kt.name(this.written(binding.write)),
      [
        {
          name: form.params[form.source]!.name,
          value: kt.member(kt.member(kt.name(STATE), list.name), "value"),
        },
        {
          name: form.params[form.key]!.name,
          value: kt.lambda([], [kt.exprStmt(kt.member(kt.name("it"), "key"))]),
        },
        ...(last ? [] : [{ name: form.params[form.content]!.name, value: items }]),
      ],
      last ? items : undefined,
    );
  }

  /**
   * A callback's parameter: a name of the body, whose Kotlin type is the
   * one the callback's declaration gives it (a Float stays a Float).
   */
  private parameter(p: ts.ParameterDeclaration): string {
    if (!ts.isIdentifier(p.name) || p.dotDotDotToken)
      fail(p, Codes.ToolkitBody, "a callback's parameters in content are names: `(value) => …`");

    const symbol = this.checker.getSymbolAtLocation(p.name);
    // Its type is the callback's declaration's: a branded Kotlin number stays one.
    const type = this.checker.getTypeAtLocation(p);
    const num = numberKindOf(this.checker, type);
    const text = !!(type.flags & ts.TypeFlags.StringLike);

    if (symbol)
      this.locals.set(symbol, {
        name: p.name.text,
        ...(num ? { num } : {}),
        ...(text ? { text } : {}),
      });

    return p.name.text;
  }

  /** A plain object the setup computed (a local holding it), if `receiver` is one. */
  private plainObject(receiver: ts.Expression, where: Where): Val | undefined {
    if (!ts.isIdentifier(receiver) || !this.locals.has(this.symbol(receiver)!)) return undefined;

    const v = this.expr(receiver, where);

    return v.vt?.k === "object" ? v : undefined;
  }

  /** A field of a plain object: the data class's property. */
  private field(e: ts.PropertyAccessExpression, object: Val): Val {
    const fields = object.vt?.k === "object" ? object.vt.fields : [];
    const f = fields.find((x) => x.name === e.name.text);

    if (!f) fail(e, Codes.ToolkitBody, `the content cannot read \`${e.getText()}\``);

    return plainVal(kt.member(object.e, f.name), fieldType(f));
  }

  // --- slots ---

  private valueSlot(source: ts.Expression, via?: HelperUse): Val {
    if (this.frame) {
      const value = this.frameValue(source, via);

      return plainVal(kt.name(value.name), value.type);
    }

    const slot = this.crossings.value(source, via);
    const holder = slot.list ? kt.name(ITEM) : kt.name(STATE);

    return plainVal(kt.member(kt.member(holder, slot.name), "value"), slot.type);
  }

  /** The helper view's value of `source` (one per use and expression): a parameter of its own. */
  private frameValue(source: ts.Expression, via?: HelperUse): HelperValue {
    const values = this.frame!.values;
    const key = `${keyOfUse(via)}${source.getText()}`;
    const found = values.find((v) => `${keyOfUse(v.via)}${v.source.getText()}` === key);

    if (found) return found;

    const value: HelperValue = {
      name: valueName(source, values.length),
      source,
      type: this.crossings.typeOf(source),
      ...(via ? { via } : {}),
    };

    values.push(value);

    return value;
  }

  /** The callback prop `e` reads (`props.onTap`), in the helper view written. */
  private callbackProp(e: ts.Expression): HelperCallback | undefined {
    const helper = this.frame?.helper;

    if (!helper?.props || !ts.isPropertyAccessExpression(e) || !ts.isIdentifier(e.expression))
      return undefined;

    if (this.symbol(e.expression) !== helper.props) return undefined;

    return helper.callbacks.find((c) => c.name === e.name.text);
  }

  /**
   * An element (or a call) using a helper view: its composable, given the
   * values it computes from its props (the setup computes them here, or a
   * helper using this one gives them), and the callbacks it is given.
   */
  private used(
    node: ts.JsxElement | ts.JsxSelfClosingElement | ts.CallExpression,
    helper: ViewHelper,
  ): kt.Expr {
    const where = ts.isCallExpression(node)
      ? node.expression
      : (ts.isJsxElement(node) ? node.openingElement : node).tagName;

    if (this.stack.includes(helper.fn))
      fail(
        where,
        Codes.ToolkitBody,
        `the helper view \`${helper.name}\` uses itself: a helper's views end`,
      );

    const args = helperArgs(node, helper);
    const callbacks = new Set(helper.callbacks.map((c) => c.name));

    for (const [name, arg] of args)
      if (!callbacks.has(name) && !this.crossings.givesValue(arg, this.frame?.helper))
        fail(
          arg,
          Codes.ToolkitBody,
          `\`${helper.name}\`'s \`${name}\` is plain data the setup computes (its props, signals, values, a list's item) or a literal`,
        );

    const fn = this.helperFunction(helper);
    const use: HelperUse = { helper, args, site: node };
    const callback = (c: HelperCallback): kt.Expr => {
      const arg = args.get(c.name);

      if (!arg) return kt.lambda(c.params.length ? c.params.map(() => "_") : [], []);

      const e = skipParentheses(arg);

      return ts.isArrowFunction(e) || ts.isFunctionExpression(e)
        ? this.lambda(e, "")
        : this.expr(e, { composable: false, suspending: false }).e;
    };

    return kt.call(kt.name(fn.name), [
      ...fn.values.map((v) => ({
        name: v.name,
        value: this.valueSlot(v.source, chainUse(v.via, use)).e,
      })),
      ...helper.callbacks.map((c) => ({ name: c.name, value: callback(c) })),
    ]);
  }

  /** A helper view's composable, written once per body. */
  private helperFunction(helper: ViewHelper): HelperFunction {
    const found = this.shared.helpers.get(helper.fn);

    if (found) return found;

    const frame: Frame = { helper, values: [] };
    const writer = new BodyWriter(
      this.checker,
      helper.jsx,
      helper.statements,
      this.crossings,
      this.shared,
      frame,
      [...this.stack, helper.fn],
    );
    const body = writer.body();

    for (const i of writer.imports) this.imports.add(i);
    this.usesText ||= writer.usesText;

    const taken = new Set([...this.shared.helpers.values()].map((h) => h.name));
    let name = `${this.shared.registration}_${helper.name}`;

    while (taken.has(name)) name = `${name}_`;

    const fn: HelperFunction = { helper, name, values: frame.values, body };

    this.shared.helpers.set(helper.fn, fn);

    return fn;
  }

  private symbol(id: ts.Identifier | ts.MemberName): ts.Symbol | undefined {
    return this.crossings.symbol(id);
  }
}

// --- numbers -----------------------------------------------------------------------------------

function numberLiteral(node: ts.Node, n: number): Val {
  if (!Number.isFinite(n)) fail(node, Codes.ToolkitBody, "content's numbers are finite");

  return { e: kt.num(literalText(n, "Double", node)), num: "Double", literal: n };
}

function literalText(n: number, kind: NumberKind, node?: ts.Node): string {
  const plain = String(n).replace("e+", "e");

  switch (kind) {
    case "Double":
      return /[.e]/.test(plain) ? plain : `${plain}.0`;
    case "Float":
      return `${plain}f`;
    case "Int":
    case "Long":
    case "Short":
    case "Byte":
      // Kotlin types an integer literal as the Short or Byte its parameter expects.
      if (!Number.isInteger(n)) fail(node, Codes.ToolkitBody, `${n} is not a Kotlin ${kind}`);

      return kind === "Long" ? `${plain}L` : plain;
  }
}

/** `v` as the Kotlin number type `to` (unchanged when `to` is undefined: not a number). */
function convert(v: Val, to: NumberKind | undefined): kt.Expr {
  if (!to || !v.num || v.num === to) return v.e;

  if (v.literal !== undefined) return kt.num(literalText(v.literal, to));

  return kt.call(kt.member(v.e, `to${to}`), []);
}

// --- helpers -----------------------------------------------------------------------------------

function describe(n: ts.Node): string {
  return `\`${n.getText().split("\n")[0]!.slice(0, 40)}\``;
}

/** A Compose list form's parameters (by index): the array, the item content, the key. */
interface ListForm {
  readonly params: readonly SdkParam[];
  readonly source: number;
  readonly content: number;
  readonly key: number;
}

/**
 * Whether a member is a list form, by its schema: a list of some T, a
 * content lambda given a T, and a `key` callback of a T (LazyListScope's
 * items). Lucent keys such a list.
 */
function listForm(binding: ComposeBinding): ListForm | undefined {
  const params = "params" in binding.member ? binding.member.params : [];
  const element = (t: SdkParam["type"]) =>
    t.k === "array" && t.list && t.of.k === "tparam" ? t.of.name : undefined;
  const takes = (p: SdkParam, name: string) =>
    p.type.k === "fn" &&
    p.type.params.length === 1 &&
    p.type.params[0]!.k === "tparam" &&
    p.type.params[0]!.name === name;

  const source = params.findIndex((p) => element(p.type));
  const t = source >= 0 ? element(params[source]!.type)! : undefined;
  const content = t ? params.findIndex((p) => p.kotlin?.role === "content" && takes(p, t)) : -1;
  const key = t
    ? params.findIndex((p) => p.name === "key" && p.kotlin?.role === "callback" && takes(p, t))
    : -1;

  return source >= 0 && content >= 0 && key >= 0 ? { params, source, content, key } : undefined;
}
