// Generated by Lucent. Do not edit.

package com.margelo.nitro.lucent

import androidx.annotation.Keep
import com.facebook.proguard.annotations.DoNotStrip
import com.margelo.nitro.core.ArrayBuffer
import com.margelo.nitro.core.Promise

@Keep
@DoNotStrip
class HybridKitchen : HybridKitchenSpec() {
  override fun summarize(stats: KitchenStats, key: String, verbose: Boolean): String {
    return KitchenBodies.summarize(KitchenBodies.Stats.fromNitro(stats), key, verbose)
  }
}

object KitchenBodies {
  data class Stats(
    var count: Int,
    var labels: Map<String, String>,
    var values: MutableList<Double>
  ) {
    fun toNitro(): KitchenStats = KitchenStats(count = count.toDouble(), labels = labels, values = values.toDoubleArray())

    companion object {
      fun fromNitro(value: KitchenStats): Stats = Stats(count = value.count.toInt(), labels = value.labels, values = value.values.toMutableList())
    }
  }

  fun label(stats: Stats, key: String): String {
    val found: String? = stats.labels[key]
    if (found != null) {
      return found!!
    }
    return "none"
  }

  fun summarize(stats: Stats, key: String, verbose: Boolean): String {
    var out: String = label(stats, key)
    var i: Int = 0
    while (i < stats.count) {
      out = out + "!"
      i = i + 1
    }
    var evens: MutableList<Double> = mutableListOf<Double>()
    for (v in stats.values) {
      if (v % 2.0 == 0.0 && v > 0.0) {
        evens.add(v)
      } else {
        if (v < 0.0) {
          break
        } else {
          continue
        }
      }
    }
    if (!verbose || evens.size.toDouble() == 0.0) {
      return out
    }
    return out + " " + lucentStr(evens.size.toDouble()) + " " + lucentStr(-i)
  }
}
