// Generated by Lucent. Do not edit.

import Foundation
import NitroModules

class HybridAdd: HybridAddSpec {
  func add(a: Double, b: Double) throws -> Double {
    let result = try AddBodies.add(a: a, b: b)
    return result
  }

  func multiply(a: Double, b: Double) throws -> Double {
    let result = try AddBodies.multiply(a: a, b: b)
    return result
  }
}

enum AddBodies {
  static func add(a: Double, b: Double) throws -> Double {
    return (a + b)
  }

  static func multiply(a: Double, b: Double) throws -> Double {
    return (a * b)
  }
}
