// Generated by Lucent. Do not edit.

import Foundation
import NitroModules

class HybridNativeClass: HybridNativeClassSpec {
  func lucentRelease(handle: Double) throws { LucentObjectRegistry.shared.release(handle) }

  func lucentInternal_8f133499183f7a85_Counter__get_value(lucentSelf: Double) throws -> Double {
    return try LucentObjectRegistry.shared.withLock {
    let result = try NativeClassBodies.lucentInternal_8f133499183f7a85_Counter__get_value(lucentSelf: try LucentObjectRegistry.shared.get(lucentSelf, lucentInternal_8f133499183f7a85_Counter.self))
    return result
    }
  }

  func lucentInternal_8f133499183f7a85_Counter__set_value(lucentSelf: Double, value: Double) throws -> Void {
    return try LucentObjectRegistry.shared.withLock {
    try NativeClassBodies.lucentInternal_8f133499183f7a85_Counter__set_value(lucentSelf: try LucentObjectRegistry.shared.get(lucentSelf, lucentInternal_8f133499183f7a85_Counter.self), value: value)
    }
  }

  func lucentInternal_8f133499183f7a85_Counter__method_increment(lucentSelf: Double, delta: Double) throws -> Double {
    return try LucentObjectRegistry.shared.withLock {
    let result = try NativeClassBodies.lucentInternal_8f133499183f7a85_Counter__method_increment(lucentSelf: try LucentObjectRegistry.shared.get(lucentSelf, lucentInternal_8f133499183f7a85_Counter.self), delta: delta)
    return result
    }
  }

  func lucentInternal_8f133499183f7a85_Counter__create(initial: Double) throws -> Double {
    return try LucentObjectRegistry.shared.withLock {
    let result = try NativeClassBodies.lucentInternal_8f133499183f7a85_Counter__create(initial: initial)
    return LucentObjectRegistry.shared.hold(result)
    }
  }

  func makeCounter(initial: Double) throws -> Double {
    return try LucentObjectRegistry.shared.withLock {
    let result = try NativeClassBodies.makeCounter(initial: initial)
    return LucentObjectRegistry.shared.hold(result)
    }
  }

  func advance(counter: Double) throws -> Double {
    return try LucentObjectRegistry.shared.withLock {
    let result = try NativeClassBodies.advance(counter: try LucentObjectRegistry.shared.get(counter, lucentInternal_8f133499183f7a85_Counter.self))
    return result
    }
  }
}

enum NativeClassBodies {
  static func lucentInternal_8f133499183f7a85_Counter__get_value(lucentSelf: lucentInternal_8f133499183f7a85_Counter) throws -> Double {
    return lucentSelf.value
  }

  static func lucentInternal_8f133499183f7a85_Counter__set_value(lucentSelf: lucentInternal_8f133499183f7a85_Counter, value: Double) throws -> Void {
    var lucentSelf: lucentInternal_8f133499183f7a85_Counter = lucentSelf
    lucentSelf.value = value
  }

  static func lucentInternal_8f133499183f7a85_Counter__method_increment(lucentSelf: lucentInternal_8f133499183f7a85_Counter, delta: Double) throws -> Double {
    var lucentSelf: lucentInternal_8f133499183f7a85_Counter = lucentSelf
    lucentSelf.value = (lucentSelf.value + delta)
    return lucentSelf.value
  }

  static func lucentInternal_8f133499183f7a85_Counter__create(initial: Double) throws -> lucentInternal_8f133499183f7a85_Counter {
    var lucentSelf: lucentInternal_8f133499183f7a85_Counter = lucentInternal_8f133499183f7a85_Counter(value: 0.0)
    lucentSelf.value = initial
    return lucentSelf
  }

  static func makeCounter(initial: Double) throws -> lucentInternal_8f133499183f7a85_Counter {
    return try lucentInternal_8f133499183f7a85_Counter__create(initial: initial)
  }

  static func advance(counter: lucentInternal_8f133499183f7a85_Counter) throws -> Double {
    return try lucentInternal_8f133499183f7a85_Counter__method_increment(lucentSelf: counter, delta: 1.0)
  }
}
