// Generated by Lucent. Do not edit.

import { NitroModules } from "react-native-nitro-modules";
import { lucentCall } from "@lucent/runtime";

const native = NitroModules.createHybridObject("Fibonacci");

export function fibonacci(n) {
  return lucentCall(() => native.fibonacci(n));
}
