// Generated by Lucent. Do not edit.

import { NitroModules } from "react-native-nitro-modules";
import { lucentCall, toArrayBuffer } from "@lucent-lang/runtime";

const native = NitroModules.createHybridObject("Bytes");

export function checksum(data) {
  return lucentCall(() => native.checksum(toArrayBuffer(data)));
}
