// Generated by Lucent. Do not edit.

import { NitroModules } from "react-native-nitro-modules";
import { lucentCall } from "@lucent-lang/runtime";

const native = NitroModules.createHybridObject("NativeUnion");

export function evaluate(value) {
  const result = lucentCall(() => native.evaluate(value));
  return ((u) => { if (u == null || typeof u !== "object") throw new TypeError("Expected Result"); switch (u["kind"]) { case "ok": if (u["value"] == null) throw new TypeError("Missing Result.value"); return { "kind": "ok", "value": u["value"] }; case "error": if (u["message"] == null) throw new TypeError("Missing Result.message"); return { "kind": "error", "message": u["message"] }; default: throw new TypeError("Invalid Result tag"); } })(result);
}

export function read(result) {
  return lucentCall(() => native.read(((u) => { if (u == null || typeof u !== "object") throw new TypeError("Expected Result"); switch (u["kind"]) { case "ok": if (u["value"] == null) throw new TypeError("Missing Result.value"); return { "kind": "ok", "value": u["value"], "message": undefined }; case "error": if (u["message"] == null) throw new TypeError("Missing Result.message"); return { "kind": "error", "message": u["message"], "value": undefined }; default: throw new TypeError("Invalid Result tag"); } })(result)));
}
