// Generated by Lucent. Do not edit.

import { NitroModules } from "react-native-nitro-modules";
import { lucentCall } from "@lucent-lang/runtime";

const native = NitroModules.createHybridObject("NativeStdlib");

export function magnitude(value) {
  return lucentCall(() => native.magnitude(value));
}

export function matches(value) {
  return lucentCall(() => native.matches(value));
}

export function roundTrip(text) {
  return lucentCall(() => native.roundTrip(text));
}
