// Generated by Lucent. Do not edit.

import { NitroModules } from "react-native-nitro-modules";
import { lucentCall } from "@lucent-lang/core/runtime";

const native = NitroModules.createHybridObject("TernaryCall");

export function choose(flag) {
  return lucentCall(() => native.choose(flag));
}

export function nested(flag, other) {
  return lucentCall(() => native.nested(flag, other));
}
