// Generated by Lucent. Do not edit.

import { type HybridObject } from 'react-native-nitro-modules';

export interface ClosureBody extends HybridObject<{ ios: 'swift'; android: 'kotlin' }> {
  scaled(base: number): number;
}
