// Generated by Lucent. Do not edit.

import { type HybridObject } from 'react-native-nitro-modules';

export interface Clamp extends HybridObject<{ ios: 'swift'; android: 'kotlin' }> {
  clamp(value: number, min: number, max: number): number;
}
