// Generated by Lucent. Do not edit.

import { type HybridObject } from 'react-native-nitro-modules';

export interface WorkerThread extends HybridObject<{ ios: 'swift'; android: 'kotlin' }> {
  summarize(values: number[]): Promise<number>;
  label(count: number): Promise<string>;
}
