// Generated by Lucent. Do not edit.

import { type HybridObject } from 'react-native-nitro-modules';

export interface TernaryCall extends HybridObject<{ ios: 'swift'; android: 'kotlin' }> {
  choose(flag: boolean): number;
  nested(flag: boolean, other: boolean): number;
}
