// Generated by Lucent. Do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const { loadModule, lucentClass } = require("./_lucent/runtime.js");
const m = loadModule("object-strings", () => require("react-native").TurboModuleRegistry, require("./_lucent/identity.js"));
exports.arrays = m.arrays;
exports.collections = m.collections;
exports.bytes = m.bytes;
exports.promises = m.promises;
exports.aborts = m.aborts;
exports.optionals = m.optionals;
exports.kinds = m.kinds;
exports.log = m.log;
