// Generated by Lucent from union-discriminants.lucent.ts. Do not edit.
#include "m_union_u2d_discriminants.h"

#pragma push_macro("kind")
#undef kind
#pragma push_macro("r")
#undef r
#pragma push_macro("s")
#undef s
#pragma push_macro("shape")
#undef shape

namespace lucent_app {

lucent::String m_union_u2d_discriminants::shape(std::variant<lucent::Ref<lucent_app::S_Circle>, lucent::Ref<lucent_app::S_Square>> p0_) {
  lucent::String v1_ = ({ const auto& u_1_ = p0_; u_1_.index() == 0 ? std::get<0>(u_1_)->kind : std::get<1>(u_1_)->kind; });
  bool v3_ = v1_ == LUCENT_STR("circle");
  lucent::String v14_{};
  if (v3_) {
    lucent::Ref<lucent_app::S_Circle> v5_ = lucent::narrow<lucent::Ref<lucent_app::S_Circle>>(p0_);
    double v6_ = v5_->r;
    v14_ = lucent::String(LUCENT_STR("circle ")) + lucent::toJsString(v6_);
  } else {
    lucent::Ref<lucent_app::S_Square> v10_ = lucent::narrow<lucent::Ref<lucent_app::S_Square>>(p0_);
    double v11_ = v10_->s;
    v14_ = lucent::String(LUCENT_STR("square ")) + lucent::toJsString(v11_);
  }
  return v14_;
}

void m_union_u2d_discriminants::init() {
}

}  // namespace lucent_app

#pragma pop_macro("shape")
#pragma pop_macro("s")
#pragma pop_macro("r")
#pragma pop_macro("kind")
