// Generated by Lucent. Do not edit.
package dev.lucent;

import android.content.Context;
import android.view.ViewGroup;

/**
 * A Flex (T50, lucent/ui_flex.h): a ViewGroup laid out by Lucent's layout
 * core, React Native's Yoga. It measures and lays out its children through
 * its C++ side (platform/android_layout.cpp), which writes their frames;
 * nothing else does. `flex` names that side; 0 once its mount has ended,
 * and the view then lays nothing out.
 */
final class LucentFlexView extends ViewGroup {
  long flex;

  LucentFlexView(Context context, long flex) {
    super(context);
    this.flex = flex;
  }

  @Override
  protected void onMeasure(int widthSpec, int heightSpec) {
    final float[] size =
        flex == 0
            ? null
            : measure(
                flex,
                MeasureSpec.getMode(widthSpec),
                MeasureSpec.getSize(widthSpec),
                MeasureSpec.getMode(heightSpec),
                MeasureSpec.getSize(heightSpec),
                getLayoutDirection() == LAYOUT_DIRECTION_RTL);

    if (size == null) {
      setMeasuredDimension(resolveSize(0, widthSpec), resolveSize(0, heightSpec));
      return;
    }

    setMeasuredDimension(
        resolveSize((int) Math.ceil(size[0]), widthSpec),
        resolveSize((int) Math.ceil(size[1]), heightSpec));
  }

  @Override
  protected void onLayout(boolean changed, int left, int top, int right, int bottom) {
    if (flex != 0) layout(flex, right - left, bottom - top, getLayoutDirection() == LAYOUT_DIRECTION_RTL);
  }

  /** The size the Flex takes under the specs, in pixels (its tree's root's: exactly the specs otherwise). */
  static native float[] measure(
      long flex, int widthMode, int width, int heightMode, int height, boolean rtl);

  /** Lays the Flex's children out in `width` by `height` pixels (its tree first, at its root). */
  static native void layout(long flex, int width, int height, boolean rtl);
}
