// Generated by Lucent. Do not edit.

package expo.modules.lucent

import expo.modules.kotlin.functions.Coroutine
import expo.modules.kotlin.jni.ArrayBuffer
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import expo.modules.kotlin.records.Field
import expo.modules.kotlin.records.Record

class LucentNativeEventModule : Module() {
  class Progress(
    @Field var percent: Double = 0.0,
    @Field var label: String = ""
  ) : Record

  private val eventTokens = mutableListOf<Int>()
  override fun definition() = ModuleDefinition {
    Name("Lucent_native-event")
    Events("progress")
    OnCreate {
      eventTokens.add(LucentEventHub.subscribe("__event_253846265b0a3b85_progress") { json -> sendEvent("progress", mapOf("json" to json)) })
    }
    OnDestroy { eventTokens.forEach { LucentEventHub.remove(it) }; eventTokens.clear() }

    Function("report") { percent: Double ->
      report(percent)
    }
  }

  private fun __event_253846265b0a3b85_progress(payload: Progress): Unit {
    LucentEventHub.emit("__event_253846265b0a3b85_progress", mapOf("percent" to payload.percent, "label" to payload.label))
  }

  private fun report(percent: Double): Unit {
    __event_253846265b0a3b85_progress(Progress(percent = percent, label = "native"))
  }
}
