// Generated by Lucent. Do not edit.

package expo.modules.lucent

import expo.modules.kotlin.functions.Coroutine
import expo.modules.kotlin.jni.ArrayBuffer
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import expo.modules.kotlin.records.Field
import expo.modules.kotlin.records.Record

class LucentBytesModule : Module() {
  override fun definition() = ModuleDefinition {
    Name("Lucent_bytes")

    Function("checksum") { data: ArrayBuffer ->
      checksum(data)
    }
  }

  private fun checksum(data: ArrayBuffer): Double {
    var sum: Double = 0.0
    var i: Double = 0.0
    while (i < LucentBytes.length(data)) {
      sum = sum + LucentBytes.get(data, i)
      i = i + 1.0
    }
    return sum % 256.0
  }
}
