// Generated by Lucent. Do not edit.

import ExpoModulesCore

@ExpoModule("Lucent_native-class")
public final class LucentNativeClassModule: Module {
  @JS func lucentRelease(handle: Double) { LucentObjectRegistry.shared.release(handle) }

  @JS("lucentInternal_8f133499183f7a85_Counter__get_value")
  func __bridge_lucentInternal_8f133499183f7a85_Counter__get_value(lucentSelf: Double) throws -> Double {
    return try LucentObjectRegistry.shared.withObjects([lucentSelf]) { lucentLeases in
      let result = try lucentInternal_8f133499183f7a85_Counter__get_value(lucentSelf: try lucentLeases.get(lucentSelf, lucentInternal_8f133499183f7a85_Counter.self))
      return result
    }
  }

  func lucentInternal_8f133499183f7a85_Counter__get_value(lucentSelf: lucentInternal_8f133499183f7a85_Counter) throws -> Double {
    return lucentSelf.value
  }

  @JS("lucentInternal_8f133499183f7a85_Counter__set_value")
  func __bridge_lucentInternal_8f133499183f7a85_Counter__set_value(lucentSelf: Double, value: Double) throws -> Void {
    return try LucentObjectRegistry.shared.withObjects([lucentSelf]) { lucentLeases in
      let result = try lucentInternal_8f133499183f7a85_Counter__set_value(lucentSelf: try lucentLeases.get(lucentSelf, lucentInternal_8f133499183f7a85_Counter.self), value: value)
      return result
    }
  }

  func lucentInternal_8f133499183f7a85_Counter__set_value(lucentSelf: lucentInternal_8f133499183f7a85_Counter, value: Double) throws -> Void {
    var lucentSelf: lucentInternal_8f133499183f7a85_Counter = lucentSelf
    lucentSelf.value = value
  }

  @JS("lucentInternal_8f133499183f7a85_Counter__method_increment")
  func __bridge_lucentInternal_8f133499183f7a85_Counter__method_increment(lucentSelf: Double, delta: Double) throws -> Double {
    return try LucentObjectRegistry.shared.withObjects([lucentSelf]) { lucentLeases in
      let result = try lucentInternal_8f133499183f7a85_Counter__method_increment(lucentSelf: try lucentLeases.get(lucentSelf, lucentInternal_8f133499183f7a85_Counter.self), delta: delta)
      return result
    }
  }

  func lucentInternal_8f133499183f7a85_Counter__method_increment(lucentSelf: lucentInternal_8f133499183f7a85_Counter, delta: Double) throws -> Double {
    var lucentSelf: lucentInternal_8f133499183f7a85_Counter = lucentSelf
    lucentSelf.value = (lucentSelf.value + delta)
    return lucentSelf.value
  }

  @JS("lucentInternal_8f133499183f7a85_Counter__create")
  func __bridge_lucentInternal_8f133499183f7a85_Counter__create(initial: Double) throws -> Double {
    return try LucentObjectRegistry.shared.withObjects([]) { lucentLeases in
      let result = try lucentInternal_8f133499183f7a85_Counter__create(initial: initial)
      return LucentObjectRegistry.shared.hold(result)
    }
  }

  func lucentInternal_8f133499183f7a85_Counter__create(initial: Double) throws -> lucentInternal_8f133499183f7a85_Counter {
    var lucentSelf: lucentInternal_8f133499183f7a85_Counter = lucentInternal_8f133499183f7a85_Counter(value: 0.0)
    lucentSelf.value = initial
    return lucentSelf
  }

  @JS("makeCounter")
  func __bridge_makeCounter(initial: Double) throws -> Double {
    return try LucentObjectRegistry.shared.withObjects([]) { lucentLeases in
      let result = try makeCounter(initial: initial)
      return LucentObjectRegistry.shared.hold(result)
    }
  }

  func makeCounter(initial: Double) throws -> lucentInternal_8f133499183f7a85_Counter {
    return try lucentInternal_8f133499183f7a85_Counter__create(initial: initial)
  }

  @JS("advance")
  func __bridge_advance(counter: Double) throws -> Double {
    return try LucentObjectRegistry.shared.withObjects([counter]) { lucentLeases in
      let result = try advance(counter: try lucentLeases.get(counter, lucentInternal_8f133499183f7a85_Counter.self))
      return result
    }
  }

  func advance(counter: lucentInternal_8f133499183f7a85_Counter) throws -> Double {
    return try lucentInternal_8f133499183f7a85_Counter__method_increment(lucentSelf: counter, delta: 1.0)
  }
}
