Pod::Spec.new do |s|
  s.name           = 'Lucent'
  s.version        = '0.0.0'
  s.summary        = 'Native code generated by Lucent'
  s.description    = 'Swift generated ahead of time from *.lucent.ts files.'
  s.author         = ''
  s.homepage       = 'https://github.com/Fausto95/lucent'
  s.platforms      = { :ios => '16.4', :tvos => '16.4' }
  s.source         = { git: '' }
  s.static_framework = true

  s.dependency 'ExpoModulesCore'

  s.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES',
  }

  s.source_files = "**/*.{h,m,mm,swift,hpp,cpp}"
end
