// Generated by Lucent. Do not edit.

import ExpoModulesCore

@ExpoModule("Lucent_add")
public final class LucentAddModule: Module {
  @JS
  func add(a: Double, b: Double) throws -> Double {
    return a + b
  }

  @JS
  func multiply(a: Double, b: Double) throws -> Double {
    return a * b
  }
}
