// Generated by Lucent. Do not edit.

import { requireNativeModule } from "expo-modules-core";
import { lucentCall } from "@lucent-lang/core/runtime";

const native = requireNativeModule("Lucent_async-sum");

export function total(values) {
  return lucentCall(() => native.total(values));
}
