// Generated by Lucent. Do not edit.

import { requireNativeModule } from "expo-modules-core";
import { lucentCall } from "@lucent-lang/core/runtime";

const native = requireNativeModule("Lucent_fibonacci");

export function fibonacci(n) {
  return lucentCall(() => native.fibonacci(n));
}
