// Generated by Lucent. Do not edit.
#include <lucent/jsi/host.h>

static_assert(lucent::js::kRuntimeAbi == 2, "generated for Lucent runtime ABI 2: build it with the runtime lucent build copied next to it");

namespace {

const lucent::js::ModuleIdentity kModuleIdentities[] = {{"module-initialization", "e03a421872fb2616"}};

}  // namespace

namespace lucent::js {

const BuildIdentity& buildIdentity() {
  static const BuildIdentity identity = {"all", "a855d4913cbdb4a9", kModuleIdentities, 1};
  return identity;
}

}  // namespace lucent::js
