// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("plus")
#undef plus
#pragma push_macro("x")
#undef x
#pragma push_macro("y")
#undef y

namespace lucent_app {

struct C_Vec : lucent::Object {
  double x{};
  double y{};
  void construct(double p0_, double p1_);
  static lucent::Ref<C_Vec> create(double p0_, double p1_);
  lucent::Ref<lucent_app::C_Vec> plus(lucent::Ref<lucent_app::C_Vec> p0_);
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_Vec::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "x", this->x);
  lucent::jsonField(w, first, "y", this->y);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("y")
#pragma pop_macro("x")
#pragma pop_macro("plus")
