// Generated by Lucent. Do not edit.
#pragma once
#include <lucent/lucent.h>

#pragma push_macro("label")
#undef label

namespace lucent_app {

struct C_Box;

struct C_Box : lucent::Object {
  lucent::Opt<lucent::String> label{};
  void construct();
  static lucent::Ref<C_Box> create();
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_Box::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "label", this->label);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("label")
