// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("note")
#undef note
#pragma push_macro("v")
#undef v

namespace lucent_app {

struct S_Note;

struct S_Note : lucent::Object {
  lucent::Opt<lucent::String> note{};
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Note>& v);

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Note>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "note", v->note);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("v")
#pragma pop_macro("note")
