// Generated by Lucent. Do not edit.
#include "m_object_u2d_strings.h"
#include <lucent/jsi/convert.h>
#include <lucent/jsi/host.h>

#pragma push_macro("aborts")
#undef aborts
#pragma push_macro("arrays")
#undef arrays
#pragma push_macro("bytes")
#undef bytes
#pragma push_macro("collections")
#undef collections
#pragma push_macro("kinds")
#undef kinds
#pragma push_macro("log")
#undef log
#pragma push_macro("optionals")
#undef optionals
#pragma push_macro("promises")
#undef promises

namespace lucent::js {

jsi::Value errorInstanceToJs(jsi::Runtime& rt, Host& h, const Error& v) {
  return jsi::Value::undefined();
}

}  // namespace lucent::js

namespace {

using namespace lucent::js;

void install_m_object_u2d_strings(jsi::Runtime& rt, Host& host, jsi::Object& exports) {
  defineFunction(rt, exports, "arrays", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("arrays", "packages/compiler/test/e2e/cases/object-strings.lucent.ts", 10), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_object_u2d_strings::arrays());
    });
  });
  defineFunction(rt, exports, "collections", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("collections", "packages/compiler/test/e2e/cases/object-strings.lucent.ts", 27), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_object_u2d_strings::collections());
    });
  });
  defineFunction(rt, exports, "bytes", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("bytes", "packages/compiler/test/e2e/cases/object-strings.lucent.ts", 35), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_object_u2d_strings::bytes());
    });
  });
  defineFunction(rt, exports, "promises", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("promises", "packages/compiler/test/e2e/cases/object-strings.lucent.ts", 44), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_object_u2d_strings::promises());
    });
  });
  defineFunction(rt, exports, "aborts", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("aborts", "packages/compiler/test/e2e/cases/object-strings.lucent.ts", 50), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_object_u2d_strings::aborts());
    });
  });
  defineFunction(rt, exports, "optionals", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("optionals", "packages/compiler/test/e2e/cases/object-strings.lucent.ts", 56), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_object_u2d_strings::optionals());
    });
  });
  defineFunction(rt, exports, "kinds", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("kinds", "packages/compiler/test/e2e/cases/object-strings.lucent.ts", 64), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_object_u2d_strings::kinds());
    });
  });
  defineFunction(rt, exports, "log", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("log", "packages/compiler/test/e2e/cases/object-strings.lucent.ts", 79), [&]() -> jsi::Value {
      lucent_app::m_object_u2d_strings::log();
      return jsi::Value::undefined();
    });
  });
}

const ModuleDef kModules[] = {{"object-strings", install_m_object_u2d_strings}};

}  // namespace

namespace lucent::js {

const ModuleDef* registeredModules(size_t& count) {
  count = 1;
  return kModules;
}

void resetModuleState() {
  lucent_app::m_object_u2d_strings::init();
}

}  // namespace lucent::js

#pragma pop_macro("promises")
#pragma pop_macro("optionals")
#pragma pop_macro("log")
#pragma pop_macro("kinds")
#pragma pop_macro("collections")
#pragma pop_macro("bytes")
#pragma pop_macro("arrays")
#pragma pop_macro("aborts")
