import type { Block } from "../../types";

export const blocks: Block[] = [
    {
      kind: "p",
      text: "JavaScript sees only what a module exports. Everything else (helpers, types, module state) stays native. You import a Lucent module like any other TypeScript file.",
    },
    {
      kind: "code",
      filename: "counter.lucent.ts",
      code: `import { delay } from "lucent:core";

export enum Mode {
  Fast = "fast",
  Safe = "safe",
}

export const LIMITS = { min: 1, max: 100 };

let calls = 0; // module state: native only, reset when JavaScript reloads

function bounded(n: number): number {
  return Math.min(LIMITS.max, Math.max(LIMITS.min, n));
}

export function clamp(n: number): number {
  calls++;
  return bounded(n);
}

export async function slowClamp(n: number, mode: Mode): Promise<number> {
  await delay(mode === Mode.Safe ? 50 : 5);
  return bounded(n);
}

export class Counter {
  value = 0;

  increment(by: number = 1): number {
    this.value = bounded(this.value + by);
    return this.value;
  }

  static callCount(): number {
    return calls;
  }
}`,
    },
    {
      kind: "code",
      filename: "App.tsx",
      code: `import { clamp, slowClamp, Counter, Mode, LIMITS } from "./counter.lucent";

clamp(250); // 100, computed natively on the JS thread
await slowClamp(250, Mode.Safe); // 100, computed on the Lucent thread
const counter = new Counter();
counter.increment(5); // 5
Counter.callCount(); // 1
LIMITS.max; // 100`,
    },
    { kind: "h2", text: "What JavaScript sees" },
    {
      kind: "table",
      head: ["Export", "In JavaScript"],
      rows: [
        ["`export function`", "A function. Arguments are checked and converted on each call (see [Type conversions](/docs/boundary/conversions/))."],
        ["`export async function`", "A function that returns a `Promise`."],
        [
          "`export class`",
          "A constructor usable with `new` and `instanceof`. Public methods, fields and accessors are on the prototype; static methods are on the constructor. `private`, `protected` and `#private` members are not visible. See [Object identity](/docs/boundary/identity/).",
        ],
        ["`export const`", "A value, converted once when the module loads. Later changes on either side are not shared."],
        ["`export enum`", "A frozen object. Numeric enums also get the reverse mapping (`Level[0] === \"Low\"`), like TypeScript's."],
        ["`export type`, `export interface`", "Nothing at runtime; the types are for the editor."],
      ],
    },
    {
      kind: "p",
      text: "Generic functions and classes cannot be exported, because JavaScript cannot pick a native instantiation: export a concrete wrapper ([LUCENT2007](/docs/language/diagnostics/)). Export lists, re-exports and default exports are not supported (`LUCENT3003`); write `export` on the declaration.",
    },
    { kind: "h2", text: "Sync and async exports" },
    {
      kind: "table",
      head: ["", "Runs on", "Use it for"],
      rows: [
        ["`export function`", "The JS thread, during the call", "Short work whose result JavaScript needs right away."],
        ["`export async function`", "The Lucent thread; the promise settles on the JS thread", "Anything heavy, or anything that waits."],
      ],
    },
    {
      kind: "p",
      text: "Lucent code runs one piece at a time, like JavaScript. While an async export is busy between two `await`s, a synchronous call from JavaScript waits for it. Keep synchronous exports short, or make heavy ones `async`. The details are in [Async](/docs/language/async/).",
    },
    { kind: "h2", text: "How the import reaches native code" },
    {
      kind: "p",
      text: "`lucent build` compiles every `*.lucent.ts` file into C++ and writes a JavaScript proxy per module to `.lucent/native/js/`. When Metro bundles the app, [`withLucent`](/docs/reference/metro/) replaces the contents of each `*.lucent.ts` file with its proxy:",
    },
    {
      kind: "code",
      filename: ".lucent/native/js/counter.js",
      code: `// Generated by Lucent. Do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const { loadModule, lucentClass } = require("./_lucent/runtime.js");
const m = loadModule("counter", () => require("react-native").TurboModuleRegistry);
exports.clamp = m.clamp;
exports.slowClamp = m.slowClamp;
exports.Counter = lucentClass(m.Counter);
exports.LIMITS = m.LIMITS;
exports.Mode = Object.freeze({ "Fast": "fast", "Safe": "safe" });`,
    },
    {
      kind: "p",
      text: "`loadModule` asks the `Lucent` TurboModule for the module's exports object, which is built in C++ on first access. Calls go straight through JSI: there is no bridge, no serialization to JSON, and no Swift or Kotlin layer. The pipeline is described in [How it works](/docs/how-it-works/).",
    },
    {
      kind: "p",
      text: "Your editor and `tsc` never see the proxy. They type-check `App.tsx` against the real `counter.lucent.ts`, so types, go-to-definition and rename work across the boundary.",
    },
    { kind: "h2", text: "When the proxy is missing" },
    {
      kind: "list",
      items: [
        "No proxy for a module: the import throws `Lucent: counter.lucent.ts has not been compiled.` Run `lucent build` (or keep Metro's watcher running) and rebuild the app.",
        "A proxy but no native module in the running binary: `Lucent: module \"counter\" is not in the native build.` Rebuild the app after adding a module.",
        "The TurboModule is not linked at all: `Lucent: the native module is not linked.` Check the `lucent` entry in `react-native.config.js` (see [CLI](/docs/reference/cli/)) and run `pod install` on iOS.",
      ],
    },
    {
      kind: "note",
      text: "Editing the body of a function changes native code, so the app binary must be rebuilt to run it. Fast Refresh reloads JavaScript only.",
    },
];
