// Generated by Lucent from exported-objects.lucent.ts. Do not edit.
#include "m_exported_u2d_objects.h"

#pragma push_macro("limit")
#undef limit
#pragma push_macro("ping")
#undef ping
#pragma push_macro("pings")
#undef pings
#pragma push_macro("settings")
#undef settings
#pragma push_macro("size")
#undef size

namespace lucent_app {

double m_exported_u2d_objects::ping(double p0_) {
  lucent::Ref<lucent::EventEmitterObject<lucent::Fn<void(double)>>> v1_ = lucent_app::m_exported_u2d_objects::pings;
  v1_->emit<0>(p0_);
  lucent::Ref<lucent::EventEmitterObject<lucent::Fn<void(double)>>> v3_ = lucent_app::m_exported_u2d_objects::pings;
  return v3_->listenerCount(0);
}

void m_exported_u2d_objects::init() {
  lucent_app::m_exported_u2d_objects::pings = lucent::EventEmitterObject<lucent::Fn<void(double)>>::create({"ping"});
  lucent_app::m_exported_u2d_objects::settings = ({ auto obj_1_ = std::make_shared<lucent_app::S_Settings>(); obj_1_->size = 2.0; obj_1_; });
  lucent_app::m_exported_u2d_objects::limit = 3.0;
}

}  // namespace lucent_app

#pragma pop_macro("size")
#pragma pop_macro("settings")
#pragma pop_macro("pings")
#pragma pop_macro("ping")
#pragma pop_macro("limit")
