// Generated by Lucent from bigint-unions.lucent.ts. Do not edit.
#include "m_bigint_u2d_unions.h"

#pragma push_macro("after")
#undef after
#pragma push_macro("b")
#undef b
#pragma push_macro("before")
#undef before
#pragma push_macro("compare")
#undef compare
#pragma push_macro("compareOptional")
#undef compareOptional
#pragma push_macro("flip")
#undef flip
#pragma push_macro("negate")
#undef negate
#pragma push_macro("steps")
#undef steps
#pragma push_macro("strings")
#undef strings
#pragma push_macro("toBigInt")
#undef toBigInt
#pragma push_macro("toBigIntOfAnything")
#undef toBigIntOfAnything
#pragma push_macro("toNumber")
#undef toNumber
#pragma push_macro("toNumberEither")
#undef toNumberEither
#pragma push_macro("toNumberNullable")
#undef toNumberNullable
#pragma push_macro("toNumberOfAnything")
#undef toNumberOfAnything
#pragma push_macro("toNumberOptional")
#undef toNumberOptional

namespace lucent_app {

double m_bigint_u2d_unions::toNumber(std::variant<lucent::BigInt, double> p0_) {
  return lucent::toNumber(p0_);
}

double m_bigint_u2d_unions::toNumberOptional(lucent::Opt<lucent::BigInt> p0_) {
  return lucent::toNumber(p0_);
}

double m_bigint_u2d_unions::toNumberNullable(lucent::Opt<lucent::BigInt> p0_) {
  return lucent::toNumber(p0_);
}

double m_bigint_u2d_unions::toNumberEither(lucent::Opt<std::variant<lucent::BigInt, double>> p0_) {
  return lucent::toNumber(p0_);
}

double m_bigint_u2d_unions::toNumberOfAnything(lucent::Opt<std::variant<lucent::BigInt, bool, double, lucent::String>> p0_) {
  return lucent::toNumber(p0_);
}

lucent::BigInt m_bigint_u2d_unions::toBigInt(std::variant<lucent::BigInt, double> p0_) {
  return lucent::toBigInt(p0_);
}

lucent::BigInt m_bigint_u2d_unions::toBigIntOfAnything(std::variant<lucent::BigInt, bool, double, lucent::String> p0_) {
  return lucent::toBigInt(p0_);
}

lucent::Array<lucent::String> m_bigint_u2d_unions::strings(lucent::Opt<std::variant<lucent::BigInt, double>> p0_) {
  lucent::String v1_ = lucent::toJsString(p0_);
  lucent::String v2_ = lucent::toJsString(p0_);
  lucent::String v5_ = lucent::String(LUCENT_STR("v=")) + lucent::toJsString(p0_);
  lucent::String v8_ = lucent::String(lucent::toJsString(p0_)) + LUCENT_STR("!");
  return lucent::Array<lucent::String>{v1_, v2_, v5_, v8_};
}

lucent::Array<bool> m_bigint_u2d_unions::compare(std::variant<lucent::BigInt, double> p0_, std::variant<lucent::BigInt, double> p1_) {
  bool v2_ = lucent::compareNumeric(p0_, p1_) < 0;
  bool v3_ = lucent::compareNumeric(p0_, p1_) <= 0;
  bool v4_ = lucent::compareNumeric(p0_, p1_) > 0;
  bool v5_ = lucent::compareNumeric(p0_, p1_) >= 0;
  bool v6_ = lucent::strictEquals(p0_, p1_);
  bool v7_ = !lucent::strictEquals(p0_, p1_);
  return lucent::Array<bool>{v2_, v3_, v4_, v5_, v6_, v7_};
}

lucent::Array<bool> m_bigint_u2d_unions::compareOptional(lucent::Opt<lucent::BigInt> p0_, lucent::BigInt p1_) {
  bool v2_ = lucent::strictEquals(p0_, p1_);
  bool v3_ = !lucent::strictEquals(p0_, p1_);
  bool v5_ = lucent::strictEquals(p0_, lucent::undefined);
  return lucent::Array<bool>{v2_, v3_, v5_};
}

std::variant<lucent::BigInt, double> m_bigint_u2d_unions::negate(std::variant<lucent::BigInt, double> p0_) {
  return lucent::negateNumeric(p0_);
}

std::variant<lucent::BigInt, double> m_bigint_u2d_unions::flip(std::variant<lucent::BigInt, double> p0_) {
  return lucent::bitNotNumeric(p0_);
}

lucent::Array<lucent::String> m_bigint_u2d_unions::steps(std::variant<lucent::BigInt, double> p0_) {
  std::variant<lucent::BigInt, double> b = p0_;
  std::variant<lucent::BigInt, double> v1_ = b;
  b = lucent::stepNumeric(v1_, 1);
  std::variant<lucent::BigInt, double> before = v1_;
  std::variant<lucent::BigInt, double> v4_ = lucent::stepNumeric(b, -1);
  b = v4_;
  std::variant<lucent::BigInt, double> after = v4_;
  b = lucent::stepNumeric(b, -1);
  lucent::String v8_ = lucent::toJsString(before);
  lucent::String v10_ = lucent::toJsString(after);
  lucent::String v12_ = lucent::toJsString(b);
  lucent::String v14_ = lucent::typeOf(b);
  return lucent::Array<lucent::String>{v8_, v10_, v12_, v14_};
}

void m_bigint_u2d_unions::init() {
}

}  // namespace lucent_app

#pragma pop_macro("toNumberOptional")
#pragma pop_macro("toNumberOfAnything")
#pragma pop_macro("toNumberNullable")
#pragma pop_macro("toNumberEither")
#pragma pop_macro("toNumber")
#pragma pop_macro("toBigIntOfAnything")
#pragma pop_macro("toBigInt")
#pragma pop_macro("strings")
#pragma pop_macro("steps")
#pragma pop_macro("negate")
#pragma pop_macro("flip")
#pragma pop_macro("compareOptional")
#pragma pop_macro("compare")
#pragma pop_macro("before")
#pragma pop_macro("b")
#pragma pop_macro("after")
