// Generated by Lucent. Do not edit.
#include <lucent/jsi/host.h>

static_assert(lucent::js::kRuntimeAbi == 2, "generated for Lucent runtime ABI 2: build it with the runtime lucent build copied next to it");

namespace {

const lucent::js::ModuleIdentity kModuleIdentities[] = {{"closures", "69ef51f241822c2d"}};

}  // namespace

namespace lucent::js {

const BuildIdentity& buildIdentity() {
  static const BuildIdentity identity = {"all", "e37d85c8549136ee", kModuleIdentities, 1};
  return identity;
}

}  // namespace lucent::js
