// Generated by Lucent from closures.lucent.ts. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_S_Object_6bd9ed01.h"

#pragma push_macro("accumulate")
#undef accumulate
#pragma push_macro("apply")
#undef apply
#pragma push_macro("callTwice")
#undef callTwice
#pragma push_macro("compose")
#undef compose
#pragma push_macro("counter")
#undef counter
#pragma push_macro("makeAdders")
#undef makeAdders
#pragma push_macro("makeGreeter")
#undef makeGreeter
#pragma push_macro("memo")
#undef memo
#pragma push_macro("ops")
#undef ops
#pragma push_macro("recurse")
#undef recurse
#pragma push_macro("sortBy")
#undef sortBy
#pragma push_macro("total")
#undef total

namespace lucent_app {

namespace m_closures {

inline double total{};
inline lucent::Dict<lucent::Fn<double(double, double)>> ops{};

lucent::Array<double> makeAdders();
double counter();
double compose(double p0_);
double recurse(double p0_);
double memo(double p0_);
double apply(lucent::String p0_, double p1_, double p2_);
double accumulate(double p0_);
lucent::Fn<lucent::String(lucent::String)> makeGreeter(lucent::String p0_);
double callTwice(lucent::Fn<double(double)> p0_, double p1_);
lucent::Array<lucent::String> sortBy(lucent::Array<lucent::Ref<lucent_app::S_Object_6bd9ed01>> p0_);
void init();

}  // namespace m_closures

}  // namespace lucent_app

#pragma pop_macro("total")
#pragma pop_macro("sortBy")
#pragma pop_macro("recurse")
#pragma pop_macro("ops")
#pragma pop_macro("memo")
#pragma pop_macro("makeGreeter")
#pragma pop_macro("makeAdders")
#pragma pop_macro("counter")
#pragma pop_macro("compose")
#pragma pop_macro("callTwice")
#pragma pop_macro("apply")
#pragma pop_macro("accumulate")
