// Generated by Lucent. Do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const { loadModule, lucentClass } = require("./_lucent/runtime.js");
const m = loadModule("numbers", () => require("react-native").TurboModuleRegistry, require("./_lucent/identity.js"));
exports.format = m.format;
exports.bits = m.bits;
exports.parse = m.parse;
exports.parseInts = m.parseInts;
exports.special = m.special;
exports.mathFns = m.mathFns;
exports.precision = m.precision;
exports.checks = m.checks;
exports.heldChecks = m.heldChecks;
exports.sum = m.sum;
exports.fib = m.fib;
exports.multiplyAdd = m.multiplyAdd;
