// Generated by Lucent from generics.lucent.ts. Do not edit.
#include "m_generics.h"

#pragma push_macro("demo")
#undef demo
#pragma push_macro("e")
#undef e
#pragma push_macro("f")
#undef f
#pragma push_macro("first")
#undef first
#pragma push_macro("g")
#undef g
#pragma push_macro("groupBy")
#undef groupBy
#pragma push_macro("groups")
#undef groups
#pragma push_macro("mapPairs")
#undef mapPairs
#pragma push_macro("n")
#undef n
#pragma push_macro("pairs")
#undef pairs
#pragma push_macro("push")
#undef push
#pragma push_macro("q")
#undef q
#pragma push_macro("s")
#undef s
#pragma push_macro("shift")
#undef shift

namespace lucent_app {

lucent::String m_generics::demo() {
  lucent::Ref<lucent_app::C_Queue<lucent::String>> q = lucent_app::C_Queue<lucent::String>::create();
  q->push(LUCENT_STR("a"));
  q->push(LUCENT_STR("b"));
  lucent::Ref<lucent_app::C_Queue<double>> n = lucent_app::C_Queue<double>::create();
  n->push(1.0);
  lucent::Array<double> v13_ = lucent::Array<double>{3.0, 4.0};
  lucent::Opt<double> v14_ = lucent_app::m_generics::first<double>(v13_);
  bool v16_ = !v14_.has();
  double v19_{};
  if (v16_) {
    v19_ = 0.0;
  } else {
    v19_ = v14_.value();
  }
  double f = v19_;
  lucent::Array<lucent::String> v21_ = lucent::Array<lucent::String>{LUCENT_STR("x")};
  lucent::Opt<lucent::String> v22_ = lucent_app::m_generics::first<lucent::String>(v21_);
  bool v24_ = !v22_.has();
  lucent::String v27_{};
  if (v24_) {
    v27_ = lucent::String();
  } else {
    v27_ = v22_.value();
  }
  lucent::String s = v27_;
  lucent::Array<double> v28_ = lucent::Array<double>{};
  lucent::Opt<double> e = lucent_app::m_generics::first<double>(v28_);
  lucent::Array<double> v32_ = lucent::Array<double>{1.0, 2.0};
  lucent::Fn<lucent::String(double)> v33_ = lucent::Fn<lucent::String(double)>([](double p0_) mutable -> lucent::String {
    return lucent::String(LUCENT_STR("#")) + lucent::toJsString(p0_);
  });
  lucent::Array<std::tuple<double, lucent::String>> pairs = lucent_app::m_generics::mapPairs<double, lucent::String>(v32_, v33_);
  lucent::Array<lucent::String> v38_ = lucent::Array<lucent::String>{LUCENT_STR("apple"), LUCENT_STR("avocado"), LUCENT_STR("banana")};
  lucent::Fn<lucent::String(lucent::String)> v39_ = lucent::Fn<lucent::String(lucent::String)>([](lucent::String p0_) mutable -> lucent::String {
    return p0_.charAt(0.0);
  });
  lucent::Map<lucent::String, lucent::Array<lucent::String>> groups = lucent_app::m_generics::groupBy<lucent::String>(v38_, v39_);
  lucent::Array<lucent::String> g = lucent::Array<lucent::String>{};
  lucent::Fn<double(lucent::Array<lucent::String>, lucent::String, lucent::Map<lucent::String, lucent::Array<lucent::String>>)> v44_ = lucent::Fn<double(lucent::Array<lucent::String>, lucent::String, lucent::Map<lucent::String, lucent::Array<lucent::String>>)>([g = g](lucent::Array<lucent::String> p0_, lucent::String p1_, lucent::Map<lucent::String, lucent::Array<lucent::String>> p2_) mutable -> double {
    lucent::String v6_ = p0_.join(LUCENT_STR("+"));
    lucent::String v8_ = lucent::concat(p1_, LUCENT_STR(":"), v6_);
    return g.push(v8_);
  });
  groups.forEach(lucent::Fn<void(lucent::Array<lucent::String>, lucent::String, lucent::Map<lucent::String, lucent::Array<lucent::String>>)>([fn_1_ = v44_](lucent::Array<lucent::String> a0, lucent::String a1, lucent::Map<lucent::String, lucent::Array<lucent::String>> a2) {
    fn_1_(a0, a1, a2);
  }));
  lucent::Opt<lucent::String> v47_ = q->shift();
  lucent::String v48_ = lucent::toJsString(v47_);
  double v51_ = q->get_size();
  lucent::String v52_ = lucent::toJsString(v51_);
  lucent::Opt<double> v55_ = n->shift();
  lucent::String v56_ = lucent::toJsString(v55_);
  lucent::String v59_ = lucent::toJsString(f);
  lucent::String v66_ = lucent::toJsString(lucent::strictEquals(e, lucent::undefined));
  lucent::String v69_ = lucent::json::stringify(pairs);
  lucent::String v73_ = g.join(LUCENT_STR(" "));
  return lucent::concat(v48_, LUCENT_STR(" "), v52_, LUCENT_STR(" "), v56_, LUCENT_STR(" "), v59_, LUCENT_STR(" "), s, LUCENT_STR(" "), v66_, LUCENT_STR(" "), v69_, LUCENT_STR(" "), v73_);
}

void m_generics::init() {
}

}  // namespace lucent_app

#pragma pop_macro("shift")
#pragma pop_macro("s")
#pragma pop_macro("q")
#pragma pop_macro("push")
#pragma pop_macro("pairs")
#pragma pop_macro("n")
#pragma pop_macro("mapPairs")
#pragma pop_macro("groups")
#pragma pop_macro("groupBy")
#pragma pop_macro("g")
#pragma pop_macro("first")
#pragma pop_macro("f")
#pragma pop_macro("e")
#pragma pop_macro("demo")
