// Generated by Lucent from generics.lucent.ts. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("A")
#undef A
#pragma push_macro("B")
#undef B
#pragma push_macro("T")
#undef T
#pragma push_macro("demo")
#undef demo
#pragma push_macro("f")
#undef f
#pragma push_macro("first")
#undef first
#pragma push_macro("groupBy")
#undef groupBy
#pragma push_macro("k")
#undef k
#pragma push_macro("list")
#undef list
#pragma push_macro("mapPairs")
#undef mapPairs
#pragma push_macro("out")
#undef out
#pragma push_macro("push")
#undef push
#pragma push_macro("size")
#undef size
#pragma push_macro("x")
#undef x

namespace lucent_app {

namespace m_generics {

template <class T>
lucent::Opt<T> first(lucent::Array<T> p0_);

template <class A, class B>
lucent::Array<std::tuple<A, B>> mapPairs(lucent::Array<A> p0_, lucent::Fn<B(A)> p1_);

template <class T>
lucent::Map<lucent::String, lucent::Array<T>> groupBy(lucent::Array<T> p0_, lucent::Fn<lucent::String(T)> p1_);

lucent::String demo();
void init();

}  // namespace m_generics

namespace m_generics {

template <class T>
lucent::Opt<T> first(lucent::Array<T> p0_) {
  return p0_.getIndex(static_cast<int64_t>(0));
}

}  // namespace m_generics

namespace m_generics {

template <class A, class B>
lucent::Array<std::tuple<A, B>> mapPairs(lucent::Array<A> p0_, lucent::Fn<B(A)> p1_) {
  return p0_.template map<std::tuple<A, B>>([f = p1_](A p0_, double p1_, lucent::Array<A> p2_) mutable -> std::tuple<A, B> {
    B v4_ = f(p0_);
    return std::tuple<A, B>(p0_, v4_);
  });
}

}  // namespace m_generics

namespace m_generics {

template <class T>
lucent::Map<lucent::String, lucent::Array<T>> groupBy(lucent::Array<T> p0_, lucent::Fn<lucent::String(T)> p1_) {
  lucent::Map<lucent::String, lucent::Array<T>> out = lucent::Map<lucent::String, lucent::Array<T>>();
  {
    auto coll0_ = p0_;
    for (size_t i0_ = 0; i0_ < coll0_.size(); i0_++) {
      T v3_ = coll0_.at(i0_);
      {
        T x = std::move(v3_);
        lucent::String k = p1_(x);
        lucent::Opt<lucent::Array<T>> list = out.get(k);
        bool v10_ = lucent::truthy(list);
        if (v10_) {
          lucent::Array<T> v12_ = list.value();
          (void)v12_.push(x);
        } else {
          lucent::Array<T> v18_ = lucent::Array<T>{x};
          (void)out.set(k, v18_);
        }
      }
    }
  }
  return out;
}

}  // namespace m_generics

}  // namespace lucent_app

#pragma pop_macro("x")
#pragma pop_macro("size")
#pragma pop_macro("push")
#pragma pop_macro("out")
#pragma pop_macro("mapPairs")
#pragma pop_macro("list")
#pragma pop_macro("k")
#pragma pop_macro("groupBy")
#pragma pop_macro("first")
#pragma pop_macro("f")
#pragma pop_macro("demo")
#pragma pop_macro("T")
#pragma pop_macro("B")
#pragma pop_macro("A")
