// Generated by Lucent. Do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const { loadModule, lucentClass } = require("./_lucent/runtime.js");
const m = loadModule("extension", () => require("react-native").TurboModuleRegistry, require("./_lucent/identity.js"));
exports.live = m.live;
exports.labelBytes = m.labelBytes;
exports.shortOutput = m.shortOutput;
exports.scoped = m.scoped;
exports.closeTwice = m.closeTwice;
exports.Filter = lucentClass(m.Filter);
