// Generated by scripts/sync-examples.ts from scripts/example-app/src/demos/files/NoteRow.tsx. Do not edit.
import { StyleSheet, Text, View } from "react-native";
import { Button } from "../../ui/Button";
import { space, type } from "../../ui/theme";
import { useTheme } from "../../ui/useTheme";
import type { Note } from "./sandbox.lucent";

interface Props {
  note: Note;
  onOpen: () => void;
  onDelete: () => void;
}

/** A file: its name, size and time, and what can be done with it. */
export function NoteRow({ note, onOpen, onDelete }: Props) {
  const { colors } = useTheme();

  return (
    <View style={styles.row}>
      <View style={styles.text}>
        <Text numberOfLines={1} style={[type.code, { color: colors.text }]}>
          {note.name}
        </Text>

        <Text style={[type.callout, { color: colors.textMuted }]}>
          {note.bytes} bytes · {new Date(note.modified).toLocaleTimeString()}
        </Text>
      </View>

      <Button
        label="Open"
        variant="secondary"
        onPress={onOpen}
        accessibilityHint={`Shows ${note.name}`}
      />

      <Button
        label="Delete"
        variant="danger"
        onPress={onDelete}
        accessibilityHint={`Deletes ${note.name}`}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  row: { flexDirection: "row", alignItems: "center", gap: space.sm },
  text: { flex: 1, gap: 2 },
});
