import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  referenceLayout: {
    display: {
      default: "grid",
      "@media (max-width: 850px)": "block",
    },
    gridTemplateColumns: {
      default: "225px minmax(0, 850px)",
      "@media (max-width: 1150px)": "190px minmax(0, 1fr)",
    },
    gap: {
      default: "70px",
      "@media (max-width: 1150px)": "36px",
    },
    padding: "62px 0 72px",
    justifyContent: "space-between",
    paddingTop: {
      default: null,
      "@media (max-width: 850px)": "32px",
      "@media (max-width: 540px)": "25px",
    },
  },
  referenceMain: {
    minWidth: "0",
  },
  referenceIntro: {
    padding: "44px 0",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#30362b",
    scrollMarginTop: "30px",
    paddingTop: "0",
    paddingBlock: {
      default: null,
      "@media (max-width: 540px)": "34px",
    },
  },
  referenceKicker: {
    display: "flex",
    gap: {
      default: "20px",
      "@media (max-width: 540px)": "12px",
    },
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
  },
  versionBadge: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#465735",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: "#465735",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#465735",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: "#465735",
    borderRadius: "4px",
    color: "#c4f778",
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
    padding: "7px 9px",
    whiteSpace: "nowrap",
  },
  referenceHeading: {
    fontSize: {
      default: "clamp(2.5rem, 4.3vw, 3.75rem)",
      "@media (max-width: 540px)": "2.625rem",
    },
    fontWeight: 500,
    letterSpacing: {
      default: "-2.5px",
      "@media (max-width: 540px)": "-1.8px",
    },
    lineHeight: 1.12,
    margin: {
      default: "28px 0 22px",
      "@media (max-width: 540px)": "25px 0",
    },
  },
  referenceHeadingAccent: {
    color: "#c4f778",
    display: {
      default: "block",
      "@media (max-width: 850px)": "inline",
      "@media (max-width: 540px)": "block",
    },
  },
  referenceLead: {
    fontSize: {
      default: "1.25rem",
      "@media (max-width: 540px)": "1.125rem",
    },
    lineHeight: 1.65,
    color: "#d0d8c7",
    margin: "17px 0",
    maxWidth: "650px",
  },
  referenceNote: {
    display: "flex",
    alignItems: "baseline",
    gap: {
      default: "15px",
      "@media (max-width: 540px)": "10px",
    },
    backgroundColor: "#1b2416",
    borderLeftWidth: "2px",
    borderLeftStyle: "solid",
    borderLeftColor: "#c4f778",
    borderRadius: "0 5px 5px 0",
    padding: {
      default: "16px 22px",
      "@media (max-width: 540px)": "15px",
    },
    margin: "26px 0",
  },
  noteMark: {
    color: "#c4f778",
    fontWeight: 400,
    fontSize: "1rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
  },
  referenceNoteText: {
    fontSize: "1rem",
    lineHeight: 1.85,
    color: "#aeb7a4",
    margin: "0",
  },
  referenceInlineCode: {
    fontWeight: 400,
    fontSize: "0.875em",
    lineHeight: 1.7,
    fontFamily: '"IBM Plex Mono", monospace',
    color: "#d5e4c7",
    overflowWrap: "anywhere",
    backgroundColor: "#20271b",
    borderRadius: "3px",
    padding: "2px 4px",
  },
  referenceParagraph: {
    fontSize: "1rem",
    lineHeight: 1.85,
    color: "#aeb7a4",
    margin: "17px 0",
  },
  referenceSection: {
    padding: "44px 0",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#30362b",
    scrollMarginTop: "30px",
    paddingBlock: {
      default: null,
      "@media (max-width: 540px)": "34px",
    },
  },
  referenceSectionLabel: {
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
    letterSpacing: "1.2px",
    color: "#93a781",
  },
  referenceSectionHeading: {
    fontSize: {
      default: "2rem",
      "@media (max-width: 540px)": "1.75rem",
    },
    lineHeight: 1.2,
    letterSpacing: "-1px",
    fontWeight: 500,
    margin: "12px 0 18px",
  },
  referenceList: {
    paddingLeft: "23px",
    margin: "20px 0",
  },
  referenceListItem: {
    fontSize: "1rem",
    lineHeight: 1.85,
    color: "#aeb7a4",
    paddingLeft: "5px",
    margin: "7px 0",
    "::marker": {
      color: "#71865d",
    },
  },
  referenceStrong: {
    color: "#f0f2eb",
    fontWeight: 550,
  },
  referenceCaveat: {
    fontSize: "1rem",
    lineHeight: 1.85,
    color: "#a5af9a",
    margin: "17px 0",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: "#5a644f",
    paddingLeft: "20px",
  },
  referenceTable: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#30362b",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: "#30362b",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#30362b",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: "#30362b",
    borderRadius: "6px",
    overflow: "auto",
    margin: "26px 0",
  },
  typeMappingTable: {
    borderCollapse: "collapse",
    width: "100%",
    fontSize: "0.875rem",
    lineHeight: 1.7,
    textAlign: "left",
    minWidth: "650px",
  },
  typeMappingHeading: {
    fontSize: "0.75rem",
    fontWeight: 500,
    color: "#d3ddc9",
    padding: {
      default: "14px 17px",
      "@media (max-width: 540px)": "12px",
    },
    backgroundColor: "#1e2519",
    width: "34%",
  },
  tableHeading: {
    fontSize: "0.75rem",
    fontWeight: 500,
    color: "#d3ddc9",
    padding: {
      default: "14px 17px",
      "@media (max-width: 540px)": "12px",
    },
    backgroundColor: "#1e2519",
  },
  tableLabelCell: {
    padding: {
      default: "14px 17px",
      "@media (max-width: 540px)": "12px",
    },
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#30362b",
    color: "#d5e4c7",
    verticalAlign: "top",
  },
  tableCode: {
    fontWeight: 400,
    fontSize: "0.8125rem",
    lineHeight: 1.7,
    fontFamily: '"IBM Plex Mono", monospace',
    color: "#d5e4c7",
    overflowWrap: "anywhere",
  },
  tableCell: {
    padding: {
      default: "14px 17px",
      "@media (max-width: 540px)": "12px",
    },
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#30362b",
    color: "#afbba5",
    verticalAlign: "top",
  },
  referenceSubheading: {
    fontSize: "1.25rem",
    fontWeight: 500,
    letterSpacing: "-0.4px",
    margin: "32px 0 12px",
  },
  referenceColumns: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 540px)": "1fr",
    },
    gap: {
      default: "35px",
      "@media (max-width: 540px)": "0",
    },
  },
  referenceColumnHeading: {
    fontSize: "1.25rem",
    fontWeight: 500,
    letterSpacing: "-0.4px",
    margin: "32px 0 12px",
    marginTop: "10px",
  },
  referenceDataTable: {
    borderCollapse: "collapse",
    width: "100%",
    fontSize: "0.875rem",
    lineHeight: 1.7,
    textAlign: "left",
  },
  semanticsList: {
    margin: "24px 0 0",
  },
  semanticsRow: {
    display: "grid",
    gridTemplateColumns: {
      default: "140px minmax(0, 1fr)",
      "@media (max-width: 540px)": "1fr",
    },
    gap: {
      default: "24px",
      "@media (max-width: 540px)": "8px",
    },
    padding: "23px 0",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#30362b",
  },
  semanticsTerm: {
    color: "#dbe4d1",
    fontWeight: 500,
    lineHeight: 1.85,
  },
  diagnosticCodeCell: {
    padding: {
      default: "14px 17px",
      "@media (max-width: 540px)": "12px",
    },
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#30362b",
    color: "#c4f778",
    verticalAlign: "top",
    fontFamily: '"IBM Plex Mono", monospace',
    whiteSpace: "nowrap",
  },
  referenceNext: {
    display: "flex",
    alignItems: {
      default: "center",
      "@media (max-width: 1150px)": "flex-start",
      "@media (max-width: 850px)": "center",
      "@media (max-width: 540px)": "flex-start",
    },
    justifyContent: "space-between",
    gap: "30px",
    marginTop: "42px",
    padding: {
      default: "30px",
      "@media (max-width: 540px)": "24px",
    },
    backgroundColor: "#1b2416",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#39482d",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: "#39482d",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#39482d",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: "#39482d",
    borderRadius: "6px",
    flexDirection: {
      default: null,
      "@media (max-width: 1150px)": "column",
      "@media (max-width: 850px)": "row",
      "@media (max-width: 540px)": "column",
    },
  },
  referenceNextHeading: {
    fontSize: {
      default: "1.5rem",
      "@media (max-width: 540px)": "1.75rem",
    },
    lineHeight: 1.2,
    letterSpacing: "-0.5px",
    fontWeight: 500,
    margin: "9px 0 0",
  },
  referenceNextButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: {
      default: "28px",
      "@media (max-width: 540px)": "18px",
    },
    padding: {
      default: "15px 20px",
      "@media (max-width: 540px)": "13px 15px",
    },
    borderRadius: "5px",
    fontSize: "0.875rem",
    fontWeight: 650,
    transitionProperty: "background-color, transform",
    transitionDuration: "0.2s, 0.2s",
    backgroundColor: "#c4f778",
    color: "#17210e",
    flexShrink: 0,
    ":hover": {
      backgroundColor: "#d5ff9c",
      transform: "translateY(-2px)",
    },
  },
});
