// Generated by Lucent. Do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const { loadModule, lucentClass } = require("./_lucent/runtime.js");
const m = loadModule("events", () => require("react-native").TurboModuleRegistry, require("./_lucent/identity.js"));
exports.download = m.download;
exports.finishNow = m.finishNow;
exports.counts = m.counts;
exports.inLucent = m.inLucent;
exports.make = m.make;
exports.ping = m.ping;
exports.channelJson = m.channelJson;
exports.Channel = lucentClass(m.Channel);
exports.downloads = m.downloads;
