// Generated by Lucent from object-keys.lucent.ts. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("enumerated")
#undef enumerated
#pragma push_macro("inRecord")
#undef inRecord
#pragma push_macro("literalKeys")
#undef literalKeys

namespace lucent_app {

namespace m_object_u2d_keys {

bool inRecord(lucent::Dict<double> p0_, lucent::String p1_);
lucent::String literalKeys();
lucent::String enumerated();
void init();

}  // namespace m_object_u2d_keys

}  // namespace lucent_app

#pragma pop_macro("literalKeys")
#pragma pop_macro("inRecord")
#pragma pop_macro("enumerated")
