import type { Block, DocPage } from "../../apps/website/src/docs/types.ts";
import { headingId } from "../../apps/website/src/docs/types.ts";
import { proseOf } from "./prose.ts";

/** Markup out: links keep their text, code keeps its content. */
const plain = (text: string): string =>
  text
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/[`*]/g, "")
    .replace(/^[#>|-]+\s*|\s*\|\s*/gm, " ")
    .replace(/\s+/g, " ")
    .trim();

/** A page's sections: its top, then one per h2, each with the prose under it. */
function sections(page: DocPage): { heading?: string; text: string }[] {
  const out: { heading?: string; blocks: Block[] }[] = [{ blocks: [] }];
  for (const block of page.blocks) {
    if (block.kind === "h2") out.push({ heading: block.text, blocks: [] });
    else out[out.length - 1]!.blocks.push(block);
  }
  return out.map((s) => ({
    ...(s.heading ? { heading: s.heading } : {}),
    text: plain(proseOf(s.blocks).join(" ")),
  }));
}

/** src/generated/search-index.ts: what the site's search looks through. */
export function searchIndex(pages: DocPage[]): string {
  const entries = pages.flatMap((page) =>
    sections(page).map(({ heading, text }) => ({
      href: `/docs/${page.slug}${page.slug ? "/" : ""}${heading ? `#${headingId(heading)}` : ""}`,
      page: plain(page.title),
      ...(heading ? { heading: plain(heading) } : {}),
      text: heading ? text : `${plain(page.description)} ${text}`.trim(),
    })),
  );
  return `// Generated by scripts/website.ts. Do not edit.\n\nimport type { SearchEntry } from "../docs/search";\n\nexport const searchIndex: SearchEntry[] = ${JSON.stringify(entries, null, 1)};\n`;
}
