// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("bump")
#undef bump
#pragma push_macro("count")
#undef count
#pragma push_macro("step")
#undef step

namespace lucent_app {

struct C_Counter : lucent::Object {
  double step{};
  double count{};
  void construct(double p0_);
  static lucent::Ref<C_Counter> create(double p0_);
  double bump();
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_Counter::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "step", this->step);
  lucent::jsonField(w, first, "count", this->count);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("step")
#pragma pop_macro("count")
#pragma pop_macro("bump")
