// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_S_Opts.h"
#include "lucent_app_C_Base.h"

#pragma push_macro("describe")
#undef describe
#pragma push_macro("opts")
#undef opts
#pragma push_macro("seen")
#undef seen

namespace lucent_app {

struct C_WithOpts : lucent_app::C_Base {
  lucent::Ref<lucent_app::S_Opts> opts{};
  void construct();
  static lucent::Ref<C_WithOpts> create();
  lucent::String describe() override;
  bool lucentJson_(lucent::JsonWriter& w, bool toJson) override;
};

inline bool C_WithOpts::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "seen", this->seen);
  lucent::jsonField(w, first, "opts", this->opts);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("seen")
#pragma pop_macro("opts")
#pragma pop_macro("describe")
