// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("first")
#undef first
#pragma push_macro("w")
#undef w

namespace lucent_app {

struct S_Object4 : lucent::Object {
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object4>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("w")
#pragma pop_macro("first")
