// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_S_Object_1e208747.h"

#pragma push_macro("first")
#undef first
#pragma push_macro("inner")
#undef inner
#pragma push_macro("w")
#undef w
#pragma push_macro("x")
#undef x
#pragma push_macro("y")
#undef y

namespace lucent_app {

struct S_Object_42336d24;

struct S_Object_42336d24 : lucent::Object {
  double x{};
  double y{};
  lucent::Ref<lucent_app::S_Object_1e208747> inner{};
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object_42336d24>& v);

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object_42336d24>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "x", v->x);
  lucent::jsonField(w, first, "y", v->y);
  lucent::jsonField(w, first, "inner", v->inner);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("y")
#pragma pop_macro("x")
#pragma pop_macro("w")
#pragma pop_macro("inner")
#pragma pop_macro("first")
