// Generated by Lucent from optimizations.lucent.ts. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("appends")
#undef appends
#pragma push_macro("boundedSum")
#undef boundedSum
#pragma push_macro("building")
#undef building
#pragma push_macro("compound")
#undef compound
#pragma push_macro("crc")
#undef crc
#pragma push_macro("directCallbacks")
#undef directCallbacks
#pragma push_macro("journal")
#undef journal
#pragma push_macro("keptCallbacks")
#undef keptCallbacks
#pragma push_macro("mutatingCallbacks")
#undef mutatingCallbacks
#pragma push_macro("negativeRemainder")
#undef negativeRemainder
#pragma push_macro("numberStrings")
#undef numberStrings
#pragma push_macro("pastExact")
#undef pastExact
#pragma push_macro("rewrite")
#undef rewrite
#pragma push_macro("signedProducts")
#undef signedProducts
#pragma push_macro("sometimesFractional")
#undef sometimesFractional
#pragma push_macro("stringKeys")
#undef stringKeys
#pragma push_macro("toInt32")
#undef toInt32
#pragma push_macro("unbounded")
#undef unbounded

namespace lucent_app {

namespace m_optimizations {

inline lucent::String journal{};

double boundedSum(double p0_);
lucent::String compound(double p0_);
lucent::String negativeRemainder();
lucent::String signedProducts(double p0_);
lucent::String unbounded();
lucent::String pastExact();
double sometimesFractional(double p0_);
lucent::String toInt32(lucent::Array<double> p0_);
double crc(double p0_);
lucent::String directCallbacks(lucent::Array<double> p0_, double p1_);
lucent::String keptCallbacks(lucent::Array<double> p0_);
lucent::String mutatingCallbacks();
lucent::String stringKeys();
lucent::String building(double p0_);
lucent::String rewrite();
lucent::String appends(double p0_);
lucent::String numberStrings();
void init();

}  // namespace m_optimizations

}  // namespace lucent_app

#pragma pop_macro("unbounded")
#pragma pop_macro("toInt32")
#pragma pop_macro("stringKeys")
#pragma pop_macro("sometimesFractional")
#pragma pop_macro("signedProducts")
#pragma pop_macro("rewrite")
#pragma pop_macro("pastExact")
#pragma pop_macro("numberStrings")
#pragma pop_macro("negativeRemainder")
#pragma pop_macro("mutatingCallbacks")
#pragma pop_macro("keptCallbacks")
#pragma pop_macro("journal")
#pragma pop_macro("directCallbacks")
#pragma pop_macro("crc")
#pragma pop_macro("compound")
#pragma pop_macro("building")
#pragma pop_macro("boundedSum")
#pragma pop_macro("appends")
