// Generated by scripts/sync-examples.ts from scripts/example-app. Do not edit.
// expo-application's ApplicationModule.kt.
import { appContext, available } from "lucent:android";
import type { PackageInfo } from "lucent:android/android.content.pm";

function packageInfo(): PackageInfo | null {
  const context = appContext();
  return context.getPackageManager()?.getPackageInfo(context.getPackageName() ?? "", 0) ?? null;
}

export function applicationId(): string | null {
  return appContext().getPackageName();
}

export function applicationName(): string | null {
  const context = appContext();
  const pm = context.getPackageManager();
  return pm ? (context.getApplicationInfo()?.loadLabel(pm) ?? null) : null;
}

export function nativeApplicationVersion(): string | null {
  return packageInfo()?.versionName ?? null;
}

export function nativeBuildVersion(): string | null {
  const info = packageInfo();
  if (!info) return null;
  return `${available("android", 28) ? info.longVersionCode : info.versionCode}`;
}

export async function getInstallationTimeAsync(): Promise<Date> {
  return new Date(packageInfo()?.firstInstallTime ?? 0);
}
