// Generated by scripts/sync-examples.ts from scripts/example-app. Do not edit.
// expo-location's LocationModule.kt, on the platform LocationManager (the
// original uses Play services' fused provider, which the bare app lacks).
import { Location, LocationManager } from "lucent:android/android.location";
import { PackageManager } from "lucent:android/android.content.pm";
import { Looper } from "lucent:android/android.os";
import { appContext, available } from "lucent:android";
import type { LocationObject, LocationPermissionResponse, LocationProviderStatus } from "./location.lucent";

function manager(): LocationManager {
  const m = appContext().getSystemService(LocationManager);
  if (!m) throw new Error("LocationManager is not available");
  return m;
}

function granted(permission: string): boolean {
  return appContext().checkSelfPermission(permission) === PackageManager.PERMISSION_GRANTED;
}

function exportLocation(l: Location): LocationObject {
  return {
    coords: {
      latitude: l.getLatitude(),
      longitude: l.getLongitude(),
      altitude: l.getAltitude(),
      accuracy: l.getAccuracy(),
      altitudeAccuracy: available("android", 26) ? l.getVerticalAccuracyMeters() : null,
      heading: l.getBearing(),
      speed: l.getSpeed(),
    },
    timestamp: l.getTime(),
  };
}

export async function getForegroundPermissionsAsync(): Promise<LocationPermissionResponse> {
  const coarse = granted("android.permission.ACCESS_COARSE_LOCATION");
  return { status: coarse ? "granted" : "undetermined", granted: coarse, canAskAgain: true, expires: "never" };
}

function locationEnabled(): boolean {
  const m = manager();
  if (available("android", 28)) return m.isLocationEnabled();
  return m.isProviderEnabled(LocationManager.GPS_PROVIDER) || m.isProviderEnabled(LocationManager.NETWORK_PROVIDER);
}

export async function hasServicesEnabledAsync(): Promise<boolean> {
  return locationEnabled();
}

export async function getProviderStatusAsync(): Promise<LocationProviderStatus> {
  const enabled = locationEnabled();
  return { locationServicesEnabled: enabled, backgroundModeEnabled: enabled };
}

export async function getLastKnownPositionAsync(): Promise<LocationObject | null> {
  const m = manager();
  let best: Location | null = null;
  // java.util.List is not bridged yet: the platform's providers, by name.
  for (const provider of [LocationManager.GPS_PROVIDER, LocationManager.NETWORK_PROVIDER, LocationManager.FUSED_PROVIDER, LocationManager.PASSIVE_PROVIDER]) {
    if (!m.isProviderEnabled(provider)) continue;
    const l = m.getLastKnownLocation(provider);
    if (l && (!best || l.getTime() > best.getTime())) best = l;
  }
  return best ? exportLocation(best) : null;
}

export function getCurrentPositionAsync(): Promise<LocationObject> {
  // The first fix of a listener removed after it (getCurrentLocation takes a
  // generic Consumer<Location>, which is not bindable yet).
  return new Promise((resolve, reject) => {
    const looper = Looper.getMainLooper();
    if (!looper) return reject(new Error("No main looper"));
    let listener = (location: Location) => {};
    listener = (location: Location) => {
      manager().removeUpdates(listener);
      resolve(exportLocation(location));
    };
    manager().requestLocationUpdates(provider(), 0, 0, listener, looper);
  });
}

/** GPS where it is on: a fused request at balanced accuracy uses network location, which emulators lack. */
function provider(): string {
  return manager().isProviderEnabled(LocationManager.GPS_PROVIDER) ? LocationManager.GPS_PROVIDER : LocationManager.FUSED_PROVIDER;
}

const watching = new Map<number, (location: Location) => void>();
let nextId = 1;

export async function watchPositionAsync(callback: (location: LocationObject) => void): Promise<number> {
  const id = nextId++;
  const listener = (location: Location) => callback(exportLocation(location));
  watching.set(id, listener);
  const looper = Looper.getMainLooper();
  if (looper) manager().requestLocationUpdates(provider(), 1000, 0, listener, looper);
  return id;
}

export async function stopWatching(id: number): Promise<void> {
  const listener = watching.get(id);
  watching.delete(id);
  if (listener) manager().removeUpdates(listener);
}
