// Generated by scripts/sync-examples.ts. Do not edit.
import { Platform } from "react-native";
import { linkedLibraries } from "./linked.lucent";
import type { SdkCase } from "./types";

// Lucent binds what the app already links like the SDK: React Native's pods
// on iOS, AndroidX on Android (scripts/example-app-bare).
export const parityCases: SdkCase[] = [
  {
    name: "linked libraries (React Native's pods; AndroidX)",
    run: linkedLibraries,
    expected: Platform.OS === "ios" ? /^\d+ request handlers, \d+ image decoders$/ : "INTERNET granted true",
  },
];
