// The docs' MDX: what the writer writes (the generated reference pages),
// the reader reads back as the same blocks, so the checks see what a page shows.
import { describe, expect, it } from "vite-plus/test";
import { headingId, parseMeta } from "../src/docs/markdown.ts";
import { readMdx } from "../src/docs/mdx-read.ts";
import { pageToMdx } from "../src/docs/mdx-write.ts";
import type { Block } from "../src/docs/types.ts";

const frontmatter = { title: "A page", description: "It shows `code`.", kind: "guide" };

/** Every kind of block, with text that Markdown or MDX would read as something else. */
const blocks: Block[] = [
  { kind: "p", text: "Plain, `code`, **strong** and [a link](/docs/install/#check-your-machine)." },
  {
    kind: "p",
    text: "Characters MDX reads: {braces}, <angle> brackets, snake_case, a * b, ~tilde, [brackets].",
  },
  { kind: "p", text: "lucent:core is text, as is https://example.com and &amp;." },
  { kind: "p", text: "1. starts like a list" },
  { kind: "h2", text: "When you need `main()`" },
  { kind: "h3", text: "What's copied" },
  { kind: "code", filename: "greet.lucent.ts", code: "export const a = 1;", cpp: true },
  {
    kind: "code",
    filename: "bad.lucent.ts",
    code: "export const a: any = 1;",
    expect: "LUCENT2001",
  },
  { kind: "code", filename: "terminal", code: "$ lucent build\n```\nnested fence", copy: false },
  { kind: "code", filename: "src/trip.lucent.ts", code: "-a\n+b", diff: true },
  {
    kind: "tabs",
    tabs: [
      { label: "module", filename: "a.lucent.ts", code: "export const a = 1;" },
      { label: 'say "hi"', filename: "App.tsx", code: "a;", from: "apps/x/App.tsx" },
    ],
  },
  { kind: "note", text: "A note with `code`." },
  { kind: "note", text: "A warning.", tone: "warn" },
  { kind: "list", items: ["one `a`", "two [b](/docs/)"] },
  { kind: "list", items: ["first", "second"], ordered: true },
  { kind: "table", head: ["Code", "Runs on"], rows: [["`a | b`", "the JS thread"]] },
  { kind: "diagram", diagram: "threads", caption: "What runs where." },
  { kind: "diagram", diagram: "places" },
  { kind: "comparison" },
  {
    kind: "steps",
    steps: [
      {
        title: "Write a module",
        blocks: [
          { kind: "p", text: "Save it." },
          {
            kind: "code",
            filename: "a.lucent.ts",
            code: "export const a = 1;\n\nexport const b = 2;",
          },
        ],
      },
      { title: "Run it", blocks: [{ kind: "p", text: "It runs." }] },
    ],
  },
  {
    kind: "panels",
    panels: [
      { label: "Expo", blocks: [{ kind: "p", text: "In Expo." }] },
      { label: "Bare React Native", blocks: [{ kind: "list", items: ["a", "b"] }] },
    ],
  },
  { kind: "cards", items: [{ title: "Install", text: "Set it up.", href: "/docs/install/" }] },
];

describe("the docs' MDX", () => {
  it("reads back the blocks it was written from", () => {
    const mdx = pageToMdx(frontmatter, blocks);
    const page = readMdx(mdx);

    expect(page.frontmatter).toEqual(frontmatter);
    expect(page.blocks).toEqual(blocks);
  });

  it("imports the components a page uses, and only those", () => {
    const mdx = pageToMdx(frontmatter, [{ kind: "comparison" }]);

    expect(mdx).toContain('import Comparison from "~/components/Comparison.astro";');
    expect(mdx).not.toContain("@astrojs/starlight/components");
  });

  it("says a generated page is generated", () => {
    expect(pageToMdx(frontmatter, [], { generatedFrom: "src/docs/templates/x.ts" })).toContain(
      "{/* Generated by scripts/website.ts from src/docs/templates/x.ts. Do not edit. */}",
    );
  });

  it("refuses what isn't a docs block", () => {
    expect(() => readMdx("---\ntitle: a\n---\n\n# Title\n")).toThrow("## and ### headings");
    expect(() => readMdx("---\ntitle: a\n---\n\n<Aside>\n\na\n\n</Aside>\n")).toThrow(
      "<Aside> is not a docs block",
    );
    expect(() => readMdx("---\ntitle: a\n---\n\n```ts\na\n```\n")).toThrow('title="<file name>"');
    expect(() => readMdx("---\ntitle: a\n---\n\n*emphasis*\n")).toThrow(
      "emphasis is not docs markup",
    );
  });

  it("names headings as Astro does", () => {
    expect(headingId("What's copied, and what isn't")).toBe("whats-copied-and-what-isnt");
    expect(headingId("When you need `main()`")).toBe("when-you-need-main");
  });

  it("reads a fence's meta", () => {
    expect(parseMeta('ts title="a b.ts" cpp expect="LUCENT1" x="q\\"uote"')).toEqual({
      ts: true,
      title: "a b.ts",
      cpp: true,
      expect: "LUCENT1",
      x: 'q"uote',
    });
  });
});
