// Generated by scripts/sync-examples.ts from scripts/example-app. Do not edit.
// Two screens: the end-to-end cases run natively, and a benchmark comparing
// Lucent with the same code run as JavaScript.
import { useState } from "react";
import { Platform, Pressable, StatusBar, Text, View } from "react-native";
import { BenchScreen } from "./src/screens/BenchScreen";
import { styles } from "./src/screens/styles";
import { TestsScreen } from "./src/screens/TestsScreen";

type Tab = "tests" | "bench";

export default function App() {
  const [tab, setTab] = useState<Tab>("tests");
  return (
    <View style={styles.root}>
      <StatusBar barStyle="dark-content" />
      <View style={styles.tabs}>
        {(["tests", "bench"] as const).map((t) => (
          <Pressable key={t} testID={`tab-${t}`} onPress={() => setTab(t)} style={[styles.tab, tab === t && styles.tabActive]}>
            <Text style={[styles.tabText, tab === t && styles.tabTextActive]}>{t === "tests" ? "Tests" : "Benchmark"}</Text>
          </Pressable>
        ))}
        <Text style={styles.platform}>{Platform.OS}</Text>
      </View>
      {tab === "tests" ? <TestsScreen /> : <BenchScreen />}
    </View>
  );
}
