// Generated by scripts/sync-examples.ts from scripts/example-app. Do not edit.
// Three screens: the end-to-end cases run natively, a benchmark comparing
// Lucent with the same code run as JavaScript, and platform SDK calls.
import { useState } from "react";
import { Platform, Pressable, Settings, StatusBar, Text, View } from "react-native";
import { BenchScreen } from "./src/screens/BenchScreen";
import { SdkScreen } from "./src/screens/SdkScreen";
import { styles } from "./src/screens/styles";
import { TestsScreen } from "./src/screens/TestsScreen";

type Tab = "tests" | "bench" | "sdk";
const TABS: Record<Tab, string> = { tests: "Tests", bench: "Benchmark", sdk: "SDK" };

// Automation: `xcrun simctl launch <device> <bundle> -lucentTab sdk` opens
// that tab (launch arguments become user defaults, which Settings reads).
const requested: unknown = Platform.OS === "ios" ? Settings.get("lucentTab") : undefined;
const initialTab: Tab = requested === "bench" || requested === "sdk" ? requested : "tests";

export default function App() {
  const [tab, setTab] = useState<Tab>(initialTab);
  return (
    // Read at render time: the status bar height is not known yet when this
    // module loads on Android (edge-to-edge).
    <View style={[styles.root, { paddingTop: Platform.OS === "ios" ? 54 : (StatusBar.currentHeight ?? 24) }]}>
      <StatusBar barStyle="dark-content" />
      <View style={styles.tabs}>
        {(Object.keys(TABS) as Tab[]).map((t) => (
          <Pressable key={t} testID={`tab-${t}`} onPress={() => setTab(t)} style={[styles.tab, tab === t && styles.tabActive]}>
            <Text style={[styles.tabText, tab === t && styles.tabTextActive]}>{TABS[t]}</Text>
          </Pressable>
        ))}
        <Text style={styles.platform}>{Platform.OS}</Text>
      </View>
      {tab === "tests" ? <TestsScreen /> : tab === "bench" ? <BenchScreen /> : <SdkScreen />}
    </View>
  );
}
