// Generated by Lucent from optional-arguments.lucent.ts. Do not edit.
#include "m_optional_u2d_arguments.h"

#pragma push_macro("absent")
#undef absent
#pragma push_macro("arrays")
#undef arrays
#pragma push_macro("at")
#undef at
#pragma push_macro("attempt")
#undef attempt
#pragma push_macro("bytes")
#undef bytes
#pragma push_macro("checks")
#undef checks
#pragma push_macro("d")
#undef d
#pragma push_macro("dates")
#undef dates
#pragma push_macro("e")
#undef e
#pragma push_macro("nan")
#undef nan
#pragma push_macro("nanArguments")
#undef nanArguments
#pragma push_macro("numbers")
#undef numbers
#pragma push_macro("removed")
#undef removed
#pragma push_macro("sep")
#undef sep
#pragma push_macro("strings")
#undef strings
#pragma push_macro("t")
#undef t
#pragma push_macro("text")
#undef text
#pragma push_macro("typed")
#undef typed
#pragma push_macro("wall")
#undef wall
#pragma push_macro("xs")
#undef xs
#pragma push_macro("ys")
#undef ys

namespace lucent_app {

lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>> m_optional_u2d_arguments::checks() {
  lucent::String text = LUCENT_STR("abcabc");
  lucent::Array<double> xs = lucent::Array<double>{1.0, 2.0, 3.0, 1.0, 2.0, 3.0};
  lucent::Array<double> v14_ = lucent::Array<double>{1.0, 2.0, 3.0, 1.0, 2.0, 3.0};
  lucent::Bytes bytes = lucent::Bytes::fromArray(v14_);
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v17_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([text = text](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    double v4_ = text.indexOf(LUCENT_STR("b"), p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v4_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v19_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([text = text](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    double v4_ = text.lastIndexOf(LUCENT_STR("b"), p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v4_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v21_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([text = text](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    bool v4_ = text.includes(LUCENT_STR("a"), p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v4_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v23_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([text = text](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    bool v4_ = text.startsWith(LUCENT_STR("c"), p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v4_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v25_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([text = text](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    bool v4_ = text.endsWith(LUCENT_STR("c"), p0_.valueOr(lucent::kInfinity));
    return lucent::toJsString(v4_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v27_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([text = text](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return text.slice(p0_.valueOr(lucent::kNaN));
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v29_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([text = text](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return text.slice(1.0, p0_.valueOr(lucent::kInfinity));
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v31_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([text = text](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return text.substring(1.0, p0_.valueOr(lucent::kInfinity));
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v33_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([text = text](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return text.substr(1.0, p0_.valueOr(lucent::kInfinity));
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v35_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([text = text](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return text.padStart(8.0, p1_.valueOr(LUCENT_STR(" ")));
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v37_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([text = text](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return text.padEnd(8.0, p1_.valueOr(LUCENT_STR(" ")));
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v38_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Array<lucent::String> v4_ = lucent::split(LUCENT_STR("a,b,c"), LUCENT_STR(","), p0_.valueOr(4294967295.0));
    return v4_.join(LUCENT_STR("|"));
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v39_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::RegExp v3_ = lucent::makeRegExp(LUCENT_STR(","), lucent::Opt<lucent::String>(lucent::String()));
    lucent::Array<lucent::String> v4_ = lucent::stringSplit(LUCENT_STR("a,b,c"), v3_, p0_);
    return v4_.join(LUCENT_STR("|"));
  });
  lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>> strings = lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>>{v17_, v19_, v21_, v23_, v25_, v27_, v29_, v31_, v33_, v35_, v37_, v38_, v39_};
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v42_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([xs = xs](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Array<double> v3_ = xs.slice(p0_.valueOr(lucent::kNaN));
    return v3_.join();
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v44_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([xs = xs](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Array<double> v4_ = xs.slice(1.0, p0_.valueOr(lucent::kInfinity));
    return v4_.join();
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v46_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([xs = xs](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Array<double> ys = ({ lucent::Array<double> arr_1_; arr_1_.append(xs); arr_1_; });
    lucent::Array<double> removed = ys.splice(1.0, p0_.valueOr(lucent::kNaN));
    lucent::String v8_ = removed.join();
    lucent::String v11_ = ys.join();
    return lucent::concat(v8_, LUCENT_STR("/"), v11_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v48_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([xs = xs](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return xs.join(p1_.valueOr(LUCENT_STR(",")));
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v49_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Array<double> v6_ = lucent::Array<double>{0.0, 0.0, 0.0, 0.0};
    lucent::Array<double> v8_ = v6_.fill(7.0, p0_.valueOr(lucent::kNaN));
    return v8_.join();
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v50_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Array<double> v6_ = lucent::Array<double>{0.0, 0.0, 0.0, 0.0};
    lucent::Array<double> v9_ = v6_.fill(7.0, 1.0, p0_.valueOr(lucent::kInfinity));
    return v9_.join();
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v52_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([xs = xs](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    double v4_ = xs.indexOf(2.0, p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v4_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v54_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([xs = xs](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    double v4_ = xs.lastIndexOf(2.0, p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v4_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v56_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([xs = xs](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    bool v4_ = xs.includes(1.0, p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v4_);
  });
  lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>> arrays = lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>>{v42_, v44_, v46_, v48_, v49_, v50_, v52_, v54_, v56_};
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v59_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([bytes = bytes](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Bytes v3_ = bytes.subarray(p0_.valueOr(lucent::kNaN));
    return v3_.join();
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v61_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([bytes = bytes](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Bytes v4_ = bytes.slice(1.0, p0_.valueOr(lucent::kInfinity));
    return v4_.join();
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v62_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Bytes v3_ = lucent::Bytes(4.0);
    lucent::Bytes v5_ = v3_.fill(7.0, p0_.valueOr(lucent::kNaN));
    return v5_.join();
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v63_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Bytes v3_ = lucent::Bytes(4.0);
    lucent::Bytes v6_ = v3_.fill(7.0, 1.0, p0_.valueOr(lucent::kInfinity));
    return v6_.join();
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v65_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([bytes = bytes](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    double v4_ = bytes.indexOf(2.0, p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v4_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v67_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([bytes = bytes](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    bool v4_ = bytes.includes(1.0, p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v4_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v68_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Bytes t = lucent::Bytes(4.0);
    lucent::Array<double> v6_ = lucent::Array<double>{9.0};
    t.setFrom(v6_, p0_.valueOr(lucent::kNaN));
    return t.join();
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v70_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([bytes = bytes](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return bytes.join(p1_.valueOr(LUCENT_STR(",")));
  });
  lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>> typed = lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>>{v59_, v61_, v62_, v63_, v65_, v67_, v68_, v70_};
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v72_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return lucent::numberToString(255.0, p0_.valueOr(10.0));
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v73_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return lucent::numberToFixed(1.25, p0_.valueOr(lucent::kNaN));
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v74_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return lucent::numberToPrecision(123.456, p0_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v75_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return lucent::numberToExponential(123.456, p0_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v76_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return lucent::BigInt::fromInt64(255).toString(p0_.valueOr(10.0));
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v77_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    double v3_ = lucent::parseInt(LUCENT_STR("11"), p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v3_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v78_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    double v3_ = lucent::parseInt(LUCENT_STR("11"), p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v3_);
  });
  lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>> numbers = lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>>{v72_, v73_, v74_, v75_, v76_, v77_, v78_};
  lucent::Fn<lucent::String(lucent::Date, double)> v80_ = lucent::Fn<lucent::String(lucent::Date, double)>([](lucent::Date p0_, double p1_) mutable -> lucent::String {
    double v2_ = p0_->getTimezoneOffset();
    double v5_ = p1_ - v2_ * 60000.0;
    return lucent::toJsString(v5_);
  });
  lucent::Fn<lucent::String(lucent::Date, double)> wall = std::move(v80_);
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v82_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([wall = wall](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Date d = lucent::dateFromLocal(2020.0, 1.0, p0_.valueOr(lucent::kNaN));
    double v8_ = d->getTime();
    return wall(d, v8_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v84_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([wall = wall](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Date d = lucent::dateFromLocal(2020.0, 1.0, 15.0);
    double v10_ = d->setHours(10.0, p0_.valueOr(lucent::kNaN));
    return wall(d, v10_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v86_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([wall = wall](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    lucent::Date d = lucent::dateFromLocal(2020.0, 1.0, 15.0);
    double v10_ = d->setMinutes(5.0, p0_.valueOr(lucent::kNaN));
    return wall(d, v10_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v87_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    double v5_ = lucent::dateUTC(2020.0, 1.0, 15.0);
    lucent::Date v6_ = lucent::makeDate(v5_);
    double v8_ = v6_->setUTCFullYear(2021.0, p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v8_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v88_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    double v3_ = lucent::dateUTC(2020.0, p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v3_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v89_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    double v4_ = lucent::dateUTC(2020.0, 1.0, p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v4_);
  });
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v90_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    double v6_ = lucent::dateUTC(2020.0, 1.0, 1.0, 0.0, p0_.valueOr(lucent::kNaN), p0_.valueOr(lucent::kNaN), p0_.valueOr(lucent::kNaN));
    return lucent::toJsString(v6_);
  });
  lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>> dates = lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>>{v82_, v84_, v86_, v87_, v88_, v89_, v90_};
  return ({ lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>> arr_2_; arr_2_.append(strings); arr_2_.append(arrays); arr_2_.append(typed); arr_2_.append(numbers); arr_2_.append(dates); arr_2_; });
}

lucent::String m_optional_u2d_arguments::attempt(lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> p0_, lucent::Opt<double> p1_, lucent::Opt<lucent::String> p2_) {
  {
    std::exception_ptr ex4_;
    try {
      return p0_(p1_, p2_);
    } catch (const lucent::GeneratorReturn&) {
      throw;
    } catch (...) {
      ex4_ = std::current_exception();
    }
    if (ex4_) {
      lucent::Error v4_ = lucent::currentError(ex4_);
      lucent::Error e = std::move(v4_);
      return e->name;
    }
  }
  lucent::unreachable();
}

lucent::Array<lucent::String> m_optional_u2d_arguments::absent(lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) {
  lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>> v2_ = lucent_app::m_optional_u2d_arguments::checks();
  return v2_.template map<lucent::String>([at = p0_, sep = p1_](lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> p0_, double p1_, lucent::Array<lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>> p2_) mutable -> lucent::String {
    return lucent_app::m_optional_u2d_arguments::attempt(p0_, at, sep);
  });
}

lucent::Array<lucent::String> m_optional_u2d_arguments::nanArguments(double p0_) {
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v1_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([nan = p0_](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return lucent::numberToString(255.0, nan);
  });
  lucent::String v2_ = lucent_app::m_optional_u2d_arguments::attempt(v1_, lucent::Opt<double>(lucent::undefined), lucent::Opt<lucent::String>(lucent::undefined));
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v3_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([nan = p0_](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    return LUCENT_STR("abcdef").substr(nan, 2.0);
  });
  lucent::String v4_ = lucent_app::m_optional_u2d_arguments::attempt(v3_, lucent::Opt<double>(lucent::undefined), lucent::Opt<lucent::String>(lucent::undefined));
  lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)> v5_ = lucent::Fn<lucent::String(lucent::Opt<double>, lucent::Opt<lucent::String>)>([nan = p0_](lucent::Opt<double> p0_, lucent::Opt<lucent::String> p1_) mutable -> lucent::String {
    double v4_ = -2.0;
    return LUCENT_STR("abcdef").substr(v4_, nan);
  });
  lucent::String v6_ = lucent_app::m_optional_u2d_arguments::attempt(v5_, lucent::Opt<double>(lucent::undefined), lucent::Opt<lucent::String>(lucent::undefined));
  return lucent::Array<lucent::String>{v2_, v4_, v6_};
}

void m_optional_u2d_arguments::init() {
}

}  // namespace lucent_app

#pragma pop_macro("ys")
#pragma pop_macro("xs")
#pragma pop_macro("wall")
#pragma pop_macro("typed")
#pragma pop_macro("text")
#pragma pop_macro("t")
#pragma pop_macro("strings")
#pragma pop_macro("sep")
#pragma pop_macro("removed")
#pragma pop_macro("numbers")
#pragma pop_macro("nanArguments")
#pragma pop_macro("nan")
#pragma pop_macro("e")
#pragma pop_macro("dates")
#pragma pop_macro("d")
#pragma pop_macro("checks")
#pragma pop_macro("bytes")
#pragma pop_macro("attempt")
#pragma pop_macro("at")
#pragma pop_macro("arrays")
#pragma pop_macro("absent")
