// Generated by Lucent. Do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const { loadModule, lucentClass } = require("./_lucent/runtime.js");
const m = loadModule("assignment-order", () => require("react-native").TurboModuleRegistry, require("./_lucent/identity.js"));
exports.reset = m.reset;
exports.trail = m.trail;
exports.moduleString = m.moduleString;
exports.moduleNumbers = m.moduleNumbers;
exports.moduleLogical = m.moduleLogical;
exports.moduleThrows = m.moduleThrows;
exports.locals = m.locals;
exports.captured = m.captured;
exports.replaced = m.replaced;
exports.fields = m.fields;
exports.elements = m.elements;
exports.entries = m.entries;
exports.elementThrows = m.elementThrows;
exports.members = m.members;
