// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_C_Point.h"

#pragma push_macro("first")
#undef first
#pragma push_macro("label")
#undef label
#pragma push_macro("origin")
#undef origin

namespace lucent_app {

struct C_Shape;

struct C_Shape : lucent::Object {
  lucent::String label{};
  lucent::Ref<lucent_app::C_Point> origin{};
  void construct(lucent::String p0_);
  static lucent::Ref<C_Shape> create(lucent::String p0_);
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_Shape::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "label", this->label);
  lucent::jsonField(w, first, "origin", this->origin);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("origin")
#pragma pop_macro("label")
#pragma pop_macro("first")
