// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_S_Object_c65abf80.h"

#pragma push_macro("at")
#undef at
#pragma push_macro("first")
#undef first
#pragma push_macro("v")
#undef v

namespace lucent_app {

struct S_Object_ab33e181;

struct S_Object_ab33e181 : lucent::Object {
  lucent::Ref<lucent_app::S_Object_c65abf80> at{};
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object_ab33e181>& v);

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object_ab33e181>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "at", v->at);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("v")
#pragma pop_macro("first")
#pragma pop_macro("at")
