// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("first")
#undef first
#pragma push_macro("keep")
#undef keep
#pragma push_macro("toJSON")
#undef toJSON

namespace lucent_app {

struct C_Dropped : lucent::Object {
  double keep{};
  lucent::Fn<lucent::Opt<double>()> toJSON{};
  void construct();
  static lucent::Ref<C_Dropped> create();
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_Dropped::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  if (toJson) {
    return lucent::jsonResult(w, this->toJSON());
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "keep", this->keep);
  lucent::jsonField(w, first, "toJSON", this->toJSON);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("toJSON")
#pragma pop_macro("keep")
#pragma pop_macro("first")
