// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_C_Shape.h"

#pragma push_macro("area")
#undef area
#pragma push_macro("first")
#undef first
#pragma push_macro("label")
#undef label
#pragma push_macro("origin")
#undef origin
#pragma push_macro("r")
#undef r

namespace lucent_app {

struct C_Circle : lucent_app::C_Shape {
  double r{};
  double _u23_area{};
  void construct(double p0_);
  static lucent::Ref<C_Circle> create(double p0_);
  virtual double area();
  bool lucentJson_(lucent::JsonWriter& w, bool toJson) override;
};

inline bool C_Circle::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "label", this->label);
  lucent::jsonField(w, first, "origin", this->origin);
  lucent::jsonField(w, first, "r", this->r);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("r")
#pragma pop_macro("origin")
#pragma pop_macro("label")
#pragma pop_macro("first")
#pragma pop_macro("area")
