// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("first")
#undef first
#pragma push_macro("other")
#undef other
#pragma push_macro("toJSON")
#undef toJSON

namespace lucent_app {

struct C_NotCalled;

struct C_NotCalled : lucent::Object {
  double toJSON{};
  lucent::String other{};
  void construct();
  static lucent::Ref<C_NotCalled> create();
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_NotCalled::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "toJSON", this->toJSON);
  lucent::jsonField(w, first, "other", this->other);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("toJSON")
#pragma pop_macro("other")
#pragma pop_macro("first")
