// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_C_Maybe.h"

#pragma push_macro("first")
#undef first
#pragma push_macro("r")
#undef r
#pragma push_macro("v")
#undef v

namespace lucent_app {

struct S_Object6 : lucent::Object {
  lucent::Dict<lucent::Ref<lucent_app::C_Maybe>> r{};
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object6>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "r", v->r);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("v")
#pragma pop_macro("r")
#pragma pop_macro("first")
