// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_C_Maybe.h"
#include "lucent_app_C_Callable.h"

#pragma push_macro("first")
#undef first
#pragma push_macro("fn")
#undef fn
#pragma push_macro("gone")
#undef gone
#pragma push_macro("kept")
#undef kept
#pragma push_macro("v")
#undef v

namespace lucent_app {

struct S_Object3 : lucent::Object {
  lucent::Ref<lucent_app::C_Maybe> gone{};
  lucent::Ref<lucent_app::C_Maybe> kept{};
  lucent::Ref<lucent_app::C_Callable> fn{};
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object3>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "gone", v->gone);
  lucent::jsonField(w, first, "kept", v->kept);
  lucent::jsonField(w, first, "fn", v->fn);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("v")
#pragma pop_macro("kept")
#pragma pop_macro("gone")
#pragma pop_macro("fn")
#pragma pop_macro("first")
