// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_C_Box.h"

#pragma push_macro("first")
#undef first
#pragma push_macro("full")
#undef full
#pragma push_macro("item")
#undef item

namespace lucent_app {

struct C_NumberBox : lucent_app::C_Box<double> {
  bool full{};
  void construct();
  static lucent::Ref<C_NumberBox> create();
  bool lucentJson_(lucent::JsonWriter& w, bool toJson) override;
};

inline bool C_NumberBox::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "item", this->item);
  lucent::jsonField(w, first, "full", this->full);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("item")
#pragma pop_macro("full")
#pragma pop_macro("first")
