// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("first")
#undef first
#pragma push_macro("toJSON")
#undef toJSON
#pragma push_macro("v")
#undef v

namespace lucent_app {

struct C_Maybe;

struct C_Maybe : lucent::Object {
  lucent::Opt<double> v{};
  void construct(lucent::Opt<double> p0_);
  static lucent::Ref<C_Maybe> create(lucent::Opt<double> p0_);
  lucent::Opt<double> toJSON();
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_Maybe::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  if (toJson) {
    return lucent::jsonResult(w, this->toJSON());
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "v", this->v);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("v")
#pragma pop_macro("toJSON")
#pragma pop_macro("first")
