import { describe, expect, it } from "vite-plus/test";
import { java } from "../src/index.ts";

const { name, call, str, printExpr } = java;
const handle = name("handle");

describe("Java expressions", () => {
  it("parenthesize casts where a member or call binds them", () => {
    const dispatch = call(name("NativeProxy"), "dispatch", [handle, str("run()")]);
    expect(printExpr(java.cast(java.type("Runnable"), dispatch))).toBe(
      '(Runnable) NativeProxy.dispatch(handle, "run()")',
    );
    expect(printExpr(call(java.cast(java.type("Integer"), dispatch), "intValue"))).toBe(
      '((Integer) NativeProxy.dispatch(handle, "run()")).intValue()',
    );
  });

  it("print array creation, fields, this and super", () => {
    expect(printExpr(java.newArray(java.type("Object"), [name("a0"), name("a1")]))).toBe(
      "new Object[] {a0, a1}",
    );
    expect(printExpr(java.newArray(java.type("Object"), []))).toBe("new Object[] {}");
    expect(printExpr(java.assign(java.access(java.self, "handle"), handle))).toBe(
      "this.handle = handle",
    );
    expect(printExpr(call(java.superRef, "finalize"))).toBe("super.finalize()");
    expect(printExpr(str('a"b\\c'))).toBe('"a\\"b\\\\c"');
  });

  it("print primitive, class and array types", () => {
    expect(java.printType(java.array(java.primitive("int")))).toBe("int[]");
    expect(java.printType(java.type("java.util.List", java.type("String")))).toBe(
      "java.util.List<String>",
    );
  });
});

describe("Java compilation units", () => {
  it("print a class with its fields, constructors and annotated methods", () => {
    const unit = java.printUnit({
      banner: "Generated by Lucent. Do not edit.",
      package: "dev.lucent.generated",
      imports: ["dev.lucent.NativeProxy"],
      types: [
        java.cls(
          "Handler",
          [
            java.field(["private", "final"], java.primitive("long"), "handle"),
            java.constructor(
              ["public"],
              "Handler",
              [java.param(java.primitive("long"), "handle")],
              [
                java.exprStmt(call(undefined, "super", [])),
                java.exprStmt(java.assign(java.access(java.self, "handle"), handle)),
              ],
            ),
            java.method(["public"], java.primitive("int"), "size", [], [java.ret(java.num(1))], {
              annotations: [{ name: "Override" }],
            }),
            java.method(
              ["protected"],
              java.primitive("void"),
              "finalize",
              [],
              [
                {
                  k: "try",
                  body: [java.exprStmt(call(name("NativeProxy"), "releaseHandle", [handle]))],
                  finally: [java.exprStmt(call(java.superRef, "finalize"))],
                },
              ],
              {
                annotations: [
                  { name: "Override" },
                  {
                    name: "SuppressWarnings",
                    value: java.arrayInit([str("deprecation"), str("removal")]),
                  },
                ],
                throws: [java.type("Throwable")],
              },
            ),
          ],
          {
            modifiers: ["public", "final"],
            extends: java.type("android.os.Handler"),
            doc: "Lucent's Handler: forwards to its C++ side.",
          },
        ),
      ],
    });
    expect(unit).toBe(
      [
        "// Generated by Lucent. Do not edit.",
        "package dev.lucent.generated;",
        "",
        "import dev.lucent.NativeProxy;",
        "",
        "/** Lucent's Handler: forwards to its C++ side. */",
        "public final class Handler extends android.os.Handler {",
        "  private final long handle;",
        "",
        "  public Handler(long handle) {",
        "    super();",
        "    this.handle = handle;",
        "  }",
        "",
        "  @Override",
        "  public int size() {",
        "    return 1;",
        "  }",
        "",
        "  @Override",
        '  @SuppressWarnings({"deprecation", "removal"})',
        "  protected void finalize() throws Throwable {",
        "    try {",
        "      NativeProxy.releaseHandle(handle);",
        "    } finally {",
        "      super.finalize();",
        "    }",
        "  }",
        "}",
        "",
      ].join("\n"),
    );
  });
});
