import { describe, expect, it } from "vite-plus/test";
import { ts } from "../src/index.ts";

const { ref, union, printType } = ts;
const num = ts.keyword("number");
const str = ts.keyword("string");
const A = ref("A");

describe("TypeScript types", () => {
  it("parenthesize array elements and union members by precedence only", () => {
    expect(printType(ts.array(union([A, ts.nullType])))).toBe("(A | null)[]");
    expect(printType(ts.array(ref("Record", str, num)))).toBe("Record<string, number>[]");
    expect(printType(ts.array(ts.fn([ts.param("arg0", num)], ts.keyword("void"))))).toBe(
      "((arg0: number) => void)[]",
    );
    expect(printType(union([ref("Runnable"), ts.fn([ts.param("arg0", num)], num)]))).toBe(
      "Runnable | ((arg0: number) => number)",
    );
  });

  it("flatten unions and keep one of each member", () => {
    expect(printType(union([union([A, ts.nullType]), ts.nullType]))).toBe("A | null");
    expect(printType(union([A]))).toBe("A");
  });

  it("print object, literal and typeof types", () => {
    expect(printType(ts.object([{ name: "prototype", type: A, readonly: true }]))).toBe(
      "{ readonly prototype: A }",
    );
    expect(printType(ts.object([]))).toBe("{}");
    expect(
      printType(ts.object([{ name: "__brand", type: ts.keyword("never"), optional: true }])),
    ).toBe("{ __brand?: never }");
    expect(printType(ts.literal('a"b'))).toBe('"a\\"b"');
    expect(printType(ts.literal(-1))).toBe("-1");
    expect(printType(ts.typeOf("Toast.LENGTH_SHORT"))).toBe("typeof Toast.LENGTH_SHORT");
  });

  it("print tuples, their optional elements parenthesized by precedence", () => {
    expect(printType(ts.tuple([{ type: A }, { type: num, optional: true }]))).toBe("[A, number?]");
    expect(printType(ts.tuple([{ type: union([A, ts.nullType]), optional: true }]))).toBe(
      "[(A | null)?]",
    );
    expect(printType(ts.array(ts.tuple([{ type: A }])))).toBe("[A][]");
  });

  it("print optional properties", () => {
    expect(
      ts.printUnit({
        decls: [
          {
            k: "interface",
            name: "Attributes",
            members: [{ k: "property", name: "padding", type: num, optional: true }],
          },
        ],
      }),
    ).toBe("export declare interface Attributes {\n  padding?: number;\n}\n");
  });

  it("print a property taking more when written as a get and a set accessor", () => {
    const listener = union([A, ts.nullType]);

    expect(
      ts.printUnit({
        decls: [
          {
            k: "class",
            name: "Dial",
            members: [
              {
                k: "property",
                name: "listener",
                type: listener,
                set: union([A, ts.fn([ts.param("arg0", num)], ts.keyword("void")), ts.nullType]),
                doc: "Its listener.",
              },
            ],
          },
        ],
      }),
    ).toBe(
      "export declare class Dial {\n  /** Its listener. */\n  get listener(): A | null;\n  set listener(value: A | ((arg0: number) => void) | null);\n}\n",
    );
  });

  it("print intersections, parenthesized by precedence", () => {
    expect(printType(ts.intersection([ts.object([{ name: "a", type: A }]), ref("B")]))).toBe(
      "{ a: A } & B",
    );
    expect(printType(ts.intersection([union([A, ts.nullType]), ref("B")]))).toBe("(A | null) & B");
    expect(printType(union([ts.intersection([A, ref("B")]), ts.nullType]))).toBe("A & B | null");
    expect(printType(ts.array(ts.intersection([A, ref("B")])))).toBe("(A & B)[]");
    expect(printType(ts.intersection([A]))).toBe("A");
  });

  it("print bigints and their literals", () => {
    expect(printType(ts.keyword("bigint"))).toBe("bigint");
    expect(printType(ts.literal(9223372036854775807n))).toBe("9223372036854775807n");
    expect(printType(ts.literal(-1n))).toBe("-1n");
  });
});

describe("TypeScript declarations", () => {
  it("print a declaration file", () => {
    const text = ts.printUnit({
      banner: "Generated by Lucent. Do not edit.",
      decls: [
        { k: "importType", names: ["NSObject", "Out"], from: "lucent:ios" },
        { k: "exportFrom", from: "lucent:ios/_Essentials" },
        { k: "blank" },
        {
          k: "enum",
          name: "Mode",
          members: [
            { name: "Fast", value: 1 },
            { name: "Named", value: "named" },
          ],
        },
        { k: "blank" },
        {
          k: "typeAlias",
          name: "Point",
          type: ts.object([
            { name: "x", type: num },
            { name: "y", type: num },
          ]),
        },
        {
          k: "typeAlias",
          name: "Result",
          typeParams: [{ name: "T", default: ts.keyword("unknown") }],
          type: ts.object([{ name: "value", type: ref("T") }]),
        },
        {
          k: "class",
          name: "Box",
          abstract: true,
          doc: ["Main thread only.", "Since iOS 13."],
          typeParams: [{ name: "T", default: ts.keyword("unknown") }],
          extends: ref("NSObject"),
          members: [
            {
              k: "property",
              name: "__lucent_Box",
              type: ts.keyword("never"),
              private: true,
              readonly: true,
            },
            { k: "constructor", params: [], protected: true },
            { k: "constructor", params: [ts.param("value", ref("T"))], doc: "Since API 21." },
            {
              k: "property",
              name: "MAX",
              type: ts.literal(3),
              static: true,
              readonly: true,
            },
            {
              k: "method",
              name: "map",
              optional: true,
              typeParams: [{ name: "U" }],
              params: [ts.param("f", ts.fn([ts.param("arg0", ref("T"))], ref("U")))],
              ret: ref("Box", ref("U")),
              doc: "Since API 24. @deprecated",
            },
          ],
        },
        {
          k: "interface",
          name: "Box",
          typeParams: [{ name: "T", default: ts.keyword("unknown") }],
          extends: [ref("PromiseLike", union([ref("T"), ts.nullType]))],
          members: [],
        },
        { k: "function", name: "make", params: [ts.param("n", num)], ret: ref("Box", num) },
        {
          k: "function",
          name: "same",
          typeParams: [{ name: "T" }],
          params: [
            ts.param("value", ref("T")),
            { name: "label", type: ref("string"), optional: true },
          ],
          ret: ref("T"),
        },
        { k: "const", name: "ZERO", type: num },
        { k: "enum", name: "Empty", members: [] },
        { k: "moduleWildcard", name: "lucent:android/*" },
      ],
    });
    expect(text).toBe(
      [
        "// Generated by Lucent. Do not edit.",
        'import type { NSObject, Out } from "lucent:ios";',
        'export * from "lucent:ios/_Essentials";',
        "",
        "export declare enum Mode {",
        "  Fast = 1,",
        '  Named = "named",',
        "}",
        "",
        "export declare type Point = { x: number; y: number };",
        "export declare type Result<T = unknown> = { value: T };",
        "/**",
        " * Main thread only.",
        " * Since iOS 13.",
        " */",
        "export declare abstract class Box<T = unknown> extends NSObject {",
        "  private readonly __lucent_Box: never;",
        "  protected constructor();",
        "  /** Since API 21. */",
        "  constructor(value: T);",
        "  static readonly MAX: 3;",
        "  /** Since API 24. @deprecated */",
        "  map?<U>(f: (arg0: T) => U): Box<U>;",
        "}",
        "export declare interface Box<T = unknown> extends PromiseLike<T | null> {}",
        "export declare function make(n: number): Box<number>;",
        "export declare function same<T>(value: T, label?: string): T;",
        "export declare const ZERO: number;",
        "export declare enum Empty {}",
        'declare module "lucent:android/*";',
        "",
      ].join("\n"),
    );
  });
});

describe("JavaScript statements", () => {
  it("print a module proxy's CommonJS", () => {
    const m = ts.name("m");
    const text = ts.printUnit({
      decls: [
        ts.stmt(ts.exprStmt(ts.str("use strict"))),
        ts.stmt({
          k: "const",
          name: ["loadModule", "lucentClass"],
          init: ts.call(ts.name("require"), [ts.str("./runtime.js")]),
        }),
        ts.stmt({
          k: "const",
          name: "m",
          init: ts.call(ts.name("loadModule"), [
            ts.str("main"),
            ts.arrow([], ts.member(ts.call(ts.name("require"), [ts.str("react-native")]), "X")),
          ]),
        }),
        ts.stmt(ts.exprStmt(ts.assign(ts.member(ts.name("exports"), "f"), ts.member(m, "f")))),
        ts.stmt(
          ts.exprStmt(
            ts.call(ts.member(ts.name("Object"), "freeze"), [
              ts.objectLit([
                { key: "A", value: ts.num(1), quoted: true },
                { key: "value", value: ts.bool(true) },
              ]),
            ]),
          ),
        ),
      ],
    });
    expect(text).toBe(
      [
        '"use strict";',
        'const { loadModule, lucentClass } = require("./runtime.js");',
        'const m = loadModule("main", () => require("react-native").X);',
        "exports.f = m.f;",
        'Object.freeze({ "A": 1, value: true });',
        "",
      ].join("\n"),
    );
  });

  it("print arrays, null, and literals one entry per line when asked", () => {
    const config = ts.objectLit(
      [
        { key: "name", value: ts.str("LucentMeter_0") },
        { key: "props", value: ts.arrayLit([ts.num(0), ts.nullLit], true) },
        { key: "empty", value: ts.arrayLit([], true) },
        { key: "inline", value: ts.arrayLit([ts.objectLit([{ key: "n", value: ts.num(0) }])]) },
      ],
      true,
    );
    const text = ts.printUnit({ decls: [ts.stmt({ k: "const", name: "config", init: config })] });

    expect(text).toBe(
      [
        "const config = {",
        '  name: "LucentMeter_0",',
        "  props: [",
        "    0,",
        "    null,",
        "  ],",
        "  empty: [],",
        "  inline: [{ n: 0 }],",
        "};",
        "",
      ].join("\n"),
    );
  });
});

describe("TypeScript property names", () => {
  it("quote the names that are not identifiers", () => {
    expect(
      printType(
        ts.object([
          { name: "aria-label", type: str, optional: true },
          { name: "$x", type: num },
          { name: "_y1", type: num },
          { name: "2d", type: num },
        ]),
      ),
    ).toBe('{ "aria-label"?: string; $x: number; _y1: number; "2d": number }');
  });
});

describe("TypeScript values of declared types", () => {
  it("print local declarations, call signatures, symbol keys and type namespaces", () => {
    const view = ts.ref("View");
    const text = ts.printUnit({
      decls: [
        { k: "const", name: "brand", type: ts.keyword("unique symbol"), local: true },
        {
          k: "interface",
          name: "Edge_Set",
          local: true,
          members: [
            {
              k: "property",
              name: "brand",
              computed: true,
              readonly: true,
              type: ts.literal(true),
            },
          ],
        },
        {
          k: "interface",
          name: "$Color",
          local: true,
          members: [
            {
              k: "call",
              params: [ts.param("red", num)],
              ret: ts.ref("Color"),
              doc: ["Makes a color.", "@swift s:Color 0"],
            },
          ],
        },
        { k: "const", name: "Color", type: ts.ref("$Color"), doc: "Colors." },
        {
          k: "function",
          name: "stack",
          params: [ts.param("content", ts.readonlyArray(ts.union([view, ts.nullType])))],
          ret: view,
          doc: ["@swift s:stack 1"],
        },
        {
          k: "namespace",
          name: "Edge",
          decls: [
            { k: "typeAlias", name: "Set", type: ts.ref("Edge_Set") },
            { k: "namespace", name: "Set", decls: [{ k: "typeAlias", name: "Kind", type: num }] },
          ],
        },
        { k: "exportNothing" },
      ],
    });

    expect(text).toBe(
      [
        "declare const brand: unique symbol;",
        "declare interface Edge_Set {",
        "  readonly [brand]: true;",
        "}",
        "declare interface $Color {",
        "  /**",
        "   * Makes a color.",
        "   * @swift s:Color 0",
        "   */",
        "  (red: number): Color;",
        "}",
        "/** Colors. */",
        "export declare const Color: $Color;",
        "/**",
        " * @swift s:stack 1",
        " */",
        "export declare function stack(content: readonly (View | null)[]): View;",
        "export declare namespace Edge {",
        "  type Set = Edge_Set;",
        "  namespace Set {",
        "    type Kind = number;",
        "  }",
        "}",
        "export {};",
        "",
      ].join("\n"),
    );
  });
});

describe("TypeScript namespaces", () => {
  it("print namespaces of documented declarations, merged with a function and an interface", () => {
    const text = ts.printUnit({
      decls: [
        {
          k: "interface",
          name: "Color",
          doc: "A color.",
          members: [
            { k: "property", name: "lucent:compose.Color", type: ts.literal(true), readonly: true },
          ],
        },
        {
          k: "function",
          name: "Color",
          doc: "A color from its bits.",
          params: [ts.param("color", num)],
          ret: ref("Color"),
        },
        {
          k: "namespace",
          name: "Color",
          decls: [
            { k: "const", name: "White", doc: "White.", type: ref("Color") },
            { k: "function", name: "hsv", params: [ts.param("hue", num)], ret: ref("Color") },
            {
              k: "namespace",
              name: "Space",
              decls: [{ k: "interface", name: "Rgb", members: [] }],
            },
          ],
        },
      ],
    });

    expect(text).toBe(
      [
        "/** A color. */",
        "export declare interface Color {",
        '  readonly "lucent:compose.Color": true;',
        "}",
        "/** A color from its bits. */",
        "export declare function Color(color: number): Color;",
        "export declare namespace Color {",
        "  /** White. */",
        "  const White: Color;",
        "  function hsv(hue: number): Color;",
        "  namespace Space {",
        "    interface Rgb {}",
        "  }",
        "}",
        "",
      ].join("\n"),
    );
  });
});

describe("TypeScript type parameters", () => {
  it("print their constraints on functions, methods and call signatures", () => {
    const scalar = union([ts.keyword("boolean"), num, str]);
    const V = { name: "V", extends: scalar };
    const text = ts.printUnit({
      decls: [
        {
          k: "interface",
          name: "$Picker",
          local: true,
          members: [
            {
              k: "call",
              typeParams: [V],
              params: [ts.param("selection", ref("Bound", ref("V")))],
              ret: ref("Picker"),
            },
          ],
        },
        {
          k: "interface",
          name: "View",
          members: [
            {
              k: "method",
              name: "onChange",
              typeParams: [V],
              params: [
                ts.param("of", ref("V")),
                ts.param("action", ts.fn([ts.param("arg0", ref("V"))], ts.keyword("void"))),
              ],
              ret: ref("View"),
            },
          ],
        },
        {
          k: "function",
          name: "same",
          typeParams: [{ name: "T", extends: num, default: ts.literal(0) }],
          params: [ts.param("value", ref("T"))],
          ret: ref("T"),
        },
        { k: "exportNothing" },
      ],
    });

    expect(text).toContain("  <V extends boolean | number | string>(selection: Bound<V>): Picker;");
    expect(text).toContain(
      "  onChange<V extends boolean | number | string>(of: V, action: (arg0: V) => void): View;",
    );
    expect(text).toContain("export declare function same<T extends number = 0>(value: T): T;");
  });
});
