// Generated by Lucent from exported-variables.lucent.ts. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("bump")
#undef bump
#pragma push_macro("config")
#undef config
#pragma push_macro("count")
#undef count
#pragma push_macro("grow")
#undef grow
#pragma push_macro("limit")
#undef limit
#pragma push_macro("list")
#undef list

namespace lucent_app {

namespace m_exported_u2d_variables {

inline double limit{};
inline lucent::Array<double> list{};
inline lucent::Ref<lucent_app::S_Config> config{};
inline double count{};

double bump();
void grow();
void init();

}  // namespace m_exported_u2d_variables

}  // namespace lucent_app

#pragma pop_macro("list")
#pragma pop_macro("limit")
#pragma pop_macro("grow")
#pragma pop_macro("count")
#pragma pop_macro("config")
#pragma pop_macro("bump")
