// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("v")
#undef v
#pragma push_macro("w")
#undef w
#pragma push_macro("z")
#undef z

namespace lucent_app {

struct S_Object6 : lucent::Object {
  double z{};
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object6>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "z", v->z);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("z")
#pragma pop_macro("w")
#pragma pop_macro("v")
