// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("children")
#undef children
#pragma push_macro("v")
#undef v
#pragma push_macro("value")
#undef value
#pragma push_macro("w")
#undef w

namespace lucent_app {

struct S_Tree;

struct S_Tree : lucent::Object {
  double value{};
  lucent::Array<lucent::Ref<lucent_app::S_Tree>> children{};
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Tree>& v);

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Tree>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "value", v->value);
  lucent::jsonField(w, first, "children", v->children);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("w")
#pragma pop_macro("value")
#pragma pop_macro("v")
#pragma pop_macro("children")
