// Generated by Lucent. Do not edit.
#pragma once
#include <lucent/lucent.h>

#pragma push_macro("a")
#undef a
#pragma push_macro("age")
#undef age
#pragma push_macro("children")
#undef children
#pragma push_macro("h")
#undef h
#pragma push_macro("inner")
#undef inner
#pragma push_macro("kind")
#undef kind
#pragma push_macro("label")
#undef label
#pragma push_macro("name")
#undef name
#pragma push_macro("nickname")
#undef nickname
#pragma push_macro("radius")
#undef radius
#pragma push_macro("tags")
#undef tags
#pragma push_macro("v")
#undef v
#pragma push_macro("value")
#undef value
#pragma push_macro("w")
#undef w
#pragma push_macro("x")
#undef x
#pragma push_macro("y")
#undef y
#pragma push_macro("z")
#undef z

namespace lucent_app {

inline lucent::Actor& actor_0() {
  static lucent::Actor& a = lucent::Actor::create("objects");
  return a;
}

struct S_Point;
struct S_Person;
struct S_Object3;
struct S_Object4;
struct S_Tree;
struct S_Object6;
struct S_Object7;

struct S_Point : lucent::Object {
  double x{};
  double y{};
};

struct S_Person : lucent::Object {
  lucent::String name{};
  double age{};
  lucent::Opt<lucent::String> nickname{};
  lucent::Array<lucent::String> tags{};
};

struct S_Object3 : lucent::Object {
  lucent::String kind{};
  double radius{};
};

struct S_Object4 : lucent::Object {
  lucent::String kind{};
  double w{};
  double h{};
};

struct S_Tree : lucent::Object {
  double value{};
  lucent::Array<lucent::Ref<lucent_app::S_Tree>> children{};
};

struct S_Object6 : lucent::Object {
  double z{};
};

struct S_Object7 : lucent::Object {
  double x{};
  double y{};
  lucent::Opt<lucent::String> label{};
  lucent::Ref<lucent_app::S_Object6> inner{};
};

void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Point>& v);
void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Person>& v);
void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object3>& v);
void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object4>& v);
void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Tree>& v);
void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object6>& v);
void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object7>& v);

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Point>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "x", v->x);
  lucent::jsonField(w, first, "y", v->y);
  (void)first;
  w.raw("}");
}

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Person>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "name", v->name);
  lucent::jsonField(w, first, "age", v->age);
  lucent::jsonField(w, first, "nickname", v->nickname);
  lucent::jsonField(w, first, "tags", v->tags);
  (void)first;
  w.raw("}");
}

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object3>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "kind", v->kind);
  lucent::jsonField(w, first, "radius", v->radius);
  (void)first;
  w.raw("}");
}

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object4>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "kind", v->kind);
  lucent::jsonField(w, first, "w", v->w);
  lucent::jsonField(w, first, "h", v->h);
  (void)first;
  w.raw("}");
}

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Tree>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "value", v->value);
  lucent::jsonField(w, first, "children", v->children);
  (void)first;
  w.raw("}");
}

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object6>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "z", v->z);
  (void)first;
  w.raw("}");
}

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object7>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "x", v->x);
  lucent::jsonField(w, first, "y", v->y);
  lucent::jsonField(w, first, "label", v->label);
  lucent::jsonField(w, first, "inner", v->inner);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("z")
#pragma pop_macro("y")
#pragma pop_macro("x")
#pragma pop_macro("w")
#pragma pop_macro("value")
#pragma pop_macro("v")
#pragma pop_macro("tags")
#pragma pop_macro("radius")
#pragma pop_macro("nickname")
#pragma pop_macro("name")
#pragma pop_macro("label")
#pragma pop_macro("kind")
#pragma pop_macro("inner")
#pragma pop_macro("h")
#pragma pop_macro("children")
#pragma pop_macro("age")
#pragma pop_macro("a")
