// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_C_Plain.h"

namespace lucent_app {

struct C_Deeper;

struct C_Deeper : lucent_app::C_Plain {
  void construct(lucent::Opt<lucent::String> p0_);
  static lucent::Ref<C_Deeper> create(lucent::Opt<lucent::String> p0_);
  bool lucentJson_(lucent::JsonWriter& w, bool toJson) override;
};

inline bool C_Deeper::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app
