// Generated by scripts/sync-examples.ts from packages/compiler/test/e2e/cases/async-throws.test.js. Do not edit.
// @ts-nocheck
export default function run(mod, print, lucentClass, mods) {
  (async () => {
    print(await mod.functions());
    print(await mod.arrows());

    let pending;

    try {
      pending = mod.exported();
      print("exported returned a promise");
    } catch (e) {
      print("exported threw", e.message);
    }

    try {
      await pending;
    } catch (e) {
      print("exported rejected", e.message);
    }
  })();

}
