// Generated by scripts/sync-examples.ts from packages/compiler/test/e2e/cases/function-values.test.js. Do not edit.
// @ts-nocheck
export default function run(mod, print, lucentClass, mods) {
  print(mod.absent(true));
  print(mod.absent(false));
  print(mod.unions(true));
  print(mod.unions(false));
  print(mod.containers());

}
