// Generated by Lucent. Do not edit.
#include "m_kind_u2d_checks.h"
#include <lucent/jsi/convert.h>
#include <lucent/jsi/host.h>

#pragma push_macro("instanceOfArray")
#undef instanceOfArray
#pragma push_macro("instanceOfKinds")
#undef instanceOfKinds
#pragma push_macro("isArrays")
#undef isArrays
#pragma push_macro("matchIsArray")
#undef matchIsArray
#pragma push_macro("tupleIsArray")
#undef tupleIsArray
#pragma push_macro("unionOfArrays")
#undef unionOfArrays
#pragma push_macro("x")
#undef x

namespace lucent::js {

template <>
struct Convert<std::variant<lucent::String, lucent::Array<lucent::String>>> {
  static std::variant<lucent::String, lucent::Array<lucent::String>> fromJs(jsi::Runtime& rt, const jsi::Value& v, const Path& p);
  static jsi::Value toJs(jsi::Runtime& rt, Host& h, const std::variant<lucent::String, lucent::Array<lucent::String>>& v);
};

jsi::Value errorInstanceToJs(jsi::Runtime& rt, Host& h, const Error& v) {
  return jsi::Value::undefined();
}

inline std::variant<lucent::String, lucent::Array<lucent::String>> Convert<std::variant<lucent::String, lucent::Array<lucent::String>>>::fromJs(jsi::Runtime& rt, const jsi::Value& v, const Path& p) {
  if (v.isString()) {
    return std::variant<lucent::String, lucent::Array<lucent::String>>(Convert<lucent::String>::fromJs(rt, v, p));
  }
  if (v.isObject() && v.getObject(rt).isArray(rt)) {
    return std::variant<lucent::String, lucent::Array<lucent::String>>(Convert<lucent::Array<lucent::String>>::fromJs(rt, v, p));
  }
  throwBoundaryError(rt, p, "a string or an array", v);
}

inline jsi::Value Convert<std::variant<lucent::String, lucent::Array<lucent::String>>>::toJs(jsi::Runtime& rt, Host& h, const std::variant<lucent::String, lucent::Array<lucent::String>>& v) {
  return std::visit([&](const auto& x) -> jsi::Value {
    return Convert<std::decay_t<decltype(x)>>::toJs(rt, h, x);
  }, v);
}

}  // namespace lucent::js

namespace {

using namespace lucent::js;

void install_m_kind_u2d_checks(jsi::Runtime& rt, Host& host, jsi::Object& exports) {
  defineFunction(rt, exports, "isArrays", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("isArrays", "packages/compiler/test/e2e/cases/kind-checks.lucent.ts", 5), [&]() -> jsi::Value {
      auto a0 = Convert<std::variant<lucent::String, lucent::Array<lucent::String>>>::fromJs(rt, arg(args, count, 0), Path{"isArrays", "argument 'x'"});
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_kind_u2d_checks::isArrays(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "tupleIsArray", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("tupleIsArray", "packages/compiler/test/e2e/cases/kind-checks.lucent.ts", 11), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_kind_u2d_checks::tupleIsArray());
    });
  });
  defineFunction(rt, exports, "matchIsArray", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("matchIsArray", "packages/compiler/test/e2e/cases/kind-checks.lucent.ts", 17), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::String>::fromJs(rt, arg(args, count, 0), Path{"matchIsArray", "argument 's'"});
      return Convert<bool>::toJs(rt, host, lucent_app::m_kind_u2d_checks::matchIsArray(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "unionOfArrays", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("unionOfArrays", "packages/compiler/test/e2e/cases/kind-checks.lucent.ts", 25), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_kind_u2d_checks::unionOfArrays());
    });
  });
  defineFunction(rt, exports, "instanceOfArray", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("instanceOfArray", "packages/compiler/test/e2e/cases/kind-checks.lucent.ts", 38), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_kind_u2d_checks::instanceOfArray());
    });
  });
  defineFunction(rt, exports, "instanceOfKinds", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("instanceOfKinds", "packages/compiler/test/e2e/cases/kind-checks.lucent.ts", 46), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_kind_u2d_checks::instanceOfKinds());
    });
  });
}

const ModuleDef kModules[] = {{"kind-checks", install_m_kind_u2d_checks, &lucent_app::actor_0}};

}  // namespace

namespace lucent::js {

const ModuleDef* registeredModules(size_t& count) {
  count = 1;
  return kModules;
}

void resetModuleState() {
  {
    lucent::LucentScope scope(lucent_app::actor_0());
    lucent_app::m_kind_u2d_checks::init();
  }
}

}  // namespace lucent::js

#pragma pop_macro("x")
#pragma pop_macro("unionOfArrays")
#pragma pop_macro("tupleIsArray")
#pragma pop_macro("matchIsArray")
#pragma pop_macro("isArrays")
#pragma pop_macro("instanceOfKinds")
#pragma pop_macro("instanceOfArray")
