// Generated by Lucent from kind-checks.lucent.ts. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("arrayKind")
#undef arrayKind
#pragma push_macro("instanceOfArray")
#undef instanceOfArray
#pragma push_macro("instanceOfKinds")
#undef instanceOfKinds
#pragma push_macro("isArrays")
#undef isArrays
#pragma push_macro("joined")
#undef joined
#pragma push_macro("kinds")
#undef kinds
#pragma push_macro("matchIsArray")
#undef matchIsArray
#pragma push_macro("tupleIsArray")
#undef tupleIsArray
#pragma push_macro("unionOfArrays")
#undef unionOfArrays

namespace lucent_app {

namespace m_kind_u2d_checks {

lucent::String isArrays(std::variant<lucent::String, lucent::Array<lucent::String>> p0_);
lucent::String tupleIsArray();
bool matchIsArray(lucent::String p0_);
lucent::String arrayKind(std::variant<lucent::Array<double>, lucent::Array<lucent::String>> p0_);
lucent::String unionOfArrays();
lucent::String joined(lucent::Opt<std::variant<lucent::String, lucent::Array<lucent::String>>> p0_);
lucent::String instanceOfArray();
lucent::String kinds(lucent::Opt<std::variant<lucent::Map<lucent::String, double>, lucent::String>> p0_, lucent::Opt<std::variant<lucent::Date, double>> p1_);
lucent::String instanceOfKinds();
void init();

}  // namespace m_kind_u2d_checks

}  // namespace lucent_app

#pragma pop_macro("unionOfArrays")
#pragma pop_macro("tupleIsArray")
#pragma pop_macro("matchIsArray")
#pragma pop_macro("kinds")
#pragma pop_macro("joined")
#pragma pop_macro("isArrays")
#pragma pop_macro("instanceOfKinds")
#pragma pop_macro("instanceOfArray")
#pragma pop_macro("arrayKind")
