// Generated by Lucent. Do not edit.
#pragma once
#include <lucent/lucent.h>

#pragma push_macro("v")
#undef v

namespace lucent_app {

struct S_Object1;
struct S_Ledger;
struct C_Account;

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object1>& v);
inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Ledger>& v);

}  // namespace lucent_app

#pragma pop_macro("v")
