// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("balance")
#undef balance
#pragma push_macro("deposit")
#undef deposit
#pragma push_macro("history")
#undef history
#pragma push_macro("r_id_")
#undef r_id_

namespace lucent_app {

struct C_Account;

struct C_Account : lucent::Object {
  lucent::BigInt r_id_{};
  lucent::BigInt balance{};
  lucent::Array<lucent::BigInt> history{};
  void construct(lucent::BigInt p0_);
  static lucent::Ref<C_Account> create(lucent::BigInt p0_);
  lucent::BigInt deposit(lucent::BigInt p0_);
  lucent::BigInt get_doubled();
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_Account::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "id", this->r_id_);
  lucent::jsonField(w, first, "balance", this->balance);
  lucent::jsonField(w, first, "history", this->history);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("r_id_")
#pragma pop_macro("history")
#pragma pop_macro("deposit")
#pragma pop_macro("balance")
