// Generated by Lucent. Do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const { loadModule, lucentClass } = require("./_lucent/runtime.js");
const m = loadModule("collections", () => require("react-native").TurboModuleRegistry, require("./_lucent/identity.js"));
exports.arrays = m.arrays;
exports.words = m.words;
exports.mapOps = m.mapOps;
exports.records = m.records;
exports.mergedRecords = m.mergedRecords;
exports.entries = m.entries;
exports.matrix = m.matrix;
exports.uniq = m.uniq;
exports.searchFrom = m.searchFrom;
exports.newArrayLength = m.newArrayLength;
exports.fromLength = m.fromLength;
exports.fromUndefined = m.fromUndefined;
exports.flatMapped = m.flatMapped;
