// Generated by Lucent from switch-returns.lucent.ts. Do not edit.
#include "m_switch_u2d_returns.h"

#pragma push_macro("count")
#undef count
#pragma push_macro("rank")
#undef rank
#pragma push_macro("s")
#undef s
#pragma push_macro("sign")
#undef sign
#pragma push_macro("size")
#undef size
#pragma push_macro("steps")
#undef steps
#pragma push_macro("weekday")
#undef weekday
#pragma push_macro("weight")
#undef weight

namespace lucent_app {

lucent::String m_switch_u2d_returns::size(double p0_) {
  {
    bool v2_ = p0_ == 0.0;
    double v13_{};
    if (v2_) {
      v13_ = 0.0;
    } else {
      bool v5_ = p0_ == 1.0;
      double v12_{};
      if (v5_) {
        v12_ = 1.0;
      } else {
        bool v8_ = p0_ == 2.0;
        double v11_{};
        if (v8_) {
          v11_ = 2.0;
        } else {
          v11_ = 3.0;
        }
        v12_ = v11_;
      }
      v13_ = v12_;
    }
    bool v15_ = v13_ <= 0.0;
    if (v15_) {
      return LUCENT_STR("none");
    }
    bool v18_ = v13_ <= 1.0;
    if (v18_) {
      return LUCENT_STR("one");
    }
    bool v21_ = v13_ <= 2.0;
    if (v21_) {
      return LUCENT_STR("two");
    }
    return LUCENT_STR("many");
  }
}

lucent::String m_switch_u2d_returns::rank(double p0_) {
  {
    bool v2_ = p0_ == 1.0;
    double v9_{};
    if (v2_) {
      v9_ = 0.0;
    } else {
      bool v5_ = p0_ == 2.0;
      double v8_{};
      if (v5_) {
        v8_ = 2.0;
      } else {
        v8_ = 1.0;
      }
      v9_ = v8_;
    }
    bool v11_ = v9_ <= 0.0;
    if (v11_) {
      return LUCENT_STR("gold");
    }
    bool v14_ = v9_ <= 1.0;
    if (v14_) {
      return LUCENT_STR("other");
    }
    return LUCENT_STR("silver");
  }
}

bool m_switch_u2d_returns::weekday(lucent::String p0_) {
  {
    bool v2_ = p0_ == LUCENT_STR("sat");
    double v13_{};
    if (v2_) {
      v13_ = 0.0;
    } else {
      bool v5_ = p0_ == LUCENT_STR("sun");
      double v12_{};
      if (v5_) {
        v12_ = 1.0;
      } else {
        bool v8_ = p0_ == LUCENT_STR("mon");
        double v11_{};
        if (v8_) {
          v11_ = 2.0;
        } else {
          v11_ = 3.0;
        }
        v12_ = v11_;
      }
      v13_ = v12_;
    }
    bool v15_ = v13_ <= 1.0;
    if (v15_) {
      return false;
    }
    return true;
  }
}

double m_switch_u2d_returns::steps(double p0_) {
  double count = 0.0;
  {
    bool v3_ = p0_ == 3.0;
    double v6_{};
    if (v3_) {
      v6_ = 1.0;
    } else {
      v6_ = 0.0;
    }
    bool v8_ = v6_ <= 0.0;
    if (v8_) {
      count = count + 1.0;
    }
    count = count + 3.0;
    return count;
  }
}

double m_switch_u2d_returns::weight(lucent::String p0_) {
  {
    bool v2_ = p0_ == LUCENT_STR("light");
    double v9_{};
    if (v2_) {
      v9_ = 0.0;
    } else {
      bool v5_ = p0_ == LUCENT_STR("heavy");
      double v8_{};
      if (v5_) {
        v8_ = 1.0;
      } else {
        v8_ = 2.0;
      }
      v9_ = v8_;
    }
    bool v11_ = v9_ <= 0.0;
    if (v11_) {
      return 1.0;
    }
    bool v14_ = v9_ <= 1.0;
    if (v14_) {
      return 10.0;
    }
  }
  lucent::unreachable();
}

lucent::String m_switch_u2d_returns::sign(double p0_) {
  bool v2_ = p0_ > 0.0;
  double v10_{};
  if (v2_) {
    v10_ = 1.0;
  } else {
    bool v5_ = p0_ < 0.0;
    double v9_{};
    if (v5_) {
      v9_ = -1.0;
    } else {
      v9_ = 0.0;
    }
    v10_ = v9_;
  }
  int32_t s = lucent::toInt32(v10_);
  {
    bool v13_ = s == 1;
    double v21_{};
    if (v13_) {
      v21_ = 0.0;
    } else {
      bool v17_ = static_cast<double>(s) == -1.0;
      double v20_{};
      if (v17_) {
        v20_ = 1.0;
      } else {
        v20_ = 2.0;
      }
      v21_ = v20_;
    }
    bool v23_ = v21_ <= 0.0;
    if (v23_) {
      return LUCENT_STR("+");
    }
    bool v26_ = v21_ <= 1.0;
    if (v26_) {
      return LUCENT_STR("-");
    }
    return LUCENT_STR("0");
  }
}

void m_switch_u2d_returns::init() {
}

}  // namespace lucent_app

#pragma pop_macro("weight")
#pragma pop_macro("weekday")
#pragma pop_macro("steps")
#pragma pop_macro("size")
#pragma pop_macro("sign")
#pragma pop_macro("s")
#pragma pop_macro("rank")
#pragma pop_macro("count")
