// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("format")
#undef format
#pragma push_macro("last")
#undef last
#pragma push_macro("onValue")
#undef onValue
#pragma push_macro("send")
#undef send

namespace lucent_app {

struct C_Relay;

struct C_Relay : lucent::Object {
  lucent::Fn<void(lucent::String)> onValue{};
  lucent::String last{};
  lucent::Fn<lucent::String(lucent::String)> format{};
  void construct(lucent::Fn<void(lucent::String)> p0_);
  static lucent::Ref<C_Relay> create(lucent::Fn<void(lucent::String)> p0_);
  void send(lucent::String p0_);
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_Relay::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "onValue", this->onValue);
  lucent::jsonField(w, first, "last", this->last);
  lucent::jsonField(w, first, "format", this->format);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("send")
#pragma pop_macro("onValue")
#pragma pop_macro("last")
#pragma pop_macro("format")
