// Generated by Lucent. Do not edit.
#include <lucent/jsi/host.h>

static_assert(lucent::js::kRuntimeAbi == 2, "generated for Lucent runtime ABI 2: build it with the runtime lucent build copied next to it");

namespace {

const lucent::js::ModuleIdentity kModuleIdentities[] = {{"collections", "3fc46e4e1657b6eb"}};

}  // namespace

namespace lucent::js {

const BuildIdentity& buildIdentity() {
  static const BuildIdentity identity = {"all", "14d28e70a5276732", kModuleIdentities, 1};
  return identity;
}

}  // namespace lucent::js
