// Generated by Lucent from collections.lucent.ts. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("arrays")
#undef arrays
#pragma push_macro("entries")
#undef entries
#pragma push_macro("flatMapped")
#undef flatMapped
#pragma push_macro("fromLength")
#undef fromLength
#pragma push_macro("fromUndefined")
#undef fromUndefined
#pragma push_macro("lengthOf")
#undef lengthOf
#pragma push_macro("mapOps")
#undef mapOps
#pragma push_macro("matrix")
#undef matrix
#pragma push_macro("mergedRecords")
#undef mergedRecords
#pragma push_macro("newArrayLength")
#undef newArrayLength
#pragma push_macro("records")
#undef records
#pragma push_macro("searchFrom")
#undef searchFrom
#pragma push_macro("uniq")
#undef uniq
#pragma push_macro("words")
#undef words

namespace lucent_app {

namespace m_collections {

lucent::String arrays(lucent::Array<double> p0_);
lucent::Map<lucent::String, double> words(lucent::String p0_);
lucent::String mapOps();
lucent::Dict<double> records(lucent::Dict<double> p0_);
lucent::String mergedRecords(lucent::Dict<double> p0_, lucent::Opt<lucent::Dict<double>> p1_);
lucent::String entries(lucent::Dict<lucent::String> p0_);
lucent::Array<lucent::Array<double>> matrix(double p0_);
lucent::Array<lucent::String> uniq(lucent::Array<lucent::String> p0_);
lucent::String searchFrom(lucent::Opt<double> p0_);
lucent::String lengthOf(lucent::Fn<lucent::String()> p0_);
lucent::String newArrayLength(double p0_);
lucent::String fromLength(double p0_);
lucent::String fromUndefined(double p0_);
lucent::String flatMapped();
void init();

}  // namespace m_collections

}  // namespace lucent_app

#pragma pop_macro("words")
#pragma pop_macro("uniq")
#pragma pop_macro("searchFrom")
#pragma pop_macro("records")
#pragma pop_macro("newArrayLength")
#pragma pop_macro("mergedRecords")
#pragma pop_macro("matrix")
#pragma pop_macro("mapOps")
#pragma pop_macro("lengthOf")
#pragma pop_macro("fromUndefined")
#pragma pop_macro("fromLength")
#pragma pop_macro("flatMapped")
#pragma pop_macro("entries")
#pragma pop_macro("arrays")
