// Generated by Lucent from collections.lucent.ts. Do not edit.
#include "m_collections.h"

#pragma push_macro("aliasA")
#undef aliasA
#pragma push_macro("aliasB")
#undef aliasB
#pragma push_macro("arrays")
#undef arrays
#pragma push_macro("copy")
#undef copy
#pragma push_macro("counts")
#undef counts
#pragma push_macro("doubled")
#undef doubled
#pragma push_macro("e")
#undef e
#pragma push_macro("entries")
#undef entries
#pragma push_macro("flatMapped")
#undef flatMapped
#pragma push_macro("found")
#undef found
#pragma push_macro("fromLength")
#undef fromLength
#pragma push_macro("fromUndefined")
#undef fromUndefined
#pragma push_macro("i")
#undef i
#pragma push_macro("j")
#undef j
#pragma push_macro("k")
#undef k
#pragma push_macro("keys")
#undef keys
#pragma push_macro("lengthOf")
#undef lengthOf
#pragma push_macro("m")
#undef m
#pragma push_macro("mapOps")
#undef mapOps
#pragma push_macro("matrix")
#undef matrix
#pragma push_macro("merged")
#undef merged
#pragma push_macro("mergedRecords")
#undef mergedRecords
#pragma push_macro("n")
#undef n
#pragma push_macro("names")
#undef names
#pragma push_macro("nested")
#undef nested
#pragma push_macro("newArrayLength")
#undef newArrayLength
#pragma push_macro("out")
#undef out
#pragma push_macro("parts")
#undef parts
#pragma push_macro("present")
#undef present
#pragma push_macro("records")
#undef records
#pragma push_macro("row")
#undef row
#pragma push_macro("rows")
#undef rows
#pragma push_macro("s")
#undef s
#pragma push_macro("searchFrom")
#undef searchFrom
#pragma push_macro("sorted")
#undef sorted
#pragma push_macro("spliced")
#undef spliced
#pragma push_macro("total")
#undef total
#pragma push_macro("uniq")
#undef uniq
#pragma push_macro("v")
#undef v
#pragma push_macro("w")
#undef w
#pragma push_macro("words")
#undef words
#pragma push_macro("xs")
#undef xs

namespace lucent_app {

lucent::String m_collections::arrays(lucent::Array<double> p0_) {
  lucent::Array<lucent::String> out = lucent::Array<lucent::String>{};
  lucent::Array<double> copy = p0_.slice();
  (void)copy.push(100.0, 200.0);
  lucent::String v10_ = copy.join(LUCENT_STR(","));
  (void)out.push(v10_);
  double v14_ = p0_.indexOf(3.0);
  lucent::String v15_ = lucent::toJsString(v14_);
  bool v17_ = p0_.includes(5.0);
  lucent::String v18_ = lucent::toJsString(v17_);
  double v20_ = p0_.findIndex([](double p0_, double p1_, lucent::Array<double> p2_) mutable -> bool {
    return p0_ > 2.0;
  });
  lucent::String v21_ = lucent::toJsString(v20_);
  (void)out.push(v15_, v18_, v21_);
  lucent::Opt<double> found = p0_.find([](double p0_, double p1_, lucent::Array<double> p2_) mutable -> bool {
    return lucent::jsMod(p0_, 2.0) == 0.0;
  });
  bool v28_ = lucent::strictEquals(found, lucent::undefined);
  lucent::String v33_{};
  if (v28_) {
    v33_ = LUCENT_STR("none");
  } else {
    double v31_ = found.value();
    v33_ = lucent::toJsString(v31_);
  }
  (void)out.push(v33_);
  lucent::Array<double> v37_ = p0_.filter([](double p0_, double p1_, lucent::Array<double> p2_) mutable -> bool {
    return p0_ > 1.0;
  });
  lucent::Array<double> v39_ = v37_.template map<double>([](double p0_, double p1_, lucent::Array<double> p2_) mutable -> double {
    return p0_ * 10.0;
  });
  lucent::String v41_ = v39_.join(LUCENT_STR("|"));
  (void)out.push(v41_);
  double v46_ = p0_.reduce([](double p0_, double p1_, double p2_, lucent::Array<double> p3_) mutable -> double {
    return p0_ + p1_;
  }, double(0.0));
  lucent::String v47_ = lucent::toJsString(v46_);
  (void)out.push(v47_);
  bool v51_ = p0_.some([](double p0_, double p1_, lucent::Array<double> p2_) mutable -> bool {
    return p0_ > 4.0;
  });
  lucent::String v52_ = lucent::toJsString(v51_);
  bool v54_ = p0_.every([](double p0_, double p1_, lucent::Array<double> p2_) mutable -> bool {
    return p0_ > 0.0;
  });
  lucent::String v55_ = lucent::toJsString(v54_);
  (void)out.push(v52_, v55_);
  lucent::Array<double> v57_ = ({ lucent::Array<double> arr_1_; arr_1_.append(p0_); arr_1_; });
  lucent::Array<double> sorted = v57_.sort([](double p0_, double p1_) mutable -> double {
    return p1_ - p0_;
  });
  lucent::String v63_ = sorted.join(LUCENT_STR(","));
  (void)out.push(v63_);
  lucent::Array<double> v70_ = lucent::Array<double>{10.0, 9.0, 1.0, 100.0};
  lucent::Array<double> v71_ = v70_.sort();
  lucent::String v73_ = v71_.join(LUCENT_STR(","));
  (void)out.push(v73_);
  lucent::Array<double> spliced = copy.splice(1.0, 2.0, 7.0, 8.0, 9.0);
  lucent::String v85_ = spliced.join(LUCENT_STR(","));
  lucent::String v88_ = copy.join(LUCENT_STR(","));
  (void)out.push(v85_, v88_);
  lucent::Opt<double> v92_ = copy.pop();
  lucent::String v93_ = lucent::toJsString(v92_);
  lucent::Opt<double> v95_ = copy.shift();
  lucent::String v96_ = lucent::toJsString(v95_);
  lucent::String v99_ = copy.join(LUCENT_STR(","));
  (void)out.push(v93_, v96_, v99_);
  double v103_ = -1.0;
  (void)copy.unshift(v103_);
  lucent::Array<double> v107_ = copy.reverse();
  lucent::String v109_ = v107_.join(LUCENT_STR(","));
  (void)out.push(v109_);
  int64_t v113_ = static_cast<int64_t>(copy.size());
  lucent::String v114_ = lucent::toJsString(static_cast<double>(v113_));
  double v117_ = -1.0;
  lucent::Opt<double> v118_ = copy.atIndex(v117_);
  lucent::String v119_ = lucent::toJsString(v118_);
  double v122_ = copy.lastIndexOf(8.0);
  lucent::String v123_ = lucent::toJsString(v122_);
  (void)out.push(v114_, v119_, v123_);
  lucent::Array<double> v127_ = lucent::Array<double>{1.0, 2.0};
  lucent::Array<double> v129_ = lucent::Array<double>{3.0};
  lucent::Array<double> v130_ = lucent::Array<double>{};
  lucent::Array<lucent::Array<double>> nested = lucent::Array<lucent::Array<double>>{v127_, v129_, v130_};
  lucent::Array<double> v135_ = nested.template flatMap<double>([](lucent::Array<double> p0_, double p1_, lucent::Array<lucent::Array<double>> p2_) mutable -> lucent::Array<double> {
    return p0_;
  });
  lucent::String v137_ = v135_.join(LUCENT_STR(","));
  (void)out.push(v137_);
  lucent::Fn<double(lucent::Undefined, double)> v141_ = lucent::Fn<double(lucent::Undefined, double)>([](lucent::Undefined p0_, double p1_) mutable -> double {
    return p1_ * p1_;
  });
  lucent::Array<double> v142_ = ({
    auto cb_2_ = v141_;
    lucent::Array<double>::generate(5.0, [&](double i) {
      return cb_2_(lucent::undefined, i);
    });
  });
  lucent::String v144_ = v142_.join(LUCENT_STR(","));
  (void)out.push(v144_);
  lucent::Array<double> v148_ = lucent::Array<double>::filled(lucent::arrayLength(3.0), double{});
  lucent::Array<double> v150_ = v148_.fill(7.0);
  lucent::String v152_ = v150_.join(LUCENT_STR(","));
  (void)out.push(v152_);
  lucent::Array<double> aliasA = lucent::Array<double>{1.0, 2.0};
  lucent::Array<double> aliasB = aliasA;
  (void)aliasB.push(3.0);
  int64_t v163_ = static_cast<int64_t>(aliasA.size());
  lucent::String v164_ = lucent::toJsString(static_cast<double>(v163_));
  (void)out.push(v164_);
  copy.setLength(2.0);
  lucent::String v172_ = copy.join(LUCENT_STR(","));
  (void)out.push(v172_);
  lucent::Box<double> total{};
  *total = 0.0;
  p0_.forEach([total = total](double p0_, double p1_, lucent::Array<double> p2_) mutable -> void {
    double v3_ = *total;
    *total = v3_ + p0_ * p1_;
  });
  double v178_ = *total;
  lucent::String v179_ = lucent::toJsString(v178_);
  (void)out.push(v179_);
  return out.join(LUCENT_STR(" / "));
}

lucent::Map<lucent::String, double> m_collections::words(lucent::String p0_) {
  lucent::Map<lucent::String, double> counts = lucent::Map<lucent::String, double>();
  lucent::Array<lucent::String> v3_ = lucent::split(p0_, LUCENT_STR(" "));
  {
    auto coll0_ = v3_;
    for (size_t i0_ = 0; i0_ < coll0_.size(); i0_++) {
      lucent::String v4_ = coll0_.at(i0_);
      {
        lucent::String w = std::move(v4_);
        bool v7_ = !lucent::truthy(w);
        if (v7_) {
          continue;
        }
        lucent::Opt<double> v12_ = counts.get(w);
        bool v14_ = !v12_.has();
        double v17_{};
        if (v14_) {
          v17_ = 0.0;
        } else {
          v17_ = v12_.value();
        }
        double v19_ = v17_ + 1.0;
        (void)counts.set(w, v19_);
      }
    }
  }
  return counts;
}

lucent::String m_collections::mapOps() {
  lucent::Map<lucent::String, double> m = lucent::Map<lucent::String, double>();
  lucent::Map<lucent::String, double> v4_ = m.set(LUCENT_STR("b"), 2.0);
  lucent::Map<lucent::String, double> v7_ = v4_.set(LUCENT_STR("a"), 1.0);
  (void)v7_.set(LUCENT_STR("c"), 3.0);
  (void)m.remove(LUCENT_STR("a"));
  (void)m.set(LUCENT_STR("a"), 10.0);
  lucent::Array<lucent::String> parts = lucent::Array<lucent::String>{};
  {
    auto coll0_ = m;
    typename std::decay_t<decltype(coll0_.table())>::Iterating coll0_guard_(coll0_.table());
    for (size_t i0_ = 0; i0_ < coll0_.table().slotCount(); i0_++) {
      if (!coll0_.table().slotLive(i0_)) {
        continue;
      }
      std::tuple<lucent::String, double> v20_ = std::tuple<lucent::String, double>(coll0_.table().slot(i0_).key, coll0_.table().slot(i0_).value);
      {
        lucent::String k = std::get<0>(v20_);
        double v = std::get<1>(v20_);
        lucent::String v27_ = lucent::toJsString(v);
        lucent::String v29_ = lucent::concat(k, LUCENT_STR("="), v27_);
        (void)parts.push(v29_);
      }
    }
  }
  double v33_ = m.size();
  lucent::String v34_ = lucent::toJsString(v33_);
  bool v37_ = m.has(LUCENT_STR("b"));
  lucent::String v38_ = lucent::toJsString(v37_);
  lucent::Opt<double> v41_ = m.get(LUCENT_STR("zz"));
  lucent::String v42_ = lucent::toJsString(v41_);
  (void)parts.push(v34_, v38_, v42_);
  lucent::Array<lucent::String> v45_ = m.keys();
  lucent::Array<lucent::String> v46_ = ({ lucent::Array<lucent::String> arr_3_; arr_3_.append(v45_); arr_3_; });
  lucent::String keys = v46_.join(LUCENT_STR(","));
  (void)parts.push(keys);
  lucent::Array<double> v56_ = lucent::Array<double>{3.0, 1.0, 3.0, 2.0};
  lucent::Set<double> s = lucent::Set<double>(v56_);
  (void)s.add(1.0);
  (void)s.add(5.0);
  double v66_ = s.size();
  lucent::String v67_ = lucent::toJsString(v66_);
  lucent::Array<double> v69_ = ({ lucent::Array<double> arr_4_; arr_4_.append(s.values()); arr_4_; });
  lucent::String v71_ = v69_.join(LUCENT_STR(","));
  bool v74_ = s.has(2.0);
  lucent::String v75_ = lucent::toJsString(v74_);
  (void)parts.push(v67_, v71_, v75_);
  (void)s.remove(3.0);
  lucent::Array<double> v82_ = s.values();
  lucent::String v84_ = v82_.join(LUCENT_STR(","));
  (void)parts.push(v84_);
  return parts.join(LUCENT_STR(" "));
}

lucent::Dict<double> m_collections::records(lucent::Dict<double> p0_) {
  lucent::Dict<double> out = ({ lucent::Dict<double> rec_5_; rec_5_; });
  lucent::Array<lucent::String> v2_ = p0_.keys();
  {
    auto coll0_ = v2_;
    for (size_t i0_ = 0; i0_ < coll0_.size(); i0_++) {
      lucent::String v3_ = coll0_.at(i0_);
      {
        lucent::String k = std::move(v3_);
        lucent::String v6_ = k.toUpperCase();
        lucent::Opt<double> v8_ = p0_.get(k);
        bool v10_ = !v8_.has();
        double v13_{};
        if (v10_) {
          v13_ = 0.0;
        } else {
          v13_ = v8_.value();
        }
        double v15_ = v13_ * 2.0;
        lucent::setEntry(out, v6_, v15_);
      }
    }
  }
  lucent::Array<double> v19_ = p0_.values();
  double v22_ = v19_.reduce([](double p0_, double p1_, double p2_, lucent::Array<double> p3_) mutable -> double {
    return p0_ + p1_;
  }, double(0.0));
  lucent::setEntry(out, LUCENT_STR("total"), v22_);
  (void)out.remove(LUCENT_STR("B"));
  return out;
}

lucent::String m_collections::mergedRecords(lucent::Dict<double> p0_, lucent::Opt<lucent::Dict<double>> p1_) {
  lucent::Dict<double> merged = ({
    lucent::Dict<double> rec_6_;
    rec_6_.set(LUCENT_STR("z"), 0.0);
    lucent::assignEntries(rec_6_, p0_);
    rec_6_.set(LUCENT_STR("a"), 9.0);
    auto src_7_ = p1_;
    if (src_7_.has()) {
      lucent::assignEntries(rec_6_, src_7_.get());
    }
    rec_6_;
  });
  return lucent::json::stringify(merged);
}

lucent::String m_collections::entries(lucent::Dict<lucent::String> p0_) {
  lucent::Array<std::tuple<lucent::String, lucent::String>> v1_ = lucent::dictEntries(p0_);
  lucent::Array<lucent::String> v3_ = v1_.template map<lucent::String>([](std::tuple<lucent::String, lucent::String> p0_, double p1_, lucent::Array<std::tuple<lucent::String, lucent::String>> p2_) mutable -> lucent::String {
    lucent::String k = std::get<0>(p0_);
    lucent::String v = std::get<1>(p0_);
    return lucent::concat(k, LUCENT_STR(":"), v);
  });
  return v3_.join(LUCENT_STR(";"));
}

lucent::Array<lucent::Array<double>> m_collections::matrix(double p0_) {
  lucent::Array<lucent::Array<double>> rows = lucent::Array<lucent::Array<double>>{};
  {
    int64_t i = static_cast<int64_t>(0);
    while (true) {
      {
        bool v5_ = !(static_cast<double>(i) < p0_);
        if (v5_) {
          break;
        }
        lucent::Array<double> row = lucent::Array<double>{};
        {
          int64_t j = static_cast<int64_t>(0);
          while (true) {
            {
              bool v10_ = !(static_cast<double>(j) < p0_);
              if (v10_) {
                break;
              }
              double v13_ = static_cast<double>(i) * p0_;
              double v15_ = v13_ + static_cast<double>(j);
              (void)row.push(v15_);
            }
            j = static_cast<int64_t>(j) + static_cast<int64_t>(1);
          }
        }
        (void)rows.push(row);
      }
      i = static_cast<int64_t>(i) + static_cast<int64_t>(1);
    }
  }
  return rows;
}

lucent::Array<lucent::String> m_collections::uniq(lucent::Array<lucent::String> p0_) {
  lucent::Set<lucent::String> v1_ = lucent::Set<lucent::String>(p0_);
  return ({ lucent::Array<lucent::String> arr_8_; arr_8_.append(v1_.values()); arr_8_; });
}

lucent::String m_collections::searchFrom(lucent::Opt<double> p0_) {
  lucent::Array<double> xs = lucent::Array<double>{1.0, 2.0, 3.0, 1.0, 2.0, 3.0};
  double v11_ = xs.indexOf(1.0, 1.0);
  double v15_ = -2.0;
  double v16_ = xs.indexOf(3.0, v15_);
  double v20_ = xs.indexOf(1.0, 10.0);
  double v24_ = xs.lastIndexOf(3.0, 3.0);
  double v28_ = -4.0;
  double v29_ = xs.lastIndexOf(1.0, v28_);
  double v33_ = -10.0;
  double v34_ = xs.lastIndexOf(1.0, v33_);
  double v37_ = xs.lastIndexOf(2.0, p0_.valueOr(lucent::kNaN));
  bool v41_ = xs.includes(1.0, 4.0);
  double v45_ = -1.0;
  bool v46_ = xs.includes(3.0, v45_);
  bool v49_ = xs.includes(1.0, p0_.valueOr(lucent::kNaN));
  double v52_ = xs.indexOf(2.0, p0_.valueOr(lucent::kNaN));
  lucent::Array<std::variant<bool, double>> v53_ = lucent::Array<std::variant<bool, double>>{std::variant<bool, double>(v11_), std::variant<bool, double>(v16_), std::variant<bool, double>(v20_), std::variant<bool, double>(v24_), std::variant<bool, double>(v29_), std::variant<bool, double>(v34_), std::variant<bool, double>(v37_), std::variant<bool, double>(v41_), std::variant<bool, double>(v46_), std::variant<bool, double>(v49_), std::variant<bool, double>(v52_)};
  return v53_.join(LUCENT_STR(","));
}

lucent::String m_collections::lengthOf(lucent::Fn<lucent::String()> p0_) {
  {
    std::exception_ptr ex2_;
    try {
      return p0_();
    } catch (const lucent::GeneratorReturn&) {
      throw;
    } catch (...) {
      ex2_ = std::current_exception();
    }
    if (ex2_) {
      lucent::Error v2_ = lucent::currentError(ex2_);
      lucent::Error e = std::move(v2_);
      return e->name;
    }
  }
  lucent::unreachable();
}

lucent::String m_collections::newArrayLength(double p0_) {
  lucent::Fn<lucent::String()> v1_ = lucent::Fn<lucent::String()>([n = p0_]() mutable -> lucent::String {
    lucent::Array<double> v1_ = lucent::Array<double>::filled(lucent::arrayLength(n), double{});
    lucent::Array<double> v3_ = v1_.fill(0.0);
    int64_t v4_ = static_cast<int64_t>(v3_.size());
    return lucent::toJsString(static_cast<double>(v4_));
  });
  return lucent_app::m_collections::lengthOf(v1_);
}

lucent::String m_collections::fromLength(double p0_) {
  lucent::Fn<lucent::String()> v1_ = lucent::Fn<lucent::String()>([n = p0_]() mutable -> lucent::String {
    lucent::Fn<double(lucent::Undefined, double)> v1_ = lucent::Fn<double(lucent::Undefined, double)>([](lucent::Undefined p0_, double p1_) mutable -> double {
      return p1_;
    });
    lucent::Array<double> v2_ = ({
      auto cb_9_ = v1_;
      lucent::Array<double>::generate(n, [&](double i) {
        return cb_9_(lucent::undefined, i);
      });
    });
    return v2_.join(LUCENT_STR(","));
  });
  return lucent_app::m_collections::lengthOf(v1_);
}

lucent::String m_collections::fromUndefined(double p0_) {
  lucent::Fn<lucent::String()> v1_ = lucent::Fn<lucent::String()>([n = p0_]() mutable -> lucent::String {
    lucent::Array<lucent::Opt<double>> xs = lucent::Array<lucent::Opt<double>>::filled(lucent::arrayLikeLength(n), lucent::Opt<double>(lucent::undefined));
    int64_t v3_ = static_cast<int64_t>(xs.size());
    lucent::String v4_ = lucent::toJsString(static_cast<double>(v3_));
    lucent::String v7_ = xs.join();
    return lucent::concat(v4_, LUCENT_STR(":"), v7_);
  });
  return lucent_app::m_collections::lengthOf(v1_);
}

lucent::String m_collections::flatMapped() {
  lucent::Array<lucent::Opt<lucent::String>> names = lucent::Array<lucent::Opt<lucent::String>>{lucent::Opt<lucent::String>(LUCENT_STR("a")), lucent::Opt<lucent::String>(lucent::null), lucent::Opt<lucent::String>(LUCENT_STR("b"))};
  lucent::Fn<std::variant<lucent::Array<lucent::Undefined>, lucent::String>(lucent::Opt<lucent::String>, double, lucent::Array<lucent::Opt<lucent::String>>)> v5_ = lucent::Fn<std::variant<lucent::Array<lucent::Undefined>, lucent::String>(lucent::Opt<lucent::String>, double, lucent::Array<lucent::Opt<lucent::String>>)>([](lucent::Opt<lucent::String> p0_, double p1_, lucent::Array<lucent::Opt<lucent::String>> p2_) mutable -> std::variant<lucent::Array<lucent::Undefined>, lucent::String> {
    bool v4_ = !p0_.has();
    std::variant<lucent::Array<lucent::Undefined>, lucent::String> v8_{};
    if (v4_) {
      lucent::Array<lucent::String> v5_ = lucent::Array<lucent::String>{};
      v8_ = std::variant<lucent::Array<lucent::Undefined>, lucent::String>(((void)v5_, lucent::Array<lucent::Undefined>()));
    } else {
      v8_ = std::variant<lucent::Array<lucent::Undefined>, lucent::String>(p0_.value());
    }
    return v8_;
  });
  lucent::Array<lucent::String> present = names.template flatMap<lucent::String>(lucent::Fn<std::variant<lucent::String, lucent::Array<lucent::String>>(lucent::Opt<lucent::String>, double, lucent::Array<lucent::Opt<lucent::String>>)>([fn_10_ = v5_](lucent::Opt<lucent::String> a0, double a1, lucent::Array<lucent::Opt<lucent::String>> a2) {
    return lucent::emptyArrayAs<std::variant<lucent::String, lucent::Array<lucent::String>>, lucent::Array<lucent::String>>(fn_10_(a0, a1, a2));
  }));
  lucent::Array<double> v10_ = lucent::Array<double>{1.0, 2.0, 3.0};
  lucent::Array<double> doubled = v10_.template flatMap<double>([](double p0_, double p1_, lucent::Array<double> p2_) mutable -> std::variant<double, lucent::Array<double>> {
    bool v6_ = lucent::jsMod(p0_, 2.0) == 0.0;
    std::variant<double, lucent::Array<double>> v10_{};
    if (v6_) {
      lucent::Array<double> v7_ = lucent::Array<double>{p0_, p0_};
      v10_ = std::variant<double, lucent::Array<double>>(v7_);
    } else {
      v10_ = std::variant<double, lucent::Array<double>>(p0_);
    }
    return v10_;
  });
  lucent::String v15_ = present.join(LUCENT_STR(","));
  lucent::String v19_ = doubled.join(LUCENT_STR(","));
  return lucent::concat(v15_, LUCENT_STR(" "), v19_);
}

void m_collections::init() {
}

}  // namespace lucent_app

#pragma pop_macro("xs")
#pragma pop_macro("words")
#pragma pop_macro("w")
#pragma pop_macro("v")
#pragma pop_macro("uniq")
#pragma pop_macro("total")
#pragma pop_macro("spliced")
#pragma pop_macro("sorted")
#pragma pop_macro("searchFrom")
#pragma pop_macro("s")
#pragma pop_macro("rows")
#pragma pop_macro("row")
#pragma pop_macro("records")
#pragma pop_macro("present")
#pragma pop_macro("parts")
#pragma pop_macro("out")
#pragma pop_macro("newArrayLength")
#pragma pop_macro("nested")
#pragma pop_macro("names")
#pragma pop_macro("n")
#pragma pop_macro("mergedRecords")
#pragma pop_macro("merged")
#pragma pop_macro("matrix")
#pragma pop_macro("mapOps")
#pragma pop_macro("m")
#pragma pop_macro("lengthOf")
#pragma pop_macro("keys")
#pragma pop_macro("k")
#pragma pop_macro("j")
#pragma pop_macro("i")
#pragma pop_macro("fromUndefined")
#pragma pop_macro("fromLength")
#pragma pop_macro("found")
#pragma pop_macro("flatMapped")
#pragma pop_macro("entries")
#pragma pop_macro("e")
#pragma pop_macro("doubled")
#pragma pop_macro("counts")
#pragma pop_macro("copy")
#pragma pop_macro("arrays")
#pragma pop_macro("aliasB")
#pragma pop_macro("aliasA")
