// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_C_Named.h"

#pragma push_macro("name")
#undef name

namespace lucent_app {

struct C_NamedChild : lucent_app::C_Named {
  void construct(lucent::Opt<lucent::String> p0_);
  static lucent::Ref<C_NamedChild> create(lucent::Opt<lucent::String> p0_);
  bool lucentJson_(lucent::JsonWriter& w, bool toJson) override;
};

inline bool C_NamedChild::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "name", this->name);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("name")
