// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_C_Base.h"

#pragma push_macro("a")
#undef a
#pragma push_macro("b")
#undef b

namespace lucent_app {

struct C_Derived;

struct C_Derived : lucent_app::C_Base {
  void construct(double p0_, lucent::Opt<lucent::String> p1_);
  static lucent::Ref<C_Derived> create(double p0_, lucent::Opt<lucent::String> p1_);
  bool lucentJson_(lucent::JsonWriter& w, bool toJson) override;
};

inline bool C_Derived::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "a", this->a);
  lucent::jsonField(w, first, "b", this->b);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("b")
#pragma pop_macro("a")
