/**
 * Embeds every `packages/*\/native/*` file into a generated TypeScript module.
 *
 * Hand-written Swift, Kotlin and build files live in `native/` as real source
 * so editors, formatters and the toolchains can read them. They cannot be read
 * back at runtime, though: `vp pack` bundles the hosts and backends into a
 * single file per integration, and a path relative to `import.meta.url` then
 * points beside the bundle rather than into the package. The compiler could
 * not read them at all — it imports nothing but `oxc-parser` by contract.
 *
 * So the text is embedded at build time instead. `--check` fails when an embed
 * is stale rather than rewriting it; `pnpm verify` runs it that way, so a
 * native edit cannot land without its regenerated module.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const packagesDir = join(root, "packages");

interface Embed {
  readonly pkg: string;
  readonly target: string;
  readonly files: readonly string[];
  readonly source: string;
}

function embedFor(pkg: string): Embed | null {
  const nativeDir = join(packagesDir, pkg, "native");
  if (!existsSync(nativeDir)) return null;
  const files = readdirSync(nativeDir)
    .filter((f) => !f.startsWith("."))
    .toSorted();
  const entries = files.map(
    (file) => `  ${JSON.stringify(file)}: ${JSON.stringify(readFileSync(join(nativeDir, file), "utf8"))},`,
  );
  return {
    pkg,
    target: join(packagesDir, pkg, "src/native-sources.generated.ts"),
    files,
    source: `// Generated by scripts/embed-native.ts from packages/${pkg}/native. Do not edit.

/** Hand-written native source, embedded so it survives bundling. */
export const NATIVE_SOURCES: Readonly<Record<string, string>> = {
${entries.join("\n")}
};

export function nativeSource(file: string): string {
  const source = NATIVE_SOURCES[file];
  if (source === undefined) throw new Error(\`Unknown native source \${file} in ${pkg}\`);
  return source;
}
`,
  };
}

const embeds = readdirSync(packagesDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => embedFor(entry.name))
  .filter((embed): embed is Embed => embed !== null);

const readIfPresent = (path: string): string | null => {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return null;
  }
};

if (process.argv.includes("--check")) {
  const stale = embeds.filter((embed) => readIfPresent(embed.target) !== embed.source);
  if (stale.length > 0) {
    console.error(
      `Stale native embeds:\n${stale.map((embed) => `  ${embed.target}`).join("\n")}\n` +
        "Run `pnpm embed:native` and commit the result alongside the native change.",
    );
    process.exit(1);
  }
  console.log(`✓ native embeds match (${embeds.map((e) => `${e.pkg}: ${e.files.length}`).join(", ")})`);
} else {
  for (const embed of embeds) writeFileSync(embed.target, embed.source);
  console.log(`✓ embedded ${embeds.map((e) => `${e.pkg}: ${e.files.length}`).join(", ")}`);
}
