/**
 * Generates packages/runtime/cpp/lucent/unicode_data.inc from the Unicode
 * data in Node's ICU: root-locale case mappings (including the special
 * casings that change length), the Cased and Case_Ignorable properties used
 * by the final sigma rule, and base letters and accents for the fallback
 * collator used where no platform collator exists.
 *
 *   tsx scripts/gen-unicode.ts
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "packages/runtime/cpp/lucent/unicode_data.inc");

const units = (s: string) => [...s].flatMap((ch) => {
  const cp = ch.codePointAt(0)!;
  if (cp < 0x10000) return [cp];
  const v = cp - 0x10000;
  return [0xd800 + (v >> 10), 0xdc00 + (v & 0x3ff)];
});
const hex = (n: number) => `0x${n.toString(16).toUpperCase()}`;

function isScalar(cp: number) {
  return cp < 0xd800 || cp > 0xdfff;
}

function caseTable(map: (s: string) => string) {
  const rows: string[] = [];
  let maxUnits = 0;
  for (let cp = 0; cp <= 0x10ffff; cp++) {
    if (!isScalar(cp)) continue;
    const s = String.fromCodePoint(cp);
    const m = map(s);
    if (m === s) continue;
    const u = units(m);
    maxUnits = Math.max(maxUnits, u.length);
    rows.push(`    {${hex(cp)}, ${u.length}, {${u.map(hex).join(", ")}}},`);
  }
  if (maxUnits > 3) throw new Error(`a mapping needs ${maxUnits} UTF-16 units`);
  return rows;
}

function ranges(re: RegExp) {
  const out: [number, number][] = [];
  for (let cp = 0; cp <= 0x10ffff; cp++) {
    if (!isScalar(cp) || !re.test(String.fromCodePoint(cp))) continue;
    const last = out[out.length - 1];
    if (last && last[1] === cp - 1) last[1] = cp;
    else out.push([cp, cp]);
  }
  return out.map(([a, b]) => `    {${hex(a)}, ${hex(b)}},`);
}

// Fallback collation: letters of the Latin, Greek and Cyrillic blocks whose
// canonical decomposition is a base letter plus an accent.
function collationTable() {
  const rows: string[] = [];
  const mark = /\p{M}/u;
  for (let cp = 0x80; cp < 0x530; cp++) {
    const nfd = String.fromCodePoint(cp).normalize("NFD");
    const chars = [...nfd];
    if (chars.length < 2 || mark.test(chars[0]!) || !chars.slice(1).every((c) => mark.test(c))) continue;
    const base = chars[0]!.codePointAt(0)!;
    const accent = chars[1]!.codePointAt(0)!;
    rows.push(`    {${hex(cp)}, ${hex(base)}, ${hex(accent)}},`);
  }
  return rows;
}

const upper = caseTable((s) => s.toUpperCase());
const lower = caseTable((s) => s.toLowerCase());
const text = `// Generated by scripts/gen-unicode.ts from Node ${process.version} (ICU ${process.versions.icu}, Unicode ${process.versions.unicode}). Do not edit.
// Included by jsstring.cpp.

struct CaseMapping {
  uint32_t cp;
  uint8_t length;
  char16_t units[3];
};

struct CodePointRange {
  uint32_t first;
  uint32_t last;
};

struct Decomposition {
  char16_t cp;
  char16_t base;
  char16_t accent;
};

const CaseMapping kUpperCase[] = {
${upper.join("\n")}
};

const CaseMapping kLowerCase[] = {
${lower.join("\n")}
};

const CodePointRange kCased[] = {
${ranges(/\p{Cased}/u).join("\n")}
};

const CodePointRange kCaseIgnorable[] = {
${ranges(/\p{Case_Ignorable}/u).join("\n")}
};

const Decomposition kDecompositions[] = {
${collationTable().join("\n")}
};
`;
fs.writeFileSync(out, text);
console.log(`✓ ${path.relative(root, out)}: ${upper.length} upper, ${lower.length} lower mappings`);
