/**
 * Build the shipped bundles and load each one.
 *
 * `vp pack` flattens the hosts, backends and compiler into one file per
 * integration, which is what Metro and the `lucent` bin actually run. Loading
 * a bundle exercises everything a package does at import time, and that is
 * where this breaks: a path resolved from `import.meta.url` points beside the
 * bundle rather than into the package it came from, so anything read at
 * runtime is simply absent. The test suite never sees it, because tests import
 * the TypeScript sources in place.
 */
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

execFileSync("pnpm", ["build:packages"], { cwd: root, stdio: "pipe", timeout: 300000 });

/** Every bundle `vp pack` produces, with the entry Metro or the bin loads. */
const bundles = [
  "packages/cli/dist/main.cjs",
  "packages/expo/dist/plugin.cjs",
  "packages/metro/dist/index.cjs",
  "packages/metro/dist/transformer.cjs",
];

for (const bundle of bundles) {
  const path = join(root, bundle);
  if (!existsSync(path)) throw new Error(`${bundle} was not built`);
  // A child process so one bundle's module-level work cannot mask another's.
  execFileSync(process.execPath, ["-e", `require(${JSON.stringify(path)})`], { stdio: "pipe", timeout: 60000 });
  console.log(`✓ loads  ${bundle}`);
}

const version = execFileSync(process.execPath, [join(root, "packages/cli/dist/main.cjs"), "--version"], {
  encoding: "utf8",
  timeout: 60000,
});
// The compiler version keys the build cache, so a bundle reporting the wrong
// one would serve output generated by a different compiler.
const expected = (
  JSON.parse(
    execFileSync("node", ["-p", "JSON.stringify(require('./packages/compiler/package.json'))"], {
      cwd: root,
      encoding: "utf8",
    }),
  ) as { version: string }
).version;
if (!version.includes(`compiler ${expected}`))
  throw new Error(`Bundled CLI reports ${version.trim()}, expected compiler ${expected}`);
console.log(`✓ version  compiler ${expected}`);
