/**
 * Keeps the website honest about the compiler:
 *   1. regenerates apps/website/src/generated/ (the homepage's C++ sample,
 *      compiled from its source, and the diagnostic code table);
 *   2. compiles every `*.lucent.ts` sample on the docs pages:
 *      a page's samples together, as one app; samples with
 *      `expect` on their own, which must fail with that code;
 *   3. checks that every retired docs slug redirects to a page that exists.
 *
 *   tsx scripts/website.ts           regenerate, then check
 *   tsx scripts/website.ts --check   fail if generated files are stale (CI)
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile, type Diagnostic, Explanations, formatDiagnostic } from "../packages/compiler/src/index.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const website = path.join(root, "apps/website/src");
const generatedDir = path.join(website, "generated");
const check = process.argv.includes("--check");
const problems: string[] = [];

type Sample = { filename: string; code: string; expect?: string };

// Samples stay in memory, but TypeScript resolves imports only in directories that exist.
const samplesRoot = fs.mkdtempSync(path.join(os.tmpdir(), "lucent-website-"));
process.on("exit", () => fs.rmSync(samplesRoot, { recursive: true, force: true }));

/** Compiles in-memory sources as if they were an app's src/ folder. */
function compileSamples(app: string, samples: Sample[]): { diagnostics: Diagnostic[]; files: Map<string, string> } {
  const dir = path.join(samplesRoot, app, "src");
  fs.mkdirSync(dir, { recursive: true });
  const sources = new Map(samples.map((s) => [path.join(dir, s.filename), s.code]));
  const result = compile([...sources.keys()], { readSource: (f) => sources.get(f) });
  return { diagnostics: result.diagnostics.map((d) => ({ ...d, file: d.file && path.relative(dir, d.file) })), files: result.files };
}

// 1. Generated sources.
const demoSource = `export type Point = { x: number; y: number };

export function squaredDistance(a: Point, b: Point): number {
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  return dx * dx + dy * dy;
}
`;
const demo = compileSamples("home", [{ filename: "geo.lucent.ts", code: demoSource }]);
const demoCpp = demo.files.get("m_geo.cpp");
if (!demoCpp) throw new Error(`the homepage sample does not compile:\n${demo.diagnostics.map(formatDiagnostic).join("\n")}`);
// The function as the compiler wrote it, minus the #line directives that map it back to the source.
const fn = demoCpp.slice(demoCpp.indexOf("double m_geo::squaredDistance"), demoCpp.indexOf("\n}\n") + 2);
const cpp = fn
  .split("\n")
  .filter((line) => !line.startsWith("#line"))
  .join("\n");

const header = "// Generated by scripts/website.ts. Do not edit.\n\n";
const generated: Record<string, string> = {
  "compiler-demo.ts": `${header}export const demoSource = ${JSON.stringify(demoSource.trimEnd())};\n\nexport const demoCpp = ${JSON.stringify(cpp)};\n`,
  // The same explanations as `lucent explain`; their examples are checked by the compiler's tests.
  "diagnostics.ts": `${header}export const explanations: { code: string; title: string; summary: string; details: string; fix: string; wrong: Record<string, string>; right: Record<string, string> }[] = ${JSON.stringify(
    Object.entries(Explanations).map(([code, { title, summary, details, fix, wrong, right }]) => ({ code, title, summary, details, fix, wrong, right })),
    null,
    2,
  )};\n`,
};
fs.mkdirSync(generatedDir, { recursive: true });
for (const [name, content] of Object.entries(generated)) {
  const file = path.join(generatedDir, name);
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : undefined;
  if (current === content) continue;
  if (check) problems.push(`apps/website/src/generated/${name} is stale: run \`pnpm exec tsx scripts/website.ts\``);
  else fs.writeFileSync(file, content);
}

// 2. Samples. Pages are plain data (see apps/website/src/docs/types.ts).
const { docsGroups } = await import("../apps/website/src/docs/nav.ts");
const { docsRedirects } = await import("../apps/website/src/docs/redirects.ts");
type Block = (typeof docsGroups)[number]["pages"][number]["blocks"][number];

function samplesOf(blocks: Block[]): Sample[] {
  return blocks.flatMap((b): Sample[] => {
    if (b.kind === "code") return b.filename.endsWith(".lucent.ts") ? [b] : [];
    if (b.kind === "tabs") return b.tabs.filter((t) => t.filename.endsWith(".lucent.ts"));
    if (b.kind === "steps") return b.steps.flatMap((s) => samplesOf(s.blocks));
    return [];
  });
}

let checked = 0;
for (const page of docsGroups.flatMap((g) => g.pages)) {
  const where = `/docs/${page.slug}${page.slug ? "/" : ""}`;
  const samples = samplesOf(page.blocks);
  const app = samples.filter((s) => !s.expect);
  const names = app.map((s) => s.filename);
  for (const dup of new Set(names.filter((n, i) => names.indexOf(n) !== i))) {
    problems.push(`${where}: two samples are named ${dup}; a page's samples form one app`);
  }
  if (app.length) {
    const { diagnostics } = compileSamples(page.slug || "index", app);
    for (const d of diagnostics) problems.push(`${where}: ${formatDiagnostic(d)}`);
  }
  for (const s of samples.filter((x) => x.expect)) {
    const { diagnostics } = compileSamples(`${page.slug}-expect`, [s]);
    if (!diagnostics.some((d) => d.code === s.expect)) {
      const got = diagnostics.length ? diagnostics.map(formatDiagnostic).join("; ") : "it compiled";
      problems.push(`${where}: ${s.filename} should fail with ${s.expect}, but ${got}`);
    }
  }
  checked += samples.length;
}

// 3. Redirects.
const slugs = new Set(docsGroups.flatMap((g) => g.pages.map((p) => p.slug)));
for (const [from, to] of Object.entries(docsRedirects)) {
  if (slugs.has(from)) problems.push(`redirect from /docs/${from}/ shadows a page`);
  if (!slugs.has(to)) problems.push(`redirect /docs/${from}/ → /docs/${to}/: no such page`);
}

if (problems.length) {
  console.error(problems.map((p) => `✗ ${p}`).join("\n"));
  process.exit(1);
}
console.log(`✓ website: ${checked} Lucent samples compile, ${Object.keys(docsRedirects).length} redirects resolve, generated files ${check ? "up to date" : "written"}`);
