/**
 * Keeps the website honest about the compiler and its own rules:
 *   1. regenerates apps/website/src/generated/: the homepage's C++ sample,
 *      the CLI and diagnostics references, and the docs route tree;
 *   2. checks the docs' structure: page files match the nav, each page has
 *      its "Next" link, retired slugs redirect to pages that exist;
 *   3. compiles every `*.lucent.ts` sample on the docs pages;
 *   4. checks internal links and their anchors, and each page's length
 *      budget (words and lines of code, by kind of page);
 *   5. writes each page's prose as Markdown to apps/website/.prose/ and runs
 *      Vale on it (apps/website/CONTRIBUTING-DOCS.md has the rules).
 *
 *   tsx scripts/website.ts           regenerate, then check
 *   tsx scripts/website.ts --check   fail if generated files are stale, or Vale is missing (CI)
 */
import fs from "node:fs";
import path from "node:path";
import { root, websiteSrc } from "./website/context.ts";
import { checkBudgets } from "./website/budget.ts";
import { generatedFiles } from "./website/generated.ts";
import { checkLinks } from "./website/links.ts";
import { checkStructure, loadPages } from "./website/pages.ts";
import { checkProse } from "./website/prose.ts";
import { checkSamples } from "./website/samples.ts";

const check = process.argv.includes("--check");
const problems: string[] = [];

const generatedDir = path.join(websiteSrc, "generated");

/** Writes a generated file, or with --check reports it as stale. */
function write(name: string, content: string): void {
  const file = path.join(generatedDir, name);
  if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === content) return;
  if (check) problems.push(`apps/website/src/generated/${name} is stale: run \`pnpm exec tsx scripts/website.ts\``);
  else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }
}

// Generated files first: pages import some of them.
const generated: Record<string, string> = generatedFiles();
for (const [name, content] of Object.entries(generated)) write(name, content);

// The JSON schemas, served where their $id says (https://lucent-lang.dev/schemas/…).
const schemasDir = path.join(root, "packages/lucent/schemas");
const publicSchemas = path.join(root, "apps/website/public/schemas");
fs.mkdirSync(publicSchemas, { recursive: true });
for (const name of fs.readdirSync(schemasDir)) {
  const content = fs.readFileSync(path.join(schemasDir, name), "utf8");
  const file = path.join(publicSchemas, name);
  if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === content) continue;
  if (check) problems.push(`apps/website/public/schemas/${name} is stale: run \`pnpm exec tsx scripts/website.ts\``);
  else fs.writeFileSync(file, content);
}

const pages = await loadPages();
problems.push(...checkStructure(pages));
const samples = checkSamples(pages);
problems.push(...samples.problems);

// The C++ of each page's `cpp` samples, then stale files out.
for (const [slug, cpp] of samples.cpp) {
  const name = `cpp/${slug || "index"}.ts`;
  generated[name] = `// Generated by scripts/website.ts from the samples of /docs/${slug}. Do not edit.\n\nimport type { CppFile } from "${"../".repeat((slug || "index").split("/").length + 1)}docs/types";\n\nexport const cpp: Record<string, CppFile[]> = ${JSON.stringify(cpp, null, 2)};\n`;
  write(name, generated[name]!);
}
const unbuilt = new Set([...samples.unbuilt.keys()].map((slug) => `cpp/${slug || "index"}.ts`));
for (const [slug, platforms] of samples.unbuilt) console.warn(`! /docs/${slug}/: its C++ is not rebuilt here, without the ${platforms.join(" and ")} SDK`);
const existing = fs.readdirSync(generatedDir, { recursive: true, encoding: "utf8" }).filter((f) => f.endsWith(".ts")).map((f) => f.split(path.sep).join("/"));
for (const name of existing.filter((f) => !(f in generated) && !unbuilt.has(f))) {
  if (check) problems.push(`apps/website/src/generated/${name} is stale: run \`pnpm exec tsx scripts/website.ts\``);
  else fs.rmSync(path.join(generatedDir, name));
}

problems.push(...checkLinks(pages));
problems.push(...checkBudgets(pages));
const prose = checkProse(pages, check);
problems.push(...prose.problems);

for (const warning of prose.warnings) console.warn(`! ${warning}`);
if (problems.length) {
  console.error(problems.map((p) => `✗ ${p}`).join("\n"));
  process.exit(1);
}
console.log(
  `✓ website: ${pages.length} pages, ${samples.checked} Lucent samples compile, links resolve, ${prose.ran ? "prose checked" : "prose not checked"}, generated files ${check ? "up to date" : "written"}`,
);
