// Generated by Lucent from union-generics.lucent.ts. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("A")
#undef A
#pragma push_macro("B")
#undef B
#pragma push_macro("T")
#undef T
#pragma push_macro("absent")
#undef absent
#pragma push_macro("comparisons")
#undef comparisons
#pragma push_macro("firstOf")
#undef firstOf
#pragma push_macro("members")
#undef members
#pragma push_macro("optionals")
#undef optionals
#pragma push_macro("orNull")
#undef orNull
#pragma push_macro("pick")
#undef pick
#pragma push_macro("same")
#undef same
#pragma push_macro("show")
#undef show

namespace lucent_app {

namespace m_union_u2d_generics {

template <class A, class B>
std::variant<A, B> pick(bool p0_, A p1_, B p2_);

template <class A, class B>
lucent::String show(std::variant<A, B> p0_);

template <class A, class B>
bool same(A p0_, std::variant<A, B> p1_);

template <class T>
lucent::String orNull(lucent::Opt<T> p0_);

template <class T>
lucent::Opt<T> firstOf(lucent::Array<T> p0_);

lucent::String members();
lucent::String comparisons();
lucent::String optionals();
lucent::String absent(bool p0_);
void init();

}  // namespace m_union_u2d_generics

namespace m_union_u2d_generics {

template <class A, class B>
std::variant<A, B> pick(bool p0_, A p1_, B p2_) {
  std::variant<A, B> v5_{};
  if (p0_) {
    v5_ = std::variant<A, B>(p1_);
  } else {
    v5_ = std::variant<A, B>(p2_);
  }
  return v5_;
}

}  // namespace m_union_u2d_generics

namespace m_union_u2d_generics {

template <class A, class B>
lucent::String show(std::variant<A, B> p0_) {
  lucent::String v1_ = lucent::typeOf(p0_);
  lucent::String v3_ = lucent::toJsString(p0_);
  return lucent::concat(v1_, LUCENT_STR(":"), v3_);
}

}  // namespace m_union_u2d_generics

namespace m_union_u2d_generics {

template <class A, class B>
bool same(A p0_, std::variant<A, B> p1_) {
  return lucent::strictEquals(p0_, p1_);
}

}  // namespace m_union_u2d_generics

namespace m_union_u2d_generics {

template <class T>
lucent::String orNull(lucent::Opt<T> p0_) {
  bool v2_ = lucent::strictEquals(p0_, lucent::null);
  lucent::String v5_{};
  if (v2_) {
    v5_ = LUCENT_STR("null");
  } else {
    v5_ = lucent::toJsString(p0_);
  }
  return v5_;
}

}  // namespace m_union_u2d_generics

namespace m_union_u2d_generics {

template <class T>
lucent::Opt<T> firstOf(lucent::Array<T> p0_) {
  return p0_.getIndex(static_cast<int64_t>(0));
}

}  // namespace m_union_u2d_generics

}  // namespace lucent_app

#pragma pop_macro("show")
#pragma pop_macro("same")
#pragma pop_macro("pick")
#pragma pop_macro("orNull")
#pragma pop_macro("optionals")
#pragma pop_macro("members")
#pragma pop_macro("firstOf")
#pragma pop_macro("comparisons")
#pragma pop_macro("absent")
#pragma pop_macro("T")
#pragma pop_macro("B")
#pragma pop_macro("A")
