// Generated by Lucent from union-generics.lucent.ts. Do not edit.
#include "m_union_u2d_generics.h"

#pragma push_macro("absent")
#undef absent
#pragma push_macro("b")
#undef b
#pragma push_macro("comparisons")
#undef comparisons
#pragma push_macro("empty")
#undef empty
#pragma push_macro("firstOf")
#undef firstOf
#pragma push_macro("members")
#undef members
#pragma push_macro("n")
#undef n
#pragma push_macro("nothing")
#undef nothing
#pragma push_macro("optionals")
#undef optionals
#pragma push_macro("orNull")
#undef orNull
#pragma push_macro("pick")
#undef pick
#pragma push_macro("s")
#undef s
#pragma push_macro("same")
#undef same
#pragma push_macro("show")
#undef show

namespace lucent_app {

lucent::String m_union_u2d_generics::members() {
  std::variant<double, lucent::String> n = lucent_app::m_union_u2d_generics::pick<double, lucent::String>(true, 1.0, LUCENT_STR("a"));
  std::variant<double, lucent::String> s = lucent::convert<std::variant<double, lucent::String>>(lucent_app::m_union_u2d_generics::pick<lucent::String, double>(false, LUCENT_STR("a"), 2.0));
  std::variant<bool, lucent::String> b = lucent_app::m_union_u2d_generics::pick<bool, lucent::String>(false, true, LUCENT_STR("b"));
  lucent::String v16_ = lucent_app::m_union_u2d_generics::show<double, lucent::String>(std::variant<double, lucent::String>(3.0));
  lucent::String v18_ = lucent_app::m_union_u2d_generics::show<lucent::String, double>(std::variant<lucent::String, double>(LUCENT_STR("x")));
  lucent::String v20_ = lucent_app::m_union_u2d_generics::show<bool, double>(std::variant<bool, double>(4.0));
  lucent::Array<std::variant<bool, double, lucent::String>> v21_ = lucent::Array<std::variant<bool, double, lucent::String>>{lucent::convert<std::variant<bool, double, lucent::String>>(n), lucent::convert<std::variant<bool, double, lucent::String>>(s), lucent::convert<std::variant<bool, double, lucent::String>>(b), std::variant<bool, double, lucent::String>(v16_), std::variant<bool, double, lucent::String>(v18_), std::variant<bool, double, lucent::String>(v20_)};
  return v21_.join(LUCENT_STR(" "));
}

lucent::String m_union_u2d_generics::comparisons() {
  bool v2_ = lucent_app::m_union_u2d_generics::same<double, lucent::String>(1.0, std::variant<double, lucent::String>(1.0));
  bool v5_ = lucent_app::m_union_u2d_generics::same<lucent::String, double>(LUCENT_STR("a"), std::variant<lucent::String, double>(1.0));
  bool v8_ = lucent_app::m_union_u2d_generics::same<lucent::String, double>(LUCENT_STR("a"), std::variant<lucent::String, double>(LUCENT_STR("a")));
  lucent::Array<bool> v9_ = lucent::Array<bool>{v2_, v5_, v8_};
  return v9_.join(LUCENT_STR(" "));
}

lucent::String m_union_u2d_generics::optionals() {
  lucent::Array<double> empty = lucent::Array<double>{};
  lucent::String v2_ = lucent_app::m_union_u2d_generics::orNull<double>(lucent::Opt<double>(1.0));
  lucent::String v4_ = lucent_app::m_union_u2d_generics::orNull<lucent::String>(lucent::Opt<lucent::String>(lucent::null));
  lucent::Array<double> v6_ = lucent::Array<double>{5.0};
  lucent::Opt<double> v7_ = lucent_app::m_union_u2d_generics::firstOf<double>(v6_);
  lucent::Opt<double> v9_ = lucent_app::m_union_u2d_generics::firstOf<double>(empty);
  lucent::Array<lucent::String> v11_ = lucent::Array<lucent::String>{LUCENT_STR("x")};
  lucent::Opt<lucent::String> v12_ = lucent_app::m_union_u2d_generics::firstOf<lucent::String>(v11_);
  lucent::Array<lucent::Opt<std::variant<double, lucent::String>>> v13_ = lucent::Array<lucent::Opt<std::variant<double, lucent::String>>>{lucent::Opt<std::variant<double, lucent::String>>(std::variant<double, lucent::String>(v2_)), lucent::Opt<std::variant<double, lucent::String>>(std::variant<double, lucent::String>(v4_)), lucent::convert<lucent::Opt<std::variant<double, lucent::String>>>(v7_), lucent::convert<lucent::Opt<std::variant<double, lucent::String>>>(v9_), lucent::convert<lucent::Opt<std::variant<double, lucent::String>>>(v12_)};
  return v13_.join(LUCENT_STR(" "));
}

lucent::String m_union_u2d_generics::absent(bool p0_) {
  lucent::Opt<lucent::Undefined> v5_{};
  if (p0_) {
    v5_ = lucent::Opt<lucent::Undefined>(lucent::null);
  } else {
    v5_ = lucent::Opt<lucent::Undefined>(lucent::undefined);
  }
  lucent::Opt<lucent::Undefined> nothing = v5_;
  bool v8_ = lucent::strictEquals(nothing, lucent::null);
  bool v11_ = lucent::strictEquals(nothing, lucent::undefined);
  bool v14_ = !nothing.has();
  lucent::String v16_ = lucent::toJsString(nothing);
  lucent::Array<std::variant<bool, lucent::String>> v17_ = lucent::Array<std::variant<bool, lucent::String>>{std::variant<bool, lucent::String>(v8_), std::variant<bool, lucent::String>(v11_), std::variant<bool, lucent::String>(v14_), std::variant<bool, lucent::String>(v16_)};
  return v17_.join(LUCENT_STR(" "));
}

void m_union_u2d_generics::init() {
}

}  // namespace lucent_app

#pragma pop_macro("show")
#pragma pop_macro("same")
#pragma pop_macro("s")
#pragma pop_macro("pick")
#pragma pop_macro("orNull")
#pragma pop_macro("optionals")
#pragma pop_macro("nothing")
#pragma pop_macro("n")
#pragma pop_macro("members")
#pragma pop_macro("firstOf")
#pragma pop_macro("empty")
#pragma pop_macro("comparisons")
#pragma pop_macro("b")
#pragma pop_macro("absent")
