// Generated by Lucent. Do not edit.
#include "m_iterable_u2d_spread.h"
#include <lucent/jsi/convert.h>
#include <lucent/jsi/host.h>

#pragma push_macro("chars")
#undef chars
#pragma push_macro("counted")
#undef counted
#pragma push_macro("entries")
#undef entries
#pragma push_macro("keysAndValues")
#undef keysAndValues
#pragma push_macro("merged")
#undef merged
#pragma push_macro("mixed")
#undef mixed
#pragma push_macro("r_union_")
#undef r_union_
#pragma push_macro("unique")
#undef unique
#pragma push_macro("withEntry")
#undef withEntry
#pragma push_macro("x")
#undef x

namespace lucent::js {

template <>
struct Convert<std::variant<double, lucent::String>> {
  static std::variant<double, lucent::String> fromJs(jsi::Runtime& rt, const jsi::Value& v, const Path& p);
  static jsi::Value toJs(jsi::Runtime& rt, Host& h, const std::variant<double, lucent::String>& v);
};

jsi::Value errorInstanceToJs(jsi::Runtime& rt, Host& h, const Error& v) {
  return jsi::Value::undefined();
}

inline std::variant<double, lucent::String> Convert<std::variant<double, lucent::String>>::fromJs(jsi::Runtime& rt, const jsi::Value& v, const Path& p) {
  if (v.isNumber()) {
    return std::variant<double, lucent::String>(Convert<double>::fromJs(rt, v, p));
  }
  if (v.isString()) {
    return std::variant<double, lucent::String>(Convert<lucent::String>::fromJs(rt, v, p));
  }
  throwBoundaryError(rt, p, "a number or a string", v);
}

inline jsi::Value Convert<std::variant<double, lucent::String>>::toJs(jsi::Runtime& rt, Host& h, const std::variant<double, lucent::String>& v) {
  return std::visit([&](const auto& x) -> jsi::Value {
    return Convert<std::decay_t<decltype(x)>>::toJs(rt, h, x);
  }, v);
}

}  // namespace lucent::js

namespace {

using namespace lucent::js;

void install_m_iterable_u2d_spread(jsi::Runtime& rt, Host& host, jsi::Object& exports) {
  defineFunction(rt, exports, "entries", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("entries", "packages/compiler/test/e2e/cases/iterable-spread.lucent.ts", 6), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Map<lucent::String, double>>::fromJs(rt, arg(args, count, 0), Path{"entries", "argument 'm'"});
      return Convert<lucent::Array<std::tuple<lucent::String, double>>>::toJs(rt, host, lucent_app::m_iterable_u2d_spread::entries(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "withEntry", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("withEntry", "packages/compiler/test/e2e/cases/iterable-spread.lucent.ts", 10), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Map<lucent::String, double>>::fromJs(rt, arg(args, count, 0), Path{"withEntry", "argument 'm'"});
      return Convert<lucent::Array<std::tuple<lucent::String, double>>>::toJs(rt, host, lucent_app::m_iterable_u2d_spread::withEntry(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "keysAndValues", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("keysAndValues", "packages/compiler/test/e2e/cases/iterable-spread.lucent.ts", 14), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Map<lucent::String, double>>::fromJs(rt, arg(args, count, 0), Path{"keysAndValues", "argument 'm'"});
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_iterable_u2d_spread::keysAndValues(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "merged", 2, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("merged", "packages/compiler/test/e2e/cases/iterable-spread.lucent.ts", 23), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Map<lucent::String, double>>::fromJs(rt, arg(args, count, 0), Path{"merged", "argument 'a'"});
      auto a1 = Convert<lucent::Map<lucent::String, double>>::fromJs(rt, arg(args, count, 1), Path{"merged", "argument 'b'"});
      return Convert<lucent::Array<std::tuple<lucent::String, double>>>::toJs(rt, host, lucent_app::m_iterable_u2d_spread::merged(std::move(a0), std::move(a1)));
    });
  });
  defineFunction(rt, exports, "unique", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("unique", "packages/compiler/test/e2e/cases/iterable-spread.lucent.ts", 27), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Array<double>>::fromJs(rt, arg(args, count, 0), Path{"unique", "argument 'xs'"});
      return Convert<lucent::Array<double>>::toJs(rt, host, lucent_app::m_iterable_u2d_spread::unique(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "union", 2, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("union", "packages/compiler/test/e2e/cases/iterable-spread.lucent.ts", 31), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Set<double>>::fromJs(rt, arg(args, count, 0), Path{"union", "argument 'a'"});
      auto a1 = Convert<lucent::Set<double>>::fromJs(rt, arg(args, count, 1), Path{"union", "argument 'b'"});
      return Convert<lucent::Array<double>>::toJs(rt, host, lucent_app::m_iterable_u2d_spread::r_union_(std::move(a0), std::move(a1)));
    });
  });
  defineFunction(rt, exports, "mixed", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("mixed", "packages/compiler/test/e2e/cases/iterable-spread.lucent.ts", 36), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Set<double>>::fromJs(rt, arg(args, count, 0), Path{"mixed", "argument 's'"});
      return Convert<lucent::Array<std::variant<double, lucent::String>>>::toJs(rt, host, lucent_app::m_iterable_u2d_spread::mixed(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "chars", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("chars", "packages/compiler/test/e2e/cases/iterable-spread.lucent.ts", 40), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::String>::fromJs(rt, arg(args, count, 0), Path{"chars", "argument 's'"});
      return Convert<lucent::Array<lucent::String>>::toJs(rt, host, lucent_app::m_iterable_u2d_spread::chars(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "counted", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("counted", "packages/compiler/test/e2e/cases/iterable-spread.lucent.ts", 48), [&]() -> jsi::Value {
      auto a0 = Convert<double>::fromJs(rt, arg(args, count, 0), Path{"counted", "argument 'n'"});
      return Convert<lucent::Array<double>>::toJs(rt, host, lucent_app::m_iterable_u2d_spread::counted(std::move(a0)));
    });
  });
}

const ModuleDef kModules[] = {{"iterable-spread", install_m_iterable_u2d_spread}};

}  // namespace

namespace lucent::js {

const ModuleDef* registeredModules(size_t& count) {
  count = 1;
  return kModules;
}

void resetModuleState() {
  lucent_app::m_iterable_u2d_spread::init();
}

}  // namespace lucent::js

#pragma pop_macro("x")
#pragma pop_macro("withEntry")
#pragma pop_macro("unique")
#pragma pop_macro("r_union_")
#pragma pop_macro("mixed")
#pragma pop_macro("merged")
#pragma pop_macro("keysAndValues")
#pragma pop_macro("entries")
#pragma pop_macro("counted")
#pragma pop_macro("chars")
