// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_S_Point.h"

#pragma push_macro("first")
#undef first
#pragma push_macro("load")
#undef load
#pragma push_macro("loads")
#undef loads
#pragma push_macro("point")
#undef point
#pragma push_macro("read")
#undef read
#pragma push_macro("total")
#undef total
#pragma push_macro("w")
#undef w

namespace lucent_app {

struct C_Cache : lucent::Object {
  lucent::Promise<lucent::Ref<lucent_app::S_Point>> point{};
  lucent::Opt<lucent::Promise<double>> total{};
  double loads{};
  void construct(double p0_);
  static lucent::Ref<C_Cache> create(double p0_);
  lucent::Promise<lucent::Ref<lucent_app::S_Point>> load(double p0_);
  lucent::Promise<double> read();
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_Cache::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "point", this->point);
  lucent::jsonField(w, first, "total", this->total);
  lucent::jsonField(w, first, "loads", this->loads);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("w")
#pragma pop_macro("total")
#pragma pop_macro("read")
#pragma pop_macro("point")
#pragma pop_macro("loads")
#pragma pop_macro("load")
#pragma pop_macro("first")
