// Generated by Lucent. Do not edit.
#pragma once
#include <lucent/lucent.h>

#pragma push_macro("a")
#undef a
#pragma push_macro("n")
#undef n
#pragma push_macro("v")
#undef v

namespace lucent_app {

inline lucent::Actor& actor_0() {
  static lucent::Actor& a = lucent::Actor::create("reduce-operands");
  return a;
}

struct S_Object1;

struct S_Object1 : lucent::Object {
  double n{};
};

void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object1>& v);

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object1>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "n", v->n);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("v")
#pragma pop_macro("n")
#pragma pop_macro("a")
