// Generated by Lucent. Do not edit.
#include <lucent/jsi/host.h>

static_assert(lucent::js::kRuntimeAbi == 2, "generated for Lucent runtime ABI 2: build it with the runtime lucent build copied next to it");

namespace {

const lucent::js::ModuleIdentity kModuleIdentities[] = {{"nullish-generics", "72e9181da85eb156"}};

}  // namespace

namespace lucent::js {

const BuildIdentity& buildIdentity() {
  static const BuildIdentity identity = {"all", "beb78bef294d7451", kModuleIdentities, 1};
  return identity;
}

}  // namespace lucent::js
