// Generated by Lucent from nullish-generics.lucent.ts. Do not edit.
#include "m_nullish_u2d_generics.h"

#pragma push_macro("a")
#undef a
#pragma push_macro("b")
#undef b
#pragma push_macro("c")
#undef c
#pragma push_macro("defaults")
#undef defaults
#pragma push_macro("e")
#undef e
#pragma push_macro("f")
#undef f
#pragma push_macro("fill")
#undef fill
#pragma push_macro("g")
#undef g
#pragma push_macro("orDefault")
#undef orDefault
#pragma push_macro("present")
#undef present
#pragma push_macro("presentString")
#undef presentString
#pragma push_macro("ran")
#undef ran
#pragma push_macro("t")
#undef t
#pragma push_macro("x")
#undef x

namespace lucent_app {

lucent::String m_nullish_u2d_generics::defaults() {
  lucent::Opt<double> a = lucent_app::m_nullish_u2d_generics::orDefault<lucent::Opt<double>>(lucent::Opt<double>(lucent::undefined), lucent::Opt<double>(7.0));
  lucent::Opt<double> b = lucent_app::m_nullish_u2d_generics::orDefault<lucent::Opt<double>>(lucent::Opt<double>(3.0), lucent::Opt<double>(7.0));
  lucent::Opt<lucent::String> c = lucent_app::m_nullish_u2d_generics::orDefault<lucent::Opt<lucent::String>>(lucent::Opt<lucent::String>(lucent::null), lucent::Opt<lucent::String>(LUCENT_STR("d")));
  double e = lucent_app::m_nullish_u2d_generics::orDefault<double>(0.0, 9.0);
  lucent::Opt<double> f = lucent_app::m_nullish_u2d_generics::fill<lucent::Opt<double>>(lucent::Opt<double>(lucent::undefined), lucent::Opt<double>(4.0));
  lucent::Opt<lucent::String> g = lucent_app::m_nullish_u2d_generics::fill<lucent::Opt<lucent::String>>(lucent::Opt<lucent::String>(LUCENT_STR("x")), lucent::Opt<lucent::String>(LUCENT_STR("y")));
  lucent::Array<lucent::Opt<std::variant<double, lucent::String>>> v24_ = lucent::Array<lucent::Opt<std::variant<double, lucent::String>>>{lucent::convert<lucent::Opt<std::variant<double, lucent::String>>>(a), lucent::convert<lucent::Opt<std::variant<double, lucent::String>>>(b), lucent::convert<lucent::Opt<std::variant<double, lucent::String>>>(c), lucent::Opt<std::variant<double, lucent::String>>(std::variant<double, lucent::String>(e)), lucent::convert<lucent::Opt<std::variant<double, lucent::String>>>(f), lucent::convert<lucent::Opt<std::variant<double, lucent::String>>>(g)};
  return v24_.join(LUCENT_STR(","));
}

double m_nullish_u2d_generics::present() {
  double x = 1.0;
  double ran = 0.0;
  double v5_ = x * 10.0;
  return v5_ + ran;
}

lucent::String m_nullish_u2d_generics::presentString(lucent::String p0_) {
  lucent::String t = p0_;
  return t;
}

void m_nullish_u2d_generics::init() {
}

}  // namespace lucent_app

#pragma pop_macro("x")
#pragma pop_macro("t")
#pragma pop_macro("ran")
#pragma pop_macro("presentString")
#pragma pop_macro("present")
#pragma pop_macro("orDefault")
#pragma pop_macro("g")
#pragma pop_macro("fill")
#pragma pop_macro("f")
#pragma pop_macro("e")
#pragma pop_macro("defaults")
#pragma pop_macro("c")
#pragma pop_macro("b")
#pragma pop_macro("a")
