// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_C_Animal.h"

#pragma push_macro("barks")
#undef barks
#pragma push_macro("name")
#undef name

namespace lucent_app {

struct C_Dog;

struct C_Dog : lucent_app::C_Animal {
  bool barks{};
  void construct();
  static lucent::Ref<C_Dog> create();
  bool lucentJson_(lucent::JsonWriter& w, bool toJson) override;
};

inline bool C_Dog::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "name", this->name);
  lucent::jsonField(w, first, "barks", this->barks);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("name")
#pragma pop_macro("barks")
