// Generated by Lucent. Do not edit.
#include "m_using_.h"
#include "lucent_app_C_Resource.h"
#include "lucent_app_C_Tracked.h"
#include <lucent/jsi/convert.h>
#include <lucent/jsi/host.h>

#pragma push_macro("disposeThrows")
#undef disposeThrows
#pragma push_macro("early")
#undef early
#pragma push_macro("inAsync")
#undef inAsync
#pragma push_macro("loop")
#undef loop
#pragma push_macro("nullable")
#undef nullable
#pragma push_macro("r_explicit_")
#undef r_explicit_
#pragma push_macro("scoped")
#undef scoped
#pragma push_macro("suppressed")
#undef suppressed
#pragma push_macro("throwing")
#undef throwing

namespace lucent::js {

jsi::Value errorInstanceToJs(jsi::Runtime& rt, Host& h, const Error& v) {
  return jsi::Value::undefined();
}

}  // namespace lucent::js

namespace {

using namespace lucent::js;

void install_m_using_(jsi::Runtime& rt, Host& host, jsi::Object& exports) {
  defineFunction(rt, exports, "scoped", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("scoped", "packages/compiler/test/e2e/cases/using.lucent.ts", 32), [&]() -> jsi::Value {
      return Convert<lucent::Array<lucent::String>>::toJs(rt, host, lucent_app::m_using_::scoped());
    });
  });
  defineFunction(rt, exports, "early", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("early", "packages/compiler/test/e2e/cases/using.lucent.ts", 49), [&]() -> jsi::Value {
      auto a0 = Convert<bool>::fromJs(rt, arg(args, count, 0), Path{"early", "argument 'stop'"});
      return Convert<lucent::Array<lucent::String>>::toJs(rt, host, lucent_app::m_using_::early(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "throwing", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("throwing", "packages/compiler/test/e2e/cases/using.lucent.ts", 54), [&]() -> jsi::Value {
      return Convert<lucent::Array<lucent::String>>::toJs(rt, host, lucent_app::m_using_::throwing());
    });
  });
  defineFunction(rt, exports, "loop", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("loop", "packages/compiler/test/e2e/cases/using.lucent.ts", 65), [&]() -> jsi::Value {
      return Convert<lucent::Array<lucent::String>>::toJs(rt, host, lucent_app::m_using_::loop());
    });
  });
  defineFunction(rt, exports, "nullable", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("nullable", "packages/compiler/test/e2e/cases/using.lucent.ts", 75), [&]() -> jsi::Value {
      auto a0 = Convert<bool>::fromJs(rt, arg(args, count, 0), Path{"nullable", "argument 'open'"});
      return Convert<lucent::Array<lucent::String>>::toJs(rt, host, lucent_app::m_using_::nullable(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "disposeThrows", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("disposeThrows", "packages/compiler/test/e2e/cases/using.lucent.ts", 83), [&]() -> jsi::Value {
      return Convert<lucent::Array<lucent::String>>::toJs(rt, host, lucent_app::m_using_::disposeThrows());
    });
  });
  defineFunction(rt, exports, "suppressed", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("suppressed", "packages/compiler/test/e2e/cases/using.lucent.ts", 93), [&]() -> jsi::Value {
      return Convert<lucent::Array<lucent::String>>::toJs(rt, host, lucent_app::m_using_::suppressed());
    });
  });
  defineFunction(rt, exports, "inAsync", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, [&]() -> jsi::Value {
      return callAsync<lucent::Array<lucent::String>>(rt, host, LUCENT_TRACE_SITE_AT("inAsync", "packages/compiler/test/e2e/cases/using.lucent.ts", 105), []() {
        return lucent_app::m_using_::inAsync();
      });
    });
  });
  defineFunction(rt, exports, "explicit", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("explicit", "packages/compiler/test/e2e/cases/using.lucent.ts", 114), [&]() -> jsi::Value {
      return Convert<lucent::Array<lucent::String>>::toJs(rt, host, lucent_app::m_using_::r_explicit_());
    });
  });
}

const ModuleDef kModules[] = {{"using", install_m_using_}};

}  // namespace

namespace lucent::js {

const ModuleDef* registeredModules(size_t& count) {
  count = 1;
  return kModules;
}

void resetModuleState() {
  lucent_app::m_using_::init();
}

}  // namespace lucent::js

#pragma pop_macro("throwing")
#pragma pop_macro("suppressed")
#pragma pop_macro("scoped")
#pragma pop_macro("r_explicit_")
#pragma pop_macro("nullable")
#pragma pop_macro("loop")
#pragma pop_macro("inAsync")
#pragma pop_macro("early")
#pragma pop_macro("disposeThrows")
