// Generated by Lucent. Do not edit.
#include "m_numbers.h"
#include <lucent/jsi/convert.h>
#include <lucent/jsi/host.h>

#pragma push_macro("bits")
#undef bits
#pragma push_macro("checks")
#undef checks
#pragma push_macro("fib")
#undef fib
#pragma push_macro("format")
#undef format
#pragma push_macro("heldChecks")
#undef heldChecks
#pragma push_macro("mathFns")
#undef mathFns
#pragma push_macro("multiplyAdd")
#undef multiplyAdd
#pragma push_macro("parse")
#undef parse
#pragma push_macro("parseInts")
#undef parseInts
#pragma push_macro("precision")
#undef precision
#pragma push_macro("special")
#undef special
#pragma push_macro("sum")
#undef sum
#pragma push_macro("v")
#undef v
#pragma push_macro("x")
#undef x

namespace lucent::js {

template <>
struct Convert<std::variant<double, lucent::String>> {
  static std::variant<double, lucent::String> fromJs(jsi::Runtime& rt, const jsi::Value& v, const Path& p);
  static jsi::Value toJs(jsi::Runtime& rt, Host& h, const std::variant<double, lucent::String>& v);
};

template <>
struct Convert<std::variant<lucent::BigInt, double>> {
  static std::variant<lucent::BigInt, double> fromJs(jsi::Runtime& rt, const jsi::Value& v, const Path& p);
  static jsi::Value toJs(jsi::Runtime& rt, Host& h, const std::variant<lucent::BigInt, double>& v);
};

jsi::Value errorInstanceToJs(jsi::Runtime& rt, Host& h, const Error& v) {
  return jsi::Value::undefined();
}

inline std::variant<double, lucent::String> Convert<std::variant<double, lucent::String>>::fromJs(jsi::Runtime& rt, const jsi::Value& v, const Path& p) {
  if (v.isNumber()) {
    return std::variant<double, lucent::String>(Convert<double>::fromJs(rt, v, p));
  }
  if (v.isString()) {
    return std::variant<double, lucent::String>(Convert<lucent::String>::fromJs(rt, v, p));
  }
  throwBoundaryError(rt, p, "a number or a string", v);
}

inline jsi::Value Convert<std::variant<double, lucent::String>>::toJs(jsi::Runtime& rt, Host& h, const std::variant<double, lucent::String>& v) {
  return std::visit([&](const auto& x) -> jsi::Value {
    return Convert<std::decay_t<decltype(x)>>::toJs(rt, h, x);
  }, v);
}

inline std::variant<lucent::BigInt, double> Convert<std::variant<lucent::BigInt, double>>::fromJs(jsi::Runtime& rt, const jsi::Value& v, const Path& p) {
  if (v.isBigInt()) {
    return std::variant<lucent::BigInt, double>(Convert<lucent::BigInt>::fromJs(rt, v, p));
  }
  if (v.isNumber()) {
    return std::variant<lucent::BigInt, double>(Convert<double>::fromJs(rt, v, p));
  }
  throwBoundaryError(rt, p, "a bigint or a number", v);
}

inline jsi::Value Convert<std::variant<lucent::BigInt, double>>::toJs(jsi::Runtime& rt, Host& h, const std::variant<lucent::BigInt, double>& v) {
  return std::visit([&](const auto& x) -> jsi::Value {
    return Convert<std::decay_t<decltype(x)>>::toJs(rt, h, x);
  }, v);
}

}  // namespace lucent::js

namespace {

using namespace lucent::js;

void install_m_numbers(jsi::Runtime& rt, Host& host, jsi::Object& exports) {
  defineFunction(rt, exports, "format", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("format", "packages/compiler/test/e2e/cases/numbers.lucent.ts", 1), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Array<double>>::fromJs(rt, arg(args, count, 0), Path{"format", "argument 'values'"});
      return Convert<lucent::Array<lucent::String>>::toJs(rt, host, lucent_app::m_numbers::format(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "bits", 2, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("bits", "packages/compiler/test/e2e/cases/numbers.lucent.ts", 8), [&]() -> jsi::Value {
      auto a0 = Convert<double>::fromJs(rt, arg(args, count, 0), Path{"bits", "argument 'a'"});
      auto a1 = Convert<double>::fromJs(rt, arg(args, count, 1), Path{"bits", "argument 'b'"});
      return Convert<lucent::Array<double>>::toJs(rt, host, lucent_app::m_numbers::bits(std::move(a0), std::move(a1)));
    });
  });
  defineFunction(rt, exports, "parse", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("parse", "packages/compiler/test/e2e/cases/numbers.lucent.ts", 12), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Array<lucent::String>>::fromJs(rt, arg(args, count, 0), Path{"parse", "argument 'values'"});
      return Convert<lucent::Array<double>>::toJs(rt, host, lucent_app::m_numbers::parse(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "parseInts", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("parseInts", "packages/compiler/test/e2e/cases/numbers.lucent.ts", 16), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Array<lucent::String>>::fromJs(rt, arg(args, count, 0), Path{"parseInts", "argument 'values'"});
      return Convert<lucent::Array<double>>::toJs(rt, host, lucent_app::m_numbers::parseInts(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "special", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("special", "packages/compiler/test/e2e/cases/numbers.lucent.ts", 20), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_numbers::special());
    });
  });
  defineFunction(rt, exports, "mathFns", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("mathFns", "packages/compiler/test/e2e/cases/numbers.lucent.ts", 38), [&]() -> jsi::Value {
      auto a0 = Convert<double>::fromJs(rt, arg(args, count, 0), Path{"mathFns", "argument 'x'"});
      return Convert<lucent::Array<double>>::toJs(rt, host, lucent_app::m_numbers::mathFns(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "precision", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("precision", "packages/compiler/test/e2e/cases/numbers.lucent.ts", 53), [&]() -> jsi::Value {
      auto a0 = Convert<double>::fromJs(rt, arg(args, count, 0), Path{"precision", "argument 'v'"});
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_numbers::precision(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "checks", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("checks", "packages/compiler/test/e2e/cases/numbers.lucent.ts", 57), [&]() -> jsi::Value {
      auto a0 = Convert<double>::fromJs(rt, arg(args, count, 0), Path{"checks", "argument 'v'"});
      return Convert<lucent::Array<bool>>::toJs(rt, host, lucent_app::m_numbers::checks(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "heldChecks", 4, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("heldChecks", "packages/compiler/test/e2e/cases/numbers.lucent.ts", 68), [&]() -> jsi::Value {
      auto a0 = optionalFromJs<double>(rt, arg(args, count, 0), Path{"heldChecks", "argument 'a'"}, false, "a number or undefined");
      auto a1 = Convert<std::variant<double, lucent::String>>::fromJs(rt, arg(args, count, 1), Path{"heldChecks", "argument 'b'"});
      auto a2 = optionalFromJs<double>(rt, arg(args, count, 2), Path{"heldChecks", "argument 'c'"}, true, "a number or null");
      auto a3 = Convert<std::variant<lucent::BigInt, double>>::fromJs(rt, arg(args, count, 3), Path{"heldChecks", "argument 'd'"});
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_numbers::heldChecks(std::move(a0), std::move(a1), std::move(a2), std::move(a3)));
    });
  });
  defineFunction(rt, exports, "sum", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("sum", "packages/compiler/test/e2e/cases/numbers.lucent.ts", 89), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Array<double>>::fromJs(rt, arg(args, count, 0), Path{"sum", "argument 'xs'"});
      return Convert<double>::toJs(rt, host, lucent_app::m_numbers::sum(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "fib", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("fib", "packages/compiler/test/e2e/cases/numbers.lucent.ts", 95), [&]() -> jsi::Value {
      auto a0 = Convert<double>::fromJs(rt, arg(args, count, 0), Path{"fib", "argument 'n'"});
      return Convert<double>::toJs(rt, host, lucent_app::m_numbers::fib(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "multiplyAdd", 3, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, lucent_app::actor_0(), LUCENT_TRACE_SITE_AT("multiplyAdd", "packages/compiler/test/e2e/cases/numbers.lucent.ts", 100), [&]() -> jsi::Value {
      auto a0 = Convert<double>::fromJs(rt, arg(args, count, 0), Path{"multiplyAdd", "argument 'a'"});
      auto a1 = Convert<double>::fromJs(rt, arg(args, count, 1), Path{"multiplyAdd", "argument 'b'"});
      auto a2 = Convert<double>::fromJs(rt, arg(args, count, 2), Path{"multiplyAdd", "argument 'c'"});
      return Convert<double>::toJs(rt, host, lucent_app::m_numbers::multiplyAdd(std::move(a0), std::move(a1), std::move(a2)));
    });
  });
}

const ModuleDef kModules[] = {{"numbers", install_m_numbers, &lucent_app::actor_0}};

}  // namespace

namespace lucent::js {

const ModuleDef* registeredModules(size_t& count) {
  count = 1;
  return kModules;
}

void resetModuleState() {
  {
    lucent::LucentScope scope(lucent_app::actor_0());
    lucent_app::m_numbers::init();
  }
}

}  // namespace lucent::js

#pragma pop_macro("x")
#pragma pop_macro("v")
#pragma pop_macro("sum")
#pragma pop_macro("special")
#pragma pop_macro("precision")
#pragma pop_macro("parseInts")
#pragma pop_macro("parse")
#pragma pop_macro("multiplyAdd")
#pragma pop_macro("mathFns")
#pragma pop_macro("heldChecks")
#pragma pop_macro("format")
#pragma pop_macro("fib")
#pragma pop_macro("checks")
#pragma pop_macro("bits")
