// Generated by Lucent from numbers.lucent.ts. Do not edit.
#include "m_numbers.h"

#pragma push_macro("bits")
#undef bits
#pragma push_macro("checks")
#undef checks
#pragma push_macro("fib")
#undef fib
#pragma push_macro("format")
#undef format
#pragma push_macro("heldChecks")
#undef heldChecks
#pragma push_macro("mathFns")
#undef mathFns
#pragma push_macro("multiplyAdd")
#undef multiplyAdd
#pragma push_macro("parse")
#undef parse
#pragma push_macro("parseInts")
#undef parseInts
#pragma push_macro("precision")
#undef precision
#pragma push_macro("results")
#undef results
#pragma push_macro("special")
#undef special
#pragma push_macro("sum")
#undef sum
#pragma push_macro("total")
#undef total
#pragma push_macro("x")
#undef x

namespace lucent_app {

lucent::Array<lucent::String> m_numbers::format(lucent::Array<double> p0_) {
  return p0_.template map<lucent::String>([](double p0_, double p1_, lucent::Array<double> p2_) mutable -> lucent::String {
    lucent::String v3_ = lucent::toJsString(p0_);
    lucent::String v6_ = lucent::numberToFixed(p0_, 2.0);
    lucent::String v9_ = lucent::numberToString(p0_, 16.0);
    double v11_ = lucent::math::round(p0_);
    lucent::String v12_ = lucent::toJsString(v11_);
    double v14_ = lucent::math::floor(p0_);
    lucent::String v15_ = lucent::toJsString(v14_);
    double v17_ = lucent::math::trunc(p0_);
    lucent::String v18_ = lucent::toJsString(v17_);
    lucent::String v22_ = lucent::toJsString(lucent::jsMod(p0_, 3.0));
    return lucent::concat(v3_, LUCENT_STR("|"), v6_, LUCENT_STR("|"), v9_, LUCENT_STR("|"), v12_, LUCENT_STR("|"), v15_, LUCENT_STR("|"), v18_, LUCENT_STR("|"), v22_);
  });
}

lucent::Array<double> m_numbers::bits(double p0_, double p1_) {
  int32_t v2_ = lucent::toInt32(p0_) & lucent::toInt32(p1_);
  int32_t v3_ = lucent::toInt32(p0_) | lucent::toInt32(p1_);
  int32_t v4_ = lucent::toInt32(p0_) ^ lucent::toInt32(p1_);
  int32_t v5_ = ~lucent::toInt32(p0_);
  int32_t v7_ = static_cast<int32_t>(lucent::toUint32(p0_) << (static_cast<uint32_t>(3) & 31u));
  int32_t v9_ = lucent::toInt32(p0_) >> (static_cast<uint32_t>(2) & 31u);
  uint32_t v11_ = lucent::toUint32(p0_) >> (static_cast<uint32_t>(1) & 31u);
  uint32_t v14_ = lucent::toUint32(-p0_) >> (static_cast<uint32_t>(0) & 31u);
  double v16_ = lucent::jsPow(p0_, 2.0);
  return lucent::Array<double>{static_cast<double>(v2_), static_cast<double>(v3_), static_cast<double>(v4_), static_cast<double>(v5_), static_cast<double>(v7_), static_cast<double>(v9_), static_cast<double>(v11_), static_cast<double>(v14_), v16_};
}

lucent::Array<double> m_numbers::parse(lucent::Array<lucent::String> p0_) {
  return p0_.template map<double>([](lucent::String p0_, double p1_, lucent::Array<lucent::String> p2_) mutable -> double {
    return lucent::stringToNumber(p0_);
  });
}

lucent::Array<double> m_numbers::parseInts(lucent::Array<lucent::String> p0_) {
  return p0_.template map<double>([](lucent::String p0_, double p1_, lucent::Array<lucent::String> p2_) mutable -> double {
    return lucent::parseInt(p0_, 10.0);
  });
}

lucent::String m_numbers::special() {
  double v2_ = 0.1 + 0.2;
  double v5_ = 1.0 / 3.0;
  double v9_ = -0.0;
  double v12_ = 100.0 / 0.0;
  double v16_ = -1.0 / 0.0;
  double v19_ = 0.0 / 0.0;
  double v22_ = lucent::jsPow(2.0, 53.0);
  double v24_ = 9007199254740991.0;
  double v25_ = 2.220446049250313e-16;
  lucent::Array<double> results = lucent::Array<double>{v2_, v5_, 1e+21, 1e-7, v9_, v12_, v16_, v19_, v22_, 123456789.12345679, v24_, v25_};
  lucent::Array<lucent::String> v29_ = results.template map<lucent::String>([](double p0_, double p1_, lucent::Array<double> p2_) mutable -> lucent::String {
    return lucent::toJsString(p0_);
  });
  return v29_.join(LUCENT_STR(","));
}

lucent::Array<double> m_numbers::mathFns(double p0_) {
  double v1_ = -p0_;
  double v2_ = lucent::math::abs(v1_);
  double v3_ = lucent::math::sqrt(p0_);
  double v6_ = lucent::math::max(1.0, p0_, 3.0);
  double v8_ = -2.0;
  double v9_ = lucent::math::min(p0_, v8_);
  double v10_ = -p0_;
  double v11_ = lucent::math::sign(v10_);
  double v14_ = lucent::math::hypot(3.0, 4.0);
  double v16_ = lucent::math::cbrt(27.0);
  double v17_ = lucent::math::clz32(p0_);
  double v18_ = lucent::math::fround(p0_);
  double v20_ = lucent::math::log2(8.0);
  return lucent::Array<double>{v2_, v3_, v6_, v9_, v11_, v14_, v16_, v17_, v18_, v20_};
}

lucent::String m_numbers::precision(double p0_) {
  lucent::String v2_ = lucent::numberToPrecision(p0_, 3.0);
  lucent::String v4_ = lucent::numberToExponential(p0_, 2.0);
  lucent::String v6_ = lucent::numberToFixed(p0_, 0.0);
  double v8_ = p0_ * 1000.0;
  lucent::String v10_ = lucent::numberToFixed(v8_, 3.0);
  lucent::Array<lucent::String> v11_ = lucent::Array<lucent::String>{v2_, v4_, v6_, v10_};
  return v11_.join(LUCENT_STR(" "));
}

lucent::Array<bool> m_numbers::checks(double p0_) {
  bool v1_ = lucent::isInteger(p0_);
  bool v2_ = lucent::isFinite(p0_);
  bool v3_ = lucent::isNaN(p0_);
  bool v4_ = std::isnan(p0_);
  bool v5_ = lucent::isSafeInteger(p0_);
  return lucent::Array<bool>{v1_, v2_, v3_, v4_, v5_};
}

lucent::String m_numbers::heldChecks(lucent::Opt<double> p0_, std::variant<double, lucent::String> p1_, lucent::Opt<double> p2_, std::variant<lucent::BigInt, double> p3_) {
  bool v4_ = lucent::numberIs(p0_, lucent::isInteger);
  bool v5_ = lucent::numberIs(p0_, lucent::isSafeInteger);
  bool v6_ = lucent::numberIs(p0_, lucent::isFinite);
  bool v7_ = lucent::numberIs(p0_, lucent::isNaN);
  bool v8_ = lucent::numberIs(p1_, lucent::isInteger);
  bool v9_ = lucent::numberIs(p1_, lucent::isFinite);
  bool v10_ = lucent::numberIs(p1_, lucent::isNaN);
  bool v11_ = lucent::numberIs(p2_, lucent::isInteger);
  bool v12_ = lucent::numberIs(p2_, lucent::isSafeInteger);
  bool v13_ = lucent::numberIs(p3_, lucent::isInteger);
  bool v14_ = lucent::numberIs(p3_, lucent::isFinite);
  lucent::Array<bool> v15_ = lucent::Array<bool>{v4_, v5_, v6_, v7_, v8_, v9_, v10_, v11_, v12_, v13_, v14_};
  return v15_.join(LUCENT_STR(","));
}

double m_numbers::sum(lucent::Array<double> p0_) {
  double total = 0.0;
  {
    auto coll0_ = p0_;
    for (size_t i0_ = 0; i0_ < coll0_.size(); i0_++) {
      double v2_ = coll0_.at(i0_);
      {
        double x = v2_;
        total = total + x;
      }
    }
  }
  return total;
}

double m_numbers::fib(double p0_) {
  bool v2_ = p0_ < 2.0;
  double v10_{};
  if (v2_) {
    v10_ = p0_;
  } else {
    double v5_ = lucent_app::m_numbers::fib(p0_ - 1.0);
    double v8_ = lucent_app::m_numbers::fib(p0_ - 2.0);
    v10_ = v5_ + v8_;
  }
  return v10_;
}

double m_numbers::multiplyAdd(double p0_, double p1_, double p2_) {
  return p0_ * p1_ + p2_;
}

void m_numbers::init() {
}

}  // namespace lucent_app

#pragma pop_macro("x")
#pragma pop_macro("total")
#pragma pop_macro("sum")
#pragma pop_macro("special")
#pragma pop_macro("results")
#pragma pop_macro("precision")
#pragma pop_macro("parseInts")
#pragma pop_macro("parse")
#pragma pop_macro("multiplyAdd")
#pragma pop_macro("mathFns")
#pragma pop_macro("heldChecks")
#pragma pop_macro("format")
#pragma pop_macro("fib")
#pragma pop_macro("checks")
#pragma pop_macro("bits")
