// Generated by Lucent. Do not edit.
#pragma once
#include <lucent/lucent.h>

namespace lucent_app {

inline lucent::Actor& actor_0() {
  static lucent::Actor& a = lucent::Actor::create("extension");
  return a;
}

}  // namespace lucent_app
