// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("buffer")
#undef buffer

namespace lucent_app {

struct S_Object_d7e62d87;

struct S_Object_d7e62d87 : lucent::Object {
  lucent::NativeBuffer buffer{};
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object_d7e62d87>& v);

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object_d7e62d87>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "buffer", v->buffer);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("buffer")
