// Generated by Lucent. Do not edit.
#pragma once
#include <lucent/lucent.h>

namespace lucent_app {

struct S_Object1;

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object1>& v);

}  // namespace lucent_app
