// Generated by Lucent. Do not edit.
#include "m_integers.h"
#include "lucent_app_S_Object_1e208747.h"
#include <lucent/jsi/convert.h>
#include <lucent/jsi/host.h>

#pragma push_macro("counters")
#undef counters
#pragma push_macro("destructured")
#undef destructured
#pragma push_macro("h")
#undef h
#pragma push_macro("mixed")
#undef mixed
#pragma push_macro("out")
#undef out
#pragma push_macro("p")
#undef p
#pragma push_macro("shifts")
#undef shifts
#pragma push_macro("signedZero")
#undef signedZero
#pragma push_macro("unsignedAccumulate")
#undef unsignedAccumulate
#pragma push_macro("wraparound")
#undef wraparound
#pragma push_macro("z")
#undef z

namespace lucent::js {

template <>
struct Convert<lucent::Ref<lucent_app::S_Object_1e208747>> {
  static lucent::Ref<lucent_app::S_Object_1e208747> fromJs(jsi::Runtime& rt, const jsi::Value& v, const Path& p);
  static lucent::Ref<lucent_app::S_Object_1e208747> fromObject(jsi::Runtime& rt, const jsi::Object& o, const Path& p);
  static jsi::Value toJs(jsi::Runtime& rt, Host& h, const lucent::Ref<lucent_app::S_Object_1e208747>& v);
};

inline lucent::Ref<lucent_app::S_Object_1e208747> Convert<lucent::Ref<lucent_app::S_Object_1e208747>>::fromJs(jsi::Runtime& rt, const jsi::Value& v, const Path& p) {
  if (!v.isObject()) {
    throwBoundaryError(rt, p, "an object", v);
  }
  return fromObject(rt, v.getObject(rt), p);
}

inline lucent::Ref<lucent_app::S_Object_1e208747> Convert<lucent::Ref<lucent_app::S_Object_1e208747>>::fromObject(jsi::Runtime& rt, const jsi::Object& o, const Path& p) {
  if (o.isArray(rt) || o.isFunction(rt)) {
    throwBoundaryError(rt, p, "an object", jsi::Value(rt, o));
  }
  Host& h = Host::get(rt);
  static const PropName n0{"z"};
  auto out = std::make_shared<lucent_app::S_Object_1e208747>();
  out->z = Convert<double>::fromJs(rt, o.getProperty(rt, h.prop(rt, n0)), p.field("z"));
  return out;
}

inline jsi::Value Convert<lucent::Ref<lucent_app::S_Object_1e208747>>::toJs(jsi::Runtime& rt, Host& h, const lucent::Ref<lucent_app::S_Object_1e208747>& v) {
  if (!v) {
    return jsi::Value::null();
  }
  static const PropName n0{"z"};
  jsi::Object o(rt);
  o.setProperty(rt, h.prop(rt, n0), Convert<double>::toJs(rt, h, v->z));
  return jsi::Value(std::move(o));
}

jsi::Value errorInstanceToJs(jsi::Runtime& rt, Host& h, const Error& v) {
  return jsi::Value::undefined();
}

}  // namespace lucent::js

namespace {

using namespace lucent::js;

void install_m_integers(jsi::Runtime& rt, Host& host, jsi::Object& exports) {
  defineFunction(rt, exports, "wraparound", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("wraparound", "packages/compiler/test/e2e/cases/integers.lucent.ts", 4), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_integers::wraparound());
    });
  });
  defineFunction(rt, exports, "shifts", 2, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("shifts", "packages/compiler/test/e2e/cases/integers.lucent.ts", 17), [&]() -> jsi::Value {
      auto a0 = Convert<double>::fromJs(rt, arg(args, count, 0), Path{"shifts", "argument 'value'"});
      auto a1 = Convert<double>::fromJs(rt, arg(args, count, 1), Path{"shifts", "argument 'by'"});
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_integers::shifts(std::move(a0), std::move(a1)));
    });
  });
  defineFunction(rt, exports, "mixed", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("mixed", "packages/compiler/test/e2e/cases/integers.lucent.ts", 27), [&]() -> jsi::Value {
      auto a0 = Convert<double>::fromJs(rt, arg(args, count, 0), Path{"mixed", "argument 'seed'"});
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_integers::mixed(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "signedZero", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("signedZero", "packages/compiler/test/e2e/cases/integers.lucent.ts", 37), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_integers::signedZero());
    });
  });
  defineFunction(rt, exports, "counters", 0, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("counters", "packages/compiler/test/e2e/cases/integers.lucent.ts", 45), [&]() -> jsi::Value {
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_integers::counters());
    });
  });
  defineFunction(rt, exports, "unsignedAccumulate", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("unsignedAccumulate", "packages/compiler/test/e2e/cases/integers.lucent.ts", 60), [&]() -> jsi::Value {
      auto a0 = Convert<double>::fromJs(rt, arg(args, count, 0), Path{"unsignedAccumulate", "argument 'n'"});
      return Convert<double>::toJs(rt, host, lucent_app::m_integers::unsignedAccumulate(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "destructured", 2, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("destructured", "packages/compiler/test/e2e/cases/integers.lucent.ts", 69), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Ref<lucent_app::S_Object_1e208747>>::fromJs(rt, arg(args, count, 0), Path{"destructured", "argument 'p'"});
      auto a1 = Convert<lucent::Array<double>>::fromJs(rt, arg(args, count, 1), Path{"destructured", "argument 'xs'"});
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_integers::destructured(std::move(a0), std::move(a1)));
    });
  });
}

const ModuleDef kModules[] = {{"integers", install_m_integers}};

}  // namespace

namespace lucent::js {

const ModuleDef* registeredModules(size_t& count) {
  count = 1;
  return kModules;
}

void resetModuleState() {
  lucent_app::m_integers::init();
}

}  // namespace lucent::js

#pragma pop_macro("z")
#pragma pop_macro("wraparound")
#pragma pop_macro("unsignedAccumulate")
#pragma pop_macro("signedZero")
#pragma pop_macro("shifts")
#pragma pop_macro("p")
#pragma pop_macro("out")
#pragma pop_macro("mixed")
#pragma pop_macro("h")
#pragma pop_macro("destructured")
#pragma pop_macro("counters")
