// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("deep")
#undef deep

namespace lucent_app {

struct S_Object2 : lucent::Object {
  lucent::Opt<lucent::String> deep{};
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object2>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "deep", v->deep);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("deep")
