// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_S_Object2.h"

#pragma push_macro("name")
#undef name
#pragma push_macro("nested")
#undef nested
#pragma push_macro("retries")
#undef retries

namespace lucent_app {

struct S_Config : lucent::Object {
  lucent::String name{};
  lucent::Opt<double> retries{};
  lucent::Opt<lucent::Ref<lucent_app::S_Object2>> nested{};
};

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Config>& v) {
  if (!v) {
    w.raw("null");
    return;
  }
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "name", v->name);
  lucent::jsonField(w, first, "retries", v->retries);
  lucent::jsonField(w, first, "nested", v->nested);
  (void)first;
  w.raw("}");
}

}  // namespace lucent_app

#pragma pop_macro("retries")
#pragma pop_macro("nested")
#pragma pop_macro("name")
