// Generated by Lucent. Do not edit.
#pragma once
#include <lucent/lucent.h>

namespace lucent_app {

struct S_Object1;
struct S_Object2;
struct S_Config;
struct S_Object4;
struct S_Object5;
struct S_Object6;

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object1>& v);
inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object2>& v);
inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Config>& v);
inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object4>& v);
inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object5>& v);
inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object6>& v);

}  // namespace lucent_app
