// Generated by scripts/sync-examples.ts from packages/compiler/test/e2e/cases/module-hooks.test.js. Do not edit.
// @ts-nocheck
export default function run(mod, print, lucentClass, mods) {
  print(mod.hooks());

}
