// Generated by scripts/sync-examples.ts from packages/compiler/test/e2e/cases/object-strings.test.js. Do not edit.
// @ts-nocheck
export default function run(mod, print, lucentClass, mods) {
  print(mod.arrays());
  print(mod.collections());
  print(mod.bytes());
  print(mod.promises());
  print(mod.aborts());
  print(mod.optionals());
  print(mod.kinds());

}
