// Generated by Lucent. Do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const { loadModule, lucentClass } = require("./_lucent/runtime.js");
const m = loadModule("main", () => require("react-native").TurboModuleRegistry, require("./_lucent/identity.js"));
exports.sum = m.sum;
exports.far = m.far;
exports.vectorsMade = m.vectorsMade;
exports.throughNamespace = m.throughNamespace;
