// Generated by Lucent. Do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const { loadModule, lucentClass } = require("./_lucent/runtime.js");
const m = loadModule("shapes", () => require("react-native").TurboModuleRegistry, require("./_lucent/identity.js"));
exports.toPoint = m.toPoint;
exports.largest = m.largest;
exports.Vec = lucentClass(m.Vec);
Object.defineProperty(exports, "created", { enumerable: true, get: () => m.created });
