// Generated by Lucent from loop-closures.lucent.ts. Do not edit.
#include "m_loop_u2d_closures.h"

#pragma push_macro("bumped")
#undef bumped
#pragma push_macro("bumps")
#undef bumps
#pragma push_macro("continued")
#undef continued
#pragma push_macro("fns")
#undef fns
#pragma push_macro("gets")
#undef gets
#pragma push_macro("i")
#undef i
#pragma push_macro("j")
#undef j
#pragma push_macro("pairs")
#undef pairs
#pragma push_macro("skipping")
#undef skipping

namespace lucent_app {

lucent::Array<double> m_loop_u2d_closures::skipping() {
  lucent::Array<lucent::Fn<double()>> fns = lucent::Array<lucent::Fn<double()>>{};
  {
    lucent::Box<double> i{};
    *i = 0.0;
    while (true) {
      {
        double v2_ = *i;
        bool v5_ = !(v2_ < 6.0);
        if (v5_) {
          break;
        }
        lucent::Fn<double()> v7_ = lucent::Fn<double()>([i = i]() mutable -> double {
          double v0_ = *i;
          return v0_;
        });
        (void)fns.push(v7_);
        double v9_ = *i;
        *i = v9_ + 1.0;
      }
      i = lucent::Box<double>(*i);
      double v12_ = *i;
      *i = v12_ + 1.0;
    }
  }
  return fns.template map<double>([](lucent::Fn<double()> p0_, double p1_, lucent::Array<lucent::Fn<double()>> p2_) mutable -> double {
    return p0_();
  });
}

lucent::Array<double> m_loop_u2d_closures::bumped() {
  lucent::Array<lucent::Fn<double()>> gets = lucent::Array<lucent::Fn<double()>>{};
  lucent::Array<lucent::Fn<void()>> bumps = lucent::Array<lucent::Fn<void()>>{};
  {
    lucent::Box<double> i{};
    *i = 0.0;
    while (true) {
      {
        double v3_ = *i;
        bool v6_ = !(v3_ < 3.0);
        if (v6_) {
          break;
        }
        lucent::Fn<double()> v8_ = lucent::Fn<double()>([i = i]() mutable -> double {
          double v0_ = *i;
          return v0_;
        });
        (void)gets.push(v8_);
        lucent::Fn<void()> v11_ = lucent::Fn<void()>([i = i]() mutable -> void {
          double v0_ = *i;
          *i = v0_ + 10.0;
        });
        (void)bumps.push(v11_);
      }
      i = lucent::Box<double>(*i);
      double v13_ = *i;
      *i = v13_ + 1.0;
    }
  }
  lucent::Opt<lucent::Fn<void()>> v18_ = bumps.getIndex(static_cast<int64_t>(1));
  v18_.value()();
  return gets.template map<double>([](lucent::Fn<double()> p0_, double p1_, lucent::Array<lucent::Fn<double()>> p2_) mutable -> double {
    return p0_();
  });
}

lucent::Array<double> m_loop_u2d_closures::continued() {
  lucent::Array<lucent::Fn<double()>> fns = lucent::Array<lucent::Fn<double()>>{};
  {
    lucent::Box<double> i{};
    *i = 0.0;
    while (true) {
      {
        double v2_ = *i;
        bool v5_ = !(v2_ < 8.0);
        if (v5_) {
          break;
        }
        double v6_ = *i;
        bool v10_ = lucent::jsMod(v6_, 3.0) == 0.0;
        if (v10_) {
          double v11_ = *i;
          *i = v11_ + 1.0;
          goto cont0_;
        }
        lucent::Fn<double()> v15_ = lucent::Fn<double()>([i = i]() mutable -> double {
          double v0_ = *i;
          return v0_ * 2.0;
        });
        (void)fns.push(v15_);
      }
      cont0_:;
      i = lucent::Box<double>(*i);
      double v17_ = *i;
      *i = v17_ + 1.0;
    }
  }
  return fns.template map<double>([](lucent::Fn<double()> p0_, double p1_, lucent::Array<lucent::Fn<double()>> p2_) mutable -> double {
    return p0_();
  });
}

lucent::Array<lucent::String> m_loop_u2d_closures::pairs() {
  lucent::Array<lucent::Fn<lucent::String()>> fns = lucent::Array<lucent::Fn<lucent::String()>>{};
  {
    lucent::Box<double> i{};
    *i = 0.0;
    lucent::Box<double> j{};
    *j = 10.0;
    while (true) {
      {
        double v3_ = *i;
        bool v6_ = !(v3_ < 4.0);
        if (v6_) {
          break;
        }
        lucent::Fn<lucent::String()> v8_ = lucent::Fn<lucent::String()>([i = i, j = j]() mutable -> lucent::String {
          double v0_ = *i;
          lucent::String v1_ = lucent::toJsString(v0_);
          double v3_ = *j;
          lucent::String v4_ = lucent::toJsString(v3_);
          return lucent::concat(v1_, LUCENT_STR(":"), v4_);
        });
        (void)fns.push(v8_);
        double v10_ = *i;
        bool v12_ = v10_ == 1.0;
        if (v12_) {
          double v13_ = *j;
          *j = v13_ - 5.0;
        }
      }
      i = lucent::Box<double>(*i);
      j = lucent::Box<double>(*j);
      double v16_ = *i;
      *i = v16_ + 1.0;
      double v19_ = *j;
      *j = v19_ - 1.0;
    }
  }
  return fns.template map<lucent::String>([](lucent::Fn<lucent::String()> p0_, double p1_, lucent::Array<lucent::Fn<lucent::String()>> p2_) mutable -> lucent::String {
    return p0_();
  });
}

void m_loop_u2d_closures::init() {
}

}  // namespace lucent_app

#pragma pop_macro("skipping")
#pragma pop_macro("pairs")
#pragma pop_macro("j")
#pragma pop_macro("i")
#pragma pop_macro("gets")
#pragma pop_macro("fns")
#pragma pop_macro("continued")
#pragma pop_macro("bumps")
#pragma pop_macro("bumped")
