// Generated by Lucent. Do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const { loadModule, lucentClass } = require("./_lucent/runtime.js");
const m = loadModule("abort", () => require("react-native").TurboModuleRegistry, require("./_lucent/identity.js"));
exports.waitOrStop = m.waitOrStop;
exports.tickUntilAborted = m.tickUntilAborted;
exports.check = m.check;
exports.checkOptional = m.checkOptional;
exports.controllerInLucent = m.controllerInLucent;
exports.customReason = m.customReason;
exports.abortedMidway = m.abortedMidway;
