import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  referenceCode: {
    margin: "25px 0",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#37412f",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: "#37412f",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#37412f",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: "#37412f",
    borderRadius: "7px",
    backgroundColor: "#181e14",
    overflow: "hidden",
  },
  referenceCodeBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: {
      default: "16px",
      "@media (max-width: 540px)": "8px",
    },
    padding: {
      default: "10px 17px",
      "@media (max-width: 540px)": "8px 12px",
    },
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#303a28",
    color: "#bdcbb0",
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
  },
  referenceCopyButton: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#2c3823",
    borderRadius: "6px",
    backgroundColor: "transparent",
    color: "#9fae93",
    fontWeight: 500,
    fontSize: "0.6875rem",
    lineHeight: 1,
    letterSpacing: "0.8px",
    textTransform: "uppercase",
    fontFamily: '"IBM Plex Mono", monospace',
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 9px",
    cursor: "pointer",
    transitionProperty: "color, border-color",
    transitionDuration: "120ms",
    ":hover": {
      color: "#c4f778",
      borderColor: "#c4f778",
    },
    ":focus-visible": {
      outlineWidth: "2px",
      outlineStyle: "solid",
      outlineColor: "#c4f778",
      outlineOffset: "2px",
    },
  },
  referencePre: {
    padding: {
      default: "21px",
      "@media (max-width: 540px)": "17px",
    },
    margin: "0",
    overflow: "auto",
    fontSize: {
      default: "0.875rem",
      "@media (max-width: 540px)": "0.8125rem",
    },
    tabSize: 2,
  },
  referenceCodeText: {
    fontWeight: 400,
    fontSize: "1em",
    lineHeight: 1.9,
    fontFamily: '"IBM Plex Mono", monospace',
    color: "#d5e4c7",
    overflowWrap: "normal",
  },
  syntaxPurple: {
    color: "#c7a4e1",
  },
  syntaxYellow: {
    color: "#d7d393",
  },
  syntaxGreen: {
    color: "#c4f778",
  },
});
