import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  referenceCode: {
    margin: "25px 0",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#37412f",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: "#37412f",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#37412f",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: "#37412f",
    borderRadius: "7px",
    backgroundColor: "#181e14",
    overflow: "hidden",
  },
  referenceCodeBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: {
      default: "16px",
      "@media (max-width: 540px)": "8px",
    },
    padding: {
      default: "10px 17px",
      "@media (max-width: 540px)": "8px 12px",
    },
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#303a28",
    color: "#bdcbb0",
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
  },
  referenceCopyButton: {
    borderTopWidth: "0",
    borderTopStyle: "none",
    borderTopColor: "currentColor",
    borderRightWidth: "0",
    borderRightStyle: "none",
    borderRightColor: "currentColor",
    borderBottomWidth: "0",
    borderBottomStyle: "none",
    borderBottomColor: "currentColor",
    borderLeftWidth: "0",
    borderLeftStyle: "none",
    borderLeftColor: "currentColor",
    backgroundColor: "transparent",
    color: "#bac9ad",
    fontWeight: 400,
    fontSize: "0.875rem",
    lineHeight: "normal",
    fontFamily: '"DM Sans", sans-serif',
    padding: "8px",
    display: "flex",
    alignItems: "center",
    gap: "9px",
    ":hover": {
      color: "#c4f778",
    },
  },
  referencePre: {
    padding: {
      default: "21px",
      "@media (max-width: 540px)": "17px",
    },
    margin: "0",
    overflow: "auto",
    fontSize: {
      default: "0.875rem",
      "@media (max-width: 540px)": "0.8125rem",
    },
    tabSize: 2,
  },
  referenceCodeText: {
    fontWeight: 400,
    fontSize: "1em",
    lineHeight: 1.9,
    fontFamily: '"IBM Plex Mono", monospace',
    color: "#d5e4c7",
    overflowWrap: "normal",
  },
  syntaxPurple: {
    color: "#c7a4e1",
  },
  syntaxYellow: {
    color: "#d7d393",
  },
  syntaxGreen: {
    color: "#c4f778",
  },
});
