import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  compilerDemo: {
    minWidth: "0",
    position: "relative",
    paddingTop: "5px",
    width: {
      default: null,
      "@media (max-width: 850px)": "100%",
    },
    maxWidth: {
      default: null,
      "@media (max-width: 850px)": "620px",
    },
    justifySelf: {
      default: null,
      "@media (max-width: 850px)": "center",
    },
  },
  demoTopline: {
    display: "flex",
    justifyContent: "space-between",
    fontWeight: 400,
    fontSize: {
      default: "0.75rem",
      "@media (max-width: 850px)": "0.75rem",
      "@media (max-width: 540px)": "0.75rem",
    },
    lineHeight: 1.5,
    fontFamily: '"IBM Plex Mono", monospace',
    letterSpacing: {
      default: "1.5px",
      "@media (max-width: 540px)": "0.3px",
    },
    color: "#9ca68f",
    margin: "0 2px 15px",
  },
  demoToplineLabel: {
    maxWidth: {
      default: null,
      "@media (max-width: 540px)": "75%",
    },
  },
  demoIndex: {
    color: "#6b7660",
  },
  codeWindow: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#37412f",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: "#37412f",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#37412f",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: "#37412f",
    borderRadius: "8px",
    overflow: "hidden",
    backgroundImage: "linear-gradient(120deg, #1e251a, #1a2017)",
    boxShadow: "0 16px 50px #00000018",
  },
  windowBar: {
    height: "47px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#323b2b",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: {
      default: "0 17px",
      "@media (max-width: 540px)": "0 12px",
    },
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
  },
  fileLabel: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    color: "#c5cdbb",
    fontSize: "0.875rem",
  },
  languageIcon: {
    fontWeight: 500,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"DM Sans", sans-serif',
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "20px",
    height: "20px",
    backgroundColor: "#bdceef",
    color: "#152030",
    borderRadius: "2px",
  },
  iconButton: {
    borderTopWidth: "0",
    borderTopStyle: "none",
    borderTopColor: "currentColor",
    borderRightWidth: "0",
    borderRightStyle: "none",
    borderRightColor: "currentColor",
    borderBottomWidth: "0",
    borderBottomStyle: "none",
    borderBottomColor: "currentColor",
    borderLeftWidth: "0",
    borderLeftStyle: "none",
    borderLeftColor: "currentColor",
    backgroundColor: "transparent",
    color: "#9aa78e",
    padding: "6px",
    display: "grid",
    placeItems: "center",
    minHeight: "36px",
    minWidth: "36px",
    ":hover": {
      color: "#c4f778",
    },
  },
  copyIcon: {
    height: "16px",
    width: "16px",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "1.5",
  },
  sourceCode: {
    margin: "0",
    padding: {
      default: "20px 20px 22px",
      "@media (max-width: 540px)": "17px 12px",
    },
    fontWeight: 400,
    fontSize: {
      default: "0.75rem",
      "@media (max-width: 850px)": "0.875rem",
      "@media (max-width: 540px)": "0.75rem",
    },
    lineHeight: 1.85,
    fontFamily: '"IBM Plex Mono", monospace',
    overflow: "auto",
    color: "#d8ddcf",
  },
  line: {
    display: "block",
    whiteSpace: "pre",
  },
  purple: {
    color: "#c7a4e1",
  },
  yellow: {
    color: "#d7d393",
  },
  compileConnector: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "14px",
    padding: "14px 26px",
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
    color: "#a2b194",
  },
  connectorLine: {
    height: "1px",
    backgroundColor: "#2e3926",
    flex: 1,
    maxWidth: "100px",
  },
  compileLabel: {
    display: "flex",
    gap: "9px",
    alignItems: "center",
  },
  compileArrow: {
    color: "#c4f778",
    fontSize: "1.0625rem",
  },
  outputWindow: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#37412f",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: "#37412f",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#37412f",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: "#37412f",
    borderRadius: "8px",
    overflow: "hidden",
    backgroundColor: "#171b15",
    boxShadow: "0 16px 50px #00000018",
  },
  outputWindowBar: {
    height: "47px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#323b2b",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: {
      default: "0 17px",
      "@media (max-width: 540px)": "0 12px",
    },
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
    paddingLeft: {
      default: "8px",
      "@media (max-width: 540px)": "5px",
    },
  },
  languageTabs: {
    height: "100%",
    display: "flex",
    gap: "5px",
  },
  languageTab: {
    borderTopWidth: "0",
    borderTopStyle: "none",
    borderTopColor: "currentColor",
    borderRightWidth: "0",
    borderRightStyle: "none",
    borderRightColor: "currentColor",
    borderBottomWidth: "0",
    borderBottomStyle: "none",
    borderBottomColor: "currentColor",
    borderLeftWidth: "0",
    borderLeftStyle: "none",
    borderLeftColor: "currentColor",
    backgroundColor: "transparent",
    color: "#8e9884",
    fontWeight: 500,
    fontSize: "0.875rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
    padding: "0 13px",
    position: "relative",
    display: "flex",
    gap: "7px",
    alignItems: "center",
  },
  tabSymbol: {
    fontWeight: 600,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"DM Sans", sans-serif',
    color: "#d9a27b",
  },
  tabSymbol2: {
    fontWeight: 600,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"DM Sans", sans-serif',
    color: "#b8a7e8",
  },
  outputLabel: {
    fontSize: "0.75rem",
    color: "#9ba68e",
  },
  generatedCode: {
    margin: "0",
    padding: {
      default: "20px 20px 22px",
      "@media (max-width: 540px)": "17px 12px",
    },
    fontWeight: 400,
    fontSize: {
      default: "0.8125rem",
      "@media (max-width: 850px)": "0.8125rem",
      "@media (max-width: 540px)": "0.75rem",
    },
    lineHeight: 1.85,
    fontFamily: '"IBM Plex Mono", monospace',
    overflow: "auto",
    color: "#d8ddcf",
    height: {
      default: "220px",
      "@media (max-width: 850px)": "178px",
      "@media (max-width: 540px)": "207px",
    },
    whiteSpace: "pre",
  },
  outputFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#2b3325",
    padding: "11px 17px",
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
    color: "#8d9b80",
  },
  check: {
    color: "#c4f778",
    marginRight: "5px",
  },
  demoCaption: {
    textAlign: "center",
    fontSize: {
      default: "0.75rem",
      "@media (max-width: 540px)": "0.75rem",
    },
    color: "#8c9582",
    margin: "15px 0 0",
  },
  selectedTab: {
    color: "#f0f2eb",
    "::after": {
      content: '""',
      height: 2,
      position: "absolute",
      bottom: -1,
      left: 10,
      right: 10,
      backgroundColor: "#c4f778",
    },
  },
  codeNumber: {
    display: "inline-block",
    width: 25,
    marginRight: 13,
    color: "#89977c",
    fontSize: ".75rem",
    userSelect: "none",
  },
});
