import * as stylex from "@stylexjs/stylex";
import { tokens } from "../styles/tokens.stylex";

export const styles = stylex.create({
  compilerDemo: {
    minWidth: "0",
    position: "relative",
    paddingTop: "5px",
    width: {
      default: null,
      "@media (max-width: 850px)": "100%",
    },
    maxWidth: {
      default: null,
      "@media (max-width: 850px)": "620px",
    },
    justifySelf: {
      default: null,
      "@media (max-width: 850px)": "center",
    },
  },
  demoTopline: {
    display: "flex",
    justifyContent: "space-between",
    fontWeight: 400,
    fontSize: {
      default: "0.75rem",
      "@media (max-width: 850px)": "0.75rem",
      "@media (max-width: 540px)": "0.75rem",
    },
    lineHeight: 1.5,
    fontFamily: '"IBM Plex Mono", monospace',
    letterSpacing: {
      default: "1.5px",
      "@media (max-width: 540px)": "0.3px",
    },
    color: tokens.textSubtle,
    margin: "0 2px 15px",
  },
  demoToplineLabel: {
    maxWidth: {
      default: null,
      "@media (max-width: 540px)": "75%",
    },
  },
  demoIndex: {
    color: tokens.textSubtle,
  },
  codeWindow: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.borderStrong,
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: tokens.borderStrong,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.borderStrong,
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: tokens.borderStrong,
    borderRadius: "8px",
    overflow: "hidden",
    backgroundColor: tokens.bgRaised,
    boxShadow: `0 16px 50px ${tokens.shadow}`,
  },
  windowBar: {
    height: "47px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.border,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: {
      default: "0 17px",
      "@media (max-width: 540px)": "0 12px",
    },
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
  },
  fileLabel: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    color: tokens.textSecondary,
    fontSize: "0.875rem",
  },
  languageIcon: {
    fontWeight: 500,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"DM Sans", sans-serif',
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "20px",
    height: "20px",
    // The TypeScript badge keeps its own blue in both themes.
    backgroundColor: "#bdceef",
    color: "#152030",
    borderRadius: "2px",
  },
  iconButton: {
    borderTopWidth: "0",
    borderTopStyle: "none",
    borderTopColor: "currentColor",
    borderRightWidth: "0",
    borderRightStyle: "none",
    borderRightColor: "currentColor",
    borderBottomWidth: "0",
    borderBottomStyle: "none",
    borderBottomColor: "currentColor",
    borderLeftWidth: "0",
    borderLeftStyle: "none",
    borderLeftColor: "currentColor",
    backgroundColor: "transparent",
    color: tokens.textSubtle,
    padding: "6px",
    display: "grid",
    placeItems: "center",
    minHeight: "36px",
    minWidth: "36px",
    ":hover": {
      color: tokens.accent,
    },
  },
  copyIcon: {
    height: "16px",
    width: "16px",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "1.5",
  },
  sourceCode: {
    margin: "0",
    padding: {
      default: "20px 20px 22px",
      "@media (max-width: 540px)": "17px 12px",
    },
    fontWeight: 400,
    fontSize: {
      default: "0.75rem",
      "@media (max-width: 850px)": "0.875rem",
      "@media (max-width: 540px)": "0.75rem",
    },
    lineHeight: 1.85,
    fontFamily: '"IBM Plex Mono", monospace',
    overflow: "auto",
    color: tokens.textCode,
  },
  compileConnector: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "14px",
    padding: "14px 26px",
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
    color: tokens.textMuted,
  },
  connectorLine: {
    height: "1px",
    backgroundColor: tokens.border,
    flex: 1,
    maxWidth: "100px",
  },
  compileLabel: {
    display: "flex",
    gap: "9px",
    alignItems: "center",
  },
  compileArrow: {
    color: tokens.accent,
    fontSize: "1.0625rem",
  },
  outputWindow: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.borderStrong,
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: tokens.borderStrong,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.borderStrong,
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: tokens.borderStrong,
    borderRadius: "8px",
    overflow: "hidden",
    backgroundColor: tokens.bgRaised,
    boxShadow: `0 16px 50px ${tokens.shadow}`,
  },
  outputWindowBar: {
    height: "47px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.border,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: {
      default: "0 17px",
      "@media (max-width: 540px)": "0 12px",
    },
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
    paddingLeft: {
      default: "8px",
      "@media (max-width: 540px)": "5px",
    },
  },
  languageTabs: {
    height: "100%",
    display: "flex",
    gap: "5px",
  },
  languageTab: {
    whiteSpace: "nowrap",
    borderTopWidth: "0",
    borderTopStyle: "none",
    borderTopColor: "currentColor",
    borderRightWidth: "0",
    borderRightStyle: "none",
    borderRightColor: "currentColor",
    borderBottomWidth: "0",
    borderBottomStyle: "none",
    borderBottomColor: "currentColor",
    borderLeftWidth: "0",
    borderLeftStyle: "none",
    borderLeftColor: "currentColor",
    backgroundColor: "transparent",
    color: tokens.textSubtle,
    fontWeight: 500,
    fontSize: "0.875rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
    padding: "0 13px",
    position: "relative",
    display: "flex",
    gap: "7px",
    alignItems: "center",
  },
  tabSymbol: {
    fontWeight: 600,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"DM Sans", sans-serif',
    color: tokens.accent,
  },
  outputLabel: {
    fontSize: "0.75rem",
    color: tokens.textSubtle,
  },
  generatedCode: {
    margin: "0",
    padding: {
      default: "20px 20px 22px",
      "@media (max-width: 540px)": "17px 12px",
    },
    fontWeight: 400,
    fontSize: {
      default: "0.8125rem",
      "@media (max-width: 850px)": "0.8125rem",
      "@media (max-width: 540px)": "0.75rem",
    },
    lineHeight: 1.85,
    fontFamily: '"IBM Plex Mono", monospace',
    overflow: "auto",
    color: tokens.textCode,
    height: {
      default: "220px",
      "@media (max-width: 850px)": "178px",
      "@media (max-width: 540px)": "207px",
    },
    whiteSpace: "pre",
  },
  outputFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.border,
    padding: "11px 17px",
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: '"IBM Plex Mono", monospace',
    color: tokens.textSubtle,
  },
  check: {
    color: tokens.accent,
    marginRight: "5px",
  },
  demoCaption: {
    textAlign: "center",
    fontSize: {
      default: "0.75rem",
      "@media (max-width: 540px)": "0.75rem",
    },
    color: tokens.textSubtle,
    margin: "15px 0 0",
  },
  selectedTab: {
    color: tokens.text,
    "::after": {
      content: '""',
      height: 2,
      position: "absolute",
      bottom: -1,
      left: 10,
      right: 10,
      backgroundColor: tokens.accentFill,
    },
  },
});
