import * as stylex from "@stylexjs/stylex";

const mono = '"IBM Plex Mono", monospace';
const border = "#30362b";
const accent = "#c4f778";
const text = "#aeb7a4";

export const styles = stylex.create({
  kicker: {
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "normal",
    fontFamily: mono,
    letterSpacing: "1.2px",
    color: "#93a781",
    textTransform: "uppercase",
  },
  title: {
    fontSize: {
      default: "clamp(2.25rem, 3.6vw, 3rem)",
      "@media (max-width: 540px)": "2.125rem",
    },
    fontWeight: 500,
    letterSpacing: "-1.8px",
    lineHeight: 1.12,
    margin: "14px 0 16px",
  },
  lead: {
    fontSize: "1.2rem",
    lineHeight: 1.65,
    color: "#d0d8c7",
    margin: "0 0 12px",
    maxWidth: "62ch",
  },
  h2: {
    fontSize: {
      default: "1.75rem",
      "@media (max-width: 540px)": "1.5rem",
    },
    lineHeight: 1.2,
    letterSpacing: "-0.8px",
    fontWeight: 500,
    margin: "52px 0 14px",
    paddingTop: "20px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: border,
    scrollMarginTop: "28px",
  },
  h3: {
    fontSize: "1.2rem",
    fontWeight: 500,
    letterSpacing: "-0.4px",
    margin: "30px 0 10px",
    scrollMarginTop: "28px",
  },
  headingAnchor: {
    color: "inherit",
    ":hover": {
      color: accent,
    },
  },
  paragraph: {
    fontSize: "1rem",
    lineHeight: 1.8,
    color: text,
    margin: "14px 0",
    maxWidth: "72ch",
  },
  inlineCode: {
    fontWeight: 400,
    fontSize: "0.875em",
    fontFamily: mono,
    color: "#d5e4c7",
    overflowWrap: "anywhere",
    backgroundColor: "#20271b",
    borderRadius: "3px",
    padding: "2px 5px",
  },
  strong: {
    color: "#f0f2eb",
    fontWeight: 550,
  },
  link: {
    color: accent,
    textDecorationLine: "underline",
    textDecorationColor: "#5f7a3d",
    textUnderlineOffset: "3px",
    ":hover": {
      textDecorationColor: accent,
    },
  },
  list: {
    paddingLeft: "22px",
    margin: "14px 0",
    maxWidth: "72ch",
  },
  listItem: {
    fontSize: "1rem",
    lineHeight: 1.8,
    color: text,
    paddingLeft: "4px",
    margin: "6px 0",
    "::marker": {
      color: "#71865d",
    },
  },
  note: {
    display: "flex",
    alignItems: "baseline",
    gap: "14px",
    backgroundColor: "#1b2416",
    borderLeftWidth: "2px",
    borderLeftStyle: "solid",
    borderLeftColor: accent,
    borderRadius: "0 5px 5px 0",
    padding: "14px 20px",
    margin: "22px 0",
    maxWidth: "76ch",
  },
  noteWarn: {
    backgroundColor: "#251f14",
    borderLeftColor: "#e6b45a",
  },
  noteMark: {
    color: accent,
    fontFamily: mono,
    fontSize: "1rem",
    flexShrink: 0,
  },
  noteMarkWarn: {
    color: "#e6b45a",
  },
  noteText: {
    fontSize: "0.95rem",
    lineHeight: 1.75,
    color: text,
    margin: 0,
  },
  tableWrap: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: border,
    borderRadius: "6px",
    overflow: "auto",
    margin: "22px 0",
  },
  table: {
    borderCollapse: "collapse",
    width: "100%",
    fontSize: "0.875rem",
    lineHeight: 1.65,
    textAlign: "left",
  },
  th: {
    fontSize: "0.72rem",
    fontWeight: 500,
    letterSpacing: "0.6px",
    textTransform: "uppercase",
    color: "#d3ddc9",
    padding: "12px 15px",
    backgroundColor: "#1e2519",
    whiteSpace: "nowrap",
  },
  td: {
    padding: "11px 15px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: border,
    color: "#afbba5",
    verticalAlign: "top",
  },
  tdFirst: {
    color: "#d5e4c7",
    minWidth: "120px",
  },
  diagram: {
    margin: "26px 0",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#37412f",
    borderRadius: "7px",
    backgroundColor: "#151a12",
    padding: {
      default: "18px 20px 10px",
      "@media (max-width: 540px)": "10px 8px 4px",
    },
    overflow: "hidden",
  },
  diagramSvg: {
    display: "block",
    width: "100%",
    height: "auto",
  },
  caption: {
    fontSize: "0.8rem",
    lineHeight: 1.6,
    color: "#8d9783",
    fontFamily: mono,
    margin: "10px 0 0",
  },
  steps: {
    listStyle: "none",
    margin: "22px 0",
    padding: 0,
    display: "grid",
    gap: "26px",
  },
  step: {
    display: "grid",
    gap: "4px",
  },
  stepTitle: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    fontSize: "1.05rem",
    fontWeight: 550,
    margin: 0,
  },
  stepNumber: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "26px",
    height: "26px",
    borderRadius: "999px",
    backgroundColor: accent,
    color: "#111411",
    fontSize: "0.8rem",
    fontWeight: 700,
    flexShrink: 0,
    fontFamily: mono,
  },
  cards: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 540px)": "1fr",
    },
    gap: "14px",
    margin: "22px 0",
  },
  card: {
    display: "block",
    padding: "18px 20px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#37412f",
    borderRadius: "7px",
    backgroundColor: "#181e14",
    transitionProperty: "border-color, transform",
    transitionDuration: "0.15s",
    ":hover": {
      borderColor: accent,
      transform: "translateY(-2px)",
    },
  },
  cardTitle: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    fontSize: "1rem",
    fontWeight: 550,
    color: "#f0f2eb",
    margin: "0 0 6px",
  },
  cardArrow: {
    color: accent,
  },
  cardText: {
    fontSize: "0.9rem",
    lineHeight: 1.65,
    color: text,
    margin: 0,
  },
  tabList: {
    display: "flex",
    gap: "4px",
  },
  tab: {
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "#9fae93",
    fontFamily: mono,
    fontSize: "0.75rem",
    padding: "4px 8px",
    borderRadius: "4px",
    cursor: "pointer",
    ":hover": {
      color: accent,
    },
  },
  tabSelected: {
    color: accent,
    backgroundColor: "#22301a",
  },
});
