/**
 * Retired docs slugs → their replacement. Old links keep working: the docs
 * route follows these before reporting a page as missing, and
 * scripts/website.ts checks that every target exists.
 */
export const docsRedirects: Record<string, string> = {
  "getting-started": "install",
  "getting-started-expo": "install",
  "what-you-can-build": "roadmap",
  "language/functions-and-control-flow": "reference/language",
  "language/async-and-errors": "thinking/threads",
  "language/unions": "reference/language",
  "language/native-classes": "reference/language",
  "language/events": "guides/accept-a-js-callback",
  "language/native-views": "roadmap",
  "language/threads": "thinking/threads",
  "language/platform-and-capabilities": "guides/call-an-ios-api",
  "api/packages": "guides/call-an-ios-api",
  "api/types": "reference/boundary-types",
  "api/objects": "thinking/three-places",
  "api/events": "guides/accept-a-js-callback",
  "api/ui": "guides/call-an-ios-api",
  "api/std": "reference/modules",
  "api/config": "reference/cli",
  "api/runtime": "reference/modules",
  "api/cli": "reference/cli",
  "api/integrations": "reference/metro-and-expo",
  "api/library-manifest": "reference/lucent-json",
  language: "reference/language",
  "language/types": "reference/language",
  "language/functions": "reference/language",
  "language/classes": "reference/language",
  "language/generics": "reference/language",
  "language/async": "thinking/threads",
  "language/modules": "reference/language",
  "language/differences": "reference/language",
  "language/diagnostics": "reference/diagnostics",
  "boundary/exports": "how-it-works/calls",
  "boundary/conversions": "reference/boundary-types",
  "boundary/identity": "thinking/three-places",
  "reference/metro": "reference/metro-and-expo",
  "reference/expo": "reference/metro-and-expo",
  "reference/core": "reference/modules",
  "language/errors": "guides/throw-and-handle-errors",
  "boundary/callbacks": "guides/accept-a-js-callback",
  "boundary/errors": "guides/throw-and-handle-errors",
  "platform-apis": "guides/call-an-ios-api",
  status: "roadmap",
};
