// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_C_Shape.h"

#pragma push_macro("area")
#undef area
#pragma push_macro("first")
#undef first
#pragma push_macro("radius")
#undef radius

namespace lucent_app {

struct C_Circle : lucent_app::C_Shape {
  double radius{};
  void construct();
  static lucent::Ref<C_Circle> create();
  double area() override;
  bool lucentJson_(lucent::JsonWriter& w, bool toJson) override;
};

inline bool C_Circle::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "radius", this->radius);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("radius")
#pragma pop_macro("first")
#pragma pop_macro("area")
