// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_C_Shape.h"

#pragma push_macro("area")
#undef area
#pragma push_macro("first")
#undef first
#pragma push_macro("side")
#undef side

namespace lucent_app {

struct C_Square : lucent_app::C_Shape {
  double side{};
  void construct();
  static lucent::Ref<C_Square> create();
  double area() override;
  bool lucentJson_(lucent::JsonWriter& w, bool toJson) override;
};

inline bool C_Square::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "side", this->side);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("side")
#pragma pop_macro("first")
#pragma pop_macro("area")
