// Generated by Lucent. Do not edit.
#pragma once
#include <lucent/lucent.h>

#pragma push_macro("v")
#undef v

namespace lucent_app {

struct S_Options;
struct S_Object2;
struct S_Object3;
struct C_Shape;
struct C_Square;
struct C_Circle;

inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Options>& v);
inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object2>& v);
inline void jsonWrite(lucent::JsonWriter& w, const lucent::Ref<S_Object3>& v);

}  // namespace lucent_app

#pragma pop_macro("v")
