// Generated by Lucent. Do not edit.
#include "m_conditional_u2d_objects.h"
#include <lucent/jsi/convert.h>
#include <lucent/jsi/host.h>

#pragma push_macro("area")
#undef area
#pragma push_macro("areaOf")
#undef areaOf
#pragma push_macro("assigned")
#undef assigned
#pragma push_macro("declared")
#undef declared
#pragma push_macro("describe")
#undef describe
#pragma push_macro("listed")
#undef listed
#pragma push_macro("name")
#undef name
#pragma push_macro("nested")
#undef nested
#pragma push_macro("o")
#undef o
#pragma push_macro("passed")
#undef passed
#pragma push_macro("pick")
#undef pick
#pragma push_macro("radiusOf")
#undef radiusOf
#pragma push_macro("returned")
#undef returned
#pragma push_macro("size")
#undef size
#pragma push_macro("v")
#undef v

namespace lucent::js {

template <>
struct Convert<lucent::Ref<lucent_app::S_Options>> {
  static lucent::Ref<lucent_app::S_Options> fromJs(jsi::Runtime& rt, const jsi::Value& v, const Path& p);
  static lucent::Ref<lucent_app::S_Options> fromObject(jsi::Runtime& rt, const jsi::Object& o, const Path& p);
  static jsi::Value toJs(jsi::Runtime& rt, Host& h, const lucent::Ref<lucent_app::S_Options>& v);
};

inline lucent::Ref<lucent_app::S_Options> Convert<lucent::Ref<lucent_app::S_Options>>::fromJs(jsi::Runtime& rt, const jsi::Value& v, const Path& p) {
  if (!v.isObject()) {
    throwBoundaryError(rt, p, "an object", v);
  }
  return fromObject(rt, v.getObject(rt), p);
}

inline lucent::Ref<lucent_app::S_Options> Convert<lucent::Ref<lucent_app::S_Options>>::fromObject(jsi::Runtime& rt, const jsi::Object& o, const Path& p) {
  if (o.isArray(rt) || o.isFunction(rt)) {
    throwBoundaryError(rt, p, "an object", jsi::Value(rt, o));
  }
  Host& h = Host::get(rt);
  static const PropName n0{"name"};
  static const PropName n1{"size"};
  auto out = std::make_shared<lucent_app::S_Options>();
  out->name = Convert<lucent::String>::fromJs(rt, o.getProperty(rt, h.prop(rt, n0)), p.field("name"));
  out->size = optionalFromJs<double>(rt, o.getProperty(rt, h.prop(rt, n1)), p.field("size"), false, "a number or undefined");
  return out;
}

inline jsi::Value Convert<lucent::Ref<lucent_app::S_Options>>::toJs(jsi::Runtime& rt, Host& h, const lucent::Ref<lucent_app::S_Options>& v) {
  if (!v) {
    return jsi::Value::null();
  }
  static const PropName n0{"name"};
  static const PropName n1{"size"};
  jsi::Object o(rt);
  o.setProperty(rt, h.prop(rt, n0), Convert<lucent::String>::toJs(rt, h, v->name));
  if (!v->size.isUndefined()) {
    o.setProperty(rt, h.prop(rt, n1), Convert<lucent::Opt<double>>::toJs(rt, h, v->size));
  }
  return jsi::Value(std::move(o));
}

jsi::Value errorInstanceToJs(jsi::Runtime& rt, Host& h, const Error& v) {
  return jsi::Value::undefined();
}

}  // namespace lucent::js

namespace {

using namespace lucent::js;

void install_m_conditional_u2d_objects(jsi::Runtime& rt, Host& host, jsi::Object& exports) {
  defineFunction(rt, exports, "declared", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("declared", "packages/compiler/test/e2e/cases/conditional-objects.lucent.ts", 10), [&]() -> jsi::Value {
      auto a0 = Convert<bool>::fromJs(rt, arg(args, count, 0), Path{"declared", "argument 'big'"});
      return Convert<lucent::Ref<lucent_app::S_Options>>::toJs(rt, host, lucent_app::m_conditional_u2d_objects::declared(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "returned", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("returned", "packages/compiler/test/e2e/cases/conditional-objects.lucent.ts", 16), [&]() -> jsi::Value {
      auto a0 = Convert<bool>::fromJs(rt, arg(args, count, 0), Path{"returned", "argument 'big'"});
      return Convert<lucent::Ref<lucent_app::S_Options>>::toJs(rt, host, lucent_app::m_conditional_u2d_objects::returned(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "nested", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("nested", "packages/compiler/test/e2e/cases/conditional-objects.lucent.ts", 20), [&]() -> jsi::Value {
      auto a0 = Convert<double>::fromJs(rt, arg(args, count, 0), Path{"nested", "argument 'n'"});
      return Convert<lucent::Ref<lucent_app::S_Options>>::toJs(rt, host, lucent_app::m_conditional_u2d_objects::nested(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "assigned", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("assigned", "packages/compiler/test/e2e/cases/conditional-objects.lucent.ts", 24), [&]() -> jsi::Value {
      auto a0 = Convert<bool>::fromJs(rt, arg(args, count, 0), Path{"assigned", "argument 'big'"});
      return Convert<lucent::Ref<lucent_app::S_Options>>::toJs(rt, host, lucent_app::m_conditional_u2d_objects::assigned(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "passed", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("passed", "packages/compiler/test/e2e/cases/conditional-objects.lucent.ts", 31), [&]() -> jsi::Value {
      auto a0 = Convert<bool>::fromJs(rt, arg(args, count, 0), Path{"passed", "argument 'big'"});
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_conditional_u2d_objects::passed(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "listed", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("listed", "packages/compiler/test/e2e/cases/conditional-objects.lucent.ts", 35), [&]() -> jsi::Value {
      auto a0 = Convert<bool>::fromJs(rt, arg(args, count, 0), Path{"listed", "argument 'big'"});
      return Convert<lucent::Array<lucent::Ref<lucent_app::S_Options>>>::toJs(rt, host, lucent_app::m_conditional_u2d_objects::listed(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "describe", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("describe", "packages/compiler/test/e2e/cases/conditional-objects.lucent.ts", 39), [&]() -> jsi::Value {
      auto a0 = Convert<lucent::Ref<lucent_app::S_Options>>::fromJs(rt, arg(args, count, 0), Path{"describe", "argument 'o'"});
      return Convert<lucent::String>::toJs(rt, host, lucent_app::m_conditional_u2d_objects::describe(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "area", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("area", "packages/compiler/test/e2e/cases/conditional-objects.lucent.ts", 66), [&]() -> jsi::Value {
      auto a0 = Convert<bool>::fromJs(rt, arg(args, count, 0), Path{"area", "argument 'round'"});
      return Convert<double>::toJs(rt, host, lucent_app::m_conditional_u2d_objects::area(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "areaOf", 2, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("areaOf", "packages/compiler/test/e2e/cases/conditional-objects.lucent.ts", 74), [&]() -> jsi::Value {
      auto a0 = Convert<bool>::fromJs(rt, arg(args, count, 0), Path{"areaOf", "argument 'round'"});
      auto a1 = Convert<double>::fromJs(rt, arg(args, count, 1), Path{"areaOf", "argument 'n'"});
      return Convert<double>::toJs(rt, host, lucent_app::m_conditional_u2d_objects::areaOf(std::move(a0), std::move(a1)));
    });
  });
  defineFunction(rt, exports, "radiusOf", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, LUCENT_TRACE_SITE_AT("radiusOf", "packages/compiler/test/e2e/cases/conditional-objects.lucent.ts", 80), [&]() -> jsi::Value {
      auto a0 = Convert<bool>::fromJs(rt, arg(args, count, 0), Path{"radiusOf", "argument 'round'"});
      return Convert<double>::toJs(rt, host, lucent_app::m_conditional_u2d_objects::radiusOf(std::move(a0)));
    });
  });
  defineFunction(rt, exports, "pick", 1, [installed = host.shared_from_this()](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args, size_t count) -> jsi::Value {
    Host& host = Host::from(rt, installed);
    return callSync(rt, host, [&]() -> jsi::Value {
      auto a0 = Convert<bool>::fromJs(rt, arg(args, count, 0), Path{"pick", "argument 'first'"});
      return callAsync<double>(rt, host, LUCENT_TRACE_SITE_AT("pick", "packages/compiler/test/e2e/cases/conditional-objects.lucent.ts", 93), [a0]() {
        return lucent_app::m_conditional_u2d_objects::pick(a0);
      });
    });
  });
}

const ModuleDef kModules[] = {{"conditional-objects", install_m_conditional_u2d_objects}};

}  // namespace

namespace lucent::js {

const ModuleDef* registeredModules(size_t& count) {
  count = 1;
  return kModules;
}

void resetModuleState() {
  lucent_app::m_conditional_u2d_objects::init();
}

}  // namespace lucent::js

#pragma pop_macro("v")
#pragma pop_macro("size")
#pragma pop_macro("returned")
#pragma pop_macro("radiusOf")
#pragma pop_macro("pick")
#pragma pop_macro("passed")
#pragma pop_macro("o")
#pragma pop_macro("nested")
#pragma pop_macro("name")
#pragma pop_macro("listed")
#pragma pop_macro("describe")
#pragma pop_macro("declared")
#pragma pop_macro("assigned")
#pragma pop_macro("areaOf")
#pragma pop_macro("area")
