// Generated by Lucent. Do not edit.
#include <lucent/jsi/host.h>

static_assert(lucent::js::kRuntimeAbi == 2, "generated for Lucent runtime ABI 2: build it with the runtime lucent build copied next to it");

namespace {

const lucent::js::ModuleIdentity kModuleIdentities[] = {{"basics", "cc4fc6dea671165c"}};

}  // namespace

namespace lucent::js {

const BuildIdentity& buildIdentity() {
  static const BuildIdentity identity = {"all", "66da9b461323d2cf", kModuleIdentities, 1};
  return identity;
}

}  // namespace lucent::js
