// Generated by Lucent from basics.lucent.ts. Do not edit.
#include "m_basics.h"

#pragma push_macro("clamp")
#undef clamp
#pragma push_macro("describe")
#undef describe
#pragma push_macro("h")
#undef h
#pragma push_macro("hash")
#undef hash
#pragma push_macro("hashMany")
#undef hashMany
#pragma push_macro("i")
#undef i
#pragma push_macro("seed")
#undef seed

namespace lucent_app {

double m_basics::hash(lucent::String p0_, lucent::Opt<double> p1_) {
  double seed{};
  bool v3_ = lucent::strictEquals(p1_, lucent::undefined);
  if (v3_) {
    seed = 0.0;
  } else {
    seed = p1_.value();
  }
  int32_t h = lucent::toInt32(seed) | 0;
  {
    int64_t i = static_cast<int64_t>(0);
    while (true) {
      {
        int64_t v11_ = static_cast<int64_t>(p0_.length());
        bool v13_ = !(i < v11_);
        if (v13_) {
          break;
        }
        double v16_ = p0_.charCodeAt(static_cast<double>(i));
        int32_t v17_ = h ^ lucent::toInt32(v16_);
        h = static_cast<int32_t>(static_cast<uint32_t>(v17_) * static_cast<uint32_t>(1540483477));
        h = h ^ static_cast<int32_t>(static_cast<uint32_t>(h) >> (static_cast<uint32_t>(15) & 31u));
      }
      i = static_cast<int64_t>(i) + static_cast<int64_t>(1);
    }
  }
  return static_cast<double>(static_cast<uint32_t>(h) >> (static_cast<uint32_t>(0) & 31u));
}

lucent::Promise<lucent::Array<double>> m_basics::hashMany(lucent::Array<lucent::String> p0_) {
  co_return p0_.template map<double>([](lucent::String p0_, double p1_, lucent::Array<lucent::String> p2_) mutable -> double {
    return lucent_app::m_basics::hash(p0_, lucent::Opt<double>(lucent::undefined));
  });
}

double m_basics::clamp(double p0_, double p1_, double p2_) {
  double v3_ = lucent::math::max(p0_, p1_);
  return lucent::math::min(v3_, p2_);
}

lucent::String m_basics::describe(double p0_) {
  bool v2_ = p0_ < 0.0;
  if (v2_) {
    return LUCENT_STR("negative");
  } else {
    bool v5_ = p0_ == 0.0;
    if (v5_) {
      return LUCENT_STR("zero");
    }
  }
  return lucent::String(LUCENT_STR("positive ")) + lucent::toJsString(p0_);
}

void m_basics::init() {
}

}  // namespace lucent_app

#pragma pop_macro("seed")
#pragma pop_macro("i")
#pragma pop_macro("hashMany")
#pragma pop_macro("hash")
#pragma pop_macro("h")
#pragma pop_macro("describe")
#pragma pop_macro("clamp")
