import { type Platform, parseSdkType, type SdkClassSchema, type SdkModuleSchema, type SdkType } from "./schema.ts";

/** Module specifier of an SDK module. */
export function sdkSpecifier(platform: Platform, module: string): string {
  return `lucent:${platform}/${module}`;
}

/**
 * TypeScript declarations for an SDK module. Classes are nominal (a private
 * brand), have a private constructor unless the SDK declares initializers,
 * and document their thread rule; the compiler maps the declarations back to
 * the schema by name and overload order.
 */
export function sdkDts(schema: SdkModuleSchema): string {
  const imports = new Map<string, Set<string>>();
  const tsType = (t: SdkType): string => {
    const base = ((): string => {
      switch (t.k) {
        case "prim":
          return t.name === "void" ? "void" : t.name === "boolean" || t.name === "bool" ? "boolean" : "number";
        case "string":
          return "string";
        case "array": {
          if (t.of.k === "prim" && t.of.name === "byte") return t.nullable ? "Uint8Array | null" : "Uint8Array";
          const inner = tsType(t.of);
          return inner.includes(" ") ? `(${inner})[]` : `${inner}[]`;
        }
        case "classOf":
          return `{ readonly prototype: ${t.param} }`;
        case "tparam":
          return t.name;
        case "ref":
          if (t.module !== schema.module) {
            const names = imports.get(t.module) ?? new Set();
            names.add(t.name);
            imports.set(t.module, names);
          }
          return t.name;
      }
    })();
    return t.nullable ? `${base} | null` : base;
  };

  const body: string[] = [];
  for (const type of schema.types) {
    if (type.kind === "enum") {
      body.push(`export declare enum ${type.name} {`, ...type.cases.map((c) => `  ${c.name} = ${c.value},`), "}", "");
      continue;
    }
    body.push(...classDts(schema, type, tsType), "");
  }
  const head = [`// Generated by Lucent from the ${schema.platform} binding schema of ${schema.module}. Do not edit.`];
  for (const [module, names] of imports) head.push(`import type { ${[...names].sort().join(", ")} } from "${sdkSpecifier(schema.platform, module)}";`);
  return [...head, "", ...body].join("\n");
}

function classDts(schema: SdkModuleSchema, cls: SdkClassSchema, tsType: (t: SdkType) => string): string[] {
  const parse = (s: string, tps: readonly string[] = []) => parseSdkType(s, schema.module, tps);
  const params = (ps: { name: string; type: string }[], tps: readonly string[] = []) => ps.map((p) => `${p.name}: ${tsType(parse(p.type, tps))}`).join(", ");
  const sinceText = (v: number | string | undefined) => (v === undefined ? undefined : `Since ${schema.platform === "android" ? "API " : "iOS "}${v}.`);
  const memberDoc = (m: { since?: number | string; deprecated?: boolean }) => {
    const parts = [sinceText(m.since), m.deprecated ? "@deprecated" : undefined].filter(Boolean);
    return parts.length ? `  /** ${parts.join(" ")} */\n` : "";
  };
  const doc: string[] = [];
  if (cls.mainActor) doc.push(" * Main thread only: use it inside `main(() => …)` from lucent:thread.");
  if (cls.interface) doc.push(" * A Java interface.");
  if (cls.since !== undefined) doc.push(` * ${sinceText(cls.since)}`);
  const out = doc.length ? ["/**", ...doc, " */"] : [];
  const ext = cls.extends ? ` extends ${tsType(parse(cls.extends))}` : "";
  // Interfaces and abstract classes cannot be constructed; implemented
  // interfaces merge into the class type below, so values convert to them.
  out.push(`export declare ${cls.interface || cls.abstract ? "abstract " : ""}class ${cls.name}${ext} {`);
  out.push(`  private readonly __lucent_${cls.name}: never;`);
  if (!cls.constructors?.length && !cls.inheritsInit) out.push("  private constructor();");
  for (const c of cls.constructors ?? []) out.push(`${memberDoc(c)}  constructor(${params(c.params)});`);
  for (const p of cls.properties ?? []) out.push(`${memberDoc(p)}  ${p.static ? "static " : ""}${p.readonly ? "readonly " : ""}${p.name}: ${tsType(parse(p.type))};`);
  for (const m of cls.methods ?? []) {
    const tps = m.typeParams ?? [];
    out.push(`${memberDoc(m)}  ${m.static ? "static " : ""}${m.name}${tps.length ? `<${tps.join(", ")}>` : ""}(${params(m.params, tps)}): ${tsType(parse(m.returns, tps))};`);
  }
  out.push("}");
  if (cls.implements?.length) out.push(`export declare interface ${cls.name} extends ${cls.implements.map((i) => tsType(parse(i))).join(", ")} {}`);
  return out;
}
