import type { NamesIndex } from "@lucent-lang/bindgen";
import { findSdkType, type Platform, parseSdkType, type SdkClassSchema, type SdkModuleSchema, type SdkType } from "./schema.ts";

/** Module specifier of an SDK module. */
export function sdkSpecifier(platform: Platform, module: string): string {
  return `lucent:${platform}/${module}`;
}

/**
 * TypeScript declarations for an SDK module. Classes are nominal (a private
 * brand), have a private constructor unless the SDK declares initializers,
 * and document their thread rule; the compiler maps the declarations back to
 * the schema by name and overload order.
 */
export function sdkDts(schema: SdkModuleSchema): string {
  const imports = new Map<string, Set<string>>();
  const use = (module: string, name: string) => {
    const names = imports.get(module) ?? new Set();
    names.add(name);
    imports.set(module, names);
  };
  /** `out`: results and properties; parameters take any Lucent value where Objective-C takes Any. */
  const tsType = (t: SdkType, out = true): string => {
    const base = ((): string => {
      switch (t.k) {
        case "prim":
          return t.name === "void" ? "void" : t.name === "boolean" || t.name === "bool" ? "boolean" : "number";
        case "string":
          return "string";
        case "bytes":
          return "Uint8Array";
        case "date":
          return "Date";
        case "id":
          use("lucent:ios", out ? "NSObject" : "ObjCValue");
          return out ? "NSObject" : "ObjCValue";
        case "record": {
          const v = tsType(t.of, out);
          return `Record<string, ${v}>`;
        }
        case "out":
          use("lucent:ios", "Out");
          use("lucent:ios", "NSObject");
          return "Out<NSObject>";
        case "array": {
          if (t.of.k === "prim" && t.of.name === "byte") return "Uint8Array";
          const inner = tsType(t.of, out);
          return inner.includes(" ") ? `(${inner})[]` : `${inner}[]`;
        }
        case "classOf":
          return `{ readonly prototype: ${t.param} }`;
        case "error":
          return "Error";
        case "fn": {
          // The block's arguments come from the platform; its result goes back.
          const ps = t.params.map((x, i) => `arg${i}: ${tsType(x, true)}`).join(", ");
          const fn = `(${ps}) => ${tsType(t.ret, false)}`;
          return t.nullable ? `(${fn})` : fn;
        }
        case "tparam":
          return t.name;
        case "ref": {
          if (t.module !== schema.module) use(`${schema.platform}/${t.module}`, t.name);
          // Where a Java interface with one abstract method is taken, so is a
          // function (Android only: other iOS modules are not extracted for names).
          const target = out || schema.platform !== "android" ? undefined : t.module === schema.module ? schema.types.find((x) => x.name === t.name) : findSdkType(schema.platform, t.module, t.name);
          const sam = target?.kind === "class" && target.functional ? target.methods?.find((m) => m.name === target.functional && m.abstract) : undefined;
          if (!sam) return t.name;
          const ps = sam.params.map((p, i) => `arg${i}: ${tsType(parseSdkType(p.type, t.module), true)}`).join(", ");
          return `${t.name} | ((${ps}) => ${tsType(parseSdkType(sam.returns, t.module), false)})`;
        }
      }
    })();
    return t.nullable && !base.endsWith("| null") ? `${base} | null` : base;
  };

  const body: string[] = [];
  for (const type of schema.types) {
    if (type.kind === "enum") {
      body.push(`export declare enum ${type.name} {`, ...type.cases.map((c) => `  ${c.name} = ${c.value},`), "}", "");
      continue;
    }
    body.push(...classDts(schema, type, tsType, use), "");
  }
  for (const f of schema.functions ?? []) {
    const params = f.params.map((p) => `${safeName(p.name)}: ${tsType(parseSdkType(p.type, schema.module), false)}`).join(", ");
    body.push(`export declare function ${f.name}(${params}): ${tsType(parseSdkType(f.returns, schema.module))};`);
  }
  for (const c of schema.constants ?? []) body.push(`export declare const ${c.name}: ${tsType(parseSdkType(c.type, schema.module))};`);
  const head = [`// Generated by Lucent from the ${schema.platform} binding schema of ${schema.module}. Do not edit.`];
  for (const [module, names] of imports) {
    const spec = module.startsWith("lucent:") ? module : `lucent:${module}`;
    head.push(`import type { ${[...names].sort().join(", ")} } from "${spec}";`);
  }
  // Implementation modules (`_LocationEssentials`) are re-exported by the
  // modules that use them, as their module maps' `export *` does: CLLocation
  // is imported from lucent:ios/CoreLocation.
  for (const module of reexports(schema, [...imports.keys()])) head.push(`export * from "lucent:${module}";`);
  return [...head, "", ...body].join("\n");
}

/** The implementation modules (`ios/_Name`) a module's declarations re-export. */
export function reexports(schema: SdkModuleSchema, imported: string[]): string[] {
  return schema.platform === "ios" ? imported.filter((m) => /^ios\/_/.test(m)) : [];
}

const RESERVED = new Set(["break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "import", "in", "instanceof", "new", "null", "return", "super", "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while", "with", "yield", "let", "static", "implements", "interface", "package", "private", "protected", "public", "await"]);
function safeName(n: string): string {
  return RESERVED.has(n) ? `${n}_` : n;
}

function classDts(schema: SdkModuleSchema, cls: SdkClassSchema, tsType: (t: SdkType, out?: boolean) => string, use: (module: string, name: string) => void): string[] {
  const parse = (s: string, tps: readonly string[] = []) => parseSdkType(s, schema.module, tps);
  const params = (ps: { name: string; type: string }[], tps: readonly string[] = []) => ps.map((p) => `${safeName(p.name)}: ${tsType(parse(p.type, tps), false)}`).join(", ");
  const sinceText = (v: number | string | undefined) => (v === undefined ? undefined : `Since ${schema.platform === "android" ? "API " : "iOS "}${v}.`);
  const memberDoc = (m: { since?: number | string; deprecated?: boolean }) => {
    const parts = [sinceText(m.since), m.deprecated ? "@deprecated" : undefined].filter(Boolean);
    return parts.length ? `  /** ${parts.join(" ")} */\n` : "";
  };
  const doc: string[] = [];
  if (cls.mainActor) doc.push(" * Main thread only: use it inside `main(() => …)` from lucent:thread.");
  if (cls.interface) doc.push(" * A Java interface.");
  if (cls.since !== undefined) doc.push(` * ${sinceText(cls.since)}`);
  const out = doc.length ? ["/**", ...doc, " */"] : [];
  // Objective-C classes are NSObjects, so they go where Any (id) is taken.
  if (schema.platform === "ios" && !cls.extends && !cls.interface) use("lucent:ios", "NSObject");
  const ext = cls.extends ? ` extends ${tsType(parse(cls.extends))}` : schema.platform === "ios" && !cls.interface ? " extends NSObject" : "";
  // Interfaces and abstract classes cannot be constructed; implemented
  // interfaces merge into the class type below, so values convert to them.
  out.push(`export declare ${cls.interface || cls.abstract ? "abstract " : ""}class ${cls.name}${ext} {`);
  // Protocols and Java interfaces are structural, so Lucent classes can
  // implement them; other classes are nominal.
  if (!cls.interface) out.push(`  private readonly __lucent_${cls.name}: never;`);
  if (!cls.constructors?.length && !cls.inheritsInit && !cls.interface) out.push("  protected constructor();");
  for (const c of cls.constructors ?? []) out.push(`${memberDoc(c)}  constructor(${params(c.params)});`);
  // A TypeScript class cannot have a property and a method of one name: the method stays.
  const methodNames = new Set((cls.methods ?? []).map((m) => `${!!m.static}:${m.name}`));
  for (const p of (cls.properties ?? []).filter((x) => !methodNames.has(`${!!x.static}:${x.name}`))) out.push(`${memberDoc(p)}  ${p.static ? "static " : ""}${p.readonly ? "readonly " : ""}${p.name}: ${tsType(parse(p.type))};`);
  for (const m of cls.methods ?? []) {
    const tps = m.typeParams ?? [];
    const head = `${memberDoc(m)}  ${m.static ? "static " : ""}${m.name}${m.optional ? "?" : ""}${tps.length ? `<${tps.join(", ")}>` : ""}`;
    out.push(`${head}(${params(m.params, tps)}): ${tsType(parse(m.returns, tps))};`);
    // Without its completion handler: a promise of what the handler receives.
    if (m.async) {
      const promiseHead = `${memberDoc(m)}  ${m.static ? "static " : ""}${m.async.name ?? m.name}${tps.length ? `<${tps.join(", ")}>` : ""}`;
      out.push(`${promiseHead}(${params(m.params.slice(0, -1), tps)}): Promise<${tsType(parse(m.async.returns, tps))}>;`);
    }
  }
  out.push("}");
  if (cls.implements?.length) out.push(`export declare interface ${cls.name} extends ${cls.implements.map((i) => tsType(parse(i))).join(", ")} {}`);
  return out;
}

/**
 * Declarations for a module the program does not import: its types' names,
 * enough for the signatures of modules it does import. Members need the
 * module imported (then it gets full declarations).
 */
export function stubDts(platform: Platform, module: string, names: NamesIndex): string {
  const out = [`// Names only: import lucent:${platform}/${module} in a platform file to use these types' members. Generated by Lucent. Do not edit.`];
  if (platform === "ios") out.push('import type { NSObject } from "lucent:ios";');
  out.push("");
  for (const [name, t] of Object.entries(names.types)) {
    if (t.kind === "enum") out.push(`export declare enum ${name} {}`);
    else if (t.kind === "protocol") out.push(`export declare abstract class ${name} {}`);
    else out.push(`export declare class ${name}${platform === "ios" ? " extends NSObject" : ""} {`, `  private readonly __lucent_${name}: never;`, "  protected constructor();", "}");
  }
  return out.join("\n");
}
