// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_I_Counter.h"

#pragma push_macro("i")
#undef i
#pragma push_macro("next")
#undef next
#pragma push_macro("w")
#undef w

namespace lucent_app {

struct C_Down;

struct C_Down : lucent::Object, virtual lucent_app::I_Counter {
  double i{};
  void construct(double p0_);
  static lucent::Ref<C_Down> create(double p0_);
  double next() override;
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_Down::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "i", this->i);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("w")
#pragma pop_macro("next")
#pragma pop_macro("i")
