// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("T")
#undef T
#pragma push_macro("next")
#undef next

namespace lucent_app {

template <class T>
struct I_Feed {
  virtual ~I_Feed() = default;
  virtual double get_count() = 0;
  virtual lucent::Opt<T> next() = 0;
};

}  // namespace lucent_app

#pragma pop_macro("next")
#pragma pop_macro("T")
