// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_I_Feed.h"

#pragma push_macro("count")
#undef count
#pragma push_macro("n")
#undef n
#pragma push_macro("next")
#undef next
#pragma push_macro("w")
#undef w

namespace lucent_app {

struct C_Countdown;

struct C_Countdown : lucent::Object, virtual lucent_app::I_Feed<double> {
  double n{};
  double count{};
  void construct(double p0_);
  static lucent::Ref<C_Countdown> create(double p0_);
  lucent::Opt<double> next() override;
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
  double get_count() override {
    return this->count;
  }
};

inline bool C_Countdown::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "n", this->n);
  lucent::jsonField(w, first, "count", this->count);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("w")
#pragma pop_macro("next")
#pragma pop_macro("n")
#pragma pop_macro("count")
