// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_I_Shape.h"
#include "lucent_app_I_Named.h"

#pragma push_macro("area")
#undef area
#pragma push_macro("describe")
#undef describe
#pragma push_macro("kind")
#undef kind
#pragma push_macro("name")
#undef name
#pragma push_macro("r")
#undef r
#pragma push_macro("v")
#undef v
#pragma push_macro("w")
#undef w

namespace lucent_app {

struct C_Circle : lucent::Object, virtual lucent_app::I_Shape, virtual lucent_app::I_Named {
  double r{};
  lucent::String kind{};
  lucent::String name{};
  void construct(double p0_);
  static lucent::Ref<C_Circle> create(double p0_);
  double area() override;
  lucent::String describe(lucent::String p0_) override;
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
  lucent::String get_kind() override {
    return this->kind;
  }
  lucent::String get_name() override {
    return this->name;
  }
  void set_name(lucent::String v) override {
    this->name = std::move(v);
  }
};

inline bool C_Circle::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  lucent::jsonField(w, first, "r", this->r);
  lucent::jsonField(w, first, "kind", this->kind);
  lucent::jsonField(w, first, "name", this->name);
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("w")
#pragma pop_macro("v")
#pragma pop_macro("r")
#pragma pop_macro("name")
#pragma pop_macro("kind")
#pragma pop_macro("describe")
#pragma pop_macro("area")
