// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"

#pragma push_macro("next")
#undef next

namespace lucent_app {

struct I_Counter {
  virtual ~I_Counter() = default;
  virtual double next() = 0;
};

}  // namespace lucent_app

#pragma pop_macro("next")
