// Generated by Lucent. Do not edit.
#pragma once
#include <lucent/lucent.h>

#pragma push_macro("T")
#undef T

namespace lucent_app {

struct I_Shape;
struct I_Named;
struct I_Counter;
struct I_Source;

template <class T>
struct I_Feed;

struct I_Tagged;
struct I_Labelled;
struct C_Circle;
struct C_Rect;
struct C_Up;
struct C_Down;
struct C_Echo;
struct C_Countdown;

template <class T>
struct C_ListSource;

struct C_Item;
struct C_Special;

}  // namespace lucent_app

#pragma pop_macro("T")
