// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_I_Source.h"

#pragma push_macro("load")
#undef load
#pragma push_macro("w")
#undef w

namespace lucent_app {

struct C_Echo : lucent::Object, virtual lucent_app::I_Source {
  void construct();
  static lucent::Ref<C_Echo> create();
  lucent::Promise<lucent::String> load(lucent::String p0_) override;
  virtual bool lucentJson_(lucent::JsonWriter& w, bool toJson);
};

inline bool C_Echo::lucentJson_(lucent::JsonWriter& w, bool toJson) {
  w.raw("{");
  bool first = true;
  (void)first;
  w.raw("}");
  return true;
}

}  // namespace lucent_app

#pragma pop_macro("w")
#pragma pop_macro("load")
