// Generated by Lucent. Do not edit.
#pragma once
#include "lucent_app.h"
#include "lucent_app_I_Labelled.h"

#pragma push_macro("tag")
#undef tag

namespace lucent_app {

struct I_Tagged;

struct I_Tagged : public virtual lucent_app::I_Labelled {
  virtual ~I_Tagged() = default;
  virtual lucent::String tag() = 0;
};

}  // namespace lucent_app

#pragma pop_macro("tag")
